<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { storeToRefs } from 'pinia'
import { RouterLink,useRoute } from 'vue-router'
import OrderFulfillmentSubnav from '../components/OrderFulfillmentSubnav.vue'
import { useOrderStore } from '../runtime/order-store'
import './order-views.css'
const route=useRoute();const store=useOrderStore();const{outbounds,loading,error,actor,saving}=storeToRefs(store);const item=computed(()=>outbounds.value.find((entry)=>entry.id===String(route.params.outboundId))??null);const reason=ref('');const message=ref('');const money=(value:number)=>actor.value.role==='warehouse'?'已遮蔽':`¥${(value/100).toFixed(2)}`
async function print(){if(item.value&&await store.printOutbounds([{outboundId:item.value.id,expectedVersion:item.value.version}])){await store.loadOutbounds();message.value='已确认打印销售出库单（原型模拟）'}}
async function voidDoc(){if(!item.value||!reason.value.trim())return;await store.loadFulfillment(item.value.orderId);if(await store.voidFulfillment(item.value.id,reason.value)){await store.loadOutbounds();message.value='出库单已作废，原批次/库位库存已恢复';reason.value=''}}
onMounted(()=>store.loadOutbounds())
</script>
<template><section class="order-page"><OrderFulfillmentSubnav/><div v-if="loading" class="order-state"><strong>正在加载出库单…</strong></div><div v-else-if="error||!item" class="order-state error"><strong>无法打开销售出库单</strong><p>{{ error??'出库单不存在' }}</p><RouterLink class="order-button" to="/orders/outbounds">返回列表</RouterLink></div><template v-else><header class="order-detail-header"><div><RouterLink class="order-back" to="/orders/outbounds">← 销售出库单列表</RouterLink><p class="eyebrow">{{ item.outboundNo }}</p><h1>{{ item.customerSnapshot.name }}</h1><span class="order-status">{{ item.status==='confirmed'?'已确认':'已作废' }}</span></div><div class="order-detail-actions"><button class="order-button" :disabled="saving" @click="print">打印</button><RouterLink class="order-button" :to="`/orders/${item.orderId}`">订单详情</RouterLink></div></header><p v-if="message" class="order-panel" style="padding:9px 12px">{{ message }}</p><section class="order-card"><h2>基础信息</h2><dl class="order-grid"><div><dt>实际仓库</dt><dd>{{ item.warehouseSnapshot.name }}</dd></div><div><dt>确认时间</dt><dd>{{ item.confirmedAt.slice(0,16).replace('T',' ') }}</dd></div><div><dt>操作人</dt><dd>{{ item.operatorSnapshot.name }}</dd></div><div><dt>单据金额</dt><dd>{{ money(item.documentAmountCents) }}</dd></div></dl></section><section class="order-card"><h2>商品与 FIFO 分配</h2><div class="order-table-wrap"><table class="order-table" style="min-width:900px"><thead><tr><th>商品</th><th>规格</th><th>数量</th><th>单位</th><th>批次 / 库位</th><th class="order-money">金额</th></tr></thead><tbody><tr v-for="line in item.lines" :key="line.id"><td>{{ line.productNameSnapshot }}<small>{{ line.skuCodeSnapshot }}</small></td><td>{{ line.specificationSnapshot }}</td><td>{{ line.quantity }}</td><td>{{ line.unitSnapshot.name }}</td><td><span v-if="!line.allocations.length">当前角色已遮蔽</span><small v-for="part in line.allocations" :key="part.movementId">{{ part.batchNumber }} · {{ part.locationName }} · {{ part.quantityMilli/1000 }}</small></td><td class="order-money">{{ money(line.amountCents) }}</td></tr></tbody></table></div></section><section v-if="item.voidInfo" class="order-card"><h2>作废记录</h2><p>{{ item.voidInfo.voidedAt.slice(0,16).replace('T',' ') }} · {{ item.voidInfo.operatorSnapshot.name }} · {{ item.voidInfo.reason }}</p></section><section v-else-if="actor.role==='super-admin'||actor.role==='warehouse'" class="order-card"><h2>作废未发货出库单</h2><label class="order-field"><span>作废原因（1～200字）</span><textarea v-model="reason" maxlength="200"/></label><button class="order-button danger" :disabled="!reason.trim()||saving" @click="voidDoc">确认作废并精确恢复库存</button></section></template></section></template>
