<script setup lang="ts">
import { onMounted,ref } from 'vue'
import { storeToRefs } from 'pinia'
import { RouterLink } from 'vue-router'
import OrderScenarioBar from '../components/OrderScenarioBar.vue'
import OrderFulfillmentSubnav from '../components/OrderFulfillmentSubnav.vue'
import { useOrderStore } from '../runtime/order-store'
import './order-views.css'
const store=useOrderStore();const{outbounds,loading,error,scenario,actor,saving}=storeToRefs(store);const selected=ref<string[]>([]);const message=ref('')
const money=(value:number)=>actor.value.role==='warehouse'?'已遮蔽':`¥${(value/100).toFixed(2)}`;const time=(value:string)=>value.slice(0,16).replace('T',' ')
async function printSelected(){const docs=outbounds.value.filter((item)=>selected.value.includes(item.id));if(await store.printOutbounds(docs.map((item)=>({outboundId:item.id,expectedVersion:item.version})))){message.value=`已确认打印 ${docs.length} 张销售出库单（原型模拟）`;selected.value=[]}}
onMounted(()=>store.loadOutbounds())
</script>
<template><section class="order-page"><header class="order-page-header"><div><p class="eyebrow">ORD-004 · 销售履约</p><h1>销售出库单</h1><p>库存扣减即确认；作废保留原单和精确反向流水。</p></div><div><OrderScenarioBar :scenario="scenario" :role="actor.role" @scenario="async v=>{await store.setScenario(v);await store.loadOutbounds()}" @role="async v=>{await store.setRole(v);await store.loadOutbounds()}"/></div></header><OrderFulfillmentSubnav/><p v-if="message" class="order-panel" style="padding:9px 12px">{{ message }}</p><section class="order-panel"><div class="order-toolbar"><strong>共 {{ outbounds.length }} 张</strong><button class="order-button primary" :disabled="!selected.length||saving" @click="printSelected">打印选中</button></div><div v-if="loading" class="order-state"><strong>正在加载销售出库单…</strong></div><div v-else-if="error" class="order-state error"><strong>销售出库单加载失败</strong><p>{{ error }}</p></div><div v-else-if="!outbounds.length" class="order-state"><strong>暂无销售出库单</strong><p>可从已审核订单执行销售出库。</p></div><div v-else class="order-table-wrap"><table class="order-table" style="min-width:1050px"><thead><tr><th>选择</th><th>出库单号</th><th>出库时间</th><th>仓库</th><th>客户</th><th>订单</th><th class="order-money">数量</th><th class="order-money">单据金额</th><th>状态</th><th>打印次数</th></tr></thead><tbody><tr v-for="item in outbounds" :key="item.id"><td><input v-model="selected" type="checkbox" :value="item.id"/></td><td><RouterLink :to="`/orders/outbounds/${item.id}`">{{ item.outboundNo }}</RouterLink></td><td>{{ time(item.confirmedAt) }}</td><td>{{ item.warehouseSnapshot.name }}</td><td>{{ item.customerSnapshot.name }}</td><td><RouterLink :to="`/orders/${item.orderId}`">查看订单</RouterLink></td><td class="order-money">{{ item.lines.reduce((s,l)=>s+l.quantityMilli,0)/1000 }}</td><td class="order-money">{{ money(item.documentAmountCents) }}</td><td><span class="order-status" :class="item.status==='voided'?'order-status-canceled':'order-status-approved'">{{ item.status==='confirmed'?'已确认':'已作废' }}</span></td><td>{{ item.printRecords.length }}</td></tr></tbody></table></div></section></section></template>
