<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import InventorySubnav from '../components/InventorySubnav.vue'
import InventoryScenarioBar from '../components/InventoryScenarioBar.vue'
import { useInventoryStore } from '../runtime/inventory-store'
import type { InventoryCategorySnapshot, InventoryStatus, InventoryStockRow } from '../types'
import './inventory-views.css'
import './inventory-dialog.css'

const store = useInventoryStore(); const route = useRoute(); const router = useRouter()
const { workspace, loading, error, isEmpty, scenario, actor, canWrite } = storeToRefs(store)
const selected = ref<string[]>([]); const thresholdRow = ref<InventoryStockRow | null>(null); const thresholdMinimum = ref(''); const thresholdMaximum = ref(''); const actionError = ref('')
const filters = reactive({ warehouseId: String(route.query.warehouseId ?? ''), categoryId: String(route.query.categoryId ?? ''), status: String(route.query.status ?? ''), keyword: String(route.query.keyword ?? '') })
const expandedCategories = ref<string[]>([])
const statusLabel = { normal: '正常', insufficient: '库存不足', zero: '零库存', overstock: '超储', unavailable: '数据源未接入' } as const
const categoryRows = computed(() => {
  const categories = workspace.value.categories; const ids = new Set(categories.map((item) => item.id)); const rows: Array<InventoryCategorySnapshot & { depth: number; hasChildren: boolean }> = []; const visited = new Set<string>()
  const append = (parentId: string | null, depth: number) => categories.filter((item) => item.parentId === parentId || (parentId === null && item.parentId !== null && !ids.has(item.parentId))).sort((a, b) => a.name.localeCompare(b.name, 'zh-CN')).forEach((item) => {
    if (visited.has(item.id)) return; visited.add(item.id); const hasChildren = categories.some((child) => child.parentId === item.id); rows.push({ ...item, depth, hasChildren }); if (hasChildren && expandedCategories.value.includes(item.id)) append(item.id, depth + 1)
  })
  append(null, 0); return rows
})
const allSelected = computed(() => workspace.value.stocks.items.length > 0 && workspace.value.stocks.items.every((row) => selected.value.includes(`${row.warehouse.id}:${row.skuId}`)))
const quantity = (milli: number | null, unit = '') => milli === null ? '数据源未接入' : `${(milli / 1000).toLocaleString('zh-CN', { maximumFractionDigits: 3 })}${unit}`
const money = (cents: number | null) => cents === null ? '—' : `¥${(cents / 100).toFixed(2)}`
async function search() { const query = { warehouseId: filters.warehouseId || undefined, categoryId: filters.categoryId || undefined, status: (filters.status || undefined) as InventoryStatus | undefined, keyword: filters.keyword || undefined, page: 1, pageSize: 30 as const }; await router.replace({ query: Object.fromEntries(Object.entries(query).filter(([, value]) => value !== undefined).map(([key, value]) => [key, String(value)])) }); selected.value = []; await store.applyQuery(query) }
async function reset() { Object.assign(filters, { warehouseId: '', categoryId: '', status: '', keyword: '' }); await router.replace({ query: {} }); await store.applyQuery({ page: 1, pageSize: 30 }) }
function toggleCategory(id: string) { expandedCategories.value = expandedCategories.value.includes(id) ? expandedCategories.value.filter((item) => item !== id) : [...expandedCategories.value, id] }
async function selectCategory(id: string) { filters.categoryId = id; await search() }
function toggle(key: string) { selected.value = selected.value.includes(key) ? selected.value.filter((item) => item !== key) : [...selected.value, key] }
function toggleAll() { const keys = workspace.value.stocks.items.map((row) => `${row.warehouse.id}:${row.skuId}`); selected.value = allSelected.value ? selected.value.filter((item) => !keys.includes(item)) : [...new Set([...selected.value, ...keys])] }
function download() { const blob = new Blob([store.exportStocks(selected.value)], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'inventory-stocks.csv'; anchor.click(); URL.revokeObjectURL(url) }
function openThreshold(row: InventoryStockRow) { thresholdRow.value = row; thresholdMinimum.value = String(row.safetyMinimumMilli / 1000); thresholdMaximum.value = row.maximumMilli === null ? '' : String(row.maximumMilli / 1000); actionError.value = '' }
async function saveThreshold() { if (!thresholdRow.value) return; actionError.value = ''; try { await store.saveThreshold({ warehouseId: thresholdRow.value.warehouse.id, skuId: thresholdRow.value.skuId, safetyMinimumMilli: Math.round(Number(thresholdMinimum.value) * 1000), maximumMilli: thresholdMaximum.value === '' ? null : Math.round(Number(thresholdMaximum.value) * 1000) }); thresholdRow.value = null } catch (caught) { actionError.value = caught instanceof Error ? caught.message : '保存失败' } }
onMounted(async () => { await store.applyQuery({ warehouseId: filters.warehouseId || undefined, categoryId: filters.categoryId || undefined, status: (filters.status || undefined) as InventoryStatus | undefined, keyword: filters.keyword || undefined, page: 1, pageSize: 30 }); if (filters.categoryId) { const byId = new Map(workspace.value.categories.map((item) => [item.id, item])); const expanded = new Set<string>(); let current = byId.get(filters.categoryId); while (current?.parentId) { expanded.add(current.parentId); current = byId.get(current.parentId) } expandedCategories.value = [...expanded] } })
</script>

<template>
  <section class="inventory-page">
    <header class="inventory-header"><div><h1>库存列表</h1><p>仓库 × SKU 账面库存；订单待出库与采购在途未接入时不以 0 冒充。</p></div><InventoryScenarioBar :scenario="scenario" :role="actor.role" @scenario="store.setScenario" @role="store.setRole" /></header>
    <InventorySubnav />
    <form class="inventory-panel inventory-filter" @submit.prevent="search"><label>仓库<select v-model="filters.warehouseId"><option value="">全部仓库</option><option v-for="item in workspace.warehouses" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label>库存状态<select v-model="filters.status"><option value="">全部状态</option><option v-for="(label, key) in statusLabel" :key="key" :value="key">{{ label }}</option></select></label><label class="keyword">商品关键词<input v-model="filters.keyword" type="search" placeholder="SKU / 商品名称 / 条码"></label><button class="inv-button" type="button" @click="reset">重置</button><button class="inv-button primary" type="submit">查询</button></form>
    <p v-if="!workspace.catalogAvailable && !error" class="inventory-warning">商品资料服务加载失败；库存标识和数量仍保留，商品名称显示“资料不可用”。</p><p v-if="actionError" class="inventory-warning">{{ actionError }}</p>
    <div class="inventory-stock-layout">
      <aside class="inventory-category-panel" aria-label="商品分类筛选"><h2>商品分类</h2><button class="category-all" :class="{ active: !filters.categoryId }" type="button" @click="selectCategory('')">全部分类</button><div v-for="item in categoryRows" :key="item.id" class="category-row" :style="{ '--category-depth': item.depth }"><button v-if="item.hasChildren" class="category-toggle" type="button" :aria-label="`${expandedCategories.includes(item.id) ? '收起' : '展开'}${item.name}`" @click="toggleCategory(item.id)">{{ expandedCategories.includes(item.id) ? '▾' : '▸' }}</button><span v-else class="category-spacer"></span><button class="category-name" :class="{ active: filters.categoryId === item.id }" type="button" @click="selectCategory(item.id)">{{ item.name }}<small v-if="item.status === 'inactive'">停用</small></button></div><p v-if="!loading && !workspace.categories.length" class="category-empty">暂无分类资料</p></aside>
      <section class="inventory-stock-content">
        <div v-if="error" class="inventory-state error" role="alert"><strong>库存数据加载失败</strong><p>{{ error }}</p><button class="inv-button" @click="store.load">重试</button></div><div v-else-if="loading" class="inventory-state"><strong>正在加载库存数据…</strong></div><div v-else-if="isEmpty" class="inventory-state"><strong>暂无库存数据</strong><p>当前筛选或模拟场景没有余额。</p></div>
        <template v-else><div class="inventory-toolbar"><strong>共 {{ workspace.stocks.total }} 条</strong><div><button class="inv-button" @click="store.load">刷新</button><button v-if="canWrite" class="inv-button" @click="download">导出 CSV</button></div></div><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th><input type="checkbox" :checked="allSelected" aria-label="选择当前页" @change="toggleAll"></th><th>仓库</th><th>商品 / 规格</th><th>SKU / 条码</th><th class="quantity">期初</th><th class="quantity">当前</th><th class="quantity">待出库</th><th class="quantity">可用</th><th class="quantity">在途</th><th class="quantity">安全库存</th><th>状态</th><th class="money">成本单价</th><th class="money">库存金额</th><th>操作</th></tr></thead><tbody><tr v-for="row in workspace.stocks.items" :key="`${row.warehouse.id}:${row.skuId}`"><td><input type="checkbox" :checked="selected.includes(`${row.warehouse.id}:${row.skuId}`)" @change="toggle(`${row.warehouse.id}:${row.skuId}`)"></td><td><strong>{{ row.warehouse.name }}</strong><small>{{ row.warehouse.code }}{{ row.warehouse.saleProhibited ? ' · 禁售' : '' }}</small></td><td><RouterLink :to="`/inventory/stocks/${row.warehouse.id}/${row.skuId}`"><strong>{{ row.sku?.productName ?? '商品资料不可用' }}</strong></RouterLink><small>{{ row.sku?.specification ?? row.skuId }}</small></td><td>{{ row.sku?.skuCode ?? row.skuId }}<small>{{ row.sku?.barcode ?? '—' }}</small></td><td class="quantity">{{ quantity(row.openingMilli, row.sku?.baseUnitName) }}</td><td class="quantity">{{ quantity(row.currentMilli, row.sku?.baseUnitName) }}</td><td class="quantity">{{ quantity(row.pendingOutboundMilli) }}</td><td class="quantity">{{ quantity(row.availableMilli) }}</td><td class="quantity">{{ quantity(row.inTransitMilli) }}</td><td class="quantity">{{ quantity(row.safetyMinimumMilli, row.sku?.baseUnitName) }}</td><td><span class="inv-status" :class="`inv-status-${row.status}`">{{ statusLabel[row.status] }}</span></td><td class="money">{{ money(row.costPerBaseUnitCents) }}</td><td class="money">{{ money(row.amountCents) }}</td><td><RouterLink :to="`/inventory/stocks/${row.warehouse.id}/${row.skuId}`">详情</RouterLink><button v-if="canWrite" class="text-button" type="button" @click="openThreshold(row)">设置阈值</button></td></tr></tbody></table></div><footer class="inventory-pagination"><span>第 {{ workspace.stocks.page }} 页</span><button class="inv-button" :disabled="workspace.stocks.page <= 1" @click="store.applyQuery({ ...store.query, page: workspace.stocks.page - 1 })">上一页</button><button class="inv-button" :disabled="workspace.stocks.page * 30 >= workspace.stocks.total" @click="store.applyQuery({ ...store.query, page: workspace.stocks.page + 1 })">下一页</button></footer></template>
      </section>
    </div>
    <div v-if="thresholdRow" class="inventory-modal"><form class="inventory-panel inventory-form inventory-modal__card" @submit.prevent="saveThreshold"><div class="wide"><h2>设置库存阈值</h2><p>{{ thresholdRow.warehouse.name }} · {{ thresholdRow.sku?.productName ?? thresholdRow.skuId }}</p><small>订单待出库未接入前，库存状态保持“数据源未接入”。</small></div><label>安全下限（基本单位）<input v-model="thresholdMinimum" type="number" min="0" step="0.001" required></label><label>超储上限（可空）<input v-model="thresholdMaximum" type="number" min="0" step="0.001"></label><div class="inventory-form-actions"><button class="inv-button" type="button" @click="thresholdRow = null">取消</button><button class="inv-button primary" :disabled="store.saving">保存阈值</button></div></form></div>
  </section>
</template>
