<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useRoute, useRouter } from 'vue-router'
import InventorySubnav from '../components/InventorySubnav.vue'
import { useInventoryStore } from '../runtime/inventory-store'
import type { ProcessingListQuery, ProcessingOrder, ProcessingRecipeDraft } from '../types'
import './inventory-views.css'

type Section = 'recipes' | 'plans' | 'orders' | 'picks' | 'returns' | 'yields'
const props = defineProps<{ section: Section }>()
const store = useInventoryStore(); const route = useRoute(); const router = useRouter()
const { workspace, processingSkus, processingRecipes, processingPlans, processingOrders, materialPicks, materialReturns, processingYields, eligibleProcessingOrders, processingOrderProviderState, loading, saving, error, canWrite, actor } = storeToRefs(store)
const showForm = ref(false); const showImport = ref(false); const importText = ref(''); const importErrors = ref<string[]>([]); const importPreviewValid = ref(false); const message = ref(''); const completionOrderId = ref(''); const selectedPlanId = ref('')
const filters = reactive({ status: String(route.query.status ?? ''), fromDate: String(route.query.fromDate ?? ''), toDate: String(route.query.toDate ?? ''), keyword: String(route.query.keyword ?? '') })
const meta = computed(() => ({
  recipes: ['加工配方', '定义成品/半成品与原料比例，历史计划和加工单保存配方快照。'],
  plans: ['加工计划', '支持直接计划与按销售订单剩余数量创建计划。'],
  orders: ['加工单', '从待领料到完工入库，完整追踪领料、退料、产出与成本。'],
  picks: ['加工领料单', '按 FIFO 分批领料；确认后原子扣减原料库存。'],
  returns: ['加工退料单', '只退本加工单原领料批次，按原成本回库。'],
  yields: ['原料出成率', '按加工单、产出和原料复算实际用量与出成率。'],
}[props.section]))
const query = (): ProcessingListQuery => ({ status: filters.status || undefined, fromDate: filters.fromDate || undefined, toDate: filters.toDate || undefined, keyword: filters.keyword.trim() || undefined, page: 1, pageSize: 30 })
const skuName = (id: string) => { const sku = processingSkus.value.find((item) => item.skuId === id); return sku ? `${sku.productName} · ${sku.skuCode} · ${sku.specification}` : id }
const warehouseName = (id: string) => workspace.value.warehouses.find((item) => item.id === id)?.name ?? id
const orderName = (id: string) => processingOrders.value.find((item) => item.id === id)?.code ?? id
const primaryOutput = (order: ProcessingOrder) => order.outputs.find((line) => order.recipeSnapshot.outputs.find((item) => item.id === line.recipeLineId)?.primary) ?? order.outputs[0]
const statusName = (status: string) => ({ pending: '待处理', processing: '加工中', completed: '已完成', cancelled: '已取消', 'pending-picking': '待领料', picking: '领料中', 'pending-outbound': '待出库', outbound: '已出库', 'pending-inbound': '待入库', inbound: '已入库' }[status] ?? status)
const quantity = (milli: number | null | undefined) => milli === null || milli === undefined ? '—' : (milli / 1000).toFixed(3).replace(/\.000$/, '')
const download = (content: string, filename: string) => { const url = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url) }

const recipeForm = reactive<{ code: string; name: string; method: ProcessingRecipeDraft['method']; category: string; note: string; outputs: Array<{ skuId: string; quantity: number; warehouseId: string; primary: boolean; allocation: number }>; materials: Array<{ skuId: string; quantity: number; warehouseId: string }> }>({ code: '', name: '', method: 'combination', category: '', note: '', outputs: [{ skuId: '', quantity: 1, warehouseId: '', primary: true, allocation: 100 }], materials: [{ skuId: '', quantity: 1, warehouseId: '' }] })
const planForm = reactive({ sourceType: 'direct' as 'direct' | 'sales-order', orderId: '', orderLineId: '', recipeId: '', plannedAt: '2026-08-10T10:00', quantity: 1, warehouseId: '', note: '' })
const orderForm = reactive({ planId: '', recipeId: '', quantity: 1, warehouseId: '', note: '' })
const pickForm = reactive({ orderId: '', warehouseId: '', occurredAt: '2026-08-10T10:00', quantities: {} as Record<string, number>, note: '' })
const returnForm = reactive({ orderId: '', warehouseId: '', occurredAt: '2026-08-10T10:00', quantities: {} as Record<string, number>, locationId: '', note: '' })
const completionForm = reactive({ occurredAt: '2026-08-10T10:00', outputs: {} as Record<string, { quantity: number; locationId: string; batchNumber: string; productionDate: string }>, returnWarehouseId: '', returnLocationId: '', finalReturns: {} as Record<string, number> })
const selectedSourceOrder = computed(() => eligibleProcessingOrders.value.find((item) => item.orderId === planForm.orderId))
const selectedPlan = computed(() => processingPlans.value.find((item) => item.id === selectedPlanId.value) ?? processingPlans.value[0] ?? null)
const selectedPickOrder = computed(() => processingOrders.value.find((item) => item.id === pickForm.orderId))
const selectedReturnOrder = computed(() => processingOrders.value.find((item) => item.id === returnForm.orderId))
const selectedCompletionOrder = computed(() => processingOrders.value.find((item) => item.id === completionOrderId.value))
const returnMovements = computed(() => {
  const order = selectedReturnOrder.value; if (!order) return []
  const pickIds = new Set(materialPicks.value.filter((item) => item.processingOrderId === order.id && item.status === 'outbound').map((item) => item.id))
  const alreadyReturned = new Map<string, number>()
  materialReturns.value.filter((item) => item.processingOrderId === order.id && item.status === 'inbound').flatMap((item) => item.lines).forEach((line) => alreadyReturned.set(line.pickMovementId, (alreadyReturned.get(line.pickMovementId) ?? 0) + line.quantityMilli))
  return workspace.value.movements.filter((item) => item.direction === 'outbound' && item.sourceType === 'processing-material-pick' && pickIds.has(item.sourceId)).map((item) => ({ ...item, remainingMilli: item.quantityMilli - (alreadyReturned.get(item.id) ?? 0), materialLineId: order.materials.find((line) => line.skuId === item.skuId)?.id ?? '' })).filter((item) => item.remainingMilli > 0)
})
const completionReturnMovements = computed(() => {
  const order = selectedCompletionOrder.value; if (!order) return []
  const pickIds = new Set(materialPicks.value.filter((item) => item.processingOrderId === order.id && item.status === 'outbound').map((item) => item.id)); const alreadyReturned = new Map<string, number>()
  materialReturns.value.filter((item) => item.processingOrderId === order.id && item.status === 'inbound').flatMap((item) => item.lines).forEach((line) => alreadyReturned.set(line.pickMovementId, (alreadyReturned.get(line.pickMovementId) ?? 0) + line.quantityMilli))
  return workspace.value.movements.filter((item) => item.direction === 'outbound' && item.sourceType === 'processing-material-pick' && pickIds.has(item.sourceId) && (!completionForm.returnWarehouseId || item.warehouseId === completionForm.returnWarehouseId)).map((item) => ({ ...item, remainingMilli: item.quantityMilli - (alreadyReturned.get(item.id) ?? 0), materialLineId: order.materials.find((line) => line.skuId === item.skuId)?.id ?? '' })).filter((item) => item.remainingMilli > 0)
})

function normalizeDate(value: string) { return value.length === 16 ? `${value}:00+08:00` : value }
function resetDefaults() {
  const warehouse = workspace.value.warehouses.find((item) => item.status === 'enabled')?.id ?? ''
  recipeForm.outputs.forEach((item) => { item.warehouseId ||= warehouse }); recipeForm.materials.forEach((item) => { item.warehouseId ||= warehouse })
  planForm.warehouseId ||= warehouse; orderForm.warehouseId ||= warehouse; pickForm.warehouseId ||= warehouse; returnForm.warehouseId ||= warehouse
  returnForm.locationId ||= workspace.value.locations.find((item) => item.warehouseId === returnForm.warehouseId && item.status === 'enabled')?.id ?? ''
}
async function loadSection(updateUrl = false) {
  if (updateUrl) await router.replace({ query: { status: filters.status || undefined, fromDate: filters.fromDate || undefined, toDate: filters.toDate || undefined, keyword: filters.keyword.trim() || undefined } })
  const loaders = { recipes: store.loadProcessingRecipes, plans: store.loadProcessingPlans, orders: store.loadProcessingOrders, picks: store.loadMaterialPicks, returns: store.loadMaterialReturns, yields: store.loadProcessingYields }
  await loaders[props.section](query())
}
async function initialize() { await store.load(); await Promise.all([store.loadProcessingCatalog(), store.loadProcessingRecipes(), store.loadProcessingPlans(), store.loadProcessingOrders(), store.loadMaterialPicks(), store.loadMaterialReturns(), store.loadEligibleProcessingOrders()]); resetDefaults(); await loadSection() }
async function act(operation: () => Promise<void>, success: string) { message.value = ''; try { await operation(); message.value = success; showForm.value = false; await store.load(); await loadSection() } catch (caught) { message.value = caught instanceof Error ? caught.message : '操作失败' } }
async function saveRecipe() { await act(() => store.saveProcessingRecipe({ code: recipeForm.code, name: recipeForm.name, method: recipeForm.method, category: recipeForm.category || null, note: recipeForm.note || null, outputs: recipeForm.outputs.map((item) => ({ skuId: item.skuId, quantityMilli: Math.round(item.quantity * 1000), warehouseId: item.warehouseId, primary: item.primary, costAllocationBasisPoints: Math.round(item.allocation * 100) })), materials: recipeForm.materials.map((item) => ({ skuId: item.skuId, quantityMilli: Math.round(item.quantity * 1000), warehouseId: item.warehouseId })) }), '加工配方已保存') }
async function savePlan() { await act(() => store.createProcessingPlan({ sourceType: planForm.sourceType, salesOrderId: planForm.sourceType === 'sales-order' ? planForm.orderId : null, salesOrderLineId: planForm.sourceType === 'sales-order' ? planForm.orderLineId : null, recipeId: planForm.recipeId, plannedAt: normalizeDate(planForm.plannedAt), plannedQuantityMilli: Math.round(planForm.quantity * 1000), processingWarehouseId: planForm.warehouseId, note: planForm.note }), '加工计划已创建') }
async function saveOrder() { const plan = processingPlans.value.find((item) => item.id === orderForm.planId); const committed = plan ? processingOrders.value.filter((item) => item.planId === plan.id).reduce((sum,item)=>sum+item.plannedQuantityMilli,0) : 0; await act(() => store.createProcessingOrder({ planId: plan?.id ?? null, recipeId: plan?.recipeSnapshot.id ?? orderForm.recipeId, plannedQuantityMilli: plan ? Math.max(1, plan.plannedQuantityMilli - committed) : Math.round(orderForm.quantity * 1000), processingWarehouseId: plan?.processingWarehouseId ?? orderForm.warehouseId, note: orderForm.note }), '加工单已创建') }
async function savePick() { const order = selectedPickOrder.value!; const lines = order.materials.filter((item) => item.warehouseId === pickForm.warehouseId).map((item) => ({ materialLineId: item.id, actualQuantityMilli: Math.round((pickForm.quantities[item.id] ?? 0) * 1000) })).filter((item) => item.actualQuantityMilli > 0); await act(() => store.createMaterialPick({ processingOrderId: order.id, warehouseId: pickForm.warehouseId, occurredAt: normalizeDate(pickForm.occurredAt), lines, note: pickForm.note }), '领料单已创建') }
async function saveReturn() { const order = selectedReturnOrder.value!; const lines = returnMovements.value.map((item) => ({ materialLineId: item.materialLineId, pickMovementId: item.id, quantityMilli: Math.round((returnForm.quantities[item.id] ?? 0) * 1000), locationId: returnForm.locationId })).filter((item) => item.quantityMilli > 0); await act(() => store.createMaterialReturn({ processingOrderId: order.id, warehouseId: returnForm.warehouseId, occurredAt: normalizeDate(returnForm.occurredAt), lines, note: returnForm.note }), '退料单已创建') }
function openCompletion(order: ProcessingOrder) { completionOrderId.value = order.id; completionForm.outputs = {}; completionForm.finalReturns = {}; completionForm.returnWarehouseId = order.materials[0]?.warehouseId ?? order.processingWarehouseId; completionForm.returnLocationId = workspace.value.locations.find((item) => item.warehouseId === completionForm.returnWarehouseId && item.status === 'enabled')?.id ?? ''; order.outputs.forEach((line) => { const sku = processingSkus.value.find((item) => item.skuId === line.skuId); completionForm.outputs[line.id] = { quantity: line.plannedQuantityMilli / 1000, locationId: workspace.value.locations.find((item) => item.warehouseId === line.warehouseId && item.status === 'enabled')?.id ?? '', batchNumber: `PROCESS-${order.code}-${line.skuId}`, productionDate: sku?.manageProductionDate || sku?.shelfLifeDays !== null ? '2026-08-10' : '' } }) }
async function complete() { const order = selectedCompletionOrder.value!; const finalLines = completionReturnMovements.value.map((item) => ({ materialLineId: item.materialLineId, pickMovementId: item.id, quantityMilli: Math.round((completionForm.finalReturns[item.id] ?? 0) * 1000), locationId: completionForm.returnLocationId })).filter((item) => item.quantityMilli > 0); await act(() => store.completeProcessingOrder({ requestId: `ui-complete-${order.id}-${order.version}`, processingOrderId: order.id, expectedVersion: order.version, occurredAt: normalizeDate(completionForm.occurredAt), outputs: order.outputs.map((line) => ({ outputLineId: line.id, actualQuantityMilli: Math.round(completionForm.outputs[line.id]!.quantity * 1000), locationId: completionForm.outputs[line.id]!.locationId, batchNumber: completionForm.outputs[line.id]!.batchNumber || null, productionDate: completionForm.outputs[line.id]!.productionDate || null })), finalReturn: finalLines.length ? { processingOrderId: order.id, warehouseId: completionForm.returnWarehouseId, occurredAt: normalizeDate(completionForm.occurredAt), lines: finalLines, note: '完工时最终退料' } : null }), '加工单已完工'); completionOrderId.value = '' }
function addOutput() { recipeForm.outputs.push({ skuId: '', quantity: 1, warehouseId: workspace.value.warehouses[0]?.id ?? '', primary: false, allocation: 0 }) }
function addMaterial() { recipeForm.materials.push({ skuId: '', quantity: 1, warehouseId: workspace.value.warehouses[0]?.id ?? '' }) }
function selectPrimary(index: number) { recipeForm.outputs.forEach((item, current) => { item.primary = current === index }) }
function exportCurrent() { if (props.section === 'orders') download(store.exportProcessingOrders(query()), 'processing-orders.csv'); if (props.section === 'yields') download(store.exportProcessingYields(query()), 'processing-yields.csv') }
function parseImport(): ProcessingRecipeDraft[] { const parsed: unknown = JSON.parse(importText.value); if (!Array.isArray(parsed)) throw new Error('导入内容必须是配方数组'); return parsed as ProcessingRecipeDraft[] }
function previewImport() { try { const result = store.previewProcessingRecipeImport(parseImport()); importErrors.value = result.errors; importPreviewValid.value = result.valid; message.value = result.valid ? `预览通过：${result.rows} 条配方，尚未写入` : '导入预览未通过' } catch (caught) { importPreviewValid.value = false; importErrors.value = [caught instanceof Error ? caught.message : '导入内容无法解析'] } }
async function confirmImport() { if (!importPreviewValid.value) return; try { const drafts = parseImport(); const preview = store.previewProcessingRecipeImport(drafts); importErrors.value = preview.errors; if (!preview.valid) { importPreviewValid.value = false; return } await store.importProcessingRecipes(drafts); showImport.value = false; message.value = `已原子导入 ${preview.rows} 条配方`; await loadSection() } catch (caught) { importPreviewValid.value = false; importErrors.value = [caught instanceof Error ? caught.message : '导入失败'] } }
watch(() => props.section, () => { showForm.value = false; message.value = ''; loadSection() })
watch(importText, () => { importPreviewValid.value = false; importErrors.value = [] })
watch(() => planForm.orderLineId, (id) => { const line = selectedSourceOrder.value?.lines.find((item) => item.orderLineId === id); if (line) planForm.quantity = line.remainingQuantityMilli / 1000 })
watch(() => completionForm.returnWarehouseId, (warehouseId) => { completionForm.returnLocationId = workspace.value.locations.find((item) => item.warehouseId === warehouseId && item.status === 'enabled')?.id ?? '' })
onMounted(initialize)
</script>

<template>
  <section class="inventory-page processing-page">
    <header class="inventory-header"><div><p class="eyebrow">INV-004 · 加工管理</p><h1>{{ meta[0] }}</h1><p>{{ meta[1] }}</p></div><div class="processing-role">当前角色：{{ actor.role }}</div></header>
    <InventorySubnav />
    <form class="inventory-toolbar processing-toolbar" @submit.prevent="loadSection(true)"><label v-if="section !== 'recipes' && section !== 'yields'">状态<select v-model="filters.status"><option value="">全部</option><option v-for="item in ['pending','processing','completed','cancelled','pending-picking','picking','pending-outbound','outbound','pending-inbound','inbound']" :key="item" :value="item">{{ statusName(item) }}</option></select></label><label v-if="section !== 'recipes'">开始日期<input v-model="filters.fromDate" type="date" /></label><label v-if="section !== 'recipes'">结束日期<input v-model="filters.toDate" type="date" /></label><label>关键字<input v-model="filters.keyword" placeholder="单号 / 配方 / 商品" /></label><button class="inv-button primary" type="submit">查询</button><button class="inv-button" type="button" @click="loadSection()">刷新</button><button v-if="canWrite && ['orders','yields'].includes(section)" class="inv-button" type="button" @click="exportCurrent">导出 CSV</button><button v-if="canWrite && section === 'recipes'" class="inv-button" type="button" @click="showImport = true">导入</button><button v-if="canWrite && section !== 'yields'" class="inv-button primary" type="button" @click="showForm = true">新增</button></form>
    <p v-if="message" class="inventory-warning">{{ message }}</p><div v-if="error" class="inventory-state error"><strong>{{ meta[0] }}加载失败</strong><span>{{ error }}</span><button class="inv-button" @click="loadSection()">重试</button></div><div v-else-if="loading" class="inventory-state">正在加载{{ meta[0] }}…</div>

    <template v-else-if="section === 'recipes'"><div v-if="!processingRecipes.length" class="inventory-state"><strong>暂无加工配方</strong><span>请先建立 BOM 配方。</span></div><div v-else class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>配方名称</th><th>编码</th><th>方式</th><th>分类</th><th>主产出</th><th>原料数</th><th>版本</th><th>操作</th></tr></thead><tbody><tr v-for="item in processingRecipes" :key="item.id"><td><strong>{{ item.name }}</strong></td><td>{{ item.code }}</td><td>{{ { combination:'组合',disassembly:'拆卸',assembly:'组装' }[item.method] }}</td><td>{{ item.category ?? '—' }}</td><td>{{ skuName(item.outputs.find(line => line.primary)!.skuId) }}</td><td>{{ item.materials.length }}</td><td>v{{ item.version }}</td><td><button v-if="canWrite" class="inv-button" @click="act(() => store.deleteProcessingRecipe(item.id), '配方已删除')">删除</button></td></tr></tbody></table></div></template>
    <template v-else-if="section === 'plans'"><div v-if="!processingPlans.length" class="inventory-state"><strong>暂无加工计划</strong><span>可直接创建或从销售订单创建。</span></div><div v-else class="processing-split"><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>计划单号</th><th>计划时间</th><th>配方</th><th>计划数量</th><th>已完工</th><th>来源</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in processingPlans" :key="item.id" :class="{ 'processing-selected': selectedPlan?.id===item.id }" @click="selectedPlanId=item.id"><td><strong>{{ item.code }}</strong></td><td>{{ item.plannedAt.slice(0,16).replace('T',' ') }}</td><td>{{ item.recipeSnapshot.name }}</td><td>{{ quantity(item.plannedQuantityMilli) }}</td><td>{{ quantity(item.completedPrimaryQuantityMilli) }}</td><td>{{ item.sourceOrder?.orderNo ?? '直接计划' }}</td><td>{{ statusName(item.status) }}</td><td><button v-if="canWrite && item.status === 'pending'" class="inv-button" @click.stop="act(() => store.cancelProcessingPlan(item), '计划已取消')">取消</button></td></tr></tbody></table></div><aside v-if="selectedPlan" class="processing-detail"><h2>{{ selectedPlan.code }}</h2><p>{{ selectedPlan.recipeSnapshot.name }} · {{ statusName(selectedPlan.status) }}</p><dl><dt>来源</dt><dd>{{ selectedPlan.sourceOrder?.orderNo ?? '直接计划' }}</dd><dt>计划/已完成</dt><dd>{{ quantity(selectedPlan.plannedQuantityMilli) }} / {{ quantity(selectedPlan.completedPrimaryQuantityMilli) }}</dd><dt>加工仓库</dt><dd>{{ warehouseName(selectedPlan.processingWarehouseId) }}</dd></dl><h3>产出明细</h3><p v-for="line in selectedPlan.recipeSnapshot.outputs" :key="line.id">{{ skuName(line.skuId) }} · 配方量 {{ quantity(line.quantityMilli) }}<span v-if="line.primary"> · 主产出</span></p><h3>原料明细</h3><p v-for="line in selectedPlan.recipeSnapshot.materials" :key="line.id">{{ skuName(line.skuId) }} · 配方量 {{ quantity(line.quantityMilli) }}</p><h3>关联加工单</h3><p v-for="item in processingOrders.filter(x=>x.planId===selectedPlan!.id)" :key="item.id">{{ item.code }} · {{ statusName(item.status) }}</p><p v-if="!processingOrders.some(x=>x.planId===selectedPlan!.id)" class="status-muted">暂无关联加工单</p></aside></div></template>
    <template v-else-if="section === 'orders'"><div v-if="!processingOrders.length" class="inventory-state"><strong>暂无加工单</strong><span>从计划或配方创建加工任务。</span></div><div v-else class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>加工单号</th><th>创建时间</th><th>配方</th><th>主产出</th><th>计划数量</th><th>实际数量</th><th>领/退料</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in processingOrders" :key="item.id"><td><strong>{{ item.code }}</strong></td><td>{{ item.createdAt.slice(0,16).replace('T',' ') }}</td><td>{{ item.recipeSnapshot.name }}</td><td>{{ skuName(primaryOutput(item)!.skuId) }}</td><td>{{ quantity(item.plannedQuantityMilli) }}</td><td>{{ quantity(primaryOutput(item)?.actualQuantityMilli) }}</td><td>{{ quantity(item.materials.reduce((s,l)=>s+l.pickedQuantityMilli,0)) }} / {{ quantity(item.materials.reduce((s,l)=>s+l.returnedQuantityMilli,0)) }}</td><td>{{ statusName(item.status) }}</td><td><button v-if="canWrite && item.status === 'pending-picking'" class="inv-button" @click="act(() => store.deleteProcessingOrder(item), '加工单已删除')">删除</button><button v-if="canWrite && item.status === 'processing'" class="inv-button primary" @click="openCompletion(item)">完工</button></td></tr></tbody></table></div></template>
    <template v-else-if="section === 'picks'"><div v-if="!materialPicks.length" class="inventory-state"><strong>暂无加工领料单</strong><span>选择待领料或领料中的加工单创建。</span></div><div v-else class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>领料单号</th><th>加工单</th><th>仓库</th><th>领料时间</th><th>明细</th><th>实际领料</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in materialPicks" :key="item.id"><td><strong>{{ item.code }}</strong></td><td>{{ orderName(item.processingOrderId) }}</td><td>{{ warehouseName(item.warehouseId) }}</td><td>{{ item.occurredAt.slice(0,16).replace('T',' ') }}</td><td>{{ item.lines.length }}</td><td>{{ quantity(item.lines.reduce((s,l)=>s+l.actualQuantityMilli,0)) }}</td><td>{{ statusName(item.status) }}</td><td><button v-if="canWrite && item.status === 'pending-outbound'" class="inv-button primary" :disabled="saving" @click="act(() => store.confirmMaterialPick(item), '领料已确认出库')">确认出库</button></td></tr></tbody></table></div></template>
    <template v-else-if="section === 'returns'"><div v-if="!materialReturns.length" class="inventory-state"><strong>暂无加工退料单</strong><span>退料必须引用本加工单的原领料流水。</span></div><div v-else class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>退料单号</th><th>加工单</th><th>仓库</th><th>退料时间</th><th>明细</th><th>退料数量</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in materialReturns" :key="item.id"><td><strong>{{ item.code }}</strong></td><td>{{ orderName(item.processingOrderId) }}</td><td>{{ warehouseName(item.warehouseId) }}</td><td>{{ item.occurredAt.slice(0,16).replace('T',' ') }}</td><td>{{ item.lines.length }}</td><td>{{ quantity(item.lines.reduce((s,l)=>s+l.quantityMilli,0)) }}</td><td>{{ statusName(item.status) }}</td><td><button v-if="canWrite && item.status === 'pending-inbound'" class="inv-button primary" :disabled="saving" @click="act(() => store.confirmMaterialReturn(item), '退料已确认入库')">确认入库</button></td></tr></tbody></table></div></template>
    <template v-else><div v-if="!processingYields.length" class="inventory-state"><strong>暂无出成率数据</strong><span>加工单完工后自动形成统计。</span></div><div v-else class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>加工单</th><th>创建时间</th><th>配方</th><th>产出</th><th>原料</th><th>配方原料量</th><th>实际用量</th><th>实际产出</th><th>预计产出</th><th>出成率</th></tr></thead><tbody><tr v-for="item in processingYields" :key="item.id"><td><strong>{{ item.processingOrderCode }}</strong></td><td>{{ item.createdAt.slice(0,16).replace('T',' ') }}</td><td>{{ item.recipeName }}</td><td>{{ skuName(item.outputSkuId) }}</td><td>{{ skuName(item.materialSkuId) }}</td><td>{{ quantity(item.formulaMaterialQuantityMilli) }}</td><td>{{ quantity(item.actualUsedQuantityMilli) }}</td><td>{{ quantity(item.actualOutputQuantityMilli) }}</td><td>{{ quantity(item.expectedOutputQuantityMilli) }}</td><td>{{ item.yieldBasisPoints === null ? 'unavailable' : `${(item.yieldBasisPoints/100).toFixed(2)}%` }}</td></tr></tbody></table></div></template>

    <div v-if="showForm" class="inventory-dialog"><section><header><strong>新增{{ meta[0] }}</strong><button class="inv-button" @click="showForm=false">关闭</button></header>
      <form v-if="section === 'recipes'" class="inventory-form processing-form" @submit.prevent="saveRecipe"><label>配方编码<input v-model="recipeForm.code" maxlength="40" required /></label><label>配方名称<input v-model="recipeForm.name" maxlength="100" required /></label><label>加工方式<select v-model="recipeForm.method"><option value="combination">组合</option><option value="disassembly">拆卸</option><option value="assembly">组装</option></select></label><label>分类<input v-model="recipeForm.category" maxlength="100" /></label><fieldset class="wide processing-lines"><legend>产出明细</legend><div v-for="(line,index) in recipeForm.outputs" :key="index" class="processing-line"><select v-model="line.skuId" required><option value="">选择产出商品</option><option v-for="sku in processingSkus" :key="sku.skuId" :value="sku.skuId">{{ skuName(sku.skuId) }}</option></select><input v-model.number="line.quantity" type="number" min="0.001" step="0.001" aria-label="产出数量" required /><select v-model="line.warehouseId" required><option v-for="w in workspace.warehouses.filter(x=>x.status==='enabled')" :key="w.id" :value="w.id">{{ w.name }}</option></select><label><input :checked="line.primary" type="radio" name="primary" @change="selectPrimary(index)" />主产出</label><input v-model.number="line.allocation" type="number" min="0" max="100" step="0.01" aria-label="成本分摊百分比" /><button v-if="recipeForm.outputs.length>1" class="inv-button" type="button" @click="recipeForm.outputs.splice(index,1)">移除</button></div><button class="inv-button" type="button" @click="addOutput">添加产出</button></fieldset><fieldset class="wide processing-lines"><legend>原料明细</legend><div v-for="(line,index) in recipeForm.materials" :key="index" class="processing-line"><select v-model="line.skuId" required><option value="">选择原料商品</option><option v-for="sku in processingSkus" :key="sku.skuId" :value="sku.skuId">{{ skuName(sku.skuId) }}</option></select><input v-model.number="line.quantity" type="number" min="0.001" step="0.001" aria-label="原料数量" required /><select v-model="line.warehouseId" required><option v-for="w in workspace.warehouses.filter(x=>x.status==='enabled')" :key="w.id" :value="w.id">{{ w.name }}</option></select><button v-if="recipeForm.materials.length>1" class="inv-button" type="button" @click="recipeForm.materials.splice(index,1)">移除</button></div><button class="inv-button" type="button" @click="addMaterial">添加原料</button></fieldset><label class="wide">备注<textarea v-model="recipeForm.note" maxlength="500" /></label><button class="inv-button primary wide" :disabled="saving" type="submit">保存配方</button></form>
      <form v-else-if="section === 'plans'" class="inventory-form" @submit.prevent="savePlan"><label>来源<select v-model="planForm.sourceType"><option value="direct">直接创建</option><option value="sales-order">按销售订单</option></select></label><label v-if="planForm.sourceType==='sales-order'">销售订单<select v-model="planForm.orderId" required><option value="">请选择</option><option v-for="item in eligibleProcessingOrders" :key="item.orderId" :value="item.orderId">{{ item.orderNo }} · {{ item.customerName }}</option></select><small v-if="processingOrderProviderState==='unavailable'">销售订单数据源 unavailable</small></label><label v-if="planForm.sourceType==='sales-order'">订单商品<select v-model="planForm.orderLineId" required><option value="">请选择</option><option v-for="line in selectedSourceOrder?.lines ?? []" :key="line.orderLineId" :value="line.orderLineId">{{ line.productName }} · 剩余 {{ quantity(line.remainingQuantityMilli) }}</option></select></label><label>配方<select v-model="planForm.recipeId" required><option value="">请选择</option><option v-for="item in processingRecipes.filter(recipe => planForm.sourceType==='direct' || recipe.outputs.find(x=>x.primary)?.skuId === selectedSourceOrder?.lines.find(x=>x.orderLineId===planForm.orderLineId)?.skuId)" :key="item.id" :value="item.id">{{ item.code }} · {{ item.name }}</option></select></label><label>计划时间<input v-model="planForm.plannedAt" type="datetime-local" required /></label><label>主产出数量<input v-model.number="planForm.quantity" type="number" min="0.001" step="0.001" required /></label><label>加工仓库<select v-model="planForm.warehouseId" required><option v-for="w in workspace.warehouses.filter(x=>x.status==='enabled')" :key="w.id" :value="w.id">{{ w.name }}</option></select></label><label class="wide">备注<textarea v-model="planForm.note" maxlength="500" /></label><button class="inv-button primary wide" :disabled="saving" type="submit">创建计划</button></form>
      <form v-else-if="section === 'orders'" class="inventory-form" @submit.prevent="saveOrder"><label>关联计划（可选）<select v-model="orderForm.planId"><option value="">不关联计划</option><option v-for="item in processingPlans.filter(x=>['pending','processing'].includes(x.status))" :key="item.id" :value="item.id">{{ item.code }} · {{ item.recipeSnapshot.name }}</option></select></label><label v-if="!orderForm.planId">配方<select v-model="orderForm.recipeId" required><option value="">请选择</option><option v-for="item in processingRecipes" :key="item.id" :value="item.id">{{ item.code }} · {{ item.name }}</option></select></label><label v-if="!orderForm.planId">计划数量<input v-model.number="orderForm.quantity" type="number" min="0.001" step="0.001" required /></label><label v-if="!orderForm.planId">加工仓库<select v-model="orderForm.warehouseId" required><option v-for="w in workspace.warehouses.filter(x=>x.status==='enabled')" :key="w.id" :value="w.id">{{ w.name }}</option></select></label><label class="wide">备注<textarea v-model="orderForm.note" maxlength="500" /></label><button class="inv-button primary wide" :disabled="saving" type="submit">创建加工单</button></form>
      <form v-else-if="section === 'picks'" class="inventory-form processing-form" @submit.prevent="savePick"><label>加工单<select v-model="pickForm.orderId" required><option value="">请选择</option><option v-for="item in processingOrders.filter(x=>['pending-picking','picking'].includes(x.status))" :key="item.id" :value="item.id">{{ item.code }} · {{ item.recipeSnapshot.name }}</option></select></label><label>领料仓库<select v-model="pickForm.warehouseId" required><option v-for="w in workspace.warehouses.filter(x=>x.status==='enabled')" :key="w.id" :value="w.id">{{ w.name }}</option></select></label><label>领料时间<input v-model="pickForm.occurredAt" type="datetime-local" required /></label><fieldset class="wide processing-lines"><legend>待领原料</legend><div v-for="line in selectedPickOrder?.materials.filter(x=>x.warehouseId===pickForm.warehouseId) ?? []" :key="line.id" class="processing-line"><span>{{ skuName(line.skuId) }}</span><span>需求 {{ quantity(line.requiredQuantityMilli) }} / 已领 {{ quantity(line.pickedQuantityMilli) }}</span><input v-model.number="pickForm.quantities[line.id]" type="number" min="0" :max="(line.requiredQuantityMilli-line.pickedQuantityMilli)/1000" step="0.001" aria-label="实际领料数量" /></div></fieldset><label class="wide">备注<textarea v-model="pickForm.note" maxlength="500" /></label><button class="inv-button primary wide" :disabled="saving" type="submit">创建领料单</button></form>
      <form v-else-if="section === 'returns'" class="inventory-form processing-form" @submit.prevent="saveReturn"><label>加工单<select v-model="returnForm.orderId" required><option value="">请选择</option><option v-for="item in processingOrders.filter(x=>['picking','processing'].includes(x.status))" :key="item.id" :value="item.id">{{ item.code }} · {{ item.recipeSnapshot.name }}</option></select></label><label>退料仓库<select v-model="returnForm.warehouseId" required><option v-for="w in workspace.warehouses.filter(x=>x.status==='enabled')" :key="w.id" :value="w.id">{{ w.name }}</option></select></label><label>退料库位<select v-model="returnForm.locationId" required><option v-for="l in workspace.locations.filter(x=>x.warehouseId===returnForm.warehouseId&&x.status==='enabled')" :key="l.id" :value="l.id">{{ l.name }}</option></select></label><label>退料时间<input v-model="returnForm.occurredAt" type="datetime-local" required /></label><fieldset class="wide processing-lines"><legend>可退原领料批次</legend><div v-for="item in returnMovements" :key="item.id" class="processing-line"><span>{{ skuName(item.skuId) }} · {{ item.batchNumber }}</span><span>可退 {{ quantity(item.remainingMilli) }} · 原成本 {{ item.costPerBaseUnitCents/100 }}</span><input v-model.number="returnForm.quantities[item.id]" type="number" min="0" :max="item.remainingMilli/1000" step="0.001" aria-label="退料数量" /></div></fieldset><label class="wide">备注<textarea v-model="returnForm.note" maxlength="500" /></label><button class="inv-button primary wide" :disabled="saving" type="submit">创建退料单</button></form>
    </section></div>
    <div v-if="completionOrderId && selectedCompletionOrder" class="inventory-dialog"><section><header><strong>完工：{{ selectedCompletionOrder.code }}</strong><button class="inv-button" @click="completionOrderId=''">关闭</button></header><form class="inventory-form processing-form" @submit.prevent="complete"><label>完工时间<input v-model="completionForm.occurredAt" type="datetime-local" required /></label><fieldset class="wide processing-lines"><legend>产出明细</legend><div v-for="line in selectedCompletionOrder.outputs" :key="line.id" class="processing-line"><span>{{ skuName(line.skuId) }} · 计划 {{ quantity(line.plannedQuantityMilli) }}</span><input v-model.number="completionForm.outputs[line.id].quantity" type="number" min="0.001" step="0.001" aria-label="实际产出数量" required /><select v-model="completionForm.outputs[line.id].locationId" required><option v-for="l in workspace.locations.filter(x=>x.warehouseId===line.warehouseId&&x.status==='enabled')" :key="l.id" :value="l.id">{{ l.name }}</option></select><input v-model="completionForm.outputs[line.id].batchNumber" placeholder="批次号" /><input v-model="completionForm.outputs[line.id].productionDate" type="date" aria-label="生产日期" /></div></fieldset><fieldset v-if="completionReturnMovements.length" class="wide processing-lines"><legend>最终退料（可选，与完工原子提交）</legend><div class="processing-line"><select v-model="completionForm.returnWarehouseId"><option v-for="w in workspace.warehouses.filter(x=>(selectedCompletionOrder?.materials ?? []).some(line=>line.warehouseId===x.id))" :key="w.id" :value="w.id">{{ w.name }}</option></select><select v-model="completionForm.returnLocationId"><option v-for="l in workspace.locations.filter(x=>x.warehouseId===completionForm.returnWarehouseId&&x.status==='enabled')" :key="l.id" :value="l.id">{{ l.name }}</option></select></div><div v-for="item in completionReturnMovements" :key="item.id" class="processing-line"><span>{{ skuName(item.skuId) }} · {{ item.batchNumber }}</span><span>可退 {{ quantity(item.remainingMilli) }}</span><input v-model.number="completionForm.finalReturns[item.id]" type="number" min="0" :max="item.remainingMilli/1000" step="0.001" aria-label="完工退料数量" /></div></fieldset><button class="inv-button primary wide" :disabled="saving" type="submit">确认完工并原子入库</button></form></section></div>
    <div v-if="showImport" class="inventory-dialog"><section><header><strong>导入加工配方（JSON 原型适配器）</strong><button class="inv-button" @click="showImport=false">关闭</button></header><p class="status-muted">粘贴配方草稿数组。必须先预览；任何一条错误时整批不会写入。</p><textarea v-model="importText" class="processing-import" aria-label="配方导入内容" placeholder='[{"code":"BOM-001","name":"示例配方","method":"combination","outputs":[...],"materials":[...]}]' /><ul v-if="importErrors.length" class="inventory-warning"><li v-for="item in importErrors" :key="item">{{ item }}</li></ul><div class="inventory-form-actions"><button class="inv-button" type="button" @click="previewImport">预览校验</button><button class="inv-button primary" :disabled="saving || !importPreviewValid" type="button" @click="confirmImport">确认整批导入</button></div></section></div>
  </section>
</template>
