import { describe,expect,it } from 'vitest'
import { createOrderMockSession } from '../../../../mock/handlers/order-handler'
import { createEmptyOrderDraft } from './order-service'
import type { OrderActor, OrderDraft } from '../types'

const admin:OrderActor={role:'super-admin',actorId:'admin-test'};const warehouse:OrderActor={role:'warehouse',actorId:'warehouse-test'};const finance:OrderActor={role:'finance',actorId:'finance-test'}
function setup(partial=false){const session=createOrderMockSession(partial?'partial-failure':'normal');return{repository:session.repository,service:session.service}}
function validDraft():OrderDraft{const draft=createEmptyOrderDraft('2026-08-10T09:00:00+08:00','staff-demo-1');draft.customerId='customer-1';draft.warehouseId='warehouse-main';draft.requestedDeliveryAt='2026-08-10T18:00:00+08:00';draft.deliveryMethod='logistics';draft.shipping={recipient:'演示收货人',phone:'000-0000-0999',province:'演示省',city:'演示市',district:'演示区',address:'演示收货地址（非真实地址）'};draft.lines=[{skuId:'sku-1',unitId:'unit-piece',quantity:21,lineKind:'sale',manualDealUnitPriceCents:null,reason:null,sourceKeys:[]}];return draft}

describe('order queries',()=>{
  it('paginates 30 rows with stable newest-first ordering',()=>{const {service}=setup();const page=service.listOrders(admin);expect(page.total).toBe(32);expect(page.items).toHaveLength(30);expect(page.items[0]!.order.id).toBe('order-032');expect(page.items[29]!.order.id).toBe('order-003');expect(service.listOrders(admin,{page:2}).items.map((item)=>item.order.id)).toEqual(['order-002','order-001'])})
  it('combines filters and includes category descendants',()=>{const {service}=setup();expect(service.listOrders(admin,{customerCategoryId:'category-retail'}).total).toBe(32);expect(service.listOrders(admin,{statuses:['approved'],keyword:'CUS-000002'}).items.every((item)=>item.order.status==='approved'&&item.order.customerSnapshot.code==='CUS-000002')).toBe(true);expect(service.listOrders(admin,{amountMinCents:3700,amountMaxCents:3800}).total).toBeGreaterThan(0)})
  it('treats orderedTo as exclusive',()=>{const {service}=setup();const result=service.listOrders(admin,{orderedFrom:'2026-08-10T00:00:00+08:00',orderedTo:'2026-08-11T00:00:00+08:00'});expect(result.items.map((item)=>item.order.id)).toEqual(['order-032'])})
})

describe('order permissions and providers',()=>{
  it('masks finance and warehouse at service boundary',()=>{const {service}=setup();const warehouseOrder=service.listOrders(warehouse).items[0]!.order;expect(warehouseOrder.amounts.orderAmountCents).toBeNull();expect(warehouseOrder.lines[0]!.dealUnitPriceCents).toBeNull();const financeOrder=service.listOrders(finance).items[0]!.order;expect(financeOrder.shippingSnapshot.phone).toBeNull();expect(financeOrder.shippingSnapshot.address).toBeNull();expect(()=>service.exportOrdersCsv(warehouse)).toThrowError(expect.objectContaining({code:'PERMISSION_DENIED'}))})
  it('keeps available finance and provider error distinct from zero',()=>{const normal=setup().service.getOrderDetail(admin,'order-001');expect(normal.financials.creditLimitCents).toMatchObject({state:'available',value:200000});expect(normal.financials.receivablesCents).toMatchObject({state:'available',value:50000});expect(normal.inventoryRecommendation).toMatchObject({state:'unavailable',value:null});const partial=setup(true).service.getOrderDetail(admin,'order-001');expect(partial.financials.creditLimitCents.state).toBe('error');expect(partial.financials.receivablesCents.state).toBe('error')})
})

describe('order outputs',()=>{
  it('exports selected rows before filtered results',()=>{const {service}=setup();const csv=service.exportOrdersCsv(admin,{},['order-001']);expect(csv).toContain('CA000000-260710-60001');expect(csv).not.toContain('CA000000-260711-60002');expect(csv).toContain('000-1000-0001')})
  it('prints atomically and idempotently by request id',()=>{const {service,repository}=setup();const before=repository.read().orders.find((item)=>item.id==='order-001')!.orderPrintCount;service.printOrders(admin,['order-001','order-002'],'print-1');expect(repository.read().orders.find((item)=>item.id==='order-001')!.orderPrintCount).toBe(before+1);const after=repository.read();service.printOrders(admin,['order-001','order-002'],'print-1');expect(repository.read()).toEqual(after)})
  it('does not partially print if one order is missing',()=>{const {service,repository}=setup();const before=repository.read();expect(()=>service.printOrders(admin,['order-001','missing'],'print-bad')).toThrowError(expect.objectContaining({code:'NOT_FOUND'}));expect(repository.read()).toEqual(before)})
})

describe('order creation and editing',()=>{
  it('creates a pending-review order with a deterministic number, snapshots and prepayment hold',()=>{const {service,repository}=setup();const before=repository.read().orders.length;const order=service.saveOrder(admin,{requestId:'save-create-1',draft:validDraft()});expect(order).toMatchObject({orderNo:'CA-260810-00001',status:'pending-order-review',customerSnapshot:{id:'customer-1'},fulfillmentWarehouseSnapshot:{id:'warehouse-main'},salespersonSnapshot:{id:'staff-demo-1'}});expect(order.amounts.orderAmountCents).toBeGreaterThanOrEqual(20000);expect(order.occupiedPrepaymentCents).toBe(order.amounts.orderAmountCents);expect(repository.read().orders).toHaveLength(before+1);expect(repository.read().nextOrderSequenceByDate).toEqual({'260810':2})})
  it('replays the same save request without consuming another number',()=>{const {service,repository}=setup();const first=service.saveOrder(admin,{requestId:'save-idempotent',draft:validDraft()});const state=repository.read();const second=service.saveOrder(admin,{requestId:'save-idempotent',draft:{...validDraft(),remark:'该变化不得生效'}});expect(second).toEqual(first);expect(repository.read()).toEqual(state)})
  it('only edits pending-review orders and rejects a stale version',()=>{const {service,repository}=setup();const editable=service.getEditableDraft(admin,'order-001');editable.draft.lines[0]!.quantity=21;const updated=service.saveOrder(admin,{requestId:'save-edit-1',orderId:'order-001',expectedUpdatedAt:editable.updatedAt,draft:editable.draft});expect(updated.orderNo).toBe('CA000000-260710-60001');expect(updated.activityLogs.at(-1)?.action).toBe('order.updated');expect(()=>service.saveOrder(admin,{requestId:'save-edit-stale',orderId:'order-001',expectedUpdatedAt:'2026-01-01T00:00:00+08:00',draft:editable.draft})).toThrowError(expect.objectContaining({code:'CONFLICT'}));expect(()=>service.getEditableDraft(admin,'order-002')).toThrowError(expect.objectContaining({code:'INVALID_STATE'}));expect(repository.read().orders.find((item)=>item.id==='order-001')?.orderNo).toBe('CA000000-260710-60001')})
  it('requires explicit fine-grained permissions and special-price acknowledgement',()=>{const noPrice:OrderActor={role:'salesperson',actorId:'staff-demo-1',permissions:['orders.create']};const {service}=setup();const draft=validDraft();draft.lines[0]!.quantity=23;draft.lines[0]!.manualDealUnitPriceCents=900;expect(()=>service.previewDraft(noPrice,draft)).toThrowError(expect.objectContaining({code:'PERMISSION_DENIED'}));expect(()=>service.previewDraft(admin,draft)).toThrowError(expect.objectContaining({code:'PRICE_OUT_OF_RANGE'}));draft.specialPrice=true;expect(service.previewDraft(admin,draft).lines[0]?.dealUnitPriceCents).toBe(900);expect(()=>service.getFormOptions(warehouse)).toThrowError(expect.objectContaining({code:'PERMISSION_DENIED'}))})
  it('keeps sale and gift semantics separate for the same SKU-unit',()=>{const {service}=setup();const draft=validDraft();draft.lines.push({...draft.lines[0]!,quantity:1,lineKind:'gift'});const preview=service.previewDraft(admin,draft);expect(preview.lines).toHaveLength(2);expect(preview.lines[1]).toMatchObject({lineKind:'gift',dealUnitPriceCents:0,subtotalCents:0});expect(preview.amounts.productDiscountCents).toBeLessThan(0)})
  it('does not turn an automatic price into a manual special price on edit',()=>{const {service}=setup();const created=service.saveOrder(admin,{requestId:'save-auto-price',draft:validDraft()});const editable=service.getEditableDraft(admin,created.id);expect(editable.draft.lines[0]?.manualDealUnitPriceCents).toBeNull();editable.draft.lines[0]!.quantity=22;expect(()=>service.previewOrder(admin,editable.draft,created.id)).not.toThrow()})
  it('rolls back when a required provider fails',()=>{const {service,repository}=setup(true);const before=repository.read();expect(()=>service.saveOrder(admin,{requestId:'save-provider-failure',draft:validDraft()})).toThrowError(expect.objectContaining({code:'DATA_PROVIDER_UNAVAILABLE'}));expect(repository.read()).toEqual(before)})
})

describe('assisted entry and sharing',()=>{
  it('merges pasted duplicate SKU-unit rows and reports invalid rows',()=>{const {service}=setup();const result=service.parsePastedProducts(admin,'customer-1','skuCode,quantity,unitCode\nSKU-000001,10,DEMO-PIECE\nSKU-000001,11,unit-piece\nUNKNOWN,1,unit-piece');expect(result.lines).toHaveLength(1);expect(result.lines[0]?.quantity).toBe(21);expect(result.errors).toEqual(['第3行SKU不存在']);expect(service.findByBarcode(admin,'customer-1','DEMO-BAR-0001')).toMatchObject({skuId:'sku-1',unitId:'unit-piece',quantity:1})})
  it('loads a template with accepted and rejected lines instead of guessing',()=>{const {service}=setup();const result=service.loadTemplateLines(admin,'customer-1','order-template-1');expect(result.accepted.map((item)=>item.skuId)).toContain('sku-1');expect(result.rejected.map((item)=>item.skuId)).toContain('sku-2')})
  it('stores only a token hash, tracks idempotent view/confirm and revokes the old share',()=>{const {service,repository}=setup();const first=service.createShare(admin,'order-001');expect(JSON.stringify(repository.read())).not.toContain(first.token);expect(service.viewSharedOrder(first.token).shareStatus).toBe('viewed');const logsAfterView=repository.read().orders.find((item)=>item.id==='order-001')!.activityLogs.length;expect(service.viewSharedOrder(first.token).shareStatus).toBe('viewed');expect(repository.read().orders.find((item)=>item.id==='order-001')!.activityLogs).toHaveLength(logsAfterView);expect(service.confirmSharedOrder(first.token).shareStatus).toBe('confirmed');const logsAfterConfirm=repository.read().orders.find((item)=>item.id==='order-001')!.activityLogs.length;expect(service.confirmSharedOrder(first.token).shareStatus).toBe('confirmed');expect(repository.read().orders.find((item)=>item.id==='order-001')!.activityLogs).toHaveLength(logsAfterConfirm);const second=service.createShare(admin,'order-001',30);expect(second.expiresAt).not.toBe(first.expiresAt);expect(()=>service.viewSharedOrder(first.token)).toThrowError(expect.objectContaining({code:'SHARE_INVALID'}));expect(service.viewSharedOrder(second.token).orderNo).toBe('CA000000-260710-60001')})
  it('does not share canceled orders',()=>{const {service}=setup();expect(()=>service.createShare(admin,'order-008')).toThrowError(expect.objectContaining({code:'INVALID_STATE'}))})
})
