import { describe,expect,it } from 'vitest'
import { createOrderMockSession } from '../../../../mock/handlers/order-handler'
import { OrderDomainError } from './order-service'

const admin={role:'super-admin' as const,actorId:'admin-demo'}
const warehouse={role:'warehouse' as const,actorId:'warehouse-demo'}
const supervisor={role:'sales-supervisor' as const,actorId:'sales-supervisor-demo'}
const finance={role:'finance' as const,actorId:'finance-demo'}
const raw=(session:ReturnType<typeof createOrderMockSession>,id:string)=>session.repository.read().orders.find((item)=>item.id===id)!
const fullInput=(session:ReturnType<typeof createOrderMockSession>,id='order-003',requestId='full-1')=>{const order=raw(session,id);const line=order.lines[0]!;return{requestId,orderId:id,expectedUpdatedAt:order.updatedAt,warehouseId:'warehouse-main',lines:[{orderLineId:line.id,quantity:line.quantityMilli/line.unitSnapshot.conversionRateMilli}],finishShort:false}}

describe('ORD-004 fulfillment service',()=>{
  it('seeds explainable progress, outbound, shipment, receipt, difference and void records',()=>{const session=createOrderMockSession();const state=session.repository.read();expect(state.outbounds?.some((item)=>item.orderId==='order-004'&&item.status==='confirmed')).toBe(true);expect(state.shipments?.some((item)=>item.orderId==='order-006')).toBe(true);expect(state.receipts?.some((item)=>item.orderId==='order-007')).toBe(true);expect(state.differences?.some((item)=>item.orderId==='order-011'&&item.status==='pending-confirmation')).toBe(true);expect(state.outbounds?.some((item)=>item.orderId==='order-019'&&item.status==='voided')).toBe(true)})
  it('keeps planned partial outbound separate from a difference',()=>{const session=createOrderMockSession();const order=raw(session,'order-003');const line=order.lines[0]!;const before=session.inventoryRepository.read().balances.reduce((sum,item)=>sum+item.quantityMilli,0);const result=session.fulfillment.confirmOutbound(warehouse,{requestId:'partial-1',orderId:order.id,expectedUpdatedAt:order.updatedAt,warehouseId:'warehouse-main',lines:[{orderLineId:line.id,quantity:1}],finishShort:false});expect(result.outbound?.status).toBe('confirmed');expect(result.difference).toBeNull();expect(raw(session,order.id).status).toBe('outbound');expect(session.inventoryRepository.read().balances.reduce((sum,item)=>sum+item.quantityMilli,0)).toBe(before-line.unitSnapshot.conversionRateMilli)})
  it('allows zero actual quantity only for an explicit final-short difference',()=>{const session=createOrderMockSession();const order=raw(session,'order-027');const result=session.fulfillment.confirmOutbound(warehouse,{requestId:'zero-short',orderId:order.id,expectedUpdatedAt:order.updatedAt,warehouseId:'warehouse-main',lines:[],finishShort:true,reason:'仓库确认整单缺货'});expect(result.outbound).toBeNull();expect(result.difference?.lines[0]?.differenceQuantityMilli).toBe(order.lines[0]?.quantityMilli);expect(raw(session,order.id).status).toBe('approved')})
  it('voids before shipment and restores the exact inventory snapshot',()=>{const session=createOrderMockSession();const before=session.inventoryRepository.read().balances;const result=session.fulfillment.confirmOutbound(warehouse,fullInput(session,'order-003','void-source'));const changed=raw(session,'order-003');session.fulfillment.voidOutbound(warehouse,{requestId:'void-command',outboundId:result.outbound!.id,expectedOrderUpdatedAt:changed.updatedAt,reason:'复核发现备货批次错误'});expect(session.inventoryRepository.read().balances).toEqual(before);expect(raw(session,'order-003').status).toBe('approved');expect(session.repository.read().outbounds?.find((item)=>item.id===result.outbound!.id)?.status).toBe('voided')})
  it('creates one Finance-owned full-order receivable at shipment and receipt only completes fulfillment',()=>{const session=createOrderMockSession();session.fulfillment.confirmOutbound(warehouse,fullInput(session,'order-003','ship-outbound'));let order=raw(session,'order-003');const shipment=session.fulfillment.confirmShipment(warehouse,{requestId:'ship-command',orderId:order.id,expectedUpdatedAt:order.updatedAt,logisticsCode:'MOCK-LOGISTICS-003'});const replay=session.fulfillment.confirmShipment(warehouse,{requestId:'ship-command',orderId:order.id,expectedUpdatedAt:order.updatedAt,logisticsCode:'MOCK-LOGISTICS-003'});expect(replay.id).toBe(shipment.id);expect(session.repository.read().receivables?.filter((item)=>item.orderId===order.id)).toHaveLength(0);expect(session.financeRepository.read().receivables.filter((item)=>item.orderId===order.id)).toHaveLength(1);expect(session.fulfillment.getFulfillment(admin,order.id).receivable?.amountCents).toBe(order.amounts.orderAmountCents);order=raw(session,'order-003');session.fulfillment.confirmReceipt(supervisor,{requestId:'receipt-command',orderId:order.id,expectedUpdatedAt:order.updatedAt,signedAt:'2026-08-10T10:00:00+08:00',signer:'客户演示签收人'});expect(raw(session,'order-003').status).toBe('completed');expect(session.financeRepository.read().receivables.filter((item)=>item.orderId===order.id)).toHaveLength(1)})
  it('closes a short shipment as refund and atomically creates the full receivable plus a no-inbound credit at shipment',()=>{const session=createOrderMockSession();const order=raw(session,'order-011');const difference=session.repository.read().differences!.find((item)=>item.orderId===order.id)!;const inventoryBefore=session.inventoryRepository.read();session.fulfillment.confirmDifference(supervisor,{requestId:'short-refund-confirm',differenceId:difference.id,expectedOrderUpdatedAt:order.updatedAt,outcome:'refund'});expect(raw(session,order.id).status).toBe('outbound');const ready=raw(session,order.id);session.fulfillment.confirmShipment(warehouse,{requestId:'short-refund-shipment',orderId:ready.id,expectedUpdatedAt:ready.updatedAt,logisticsCode:'MOCK-SHORT-REFUND'});const financeState=session.financeRepository.read();expect(financeState.receivables.filter((item)=>item.orderId===order.id)).toHaveLength(1);expect(financeState.creditAdjustments).toContainEqual(expect.objectContaining({sourceType:'short-shipment-refund',sourceId:difference.id,amountCents:difference.differenceAmountCents,status:'active'}));expect(session.inventoryRepository.read()).toEqual(inventoryBefore)})
  it('enforces permissions and masks warehouse amounts',()=>{const session=createOrderMockSession();const detail=session.fulfillment.getFulfillment(warehouse,'order-005');expect(detail.outbounds[0]?.documentAmountCents).toBe(0);expect(detail.outbounds[0]?.lines[0]?.dealUnitPriceCents).toBe(0);expect(()=>session.fulfillment.confirmOutbound(finance,fullInput(session,'order-003','finance-denied'))).toThrowError(expect.objectContaining({code:'PERMISSION_DENIED'}));expect(()=>session.fulfillment.listDifferences(warehouse)).toThrowError(expect.objectContaining({code:'PERMISSION_DENIED'}))})
  it('rejects stale versions before inventory changes',()=>{const session=createOrderMockSession();const before=session.inventoryRepository.read();const input=fullInput(session,'order-003','stale');input.expectedUpdatedAt='2026-08-10T09:00:00+08:00';expect(()=>session.fulfillment.confirmOutbound(warehouse,input)).toThrowError(expect.objectContaining({code:'CONFLICT'}));expect(session.inventoryRepository.read()).toEqual(before)})
  it('blocks when the inventory gate is unavailable without a half result',()=>{const session=createOrderMockSession('partial-failure');const beforeOrder=session.repository.read();const beforeInventory=session.inventoryRepository.read();expect(()=>session.fulfillment.confirmOutbound(admin,fullInput(session,'order-003','provider-down'))).toThrowError(expect.objectContaining({code:'DATA_PROVIDER_UNAVAILABLE'}));expect(session.repository.read()).toEqual(beforeOrder);expect(session.inventoryRepository.read()).toEqual(beforeInventory)})
  it('prints the current selection atomically and rejects a stale document version',()=>{const session=createOrderMockSession();const docs=session.fulfillment.listOutbounds(admin).slice(0,2);const before=session.repository.read();expect(()=>session.fulfillment.printOutbounds(admin,{requestId:'print-stale',items:[{outboundId:docs[0]!.id,expectedVersion:docs[0]!.version},{outboundId:docs[1]!.id,expectedVersion:999}]})).toThrow(OrderDomainError);expect(session.repository.read()).toEqual(before);const printed=session.fulfillment.printOutbounds(admin,{requestId:'print-ok',items:docs.map((item)=>({outboundId:item.id,expectedVersion:item.version}))});expect(printed.every((item)=>item.printRecords.some((record)=>record.requestId==='print-ok'))).toBe(true)})
})
