import { normalizeOrderQuery } from '../schemas/order-schema'
import type { OrderRepository } from '../repositories/order-repository'
import type { CustomerOrder, OrderActor, OrderCustomerProvider, OrderDetailResult, OrderFinanceProvider, OrderFinancialCards, OrderListRow, OrderProviderValue, OrderQuery, PageResult, VisibleOrder } from '../types'

export type OrderDomainErrorCode='PERMISSION_DENIED'|'NOT_FOUND'|'INVALID_SELECTION'
export class OrderDomainError extends Error { constructor(readonly code:OrderDomainErrorCode,message:string){super(message);this.name='OrderDomainError'} }
export interface OrderServiceDependencies { repository:OrderRepository; customers:OrderCustomerProvider; finance:OrderFinanceProvider; now:()=>string; nextId:(kind:'activity')=>string }
const readRoles=new Set(['super-admin','sales-supervisor','salesperson','warehouse','finance']); const fullRoles=new Set(['super-admin','sales-supervisor','salesperson'])
const normalize=(value:string)=>value.trim().toLocaleLowerCase()
function assertRead(actor:OrderActor):void{if(!readRoles.has(actor.role))throw new OrderDomainError('PERMISSION_DENIED','当前角色不可访问订单模块')}
function assertOutput(actor:OrderActor):void{if(!fullRoles.has(actor.role))throw new OrderDomainError('PERMISSION_DENIED','当前角色不可导出或打印订单')}
function maskOrder(actor:OrderActor,source:CustomerOrder):VisibleOrder{
  const order=structuredClone(source) as VisibleOrder
  if(actor.role==='warehouse'){order.amounts={originalAmountCents:null,productDiscountCents:null,orderDiscountCents:null,freightCents:null,orderAmountCents:null};order.lines=order.lines.map((line)=>({...line,discountBasisPoints:null,originalUnitPriceCents:null,dealUnitPriceCents:null,subtotalCents:null}))}
  if(actor.role==='finance'){order.shippingSnapshot={...order.shippingSnapshot,phone:null,address:null};order.lines=order.lines.map((line)=>({...line,imageSnapshot:null,reason:null}))}
  return order
}
function logisticsSummary(order:CustomerOrder):string|null{const codes=order.fulfillmentProjection.logisticsCodes;if(codes===null)return null;if(!codes.length)return '—';return codes.length===1?codes[0]!: `${codes[0]} +${codes.length-1}`}
function unavailable<T>(message:string):OrderProviderValue<T>{return{state:'unavailable',value:null,message}}
function error<T>(message:string):OrderProviderValue<T>{return{state:'error',value:null,message}}
function available<T>(value:T,message='已加载'):OrderProviderValue<T>{return{state:'available',value,message}}

export function createOrderService(deps:OrderServiceDependencies){
  function matching(actor:OrderActor,input:OrderQuery):CustomerOrder[]{assertRead(actor);const query=normalizeOrderQuery(input);const state=deps.repository.read();let categoryIds:string[]|null=null;if(query.customerCategoryId){try{categoryIds=[query.customerCategoryId,...deps.customers.categoryDescendants(query.customerCategoryId)]}catch{throw new OrderDomainError('NOT_FOUND','客户分类数据加载失败')}}const keyword=query.keyword?normalize(query.keyword):null
    return state.orders.filter((order)=>order.deletedAt===null).filter((order)=>!query.statuses?.length||query.statuses.includes(order.status)).filter((order)=>!query.orderedFrom||Date.parse(order.orderedAt)>=Date.parse(query.orderedFrom)).filter((order)=>!query.orderedTo||Date.parse(order.orderedAt)<Date.parse(query.orderedTo)).filter((order)=>!keyword||[order.orderNo,order.customerSnapshot.code,order.customerSnapshot.name].some((value)=>normalize(value).includes(keyword))).filter((order)=>!categoryIds||categoryIds.includes(order.customerSnapshot.categoryId)).filter((order)=>!query.salespersonId||order.salespersonSnapshot.id===query.salespersonId).filter((order)=>!query.warehouseId||order.fulfillmentWarehouseSnapshot.id===query.warehouseId).filter((order)=>!query.settlementMethod||order.settlementSnapshot.method===query.settlementMethod).filter((order)=>query.amountMinCents===undefined||order.amounts.orderAmountCents>=query.amountMinCents).filter((order)=>query.amountMaxCents===undefined||order.amounts.orderAmountCents<=query.amountMaxCents).filter((order)=>!query.deliveryFrom||Date.parse(order.requestedDeliveryAt)>=Date.parse(query.deliveryFrom)).filter((order)=>!query.deliveryTo||Date.parse(order.requestedDeliveryAt)<Date.parse(query.deliveryTo)).filter((order)=>query.hasDifference===undefined||order.fulfillmentProjection.hasDifference===query.hasDifference).sort((a,b)=>b.orderedAt.localeCompare(a.orderedAt)||b.id.localeCompare(a.id))
  }
  function listOrders(actor:OrderActor,input:OrderQuery={}):PageResult<OrderListRow>{const query=normalizeOrderQuery(input);const items=matching(actor,query);const start=(query.page-1)*query.pageSize;return{items:items.slice(start,start+query.pageSize).map((order)=>({order:maskOrder(actor,order),logisticsSummary:logisticsSummary(order)})),total:items.length,page:query.page,pageSize:query.pageSize}}
  function getRaw(actor:OrderActor,id:string):CustomerOrder{assertRead(actor);const order=deps.repository.read().orders.find((item)=>item.id===id&&item.deletedAt===null);if(!order)throw new OrderDomainError('NOT_FOUND','订单不存在');return order}
  function getFinancials(actor:OrderActor,order:CustomerOrder):OrderFinancialCards{if(actor.role==='warehouse')return{creditLimitCents:unavailable('当前角色不可查看'),receivablesCents:unavailable('当前角色不可查看'),availablePrepaymentCents:unavailable('当前角色不可查看'),occupiedPrepaymentCents:unavailable('当前角色不可查看')};let credit:OrderFinancialCards['creditLimitCents'];try{const value=deps.customers.getCreditLimitCents(order.customerSnapshot.id);credit=value===null?unavailable('客户资料尚未接入'):available(value)}catch{credit=error('客户资料加载失败')}let receivables:OrderFinancialCards['receivablesCents'];let prepayment:OrderFinancialCards['availablePrepaymentCents'];try{const value=deps.finance.getCustomerSummary(order.customerSnapshot.id);receivables=value?available(value.receivablesCents):unavailable('资金数据源尚未接入');prepayment=value?available(value.availablePrepaymentCents):unavailable('资金数据源尚未接入')}catch{receivables=error('资金数据加载失败');prepayment=error('资金数据加载失败')}return{creditLimitCents:credit,receivablesCents:receivables,availablePrepaymentCents:prepayment,occupiedPrepaymentCents:unavailable('等待预收占用规则确认')}}
  function getOrderDetail(actor:OrderActor,id:string):OrderDetailResult{const order=getRaw(actor,id);return{order:maskOrder(actor,order),financials:getFinancials(actor,order),inventoryRecommendation:unavailable('库荐算法尚未接入')}}
  function exportOrdersCsv(actor:OrderActor,query:OrderQuery={},selected:string[]=[]):string{assertOutput(actor);let orders=matching(actor,query);if(selected.length){const ids=new Set(selected);orders=orders.filter((item)=>ids.has(item.id))}const headers=['orderNo','status','orderedAt','customerCode','customerName','settlementCustomer','recipient','phone','address','warehouse','requestedDeliveryAt','logisticsCodes','orderPrintCount','outboundPrintCount','orderAmountCents'];const body=orders.map((order)=>[order.orderNo,order.status,order.orderedAt,order.customerSnapshot.code,order.customerSnapshot.name,order.settlementCustomerSnapshot.name,order.shippingSnapshot.recipient,order.shippingSnapshot.phone,`${order.shippingSnapshot.province}${order.shippingSnapshot.city}${order.shippingSnapshot.district}${order.shippingSnapshot.address}`,order.fulfillmentWarehouseSnapshot.name,order.requestedDeliveryAt,order.fulfillmentProjection.logisticsCodes?.join('|')??'unavailable',order.orderPrintCount,order.fulfillmentProjection.outboundPrintCount??'unavailable',order.amounts.orderAmountCents].map((value)=>`"${String(value).replaceAll('"','""')}"`).join(','));return `\uFEFF${[headers.join(','),...body].join('\r\n')}`}
  function printOrders(actor:OrderActor,orderIds:string[],requestId:string):CustomerOrder[]{assertOutput(actor);if(!requestId.trim()||!orderIds.length||new Set(orderIds).size!==orderIds.length)throw new OrderDomainError('INVALID_SELECTION','打印请求或订单选择无效');const existing=deps.repository.read().printRequests.find((item)=>item.requestId===requestId);if(existing)return existing.orderIds.map((id)=>getRaw(actor,id));return deps.repository.transact((state)=>{const orders=orderIds.map((id)=>{const order=state.orders.find((item)=>item.id===id&&item.deletedAt===null);if(!order)throw new OrderDomainError('NOT_FOUND','选中订单不存在');return order});const printedAt=deps.now();orders.forEach((order)=>{order.orderPrintCount+=1;order.updatedAt=printedAt;order.activityLogs.push({id:deps.nextId('activity'),action:'order.printed',actor:{id:actor.actorId,name:'当前模拟用户'},occurredAt:printedAt,summary:'确认打印订单'})});state.printRequests.push({requestId,orderIds:[...orderIds],actorId:actor.actorId,printedAt});return orders})}
  return{listOrders,getOrderDetail,exportOrdersCsv,printOrders}
}

