import type { Warehouse, WarehouseDraft } from '@/features/inventory/public'
import { assertValid, validateAnnouncementDraft, validateCompanyDraft, validateEmployeeDraft, validateRegionDraft, validateRoleDraft } from '../schemas/settings-schema'
import { defaultRolePermissionIds, getPermissionCatalog } from '../config/permission-catalog'
import type { Announcement, AnnouncementDraft, CompanyDraft, Department, DepartmentDraft, Region, RegionDraft, SettingsActor, SettingsEmployee, SettingsEmployeeDraft, SettingsFeatureState, SettingsRoleDraft, SettingsRoleRecord, SettingsSession, SettingsWarehouseProvider } from '../types'
import type { SettingsRepository } from '../repositories/settings-repository'

export class SettingsDomainError extends Error { constructor(readonly code: string, message: string) { super(message); this.name = 'SettingsDomainError' } }
interface Deps { repository: SettingsRepository; now: () => string; nextId: (kind: string) => string; warehouseProvider: SettingsWarehouseProvider }
const assertAdmin = (actor: SettingsActor) => { if (actor.role !== 'super-admin') throw new SettingsDomainError('PERMISSION_DENIED', '只有超级管理员可以维护设置基础资料') }
const normalize = (value: string) => value.trim().toLocaleLowerCase()
const dateCode = (now: string) => now.slice(0, 10).replaceAll('-', '')
export function createSettingsService(deps: Deps) {
  const audit = (state: SettingsFeatureState, actor: SettingsActor, action: string, targetId: string, detail: string) => state.auditLogs.push({ id: deps.nextId('audit'), action, targetId, operatorId: actor.actorId, detail, createdAt: deps.now() })
  const departmentById = (state: SettingsFeatureState, id: string) => { const value = state.departments.find((item) => item.id === id); if (!value) throw new SettingsDomainError('NOT_FOUND', '部门不存在'); return value }
  const regionById = (state: SettingsFeatureState, id: string) => { const value = state.regions.find((item) => item.id === id); if (!value) throw new SettingsDomainError('NOT_FOUND', '区域不存在'); return value }
  function listDepartments(): Department[] { return deps.repository.read().departments.sort((a, b) => a.code.localeCompare(b.code)) }
  function saveCompany(actor: SettingsActor, draft: CompanyDraft): CompanyDraft { assertAdmin(actor); assertValid(validateCompanyDraft(draft)); return deps.repository.transact((state) => { const duplicate = state.company && normalize(state.company.code) !== normalize(draft.code) ? null : null; if (duplicate) throw new SettingsDomainError('DUPLICATE', '公司编码已存在'); const current = state.company; const value = current ? { ...current, ...structuredClone(draft), version: current.version + 1, updatedAt: deps.now(), updatedBy: actor.actorId } : { id: deps.nextId('company'), enterpriseId: state.enterpriseId, ...structuredClone(draft), version: 1, updatedAt: deps.now(), updatedBy: actor.actorId }; state.company = value; audit(state, actor, 'company.saved', value.id, current ? '编辑公司资料' : '创建公司资料'); return value }) }
  function saveDepartment(actor: SettingsActor, draft: DepartmentDraft, id?: string): Department { assertAdmin(actor); if (!draft.name.trim()) throw new SettingsDomainError('INVALID', '部门名称不能为空'); return deps.repository.transact((state) => { if (draft.parentId === id) throw new SettingsDomainError('INVALID_STATE', '部门不能选择自身为上级'); if (draft.parentId) departmentById(state, draft.parentId); let cursor = draft.parentId; while (cursor) { if (cursor === id) throw new SettingsDomainError('INVALID_STATE', '部门层级不能形成循环'); cursor = state.departments.find((item) => item.id === cursor)?.parentId ?? null } const current = id ? departmentById(state, id) : null; const value: Department = current ? { ...current, ...draft, updatedAt: deps.now(), version: current.version + 1 } : { id: deps.nextId('department'), enterpriseId: state.enterpriseId, code: `DEPT-${dateCode(deps.now())}-${String(state.departments.length + 1).padStart(3, '0')}`, ...draft, employeeCount: 0, customerCount: 0, announcementCount: 0, version: 1, createdAt: deps.now(), updatedAt: deps.now() }; if (current) state.departments[state.departments.findIndex((item) => item.id === id)] = value; else state.departments.push(value); audit(state, actor, 'department.saved', value.id, current ? '编辑部门' : '新增部门'); return value }) }
  function deleteDepartment(actor: SettingsActor, id: string): void { assertAdmin(actor); deps.repository.transact((state) => { const current = departmentById(state, id); const child = state.departments.some((item) => item.parentId === id); if (child || current.employeeCount || current.customerCount || current.announcementCount) throw new SettingsDomainError('REFERENCE_EXISTS', '部门存在子部门、员工、客户或公告引用，不能删除'); state.departments = state.departments.filter((item) => item.id !== id); audit(state, actor, 'department.deleted', id, '删除部门') }) }
  function listAnnouncements(query: { status?: string; keyword?: string } = {}): Announcement[] { const state = deps.repository.read(); return state.announcements.filter((item) => !query.status || item.status === query.status).filter((item) => !query.keyword || normalize(item.title).includes(normalize(query.keyword))).sort((a, b) => b.createdAt.localeCompare(a.createdAt)) }
  function saveAnnouncement(actor: SettingsActor, draft: AnnouncementDraft, id?: string): Announcement { assertAdmin(actor); assertValid(validateAnnouncementDraft(draft)); return deps.repository.transact((state) => { const current = id ? state.announcements.find((item) => item.id === id) : null; if (current?.status === 'published') throw new SettingsDomainError('INVALID_STATE', '已发布公告快照不可编辑'); const value: Announcement = current ? { ...current, ...structuredClone(draft), linkText: draft.linkText?.trim() || null, linkUrl: draft.linkUrl?.trim() || null, recipientDepartmentIds: [...(draft.recipientDepartmentIds ?? [])], attachments: [...(draft.attachments ?? [])], contentMeta: { images: [...(draft.contentMeta?.images ?? [])], aiDraft: draft.contentMeta?.aiDraft ?? null }, updatedAt: deps.now(), version: current.version + 1 } : { id: deps.nextId('announcement'), enterpriseId: state.enterpriseId, title: draft.title.trim(), type: draft.type, content: draft.content, contentMeta: { images: [...(draft.contentMeta?.images ?? [])], aiDraft: draft.contentMeta?.aiDraft ?? null }, linkText: draft.linkText?.trim() || null, linkUrl: draft.linkUrl?.trim() || null, recipientScope: draft.recipientScope, recipientDepartmentIds: [...(draft.recipientDepartmentIds ?? [])], pushEnabled: draft.pushEnabled ?? false, publisher: draft.publisher, attachments: [...(draft.attachments ?? [])], status: 'draft', publishedAt: null, publishedSnapshot: null, pushState: 'not-requested', pushError: null, version: 1, createdAt: deps.now(), updatedAt: deps.now() }; if (current) state.announcements[state.announcements.findIndex((item) => item.id === id)] = value; else state.announcements.push(value); audit(state, actor, 'announcement.saved', value.id, current ? '保存公告草稿' : '创建公告草稿'); return value }) }
  function publishAnnouncement(actor: SettingsActor, id: string): Announcement { assertAdmin(actor); return deps.repository.transact((state) => { const current = state.announcements.find((item) => item.id === id); if (!current) throw new SettingsDomainError('NOT_FOUND', '公告不存在'); if (current.status !== 'draft') throw new SettingsDomainError('INVALID_STATE', '只有草稿可以发布'); current.status = 'published'; current.publishedAt = deps.now(); current.publishedSnapshot = { title: current.title, type: current.type, content: current.content, linkText: current.linkText, linkUrl: current.linkUrl, recipientScope: current.recipientScope, recipientDepartmentIds: [...current.recipientDepartmentIds], attachments: [...current.attachments] }; current.pushState = current.pushEnabled ? 'failed' : 'not-requested'; current.pushError = current.pushEnabled ? '原型模拟：推送服务未接入' : null; current.version++; current.updatedAt = deps.now(); audit(state, actor, 'announcement.published', id, '发布公告并保存不可变快照'); return current }) }
  function retryAnnouncementPush(actor: SettingsActor, id: string): Announcement { assertAdmin(actor); return deps.repository.transact((state) => { const current = state.announcements.find((item) => item.id === id); if (!current || current.status !== 'published') throw new SettingsDomainError('INVALID_STATE', '只有已发布公告可以重试推送'); current.pushState = 'failed'; current.pushError = '原型模拟：推送服务未接入'; current.updatedAt = deps.now(); audit(state, actor, 'announcement.push-retry', id, '记录推送重试'); return current }) }
  function listRegions(): Region[] { return deps.repository.read().regions.sort((a, b) => a.code.localeCompare(b.code)) }
  function saveRegion(actor: SettingsActor, draft: RegionDraft, id?: string): Region { assertAdmin(actor); assertValid(validateRegionDraft(draft)); return deps.repository.transact((state) => { if (draft.parentId === id) throw new SettingsDomainError('INVALID_STATE', '区域不能选择自身为上级'); if (draft.parentId) regionById(state, draft.parentId); let cursor = draft.parentId; while (cursor) { if (cursor === id) throw new SettingsDomainError('INVALID_STATE', '区域层级不能形成循环'); cursor = state.regions.find((item) => item.id === cursor)?.parentId ?? null } const current = id ? regionById(state, id) : null; if (draft.isDefault && draft.parentId !== null) throw new SettingsDomainError('INVALID_STATE', '默认区域必须是根区域'); if (draft.isDefault) state.regions.forEach((item) => { item.isDefault = false }); const value: Region = current ? { ...current, ...draft, updatedAt: deps.now(), version: current.version + 1 } : { id: deps.nextId('region'), enterpriseId: state.enterpriseId, code: `REG-${dateCode(deps.now())}-${String(state.regions.length + 1).padStart(3, '0')}`, ...draft, customerCount: 0, warehouseCount: 0, version: 1, createdAt: deps.now(), updatedAt: deps.now() }; if (current) state.regions[state.regions.findIndex((item) => item.id === id)] = value; else state.regions.push(value); audit(state, actor, 'region.saved', value.id, current ? '编辑区域' : '新增区域'); return value }) }
  function deleteRegion(actor: SettingsActor, id: string): void { assertAdmin(actor); deps.repository.transact((state) => { const current = regionById(state, id); if (current.isDefault) throw new SettingsDomainError('REFERENCE_EXISTS', '默认根区域不能删除'); if (state.regions.some((item) => item.parentId === id) || current.customerCount || current.warehouseCount) throw new SettingsDomainError('REFERENCE_EXISTS', '区域存在子区域、客户或仓库引用，不能删除'); state.regions = state.regions.filter((item) => item.id !== id); audit(state, actor, 'region.deleted', id, '删除区域') }) }
  function listWarehouses(actor: SettingsActor): Warehouse[] { return deps.warehouseProvider.listWarehouses(actor) }
  function saveWarehouse(actor: SettingsActor, draft: WarehouseDraft, id?: string): Warehouse { return deps.warehouseProvider.saveWarehouse(actor, draft, id) }
  const rolePermissionIds = (state: SettingsFeatureState, roleId: string): string[] => { const role = state.roles?.find((item) => item.id === roleId); return role ? role.status === 'enabled' ? role.permissionIds : [] : defaultRolePermissionIds[roleId.replace('role-', '') as SettingsActor['role']] ?? [] }
  const permissionsForActor = (state: SettingsFeatureState, actor: SettingsActor): string[] => actor.role === 'super-admin' ? getPermissionCatalog().map((item) => item.id) : rolePermissionIds(state, `role-${actor.role}`)
  const assertPermission = (actor: SettingsActor, permissionId: string) => { const state = deps.repository.read(); if (!permissionsForActor(state, actor).includes(permissionId)) throw new SettingsDomainError('PERMISSION_DENIED', '当前角色没有此操作权限') }
  const ensureAccessState = (state: SettingsFeatureState) => { state.roles ??= []; state.employees ??= []; state.sessions ??= []; state.permissionCatalogVersion ??= 1 }
  const roleById = (state: SettingsFeatureState, id: string): SettingsRoleRecord => { const value = state.roles?.find((item) => item.id === id); if (!value) throw new SettingsDomainError('NOT_FOUND', '角色不存在'); return value }
  const employeeById = (state: SettingsFeatureState, id: string): SettingsEmployee => { const value = state.employees?.find((item) => item.id === id); if (!value) throw new SettingsDomainError('NOT_FOUND', '员工不存在'); return value }
  function listPermissionCatalog() { return getPermissionCatalog() }
  function listRoles(actor: SettingsActor): SettingsRoleRecord[] { assertPermission(actor, 'settings.roles.view'); return structuredClone(deps.repository.read().roles ?? []) }
  function saveRole(actor: SettingsActor, draft: SettingsRoleDraft, id?: string): SettingsRoleRecord { assertPermission(actor, 'settings.roles.manage'); assertValid(validateRoleDraft(draft)); const catalog = new Set(getPermissionCatalog().map((item) => item.id)); if (draft.permissionIds.some((item) => !catalog.has(item))) throw new SettingsDomainError('INVALID', '权限不在当前 catalog 中'); return deps.repository.transact((state) => { ensureAccessState(state); const current = id ? roleById(state, id) : null; if (current?.kind === 'system') throw new SettingsDomainError('PROTECTED', '系统管理员角色不可编辑'); const duplicate = state.roles!.some((item) => item.id !== id && normalize(item.name) === normalize(draft.name)); if (duplicate) throw new SettingsDomainError('DUPLICATE', '角色名称已存在'); const value: SettingsRoleRecord = current ? { ...current, ...structuredClone(draft), permissionIds: [...draft.permissionIds], version: current.version + 1, updatedAt: deps.now() } : { id: deps.nextId('role'), enterpriseId: state.enterpriseId, ...structuredClone(draft), kind: 'custom', permissionIds: [...draft.permissionIds], version: 1, createdAt: deps.now(), updatedAt: deps.now() }; if (current) state.roles![state.roles!.findIndex((item) => item.id === id)] = value; else state.roles!.push(value); state.permissionCatalogVersion!++; audit(state, actor, current ? 'role.updated' : 'role.created', value.id, current ? '编辑自定义角色' : '新增自定义角色'); return value }) }
  function disableRole(actor: SettingsActor, id: string): void { assertPermission(actor, 'settings.roles.manage'); deps.repository.transact((state) => { ensureAccessState(state); const role = roleById(state, id); if (role.kind === 'system' || id === 'role-super-admin') throw new SettingsDomainError('PROTECTED', '系统管理员角色不可停用'); role.status = 'disabled'; role.version++; role.updatedAt = deps.now(); audit(state, actor, 'role.disabled', id, '停用角色；员工历史引用保留') }) }
  function listEmployees(actor: SettingsActor, query: { keyword?: string; status?: string; roleId?: string } = {}): SettingsEmployee[] { assertPermission(actor, 'settings.employees.view'); const keyword = normalize(query.keyword ?? ''); return (deps.repository.read().employees ?? []).filter((item) => !query.status || item.status === query.status).filter((item) => !query.roleId || item.roleIds.includes(query.roleId)).filter((item) => !keyword || [item.name, item.account, item.jobNumber ?? '', item.phone].some((value) => normalize(value).includes(keyword))).sort((a, b) => b.createdAt.localeCompare(a.createdAt)) }
  function saveEmployee(actor: SettingsActor, draft: SettingsEmployeeDraft, id?: string): SettingsEmployee { assertPermission(actor, 'settings.employees.manage'); assertValid(validateEmployeeDraft(draft)); return deps.repository.transact((state) => { ensureAccessState(state); if (!state.departments.some((item) => item.id === draft.departmentId && item.status === 'enabled')) throw new SettingsDomainError('INVALID', '员工部门不存在或已停用'); const roles = draft.roleIds.map((roleId) => roleById(state, roleId)); if (roles.some((role) => role.status !== 'enabled')) throw new SettingsDomainError('INVALID', '不能分配已停用角色'); const duplicate = state.employees!.some((item) => item.id !== id && normalize(item.account) === normalize(draft.account)); if (duplicate) throw new SettingsDomainError('DUPLICATE', '员工登录账号已存在'); const current = id ? employeeById(state, id) : null; const password = draft.password?.trim(); const { password: _ignoredPassword, ...employeeDraft } = draft; const value: SettingsEmployee = current ? { ...current, ...structuredClone(employeeDraft), roleIds: [...draft.roleIds], passwordMeta: password ? { fingerprint: `fake:${password.length}`, resetCount: current.passwordMeta.resetCount, updatedAt: deps.now() } : current.passwordMeta, mustChangePassword: password ? true : current.mustChangePassword, version: current.version + 1, updatedAt: deps.now() } : { id: deps.nextId('employee'), enterpriseId: state.enterpriseId, ...structuredClone(employeeDraft), roleIds: [...draft.roleIds], passwordMeta: { fingerprint: `fake:${(password ?? 'default').length}`, resetCount: 0, updatedAt: deps.now() }, mustChangePassword: true, version: 1, createdAt: deps.now(), updatedAt: deps.now() }; if (current) state.employees![state.employees!.findIndex((item) => item.id === id)] = value; else state.employees!.push(value); audit(state, actor, current ? 'employee.updated' : 'employee.created', value.id, current ? '编辑员工' : '新增员工'); return value }) }
  function disableEmployee(actor: SettingsActor, id: string): void { assertPermission(actor, 'settings.employees.manage'); deps.repository.transact((state) => { ensureAccessState(state); const employee = employeeById(state, id); if (employee.roleIds.includes('role-super-admin') && state.employees!.filter((item) => item.status === 'enabled' && item.roleIds.includes('role-super-admin')).length <= 1) throw new SettingsDomainError('PROTECTED', '至少保留一个启用系统管理员账号'); employee.status = 'disabled'; employee.version++; employee.updatedAt = deps.now(); audit(state, actor, 'employee.disabled', id, '停用员工') }) }
  function resetEmployeePassword(actor: SettingsActor, id: string): SettingsEmployee { assertPermission(actor, 'settings.employees.manage'); return deps.repository.transact((state) => { ensureAccessState(state); const employee = employeeById(state, id); employee.passwordMeta = { fingerprint: 'fake:8', resetCount: employee.passwordMeta.resetCount + 1, updatedAt: deps.now() }; employee.mustChangePassword = true; employee.updatedAt = deps.now(); audit(state, actor, 'employee.password-reset', id, '重置为 fake 默认密码并要求首次修改'); return employee }) }
  function authenticate(account: string, password: string): { session: SettingsSession; employee: SettingsEmployee } { return deps.repository.transact((state) => { ensureAccessState(state); const employee = state.employees!.find((item) => normalize(item.account) === normalize(account) && item.status === 'enabled'); if (!employee || employee.passwordMeta.fingerprint !== `fake:${password.trim().length}`) throw new SettingsDomainError('AUTH_FAILED', '账号不存在、已停用或密码不匹配'); const permissionIds = [...new Set(employee.roleIds.flatMap((roleId) => rolePermissionIds(state, roleId)))]; const session: SettingsSession = { id: deps.nextId('session'), employeeId: employee.id, permissionVersion: state.permissionCatalogVersion!, permissionIds, createdAt: deps.now(), active: true }; state.sessions!.push(session); return { session, employee } }) }
  function changePassword(sessionId: string, newPassword: string): SettingsEmployee { if (newPassword.trim().length < 6) throw new SettingsDomainError('INVALID', '新密码至少 6 位'); return deps.repository.transact((state) => { ensureAccessState(state); const session = state.sessions!.find((item) => item.id === sessionId && item.active); if (!session) throw new SettingsDomainError('AUTH_FAILED', '登录会话不存在'); const employee = employeeById(state, session.employeeId); employee.passwordMeta = { fingerprint: `fake:${newPassword.trim().length}`, resetCount: employee.passwordMeta.resetCount, updatedAt: deps.now() }; employee.mustChangePassword = false; employee.updatedAt = deps.now(); audit(state, { actorId: employee.id, role: 'super-admin' }, 'employee.password-changed', employee.id, '首次登录修改 fake 密码'); return employee }) }
  function listAuditLogs(actor: SettingsActor, query: { keyword?: string; from?: string; to?: string } = {}) { assertPermission(actor, 'settings.logs.view'); const keyword = normalize(query.keyword ?? ''); const cutoff = new Date(deps.now()).getTime() - 183 * 24 * 60 * 60 * 1000; return deps.repository.read().auditLogs.filter((item) => new Date(item.createdAt).getTime() >= cutoff).filter((item) => !query.from || item.createdAt.slice(0, 10) >= query.from).filter((item) => !query.to || item.createdAt.slice(0, 10) <= query.to).filter((item) => !keyword || [item.action, item.operatorId, item.targetId, item.detail].some((value) => normalize(value).includes(keyword))).sort((a, b) => b.createdAt.localeCompare(a.createdAt)) }
  function exportAuditCsv(actor: SettingsActor, query: { keyword?: string; from?: string; to?: string } = {}): string { assertPermission(actor, 'settings.logs.export'); const rows = listAuditLogs(actor, query); const escape = (value: string) => `"${value.replaceAll('"', '""')}"`; return ['日志ID,时间,操作人,操作类型,对象,详情', ...rows.map((row) => [row.id, row.createdAt, row.operatorId, row.action, row.targetId, row.detail].map(escape).join(','))].join('\n') }
  return { listDepartments, saveCompany, saveDepartment, deleteDepartment, listAnnouncements, saveAnnouncement, publishAnnouncement, retryAnnouncementPush, listRegions, saveRegion, deleteRegion, listWarehouses, saveWarehouse, listPermissionCatalog, listRoles, saveRole, disableRole, listEmployees, saveEmployee, disableEmployee, resetEmployeePassword, authenticate, changePassword, listAuditLogs, exportAuditCsv }
}
