import { describe, expect, it } from 'vitest'
import { InMemorySettingsRepository } from '../repositories/settings-repository'
import { createSettingsService, SettingsDomainError } from './settings-service'
import type { SettingsFeatureState } from '../types'
import { defaultRolePermissionIds } from '../config/permission-catalog'

const state: SettingsFeatureState = { schemaVersion: 1, enterpriseId: 'e1', company: null, departments: [{ id: 'd1', enterpriseId: 'e1', code: 'D1', name: '销售', parentId: null, managerId: null, status: 'enabled', employeeCount: 0, customerCount: 0, announcementCount: 0, version: 1, createdAt: '2026-08-10', updatedAt: '2026-08-10' }], announcements: [], regions: [{ id: 'r1', enterpriseId: 'e1', code: 'R1', name: '全国', parentId: null, type: 'region', status: 'enabled', isDefault: true, customerCount: 0, warehouseCount: 0, version: 1, createdAt: '2026-08-10', updatedAt: '2026-08-10' }], auditLogs: [] }
const setup = () => { const repository = new InMemorySettingsRepository(state); let n = 1; const service = createSettingsService({ repository, now: () => '2026-08-25T10:00:00+08:00', nextId: (kind) => `${kind}-${n++}`, warehouseProvider: { listWarehouses: () => [], saveWarehouse: (_actor, draft) => ({ ...draft, id: 'warehouse-1', enterpriseId: 'e1', createdAt: '', updatedAt: '' }) as never } }); return { repository, service } }
const admin = { actorId: 'admin', role: 'super-admin' as const }
describe('settings service', () => {
  it('validates company and records audit', () => { const { service, repository } = setup(); expect(() => service.saveCompany(admin, { name: '公司', code: 'C', contactName: '管理员', phone: 'bad', email: 'bad', region: null, address: null, logo: null, description: null })).toThrow('联系电话格式无效'); const value = service.saveCompany(admin, { name: '公司', code: 'C', contactName: '管理员', phone: '13800000000', email: 'a@example.com', region: null, address: null, logo: null, description: '简介' }); expect(value.code).toBe('C'); expect(repository.read().auditLogs).toHaveLength(1) })
  it('blocks department cycles and referenced deletes', () => { const { service } = setup(); const child = service.saveDepartment(admin, { name: '子部门', parentId: 'd1', managerId: null, status: 'enabled' }); expect(() => service.saveDepartment(admin, { name: '销售', parentId: child.id, managerId: null, status: 'enabled' }, 'd1')).toThrow('循环'); const { repository } = setup(); repository.transact((draft) => { draft.departments[0]!.customerCount = 1 }); const service2 = createSettingsService({ repository, now: () => '2026-08-25', nextId: (kind) => kind, warehouseProvider: { listWarehouses: () => [], saveWarehouse: (_actor, draft) => ({ ...draft, id: 'w', enterpriseId: 'e1', createdAt: '', updatedAt: '' }) as never } }); expect(() => service2.deleteDepartment(admin, 'd1')).toThrow(SettingsDomainError) })
  it('publishes an immutable snapshot and records fake push failure', () => { const { service } = setup(); const draft = service.saveAnnouncement(admin, { title: '通知', type: 'general', content: '正文', recipientScope: 'all', publisher: '管理员', pushEnabled: true }); const published = service.publishAnnouncement(admin, draft.id); expect(published.status).toBe('published'); expect(published.publishedSnapshot?.content).toBe('正文'); expect(published.pushState).toBe('failed'); expect(() => service.saveAnnouncement(admin, { ...draft, content: '修改' }, draft.id)).toThrow('不可编辑') })
  it('keeps one default root and blocks referenced region deletion', () => { const { service } = setup(); const region = service.saveRegion(admin, { name: '华东', parentId: 'r1', type: 'region', status: 'enabled', isDefault: false }); expect(() => service.deleteRegion(admin, 'r1')).toThrow('默认根区域'); expect(region.code).toMatch(/^REG-/) })
  it('protects system roles, enforces unique accounts, and snapshots permissions', () => { const { service, repository } = setup(); repository.transact((draft) => { draft.roles = [{ id: 'role-super-admin', enterpriseId: 'e1', name: '系统管理员', description: null, kind: 'system', permissionIds: [...defaultRolePermissionIds['super-admin']], status: 'enabled', version: 1, createdAt: '2026-08-10', updatedAt: '2026-08-10' }]; draft.employees = [{ id: 'admin-1', enterpriseId: 'e1', name: '管理员', account: 'admin', jobNumber: null, departmentId: 'd1', position: null, employeeType: 'full-time', roleIds: ['role-super-admin'], regionId: null, phone: '13800000000', email: null, passwordMeta: { fingerprint: 'fake:8', resetCount: 0, updatedAt: '2026-08-10' }, mustChangePassword: false, status: 'enabled', version: 1, createdAt: '2026-08-10', updatedAt: '2026-08-10' }] }); expect(() => service.disableRole(admin, 'role-super-admin')).toThrow('不可停用'); const role = service.saveRole(admin, { name: '日志查看', description: null, permissionIds: ['settings.logs.view'], status: 'enabled' }); const employee = service.saveEmployee(admin, { name: '张三', account: 'zhang', jobNumber: null, departmentId: 'd1', position: null, employeeType: 'full-time', roleIds: [role.id], regionId: null, phone: '13800000001', email: null, status: 'enabled', password: 'secret1' }); expect('password' in employee).toBe(false); expect(employee.mustChangePassword).toBe(true); expect(() => service.saveEmployee(admin, { name: '李四', account: 'ZHANG', jobNumber: null, departmentId: 'd1', position: null, employeeType: 'full-time', roleIds: [role.id], regionId: null, phone: '13800000002', email: null, status: 'enabled', password: 'secret1' })).toThrow('账号已存在'); const session = service.authenticate('zhang', 'secret1').session; expect(session.permissionIds).toContain('settings.logs.view'); service.saveRole(admin, { name: '日志查看', description: null, permissionIds: ['settings.logs.view', 'settings.logs.export'], status: 'enabled' }, role.id); expect(session.permissionIds).not.toContain('settings.logs.export'); expect(service.listAuditLogs(admin).length).toBeGreaterThan(0); expect(service.exportAuditCsv(admin)).toContain('日志ID') })
})
