import type { CustomerOrder, OrderDraft, OrderFeatureState, OrderQuery } from '../types'
import { validateReturnState } from './order-return-schema'

export interface OrderValidationIssue { path: string; message: string }
export class OrderValidationError extends Error {
  readonly code = 'ORDER_VALIDATION_FAILED'
  constructor(readonly issues: OrderValidationIssue[]) { super(issues.map((item) => `${item.path}: ${item.message}`).join('；')); this.name = 'OrderValidationError' }
}

const statuses = new Set(['pending-order-review', 'pending-finance-review', 'approved', 'outbound-in-progress', 'outbound', 'shipped', 'completed', 'canceled'])
const settlementMethods = new Set(['cash', 'monthly', 'terms'])
const deliveryMethods = new Set(['door-delivery', 'logistics', 'customer-pickup'])
const invoiceTypes = new Set(['none', 'vat-normal', 'vat-special'])
const attachmentTypes = new Set(['application/pdf', 'image/jpeg', 'image/png'])
const reviewActions = new Set(['approve-order','return-order','approve-finance','return-finance','cancel-order'])
const reviewStages = new Set(['order','finance'])
const reviewOutcomes = new Set(['approved','returned','canceled'])
const specialDirections = new Set(['below-minimum','above-maximum'])
const iso = (value: string) => Number.isFinite(Date.parse(value))
function required(issues: OrderValidationIssue[], path: string, value: string, max = 200): void { const clean=value.trim(); if(!clean) issues.push({path,message:'不能为空'}); else if(clean.length>max) issues.push({path,message:`不能超过 ${max} 个字符`}) }
function nonnegative(issues: OrderValidationIssue[], path: string, value: number): void { if(!Number.isSafeInteger(value)||value<0) issues.push({path,message:'必须是非负安全整数'}) }

export function validateOrderDraft(draft: OrderDraft): OrderValidationIssue[] {
  const issues: OrderValidationIssue[]=[]
  required(issues,'customerId',draft.customerId,100); required(issues,'warehouseId',draft.warehouseId,100)
  if(!invoiceTypes.has(draft.invoiceType)) issues.push({path:'invoiceType',message:'发票类型无效'})
  if(draft.invoiceType!=='none') required(issues,'invoiceTitle',draft.invoiceTitle??'',100)
  if(!iso(draft.requestedDeliveryAt)) issues.push({path:'requestedDeliveryAt',message:'必须是有效时间'})
  if(!deliveryMethods.has(draft.deliveryMethod)) issues.push({path:'deliveryMethod',message:'请选择配送方式'})
  required(issues,'shipping.recipient',draft.shipping.recipient,80); required(issues,'shipping.phone',draft.shipping.phone,40)
  required(issues,'shipping.province',draft.shipping.province,40); required(issues,'shipping.city',draft.shipping.city,40); required(issues,'shipping.district',draft.shipping.district,40); required(issues,'shipping.address',draft.shipping.address,200)
  if(!draft.lines.length) issues.push({path:'lines',message:'至少添加一个商品'})
  const pairs=new Set<string>()
  draft.lines.forEach((line,index)=>{const base=`lines.${index}`;required(issues,`${base}.skuId`,line.skuId,100);required(issues,`${base}.unitId`,line.unitId,100);if(!Number.isSafeInteger(line.quantity)||line.quantity<1)issues.push({path:`${base}.quantity`,message:'必须是大于等于1的整数'});if(!['sale','gift'].includes(line.lineKind))issues.push({path:`${base}.lineKind`,message:'行类型无效'});if(line.manualDealUnitPriceCents!==null)nonnegative(issues,`${base}.manualDealUnitPriceCents`,line.manualDealUnitPriceCents);if(line.reason&&line.reason.trim().length>500)issues.push({path:`${base}.reason`,message:'不能超过500个字符'});const pair=`${line.skuId}:${line.unitId}:${line.lineKind}`;if(pairs.has(pair))issues.push({path:base,message:'同一SKU、单位和行类型不能重复'});pairs.add(pair)})
  nonnegative(issues,'couponDiscountCents',draft.couponDiscountCents); nonnegative(issues,'manualOrderDiscountCents',draft.manualOrderDiscountCents); nonnegative(issues,'freightCents',draft.freightCents)
  if(draft.specialPrice)required(issues,'specialPriceReason',draft.specialPriceReason??'',200)
  else if(draft.specialPriceReason?.trim())issues.push({path:'specialPriceReason',message:'非特价订单不能填写特价原因'})
  if(draft.remark&&draft.remark.trim().length>500) issues.push({path:'remark',message:'不能超过500个字符'})
  if(draft.attachments.length>10) issues.push({path:'attachments',message:'最多上传10个附件'})
  draft.attachments.forEach((item,index)=>{required(issues,`attachments.${index}.id`,item.id,100);required(issues,`attachments.${index}.name`,item.name,200);if(!attachmentTypes.has(item.mediaType))issues.push({path:`attachments.${index}.mediaType`,message:'只支持pdf/jpg/png'});if(!Number.isSafeInteger(item.sizeBytes)||item.sizeBytes<=0||item.sizeBytes>5*1024*1024)issues.push({path:`attachments.${index}.sizeBytes`,message:'单文件必须大于0且不超过5MB'})})
  const keys=draft.customAttributes.map((item)=>item.key);if(new Set(keys).size!==keys.length)issues.push({path:'customAttributes.key',message:'属性key必须唯一'})
  return issues
}
export function assertOrderDraft(draft:OrderDraft):void{const issues=validateOrderDraft(draft);if(issues.length)throw new OrderValidationError(issues)}

export function validateOrder(order: CustomerOrder): OrderValidationIssue[] {
  const issues: OrderValidationIssue[]=[]
  required(issues,'id',order.id,100); required(issues,'enterpriseId',order.enterpriseId,100); required(issues,'orderNo',order.orderNo,80)
  if(!statuses.has(order.status)) issues.push({path:'status',message:'不是规范订单状态'})
  ;['orderedAt','requestedDeliveryAt','createdAt','updatedAt'].forEach((field)=>{ if(!iso(order[field as keyof CustomerOrder] as string)) issues.push({path:field,message:'必须是 ISO 时间'}) })
  required(issues,'customerSnapshot.id',order.customerSnapshot.id,100); required(issues,'customerSnapshot.code',order.customerSnapshot.code,80); required(issues,'customerSnapshot.name',order.customerSnapshot.name,100)
  required(issues,'settlementCustomerSnapshot.id',order.settlementCustomerSnapshot.id,100); if(!settlementMethods.has(order.settlementSnapshot.method)) issues.push({path:'settlementSnapshot.method',message:'结算方式无效'})
  if(order.settlementSnapshot.method==='terms' && (!Number.isSafeInteger(order.settlementSnapshot.creditTermDays)||order.settlementSnapshot.creditTermDays!<0)) issues.push({path:'settlementSnapshot.creditTermDays',message:'账期结算必须有非负整数天数'})
  if(order.settlementSnapshot.method!=='terms' && order.settlementSnapshot.creditTermDays!==null) issues.push({path:'settlementSnapshot.creditTermDays',message:'非账期结算必须为空'})
  required(issues,'shippingSnapshot.recipient',order.shippingSnapshot.recipient,80); required(issues,'shippingSnapshot.phone',order.shippingSnapshot.phone,40); required(issues,'shippingSnapshot.address',order.shippingSnapshot.address,200)
  if(!deliveryMethods.has(order.shippingSnapshot.deliveryMethod))issues.push({path:'shippingSnapshot.deliveryMethod',message:'配送方式无效'})
  const amounts=order.amounts; Object.entries(amounts).forEach(([key,value])=>{ if(!Number.isSafeInteger(value)) issues.push({path:`amounts.${key}`,message:'必须是安全整数分'}) })
  const coupon=amounts.couponDiscountCents??0;const manual=amounts.manualOrderDiscountCents??0
  if(amounts.originalAmountCents<0||amounts.productDiscountCents>0||coupon>0||manual>0||amounts.orderDiscountCents>0||amounts.freightCents<0||amounts.orderAmountCents<0) issues.push({path:'amounts',message:'原价/运费/总额须非负且优惠须为0或负数'})
  if((amounts.couponDiscountCents!==undefined||amounts.manualOrderDiscountCents!==undefined)&&amounts.orderDiscountCents!==coupon+manual)issues.push({path:'amounts.orderDiscountCents',message:'必须等于优惠券和手工整单优惠之和'})
  if(amounts.orderAmountCents!==amounts.originalAmountCents+amounts.productDiscountCents+amounts.orderDiscountCents+amounts.freightCents) issues.push({path:'amounts.orderAmountCents',message:'金额汇总等式不成立'})
  nonnegative(issues,'orderPrintCount',order.orderPrintCount);if(order.occupiedPrepaymentCents!==undefined)nonnegative(issues,'occupiedPrepaymentCents',order.occupiedPrepaymentCents)
  if(order.specialPrice){required(issues,'specialPriceReason',order.specialPriceReason??'',200)}else{if(order.specialPriceReason?.trim())issues.push({path:'specialPriceReason',message:'非特价订单不能保留特价原因'});if(order.specialPriceEvidence?.length)issues.push({path:'specialPriceEvidence',message:'非特价订单不能保留特价依据'})}
  if(order.reviewRound!==undefined&&(!Number.isSafeInteger(order.reviewRound)||order.reviewRound<1))issues.push({path:'reviewRound',message:'必须是正整数'})
  if(order.fulfillmentProjection.outboundPrintCount!==null) nonnegative(issues,'fulfillmentProjection.outboundPrintCount',order.fulfillmentProjection.outboundPrintCount)
  const lineIds=new Set<string>(); const sequences=new Set<number>();const pairs=new Set<string>()
  order.lines.forEach((line,index)=>{ const base=`lines.${index}`; if(lineIds.has(line.id)) issues.push({path:`${base}.id`,message:'行ID重复'}); lineIds.add(line.id); if(sequences.has(line.sequence)||!Number.isSafeInteger(line.sequence)||line.sequence<1) issues.push({path:`${base}.sequence`,message:'序号必须为不重复正整数'}); sequences.add(line.sequence); required(issues,`${base}.skuId`,line.skuId,100); required(issues,`${base}.skuCodeSnapshot`,line.skuCodeSnapshot,80); required(issues,`${base}.productNameSnapshot`,line.productNameSnapshot,100); if(!Number.isSafeInteger(line.quantityMilli)||line.quantityMilli<=0) issues.push({path:`${base}.quantityMilli`,message:'必须是正整数毫单位'}); if(!Number.isSafeInteger(line.discountBasisPoints)||line.discountBasisPoints<0||line.discountBasisPoints>10000) issues.push({path:`${base}.discountBasisPoints`,message:'必须在0到10000之间'}); nonnegative(issues,`${base}.originalUnitPriceCents`,line.originalUnitPriceCents); nonnegative(issues,`${base}.dealUnitPriceCents`,line.dealUnitPriceCents); nonnegative(issues,`${base}.subtotalCents`,line.subtotalCents);const pair=`${line.skuId}:${line.unitSnapshot.id}:${line.lineKind??'sale'}`;if(pairs.has(pair))issues.push({path:base,message:'同一SKU、单位和行类型不能重复'});pairs.add(pair) })
  ;(order.specialPriceEvidence??[]).forEach((item,index)=>{const base=`specialPriceEvidence.${index}`;if(!lineIds.has(item.lineId))issues.push({path:`${base}.lineId`,message:'关联商品行不存在'});required(issues,`${base}.skuId`,item.skuId,100);required(issues,`${base}.skuCodeSnapshot`,item.skuCodeSnapshot,80);required(issues,`${base}.unitId`,item.unitId,100);required(issues,`${base}.unitNameSnapshot`,item.unitNameSnapshot,80);nonnegative(issues,`${base}.dealUnitPriceCents`,item.dealUnitPriceCents);if(item.minimumSalePriceCents!==null)nonnegative(issues,`${base}.minimumSalePriceCents`,item.minimumSalePriceCents);if(item.maximumSalePriceCents!==null)nonnegative(issues,`${base}.maximumSalePriceCents`,item.maximumSalePriceCents);if(!specialDirections.has(item.direction))issues.push({path:`${base}.direction`,message:'越界方向无效'});if(item.direction==='below-minimum'&&(item.minimumSalePriceCents===null||item.dealUnitPriceCents>=item.minimumSalePriceCents))issues.push({path:base,message:'低于最低价依据不成立'});if(item.direction==='above-maximum'&&(item.maximumSalePriceCents===null||item.dealUnitPriceCents<=item.maximumSalePriceCents))issues.push({path:base,message:'高于最高价依据不成立'})})
  const reviewIds=new Set<string>();(order.reviewRecords??[]).forEach((item,index)=>{const base=`reviewRecords.${index}`;if(reviewIds.has(item.id))issues.push({path:`${base}.id`,message:'审核记录ID重复'});reviewIds.add(item.id);required(issues,`${base}.id`,item.id,100);if(!Number.isSafeInteger(item.round)||item.round<1)issues.push({path:`${base}.round`,message:'轮次必须为正整数'});if(item.round>(order.reviewRound??1))issues.push({path:`${base}.round`,message:'不能大于订单当前审核轮次'});if(!reviewStages.has(item.stage))issues.push({path:`${base}.stage`,message:'审核阶段无效'});if(!reviewOutcomes.has(item.outcome))issues.push({path:`${base}.outcome`,message:'审核结果无效'});required(issues,`${base}.actorSnapshot.id`,item.actorSnapshot.id,100);required(issues,`${base}.actorSnapshot.name`,item.actorSnapshot.name,100);if(!statuses.has(item.fromStatus)||!statuses.has(item.toStatus))issues.push({path:base,message:'审核状态无效'});if(item.reason!==null&&item.reason.trim().length>200)issues.push({path:`${base}.reason`,message:'不能超过200个字符'});if((item.outcome==='returned'||item.outcome==='canceled')&&!item.reason?.trim())issues.push({path:`${base}.reason`,message:'退回或取消必须填写原因'});nonnegative(issues,`${base}.releasedPrepaymentCents`,item.releasedPrepaymentCents);if(!iso(item.occurredAt))issues.push({path:`${base}.occurredAt`,message:'必须是ISO时间'});required(issues,`${base}.requestId`,item.requestId,100)})
  const keys=order.customAttributes.map((item)=>item.key); if(new Set(keys).size!==keys.length) issues.push({path:'customAttributes.key',message:'属性 key 必须唯一'})
  if(order.remark&&order.remark.length>500)issues.push({path:'remark',message:'不能超过500个字符'})
  if(order.attachments.length>10)issues.push({path:'attachments',message:'最多10个附件'})
  return issues
}

export function assertOrderFeatureState(state: OrderFeatureState): void {
  const issues: OrderValidationIssue[]=[]
  if(state.schemaVersion!==1) issues.push({path:'schemaVersion',message:'必须为1'}); required(issues,'enterpriseId',state.enterpriseId,100)
  const ids=state.orders.map((item)=>item.id); const numbers=state.orders.map((item)=>item.orderNo.toLocaleLowerCase())
  if(new Set(ids).size!==ids.length) issues.push({path:'orders.id',message:'企业内必须唯一'}); if(new Set(numbers).size!==numbers.length) issues.push({path:'orders.orderNo',message:'企业内必须唯一'})
  state.orders.forEach((order,index)=>{ if(order.enterpriseId!==state.enterpriseId) issues.push({path:`orders.${index}.enterpriseId`,message:'实体企业不一致'}); validateOrder(order).forEach((issue)=>issues.push({...issue,path:`orders.${index}.${issue.path}`})) })
  const requestIds=state.printRequests.map((item)=>item.requestId); if(new Set(requestIds).size!==requestIds.length) issues.push({path:'printRequests.requestId',message:'必须唯一'})
  state.printRequests.forEach((request,index)=>{ required(issues,`printRequests.${index}.requestId`,request.requestId,100); if(!iso(request.printedAt)) issues.push({path:`printRequests.${index}.printedAt`,message:'必须是 ISO 时间'}); request.orderIds.forEach((id)=>{if(!ids.includes(id)) issues.push({path:`printRequests.${index}.orderIds`,message:'订单不存在'})}) })
  const saveIds=(state.saveRequests??[]).map((item)=>item.requestId);if(new Set(saveIds).size!==saveIds.length)issues.push({path:'saveRequests.requestId',message:'必须唯一'});(state.saveRequests??[]).forEach((item,index)=>{required(issues,`saveRequests.${index}.requestId`,item.requestId,100);if(!ids.includes(item.orderId))issues.push({path:`saveRequests.${index}.orderId`,message:'订单不存在'});if(!iso(item.savedAt))issues.push({path:`saveRequests.${index}.savedAt`,message:'必须是ISO时间'})})
  const shareIds=(state.shares??[]).map((item)=>item.id);const hashes=(state.shares??[]).map((item)=>item.tokenHash);if(new Set(shareIds).size!==shareIds.length)issues.push({path:'shares.id',message:'必须唯一'});if(new Set(hashes).size!==hashes.length)issues.push({path:'shares.tokenHash',message:'必须唯一'});(state.shares??[]).forEach((item,index)=>{if(!ids.includes(item.orderId))issues.push({path:`shares.${index}.orderId`,message:'订单不存在'});if(!['unviewed','viewed','confirmed'].includes(item.status))issues.push({path:`shares.${index}.status`,message:'状态无效'});if(!iso(item.createdAt)||!iso(item.expiresAt))issues.push({path:`shares.${index}`,message:'分享时间无效'})})
  const reviewRequestIds=(state.reviewRequests??[]).map((item)=>item.requestId);if(new Set(reviewRequestIds).size!==reviewRequestIds.length)issues.push({path:'reviewRequests.requestId',message:'必须唯一'});(state.reviewRequests??[]).forEach((item,index)=>{required(issues,`reviewRequests.${index}.requestId`,item.requestId,100);if(!reviewActions.has(item.action))issues.push({path:`reviewRequests.${index}.action`,message:'动作无效'});if(!item.orderIds.length||new Set(item.orderIds).size!==item.orderIds.length)issues.push({path:`reviewRequests.${index}.orderIds`,message:'订单必须非空且唯一'});item.orderIds.forEach((id)=>{if(!ids.includes(id))issues.push({path:`reviewRequests.${index}.orderIds`,message:'订单不存在'})});if(!iso(item.appliedAt))issues.push({path:`reviewRequests.${index}.appliedAt`,message:'必须是ISO时间'})})
  const outboundIds=(state.outbounds??[]).map((item)=>item.id);const outboundNumbers=(state.outbounds??[]).map((item)=>item.outboundNo.toLocaleLowerCase());if(new Set(outboundIds).size!==outboundIds.length)issues.push({path:'outbounds.id',message:'必须唯一'});if(new Set(outboundNumbers).size!==outboundNumbers.length)issues.push({path:'outbounds.outboundNo',message:'企业内必须唯一'});(state.outbounds??[]).forEach((item,index)=>{const base=`outbounds.${index}`;required(issues,`${base}.id`,item.id,100);if(!/^XSCK-\d{6}-\d{5}$/.test(item.outboundNo))issues.push({path:`${base}.outboundNo`,message:'编号格式无效'});if(!ids.includes(item.orderId))issues.push({path:`${base}.orderId`,message:'订单不存在'});if(!['confirmed','voided'].includes(item.status))issues.push({path:`${base}.status`,message:'状态无效'});if(!iso(item.confirmedAt))issues.push({path:`${base}.confirmedAt`,message:'时间无效'});nonnegative(issues,`${base}.documentAmountCents`,item.documentAmountCents);if(!Number.isSafeInteger(item.version)||item.version<1)issues.push({path:`${base}.version`,message:'版本必须为正整数'});const lineIds=item.lines.map((line)=>line.id);if(!lineIds.length||new Set(lineIds).size!==lineIds.length)issues.push({path:`${base}.lines`,message:'出库行必须非空且唯一'});let amount=0;item.lines.forEach((line,lineIndex)=>{const lineBase=`${base}.lines.${lineIndex}`;if(!state.orders.find((order)=>order.id===item.orderId)?.lines.some((orderLine)=>orderLine.id===line.orderLineId))issues.push({path:`${lineBase}.orderLineId`,message:'订单行不存在'});if(!Number.isSafeInteger(line.quantity)||line.quantity<1)issues.push({path:`${lineBase}.quantity`,message:'必须是正整数'});if(!Number.isSafeInteger(line.quantityMilli)||line.quantityMilli<=0)issues.push({path:`${lineBase}.quantityMilli`,message:'必须是正整数毫单位'});nonnegative(issues,`${lineBase}.dealUnitPriceCents`,line.dealUnitPriceCents);nonnegative(issues,`${lineBase}.amountCents`,line.amountCents);if(line.amountCents!==line.quantity*line.dealUnitPriceCents)issues.push({path:`${lineBase}.amountCents`,message:'行金额计算不一致'});const allocationTotal=line.allocations.reduce((sum,value)=>sum+value.quantityMilli,0);if(allocationTotal!==line.quantityMilli)issues.push({path:`${lineBase}.allocations`,message:'FIFO 分配数量必须等于出库数量'});line.allocations.forEach((part,partIndex)=>{if(!Number.isSafeInteger(part.quantityMilli)||part.quantityMilli<=0)issues.push({path:`${lineBase}.allocations.${partIndex}.quantityMilli`,message:'必须是正整数毫单位'});required(issues,`${lineBase}.allocations.${partIndex}.movementId`,part.movementId,100)});amount+=line.amountCents});if(amount!==item.documentAmountCents)issues.push({path:`${base}.documentAmountCents`,message:'必须等于行金额之和'});if(item.status==='voided'&&!item.voidInfo)issues.push({path:`${base}.voidInfo`,message:'作废单必须保留作废信息'});if(item.voidInfo&&!iso(item.voidInfo.voidedAt))issues.push({path:`${base}.voidInfo.voidedAt`,message:'时间无效'})})
  const differenceIds=(state.differences??[]).map((item)=>item.id);const differenceNumbers=(state.differences??[]).map((item)=>item.differenceNo.toLocaleLowerCase());if(new Set(differenceIds).size!==differenceIds.length)issues.push({path:'differences.id',message:'必须唯一'});if(new Set(differenceNumbers).size!==differenceNumbers.length)issues.push({path:'differences.differenceNo',message:'企业内必须唯一'});(state.differences??[]).forEach((item,index)=>{const base=`differences.${index}`;if(!/^CY-\d{6}-\d{5}$/.test(item.differenceNo))issues.push({path:`${base}.differenceNo`,message:'编号格式无效'});if(!ids.includes(item.orderId))issues.push({path:`${base}.orderId`,message:'订单不存在'});if(item.outboundId!==null&&!outboundIds.includes(item.outboundId))issues.push({path:`${base}.outboundId`,message:'出库单不存在'});if(!['pending-confirmation','confirmed','voided'].includes(item.status))issues.push({path:`${base}.status`,message:'状态无效'});required(issues,`${base}.reason`,item.reason,200);if(!item.lines.length)issues.push({path:`${base}.lines`,message:'差异行不能为空'});const total=item.lines.reduce((sum,line)=>sum+line.differenceAmountCents,0);if(total!==item.differenceAmountCents)issues.push({path:`${base}.differenceAmountCents`,message:'必须等于行金额之和'});if(item.status==='confirmed'&&(!item.outcome||!item.confirmedAt||!item.confirmedBy))issues.push({path:base,message:'已确认差异缺少处理结果'});if(item.outcome!==null&&!['reship','ignore','refund'].includes(item.outcome))issues.push({path:`${base}.outcome`,message:'结果无效'});if(!Number.isSafeInteger(item.version)||item.version<1)issues.push({path:`${base}.version`,message:'版本必须为正整数'})})
  const onePerOrder=(path:string,values:Array<{orderId:string}>)=>{const orderIds=values.map((item)=>item.orderId);if(new Set(orderIds).size!==orderIds.length)issues.push({path,message:'每订单最多一条记录'});orderIds.forEach((id)=>{if(!ids.includes(id))issues.push({path,message:'订单不存在'})})};onePerOrder('shipments.orderId',state.shipments??[]);onePerOrder('receipts.orderId',state.receipts??[]);onePerOrder('receivables.orderId',state.receivables??[]);(state.shipments??[]).forEach((item,index)=>{if(!iso(item.shippedAt))issues.push({path:`shipments.${index}.shippedAt`,message:'时间无效'});if(item.deliveryMethod==='logistics'&&!item.logisticsCode?.trim())issues.push({path:`shipments.${index}.logisticsCode`,message:'物流配送必须有编码'});item.outboundIds.forEach((id)=>{if(!outboundIds.includes(id))issues.push({path:`shipments.${index}.outboundIds`,message:'出库单不存在'})})});(state.receipts??[]).forEach((item,index)=>{if(!iso(item.signedAt))issues.push({path:`receipts.${index}.signedAt`,message:'时间无效'});required(issues,`receipts.${index}.signer`,item.signer,80)});(state.receivables??[]).forEach((item,index)=>{nonnegative(issues,`receivables.${index}.amountCents`,item.amountCents);if(!iso(item.occurredAt))issues.push({path:`receivables.${index}.occurredAt`,message:'时间无效'})})
  const fulfillmentRequestIds=(state.fulfillmentRequests??[]).map((item)=>item.requestId);if(new Set(fulfillmentRequestIds).size!==fulfillmentRequestIds.length)issues.push({path:'fulfillmentRequests.requestId',message:'必须唯一'});(state.fulfillmentRequests??[]).forEach((item,index)=>{required(issues,`fulfillmentRequests.${index}.requestId`,item.requestId,100);if(!item.targetIds.length)issues.push({path:`fulfillmentRequests.${index}.targetIds`,message:'不能为空'});if(!iso(item.appliedAt))issues.push({path:`fulfillmentRequests.${index}.appliedAt`,message:'时间无效'})})
  Object.entries(state.nextOrderSequenceByDate??{}).forEach(([day,value])=>{if(!/^\d{6}$/.test(day)||!Number.isSafeInteger(value)||value<1)issues.push({path:`nextOrderSequenceByDate.${day}`,message:'日期序列无效'})})
  Object.entries(state.nextOutboundSequenceByDate??{}).forEach(([day,value])=>{if(!/^\d{6}$/.test(day)||!Number.isSafeInteger(value)||value<1)issues.push({path:`nextOutboundSequenceByDate.${day}`,message:'日期序列无效'})});Object.entries(state.nextDifferenceSequenceByDate??{}).forEach(([day,value])=>{if(!/^\d{6}$/.test(day)||!Number.isSafeInteger(value)||value<1)issues.push({path:`nextDifferenceSequenceByDate.${day}`,message:'日期序列无效'})})
  issues.push(...validateReturnState(state))
  if(issues.length) throw new OrderValidationError(issues)
}

export function normalizeOrderQuery(query: OrderQuery): Required<Pick<OrderQuery,'page'|'pageSize'>> & OrderQuery {
  const issues: OrderValidationIssue[]=[]; const page=query.page??1; const pageSize=query.pageSize??30
  if(!Number.isSafeInteger(page)||page<1) issues.push({path:'page',message:'必须是正整数'}); if(![10,30,50,100].includes(pageSize)) issues.push({path:'pageSize',message:'只允许10/30/50/100'})
  if(query.statuses?.some((item)=>!statuses.has(item))) issues.push({path:'statuses',message:'包含无效状态'})
  const dates: Array<[string,string|undefined]>=[['orderedFrom',query.orderedFrom],['orderedTo',query.orderedTo],['deliveryFrom',query.deliveryFrom],['deliveryTo',query.deliveryTo]]
  dates.forEach(([path,value])=>{if(value&&!iso(value)) issues.push({path,message:'必须是 ISO 时间'})})
  if(query.orderedFrom&&query.orderedTo&&Date.parse(query.orderedFrom)>Date.parse(query.orderedTo)) issues.push({path:'orderedTo',message:'不能早于开始时间'})
  if(query.deliveryFrom&&query.deliveryTo&&Date.parse(query.deliveryFrom)>Date.parse(query.deliveryTo)) issues.push({path:'deliveryTo',message:'不能早于开始时间'})
  const amounts: Array<[string,number|undefined]>=[['amountMinCents',query.amountMinCents],['amountMaxCents',query.amountMaxCents]]
  amounts.forEach(([path,value])=>{if(value!==undefined&&(!Number.isSafeInteger(value)||value<0)) issues.push({path,message:'必须是非负整数分'})})
  if(query.amountMinCents!==undefined&&query.amountMaxCents!==undefined&&query.amountMinCents>query.amountMaxCents) issues.push({path:'amountMaxCents',message:'不能小于最低金额'})
  if(issues.length) throw new OrderValidationError(issues)
  return {...query,keyword:query.keyword?.trim()||undefined,page,pageSize}
}
