<script setup lang="ts">
import { computed } from 'vue'
import type { CustomerScope, DistributionWorkspaceOptions } from '../types'
const scope = defineModel<CustomerScope>({ required: true })
const props = defineProps<{ options: DistributionWorkspaceOptions; disabled?: boolean }>()
const provinces = computed(() => [...new Set(props.options.customers.map((item) => item.provinceCode))])
const cities = computed(() => [...new Set(props.options.customers.map((item) => item.cityCode))])
const districts = computed(() => [...new Set(props.options.customers.map((item) => item.districtCode))])
function setType(type: CustomerScope['type']) { scope.value = { type, provinceCodes: [], cityCodes: [], districtCodes: [], categoryIds: [], tagIds: [], customerIds: [] } }
</script>
<template><fieldset class="scope-editor" :disabled="disabled"><legend>适用客户范围 *</legend><div class="scope-types"><label><input type="radio" :checked="scope.type==='all'" @change="setType('all')">全部客户</label><label><input type="radio" :checked="scope.type==='criteria'" @change="setType('criteria')">按区域 / 分类 / 标签</label><label><input type="radio" :checked="scope.type==='specified'" @change="setType('specified')">指定客户</label></div><p v-if="scope.type==='all'" class="hint">解析时仍会动态排除非启用客户；移动端还会检查自主下单开关。</p><div v-else-if="scope.type==='criteria'" class="scope-groups"><section><strong>区域（跨维度取交集，同维度取并集）</strong><div class="checks"><label v-for="item in provinces" :key="item"><input v-model="scope.provinceCodes" type="checkbox" :value="item">省 {{item}}</label><label v-for="item in cities" :key="item"><input v-model="scope.cityCodes" type="checkbox" :value="item">市 {{item}}</label><label v-for="item in districts" :key="item"><input v-model="scope.districtCodes" type="checkbox" :value="item">区 {{item}}</label></div></section><section><strong>客户分类（包含后代分类）</strong><div class="checks"><label v-for="item in options.customerCategories" :key="item.id"><input v-model="scope.categoryIds" type="checkbox" :value="item.id">{{item.name}}</label></div></section><section><strong>客户标签（任一标签命中）</strong><div class="checks"><label v-for="item in options.customerTags" :key="item.id"><input v-model="scope.tagIds" type="checkbox" :value="item.id">{{item.name}}</label></div></section></div><div v-else class="checks customer-checks"><label v-for="item in options.customers.filter(x=>x.status==='active')" :key="item.id"><input v-model="scope.customerIds" type="checkbox" :value="item.id">{{item.code}} · {{item.name}}</label><em v-if="!options.customers.length">客户资料不可用，不允许用空名单覆盖已有配置</em></div></fieldset></template>
