<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { useSettingsStore } from '../runtime/settings-store'
import SettingsSubnav from '../components/SettingsSubnav.vue'
import SettingsScenarioBar from '../components/SettingsScenarioBar.vue'
import './settings-views.css'
const store = useSettingsStore(); const { announcements, loading, error, saving, scenario, actor } = storeToRefs(store)
const editing = ref<string | null>(null); const showForm = ref(false); const formError = ref('')
const blank = () => ({ title: '', type: 'general' as const, content: '', linkText: null, linkUrl: null, recipientScope: 'all' as const, recipientDepartmentIds: [] as string[], pushEnabled: false, publisher: '系统管理员', attachments: [], contentMeta: { images: [], aiDraft: null } })
const form = reactive<any>(blank())
onMounted(() => store.load())
function open(row?: any) { showForm.value = true; editing.value = row?.id ?? null; Object.assign(form, row ? structuredClone(row) : blank()); formError.value = '' }
function close() { showForm.value = false; editing.value = null; Object.assign(form, blank()) }
async function submit() { try { await store.saveAnnouncement(form, editing.value ?? undefined); close() } catch (e) { formError.value = e instanceof Error ? e.message : '保存失败' } }
async function publish(id: string) { try { await store.publishAnnouncement(id) } catch (e) { formError.value = e instanceof Error ? e.message : '发布失败' } }
async function retry(id: string) { try { await store.retryAnnouncementPush(id) } catch (e) { formError.value = e instanceof Error ? e.message : '重试失败' } }
</script>
<template><section class="settings-page"><header class="settings-header"><div><p class="eyebrow">SET-001 · 内部沟通</p><h1>内部公告</h1><p>AI、图片、附件和推送均为 fake；发布后保存不可变快照。</p></div><SettingsScenarioBar :scenario="scenario" :role="actor.role" @scenario="store.setScenario" @role="store.setRole"/></header><SettingsSubnav/><div v-if="error||formError" class="settings-warning">{{error||formError}}</div><section class="settings-panel"><div class="settings-toolbar"><strong>公告（{{announcements.length}}）</strong><button class="set-button primary" :disabled="!store.canWrite" @click="open()">新建公告</button></div><div v-if="loading" class="settings-state">正在加载公告…</div><div v-else-if="!announcements.length" class="settings-state">暂无公告</div><div v-else class="settings-table-wrap"><table class="settings-table"><thead><tr><th>标题</th><th>类型</th><th>接收对象</th><th>状态</th><th>发布时间</th><th>操作</th></tr></thead><tbody><tr v-for="row in announcements" :key="row.id"><td><strong>{{row.title}}</strong><small>{{row.publisher}}</small></td><td>{{row.type}}</td><td>{{row.recipientScope==='all'?'全部员工':'指定部门'}}</td><td>{{row.status==='published'?'已发布':row.status==='withdrawn'?'已撤回':'草稿'}}<small v-if="row.pushState==='failed'">推送失败</small></td><td>{{row.publishedAt??'—'}}</td><td><button v-if="row.status==='draft'" class="set-button" @click="open(row)">编辑</button><button v-if="row.status==='draft'" class="set-button primary" @click="publish(row.id)">发布</button><button v-if="row.pushState==='failed'" class="set-button" @click="retry(row.id)">重试推送</button></td></tr></tbody></table></div></section><section v-if="showForm" class="settings-panel"><form class="settings-form" @submit.prevent="submit"><label>标题<input v-model.trim="form.title" maxlength="20" required></label><label>通知类型<select v-model="form.type"><option value="general">普通通知</option><option value="policy">制度通知</option><option value="event">活动通知</option><option value="alert">告警通知</option></select></label><label class="wide">内容<textarea v-model="form.content" required></textarea></label><label>链接文字<input v-model.trim="form.linkText" maxlength="100"></label><label>链接地址<input v-model.trim="form.linkUrl" maxlength="300" placeholder="https://"></label><label>接收对象<select v-model="form.recipientScope"><option value="all">全部员工</option><option value="departments">指定部门</option></select></label><label>推送消息<select v-model="form.pushEnabled"><option :value="false">关闭</option><option :value="true">开启（fake）</option></select></label><div class="settings-actions"><button type="button" class="set-button" @click="close">取消</button><button class="set-button primary" :disabled="saving">保存草稿</button></div></form></section></section></template>
