<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { useSettingsStore } from '../runtime/settings-store'
import SettingsSubnav from '../components/SettingsSubnav.vue'
import SettingsScenarioBar from '../components/SettingsScenarioBar.vue'
import type { SettingsRoleDraft } from '../types'
import './settings-views.css'

const store = useSettingsStore(); const { roles, permissionCatalog, loading, saving, error, scenario, actor } = storeToRefs(store)
const editingId = ref<string>(); const form = reactive<SettingsRoleDraft>({ name: '', description: '', permissionIds: [], status: 'enabled' }); const formError = ref('')
onMounted(() => store.load())
function edit(role: typeof roles.value[number]) { editingId.value = role.id; Object.assign(form, { name: role.name, description: role.description, permissionIds: [...role.permissionIds], status: role.status }) }
function reset() { editingId.value = undefined; Object.assign(form, { name: '', description: '', permissionIds: [], status: 'enabled' }) }
async function submit() { formError.value = ''; try { await store.saveRole({ ...form, permissionIds: [...form.permissionIds] }, editingId.value); reset() } catch (e) { formError.value = e instanceof Error ? e.message : '保存失败' } }
</script>
<template><section class="settings-page"><header class="settings-header"><div><p class="eyebrow">SET-002 · RBAC</p><h1>角色权限</h1><p>权限保存为版本快照，重新登录后对新会话生效。</p></div><SettingsScenarioBar :scenario="scenario" :role="actor.role" @scenario="store.setScenario" @role="store.setRole"/></header><SettingsSubnav/><div v-if="error||formError" class="settings-warning" role="alert">{{error||formError}} <button class="set-button" @click="store.load">重试</button></div><div class="settings-access-grid"><div class="settings-panel"><div class="settings-toolbar"><strong>角色列表</strong><button class="set-button primary" :disabled="actor.role!=='super-admin'" @click="reset">新建角色</button></div><div v-if="loading" class="settings-state">正在加载角色…</div><div v-else class="settings-table-wrap"><table class="settings-table"><thead><tr><th>名称</th><th>类型</th><th>权限数</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="role in roles" :key="role.id"><td>{{role.name}}<small>{{role.description||'—'}}</small></td><td>{{role.kind==='system'?'系统':'自定义'}}</td><td>{{role.permissionIds.length}}</td><td><span :class="['settings-status',{disabled:role.status==='disabled'}]">{{role.status==='enabled'?'启用':'停用'}}</span></td><td><button class="set-button" :disabled="role.kind==='system'" @click="edit(role)">编辑</button><button class="set-button danger" :disabled="role.kind==='system'||role.status==='disabled'" @click="store.disableRole(role.id)">停用</button></td></tr></tbody></table></div></div><form class="settings-panel settings-form" @submit.prevent="submit"><h2 class="settings-form-title">{{editingId?'编辑自定义角色':'新建自定义角色'}}</h2><label>角色名称<input v-model.trim="form.name" maxlength="60" required></label><label>状态<select v-model="form.status"><option value="enabled">启用</option><option value="disabled">停用</option></select></label><label class="wide">描述<input v-model.trim="form.description"></label><fieldset class="settings-permissions"><legend>权限目录</legend><label v-for="permission in permissionCatalog" :key="permission.id" class="permission-option"><input v-model="form.permissionIds" type="checkbox" :value="permission.id">{{permission.label}}<small>{{permission.id}}</small></label></fieldset><div class="settings-actions"><button type="button" class="set-button" @click="reset">清空</button><button class="set-button primary" :disabled="saving||actor.role!=='super-admin'">{{saving?'保存中…':'保存角色'}}</button></div></form></div></section></template>
