<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { useSettingsStore } from '../runtime/settings-store'
import SettingsSubnav from '../components/SettingsSubnav.vue'
import SettingsScenarioBar from '../components/SettingsScenarioBar.vue'
import './settings-views.css'
const store = useSettingsStore(); const { regions, loading, error, saving, scenario, actor } = storeToRefs(store)
const editing = ref<string | null>(null); const showForm = ref(false); const formError = ref('')
const form = reactive({ name: '', parentId: null as string | null, type: 'region' as 'region'|'province'|'city'|'district'|'warehouse', status: 'enabled' as 'enabled'|'disabled', isDefault: false })
const rows = computed(() => regions.value.map((item) => ({ ...item, level: item.parentId ? 1 : 0 })))
onMounted(() => store.load())
function open(row?: any) { showForm.value = true; editing.value = row?.id ?? null; Object.assign(form, row ? { name: row.name, parentId: row.parentId, type: row.type, status: row.status, isDefault: row.isDefault } : { name: '', parentId: null, type: 'region', status: 'enabled', isDefault: false }); formError.value = '' }
function close() { showForm.value = false; editing.value = null; form.name = ''; form.parentId = null; form.isDefault = false }
async function submit() { try { await store.saveRegion({ ...form }, editing.value ?? undefined); close() } catch (e) { formError.value = e instanceof Error ? e.message : '保存失败' } }
async function remove(id: string) { if (confirm('确认删除该区域？')) try { await store.deleteRegion(id) } catch (e) { formError.value = e instanceof Error ? e.message : '删除失败' } }
</script>
<template><section class="settings-page"><header class="settings-header"><div><p class="eyebrow">SET-003 · 归属资料</p><h1>区域管理</h1><p>保留唯一默认根区域；存在子区域、客户或仓库引用时不能删除。</p></div><SettingsScenarioBar :scenario="scenario" :role="actor.role" @scenario="store.setScenario" @role="store.setRole"/></header><SettingsSubnav/><div v-if="error||formError" class="settings-warning">{{error||formError}}</div><section class="settings-panel"><div class="settings-toolbar"><strong>区域树（{{regions.length}}）</strong><button class="set-button primary" @click="open()">新增区域</button></div><div v-if="loading" class="settings-state">正在加载区域…</div><div v-else-if="!rows.length" class="settings-state">暂无区域资料</div><div v-else class="settings-tree"><div v-for="row in rows" :key="row.id" class="settings-tree-row" :class="`level-${row.level}`"><div class="settings-tree-main"><strong>{{row.name}}</strong><small>{{row.code}} · {{row.type}} <span v-if="row.isDefault">· 默认</span></small><span class="settings-status" :class="{disabled:row.status==='disabled'}">{{row.status==='enabled'?'启用':'停用'}}</span></div><div><button class="set-button" @click="open(row)">编辑</button><button class="set-button danger" :disabled="saving" @click="remove(row.id)">删除</button></div></div></div></section><section v-if="showForm" class="settings-panel"><form class="settings-form" @submit.prevent="submit"><label>区域名称<input v-model.trim="form.name" required maxlength="100"></label><label>上级区域<select v-model="form.parentId"><option :value="null">无（根区域）</option><option v-for="row in regions.filter(x=>x.id!==editing)" :key="row.id" :value="row.id">{{row.name}}</option></select></label><label>区域类型<select v-model="form.type"><option value="region">大区</option><option value="province">省份</option><option value="city">城市</option><option value="district">区县</option><option value="warehouse">仓库</option></select></label><label>状态<select v-model="form.status"><option value="enabled">启用</option><option value="disabled">停用</option></select></label><label><input v-model="form.isDefault" type="checkbox"> 默认根区域</label><div class="settings-actions"><button type="button" class="set-button" @click="close">取消</button><button class="set-button primary" :disabled="saving">保存</button></div></form></section></section></template>
