<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { storeToRefs } from 'pinia'
import CustomerSubnav from '../components/CustomerSubnav.vue'
import { useCustomerStore } from '../runtime/customer-store'

const props = defineProps<{ mode: 'wecom' | 'mall' }>()
const store = useCustomerStore()
const { channelState, loading, error } = storeToRefs(store)
const actionError = ref<string | null>(null)
const title = computed(() => props.mode === 'wecom' ? '企微运营' : '商城运营')
const syncDraft = reactive({ enabled: false, frequency: 'daily' as const, scope: ['all'], autoCreateCustomer: false, autoMapStaff: false })
const broadcastDraft = reactive({ title: '', employeeIds: ['staff-demo-1'], audience: 'all' as const, customerIds: [] as string[], content: '', image: null, link: null, sendMode: 'now' as 'now' | 'scheduled', scheduledAt: null as string | null })
const mallCustomerDraft = reactive({ customerId: null, name: '', account: '', phone: '', channel: 'h5' as const, status: 'active' as const, password: '' })
const mallEmployeeDraft = reactive({ customerId: 'customer-demo-1', name: '', phone: '', role: 'clerk' as const, permissions: ['view-product'], status: 'active' as const, password: '' })
const mallSettingsDraft = reactive({ name: '蜂订商城（原型）', introduction: '', displayMode: 'double' as const, searchEnabled: true, categoryEnabled: true, salesVisible: false, stockVisible: false, reviewVisible: false, cartEnabled: true, favoriteEnabled: true, shareEnabled: true, reviewEnabled: true, serviceEnabled: false, paymentMethods: ['wechat'], minimumPaymentCents: 0, paymentTimeoutMinutes: 30 })
function run(action: () => Promise<unknown>): void { actionError.value = null; action().catch((caught) => { actionError.value = caught instanceof Error ? caught.message : '操作失败' }) }
function saveSync(): void { run(() => store.saveWecomSyncSettings({ ...syncDraft })) }
function saveBroadcast(): void { run(async () => { await store.saveWecomBroadcast({ ...broadcastDraft }); broadcastDraft.title = ''; broadcastDraft.content = '' }) }
function saveMallCustomer(): void { run(async () => { await store.saveMallCustomer({ ...mallCustomerDraft }); mallCustomerDraft.name = ''; mallCustomerDraft.account = ''; mallCustomerDraft.phone = ''; mallCustomerDraft.password = '' }) }
function saveMallEmployee(): void { run(async () => { await store.saveMallEmployee({ ...mallEmployeeDraft }); mallEmployeeDraft.name = ''; mallEmployeeDraft.phone = ''; mallEmployeeDraft.password = '' }) }
function saveMallSettings(): void { run(() => store.saveMallSettings({ ...mallSettingsDraft })) }
onMounted(() => store.loadOperations())
</script>

<template>
  <section class="channel-page">
    <header class="page-header"><div><p class="eyebrow">客户运营 · 原型模拟</p><h1>{{ title }}</h1><p>外部渠道只保存 fake 配置和预览，不连接第三方、不发送消息、不执行支付。</p></div><RouterLink class="button" to="/customers">返回客户</RouterLink></header>
    <CustomerSubnav />
    <p v-if="actionError || error" class="alert" role="alert">{{ actionError || error }}</p>
    <div v-if="loading" class="state">正在加载渠道资料…</div>
    <template v-else-if="props.mode === 'wecom'">
      <section class="card"><div class="toolbar"><h2>企微同步设置</h2><span class="unavailable">fake adapter</span></div><div class="form-grid"><label>开启同步<input v-model="syncDraft.enabled" type="checkbox"></label><label>同步频率<select v-model="syncDraft.frequency"><option value="realtime">实时</option><option value="hourly">每小时</option><option value="daily">每天</option></select></label><label>自动创建客户<input v-model="syncDraft.autoCreateCustomer" type="checkbox"></label><label>默认业务员映射<input v-model="syncDraft.autoMapStaff" type="checkbox"></label></div><button class="button button--primary" type="button" @click="saveSync">保存同步设置</button></section>
      <section class="card"><div class="toolbar"><h2>群发记录 <small>{{ channelState?.wecomBroadcasts?.length ?? 0 }} 条</small></h2></div><table><thead><tr><th>标题</th><th>对象</th><th>方式</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in channelState?.wecomBroadcasts ?? []" :key="item.id"><td>{{ item.title }}</td><td>{{ item.audience === 'all' ? '全部客户' : '指定客户' }}</td><td>{{ item.sendMode === 'now' ? '立即' : '定时' }}</td><td>{{ item.status }}</td><td><button class="link danger" type="button" @click="run(() => store.setWecomBroadcastStatus(item.id, 'recalled'))">撤回</button></td></tr></tbody></table><p class="hint">同步记录 {{ channelState?.wecomSyncRecords?.length ?? 0 }} 条，标签映射 {{ channelState?.wecomTagMappings?.length ?? 0 }} 条，话术 {{ channelState?.wecomScripts?.length ?? 0 }} 条，客户群 {{ channelState?.wecomGroups?.length ?? 0 }} 个。</p></section>
      <form class="card form" @submit.prevent="saveBroadcast"><h2>新增企微群发（fake）</h2><label>群发标题<input v-model="broadcastDraft.title" required maxlength="50"></label><label>群发内容<textarea v-model="broadcastDraft.content" rows="4" required></textarea></label><label>发送方式<select v-model="broadcastDraft.sendMode"><option value="now">立即发送</option><option value="scheduled">定时发送</option></select></label><label v-if="broadcastDraft.sendMode === 'scheduled'">定时发送时间<input v-model="broadcastDraft.scheduledAt" type="datetime-local" required></label><button class="button button--primary" type="submit">保存 fake 群发</button></form>
    </template>
    <template v-else>
      <section class="card"><div class="toolbar"><h2>商城客户 <small>{{ channelState?.mallCustomers?.length ?? 0 }} 个</small></h2><span class="unavailable">账号登录未接入</span></div><table><thead><tr><th>客户</th><th>账号</th><th>渠道</th><th>登录次数</th><th>订单数</th><th>状态</th></tr></thead><tbody><tr v-for="item in channelState?.mallCustomers ?? []" :key="item.id"><td>{{ item.name }}</td><td>{{ item.account }}</td><td>{{ item.channel }}</td><td>{{ item.loginCount }}</td><td>{{ item.orderCount ?? 'unavailable' }}</td><td>{{ item.status }}</td></tr></tbody></table></section>
      <form class="card form" @submit.prevent="saveMallCustomer"><h2>新增商城客户（fake）</h2><label>客户名称<input v-model="mallCustomerDraft.name" required></label><label>登录账号<input v-model="mallCustomerDraft.account" required></label><label>手机号<input v-model="mallCustomerDraft.phone" required></label><label>一次性密码<input v-model="mallCustomerDraft.password" type="password" required></label><button class="button button--primary" type="submit">保存 fake 账号</button><p class="hint">密码不会写入 Repository，也不会创建可登录账号。</p></form>
      <section class="card"><div class="toolbar"><h2>商城扩展</h2><span>{{ channelState?.mallExtensions?.filter((item) => item.enabled).length ?? 0 }} 个已启用</span></div><div class="extension-grid"><label v-for="item in channelState?.mallExtensions ?? []" :key="item.id"><input :checked="item.enabled" type="checkbox" @change="run(() => store.setMallExtension(item.id, !item.enabled))">{{ item.name }}</label></div></section>
      <form class="card form" @submit.prevent="saveMallEmployee"><h2>新增商城员工（fake）</h2><label>员工姓名<input v-model="mallEmployeeDraft.name" required></label><label>手机号<input v-model="mallEmployeeDraft.phone" required></label><label>角色<select v-model="mallEmployeeDraft.role"><option value="manager">店长</option><option value="clerk">店员</option></select></label><label>一次性密码<input v-model="mallEmployeeDraft.password" type="password" required></label><button class="button button--primary" type="submit">保存 fake 员工</button></form>
      <form class="card form" @submit.prevent="saveMallSettings"><h2>商城设置</h2><label>商城名称<input v-model="mallSettingsDraft.name" required maxlength="20"></label><label>展示方式<select v-model="mallSettingsDraft.displayMode"><option value="list">列表</option><option value="large">大图</option><option value="double">双列</option></select></label><label>支付方式（fake）<input v-model="mallSettingsDraft.paymentMethods[0]" required></label><label>支付超时（分钟）<input v-model.number="mallSettingsDraft.paymentTimeoutMinutes" type="number" min="1"></label><button class="button button--primary" type="submit">保存商城设置</button></form>
      <section class="card"><h2>装修预览</h2><p>{{ channelState?.mallDesigns?.[0]?.name ?? '暂无装修方案' }}</p><div class="preview">{{ channelState?.mallDesigns?.[0]?.components?.map((item) => item.title || item.type).join(' · ') || '暂无组件' }}</div><p class="hint">广告、弹窗、渠道消息和装修发布均为本地 fake 快照。</p></section>
    </template>
  </section>
</template>

<style scoped>
.channel-page{max-width:1680px;margin:0 auto}.page-header{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:14px}.page-header h1{margin:3px 0}.page-header p{margin-bottom:0;color:var(--color-muted)}.button{display:inline-flex;align-items:center;min-height:36px;padding:0 14px;color:#4d5968;background:#fff;border:1px solid var(--color-border-strong);border-radius:var(--radius-sm);text-decoration:none;cursor:pointer}.button--primary{color:#fff;background:var(--color-primary);border-color:var(--color-primary)}.alert{padding:10px;color:var(--color-danger);background:#fff0f0;border:1px solid #efcaca}.card{padding:16px;background:#fff;border:1px solid var(--color-border);border-radius:var(--radius-md);margin-bottom:14px}.card h2{margin:0 0 14px;font-size:16px}.card h2 small{margin-left:8px;color:var(--color-muted);font-size:12px;font-weight:400}.form{display:grid;gap:10px;align-content:start}.form label,.form-grid label{display:grid;gap:4px;color:var(--color-muted);font-size:12px}.form input,.form select,.form textarea,.form-grid input,.form-grid select{min-height:35px;padding:6px 8px;border:1px solid var(--color-border-strong);border-radius:var(--radius-sm)}.form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:12px}table{width:100%;border-collapse:collapse}th,td{padding:10px 11px;text-align:left;border-bottom:1px solid var(--color-border);white-space:nowrap}th{color:var(--color-muted);font-size:12px;background:var(--color-table-head)}.toolbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.link{padding:0;color:var(--color-primary-strong);cursor:pointer;background:transparent;border:0}.danger{color:var(--color-danger)}.hint,.unavailable{color:var(--color-muted);font-size:12px}.state{display:grid;min-height:220px;place-items:center;color:var(--color-muted)}.extension-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.extension-grid label{padding:10px;background:var(--color-table-head);border:1px solid var(--color-border)}.preview{padding:26px;background:#f5f7fa;border:1px dashed var(--color-border-strong);color:var(--color-muted)}@media(max-width:900px){.page-header{align-items:flex-start;flex-direction:column;gap:10px}.form-grid,.extension-grid{grid-template-columns:repeat(2,minmax(0,1fr))}table{min-width:760px}}
</style>
