<script setup lang="ts">
import { onMounted, reactive, ref, toRaw } from 'vue'
import { storeToRefs } from 'pinia'
import CustomerSubnav from '../components/CustomerSubnav.vue'
import { validateTagDraft } from '../schemas/customer-schema'
import { useCustomerStore } from '../runtime/customer-store'
import type { CustomerTag, CustomerTagColor, CustomerTagDraft } from '../types'

const store = useCustomerStore()
const { tags, loading, error } = storeToRefs(store)
const editingId = ref<string | null>(null)
const actionError = ref<string | null>(null)
const errors = reactive<Record<string, string>>({})
const colors: CustomerTagColor[] = ['#F5222D', '#FA8C16', '#52C41A', '#1890FF', '#8C8C8C']
const draft = reactive<CustomerTagDraft>(emptyDraft())

function emptyDraft(): CustomerTagDraft { return { name: '', code: '', color: '#1890FF', type: 'manual', sortOrder: 0, description: null, status: 'active' } }
function reset(): void { editingId.value = null; Object.assign(draft, emptyDraft()); Object.keys(errors).forEach((key) => delete errors[key]); actionError.value = null }
function edit(item: CustomerTag): void { editingId.value = item.id; Object.assign(draft, structuredClone(toRaw(item))); actionError.value = null }
async function save(): Promise<void> { Object.keys(errors).forEach((key) => delete errors[key]); for (const issue of validateTagDraft(draft)) if (!errors[issue.path]) errors[issue.path] = issue.message; if (Object.keys(errors).length) return; try { await store.saveTag(structuredClone(toRaw(draft)), editingId.value ?? undefined); reset() } catch (caught) { actionError.value = caught instanceof Error ? caught.message : '标签保存失败' } }
async function remove(item: CustomerTag): Promise<void> { if (!window.confirm(`确认删除标签“${item.name}”吗？`)) return; try { await store.deleteTag(item.id) } catch (caught) { actionError.value = caught instanceof Error ? caught.message : '标签删除失败' } }
onMounted(() => store.loadManagement())
</script>

<template>
  <section class="tag-page"><header><div><p class="eyebrow">CUS-001 · 客户资料</p><h1>客户标签</h1><p>手动与智能标签共用统一字典；停用不会删除已有关系。</p></div><button class="button button--primary" type="button" @click="reset">新增标签</button></header><CustomerSubnav />
    <p v-if="actionError || error" class="error" role="alert">{{ actionError || error }}</p>
    <div class="tag-layout"><section class="tag-list-card"><div class="card-title"><h2>标签列表</h2><span>{{ tags.length }} 个标签</span></div><div v-if="loading" class="empty">正在加载…</div><table v-else><thead><tr><th>标签</th><th>编码</th><th>类型</th><th>排序</th><th>状态</th><th>说明</th><th>操作</th></tr></thead><tbody><tr v-for="item in tags" :key="item.id"><td><span class="tag-pill"><i :style="{ backgroundColor: item.color }"></i>{{ item.name }}</span></td><td class="mono">{{ item.code }}</td><td>{{ item.type === 'manual' ? '手动标签' : '智能标签' }}</td><td>{{ item.sortOrder }}</td><td><span :class="['state', item.status]">{{ item.status === 'active' ? '启用' : '停用' }}</span></td><td>{{ item.description || '—' }}</td><td><button type="button" @click="edit(item)">编辑</button><button class="danger" type="button" @click="remove(item)">删除</button></td></tr></tbody></table></section>
      <form class="edit-card" @submit.prevent="save"><h2>{{ editingId ? '编辑标签' : '新增标签' }}</h2><label><span>标签名称 *</span><input v-model="draft.name" maxlength="10"><em>{{ errors.name }}</em></label><label><span>标签编码 *</span><input v-model="draft.code"><em>{{ errors.code }}</em></label><fieldset><legend>标签颜色 *</legend><label v-for="color in colors" :key="color" class="color-choice"><input v-model="draft.color" type="radio" :value="color"><i :style="{ backgroundColor: color }"></i><code>{{ color }}</code></label></fieldset><label><span>标签类型 *</span><select v-model="draft.type"><option value="manual">手动标签</option><option value="smart">智能标签</option></select><small>标签被客户或建议引用后不能修改类型</small></label><label><span>排序</span><input v-model.number="draft.sortOrder" type="number"></label><label><span>状态</span><select v-model="draft.status"><option value="active">启用</option><option value="inactive">停用</option></select></label><label><span>标签描述</span><textarea v-model="draft.description" rows="3"></textarea></label><div class="form-actions"><button class="button" type="button" @click="reset">取消</button><button class="button button--primary" type="submit">保存标签</button></div></form>
    </div>
  </section>
</template>

<style scoped>
.tag-page { max-width: 1600px; margin: 0 auto; }.tag-page > header { display: flex; align-items: flex-end; justify-content: space-between; margin-bottom: 14px; }.tag-page h1 { margin-bottom: 4px; }.tag-page header p { margin-bottom: 0; color: var(--color-muted); }.button { min-height: 36px; padding: 0 14px; cursor: pointer; background: #fff; border: 1px solid var(--color-border-strong); border-radius: var(--radius-sm); }.button--primary { color: #fff; background: var(--color-primary); border-color: var(--color-primary); }.error { margin: 12px 0 0; padding: 10px; color: var(--color-danger); background: #fff0f0; border: 1px solid #efcaca; }.tag-layout { display: grid; grid-template-columns: minmax(0, 1fr) 330px; gap: 14px; margin-top: 14px; }.tag-list-card, .edit-card { overflow: hidden; background: #fff; border: 1px solid var(--color-border); border-radius: var(--radius-md); }.card-title { display: flex; justify-content: space-between; padding: 14px; }.card-title h2 { margin: 0; }.card-title span { color: var(--color-muted); font-size: 12px; }table { width: 100%; min-width: 780px; border-collapse: collapse; }th, td { padding: 10px 12px; text-align: left; border-top: 1px solid var(--color-border); }th { color: var(--color-muted); font-size: 12px; background: var(--color-table-head); }td button { padding: 0; margin-right: 10px; color: var(--color-primary-strong); cursor: pointer; background: none; border: 0; }.danger { color: var(--color-danger); }.tag-pill { display: inline-flex; gap: 7px; align-items: center; }.tag-pill i, .color-choice i { width: 9px; height: 9px; border-radius: 50%; }.mono { font-family: Consolas, monospace; font-size: 12px; }.state { padding: 3px 7px; border-radius: 999px; }.state.active { color: var(--color-success); background: var(--color-success-soft); }.state.inactive { color: var(--color-muted); background: #eef1f5; }.edit-card { display: grid; gap: 11px; align-content: start; padding: 16px; }.edit-card label { display: grid; gap: 4px; color: var(--color-muted); font-size: 12px; }.edit-card input, .edit-card select, .edit-card textarea { min-height: 35px; padding: 6px 8px; border: 1px solid var(--color-border-strong); border-radius: var(--radius-sm); }.edit-card em { color: var(--color-danger); font-size: 11px; font-style: normal; }.edit-card small { color: #8993a1; }.edit-card fieldset { padding: 10px; border: 1px solid var(--color-border); border-radius: var(--radius-sm); }.edit-card legend { color: var(--color-muted); font-size: 12px; }.color-choice { display: flex !important; gap: 7px !important; align-items: center; min-height: 28px; color: var(--color-text) !important; }.color-choice input { min-height: auto; }.color-choice code { font-size: 11px; }.form-actions { display: flex; justify-content: flex-end; }.form-actions .button + .button { margin-left: 8px; }.empty { display: grid; min-height: 220px; place-items: center; color: var(--color-muted); }
@media (max-width: 1000px) { .tag-layout { grid-template-columns: 1fr; }.tag-list-card { overflow-x: auto; } } @media (max-width: 640px) { .tag-page > header { align-items: flex-start; flex-direction: column; gap: 10px; } }
</style>
