<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { storeToRefs } from 'pinia'
import CustomerSubnav from '../components/CustomerSubnav.vue'
import { useCustomerStore } from '../runtime/customer-store'
import type { ArticlePublishMode, CouponTemplateDraft, CouponType, MarketingArticleDraft, MarketingAnalysisResult, MarketingStatus, PromotionDraft, PromotionType, VoucherCampaignDraft } from '../types'

const props = defineProps<{ mode: 'coupons' | 'promotions' | 'voucher-campaigns' | 'articles' | 'marketing-analysis' | 'ai-analysis' | 'referral-commission' }>()
const store = useCustomerStore()
const { coupons, promotions, voucherCampaigns, voucherIssues, marketingArticles, marketingAnalysis, loading, error } = storeToRefs(store)
const actionError = ref<string | null>(null)

const couponDraft = reactive<CouponTemplateDraft>({ code: '', name: '', type: 'threshold-discount', thresholdCents: 0, amountCents: 1000, discountPercent: null, maxDiscountCents: null, issueQuantity: 1000, validityType: 'date-range', validityDays: null, startsAt: '2026-08-27T00:00:00+08:00', endsAt: '2026-09-30T23:59:59+08:00', scopeKind: 'all', scopeIds: [], audienceKind: 'all', audienceIds: [], perCustomerLimit: 1, newCustomerOnly: false, allowPromotionalItems: false, description: null })
const promotionDraft = reactive<PromotionDraft>({ code: '', name: '', type: 'limited-discount', startsAt: '2026-08-27T00:00:00+08:00', endsAt: '2026-09-30T23:59:59+08:00', customerAudienceKind: 'all', customerAudienceIds: [], scopeKind: 'all', scopeIds: [], discountMode: 'rate', discountPercent: 95, discountPriceCents: null, limitQuantity: 0, limitPeriod: 'campaign', rules: [], allowCoupon: false, allowMemberDiscount: false, showCountdown: false, showStock: false, sortWeight: 1, description: null })
const voucherDraft = reactive<VoucherCampaignDraft>({ name: '', startsAt: '2026-08-27T00:00:00+08:00', endsAt: '2026-09-30T23:59:59+08:00', couponId: '', audienceKind: 'all', audienceIds: [], quantityPerCustomer: 1, channels: ['inbox'], description: null })
const articleDraft = reactive<MarketingArticleDraft>({ title: '', type: 'graphic', cover: null, summary: null, content: '', productIds: [], couponId: null, promotionId: null, publishMode: 'draft', scheduledAt: null, channels: ['h5'], readPermission: 'public' })

const title = computed(() => ({ coupons: '优惠券', promotions: '促销活动', 'voucher-campaigns': '易发券', articles: '获客文章', 'marketing-analysis': '营销分析', 'ai-analysis': 'AI 营销分析', 'referral-commission': '客户拉新提成' }[props.mode]))
const activeCoupons = computed(() => coupons.value.filter((item) => item.status === 'active'))
const metricText = (metric: { value: number | null; unavailableReason: string | null }, percent = false): string => metric.value === null ? `unavailable（${metric.unavailableReason ?? '数据源未接入'}）` : percent ? `${(metric.value * 100).toFixed(1)}%` : String(metric.value)
function run(action: () => Promise<unknown>): void { actionError.value = null; action().catch((caught) => { actionError.value = caught instanceof Error ? caught.message : '操作失败' }) }
function saveCoupon(): void { run(async () => { await store.saveCoupon({ ...couponDraft, scopeIds: [...couponDraft.scopeIds], audienceIds: [...couponDraft.audienceIds] }); couponDraft.code = ''; couponDraft.name = '' }) }
function savePromotion(): void { run(async () => { await store.savePromotion({ ...promotionDraft, customerAudienceIds: [...promotionDraft.customerAudienceIds], scopeIds: [...promotionDraft.scopeIds], rules: promotionDraft.rules.map((rule) => ({ ...rule })) }); promotionDraft.code = ''; promotionDraft.name = '' }) }
function createVoucher(): void { if (!voucherDraft.couponId) voucherDraft.couponId = activeCoupons.value[0]?.id ?? ''; run(() => store.createVoucherCampaign({ ...voucherDraft, audienceIds: [...voucherDraft.audienceIds], channels: [...voucherDraft.channels] })) }
function issueVoucher(id: string): void { run(() => store.issueVoucherCampaign(id)) }
function saveArticle(): void { run(async () => { await store.saveMarketingArticle({ ...articleDraft, productIds: [...articleDraft.productIds], channels: [...articleDraft.channels] }); articleDraft.title = ''; articleDraft.content = '' }) }
function loadAnalysis(): void { run(() => store.loadMarketingAnalysis()) }
function metric(result: MarketingAnalysisResult | null): MarketingAnalysisResult { return result ?? { couponClaimRate: { value: null, unavailableReason: '正在加载' }, couponUseRate: { value: null, unavailableReason: '正在加载' }, promotionOrderCount: { value: null, unavailableReason: '正在加载' }, promotionOrderAmountCents: { value: null, unavailableReason: '正在加载' }, acquisitionConversionRate: { value: null, unavailableReason: '正在加载' }, pointsUseRate: { value: null, unavailableReason: '正在加载' }, activities: [], ai: { activityCount: { value: null, unavailableReason: '正在加载' }, customerCount: { value: null, unavailableReason: '正在加载' }, productCount: { value: null, unavailableReason: '正在加载' }, totalCostCents: { value: null, unavailableReason: '正在加载' }, activities: [] }, referral: [] } }
onMounted(() => { store.loadOperations(); if (props.mode === 'marketing-analysis' || props.mode === 'ai-analysis' || props.mode === 'referral-commission') loadAnalysis() })
</script>

<template>
  <section class="marketing-page">
    <header class="page-header"><div><p class="eyebrow">客户运营 · 原型模拟</p><h1>{{ title }}</h1><p>营销配置维护领域事实，真实渠道、订单金额和 AI 结果由 provider 决定。</p></div><RouterLink class="button" to="/customers">返回客户</RouterLink></header>
    <CustomerSubnav />
    <p v-if="actionError || error" class="alert" role="alert">{{ actionError || error }}</p>
    <div v-if="loading" class="state">正在加载营销资料…</div>

    <template v-else-if="props.mode === 'coupons'"><section class="card"><div class="toolbar"><h2>优惠券列表 <small>{{ coupons.length }} 个</small></h2></div><table><thead><tr><th>名称</th><th>类型</th><th>力度</th><th>发行量</th><th>已领取</th><th>已使用</th><th>有效期</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in coupons" :key="item.id"><td>{{ item.name }}</td><td>{{ item.type }}</td><td>{{ item.amountCents ?? item.discountPercent ?? '免运费' }}</td><td>{{ item.issueQuantity }}</td><td>{{ item.claimedQuantity }}</td><td>{{ item.usedQuantity }}</td><td>{{ item.startsAt.slice(0, 10) }} ~ {{ item.endsAt.slice(0, 10) }}</td><td>{{ item.status }}</td><td><button class="link" type="button" @click="run(() => store.setCouponStatus(item.id, 'paused'))">暂停</button><button class="link danger" type="button" @click="run(() => store.setCouponStatus(item.id, 'ended'))">结束</button></td></tr></tbody></table><p class="hint">优惠券实例不可编辑/删除；订单使用由 Order provider 决定。</p></section><form class="card form" @submit.prevent="saveCoupon"><h2>新增优惠券</h2><label>编码<input v-model="couponDraft.code" required></label><label>名称<input v-model="couponDraft.name" required></label><label>类型<select v-model="couponDraft.type"><option value="threshold-discount">满减券</option><option value="percentage">折扣券</option><option value="direct-discount">直减券</option><option value="free-shipping">免运费券</option></select></label><label>发行数量<input v-model.number="couponDraft.issueQuantity" type="number" min="1" max="10000000"></label><label>门槛（分）<input v-model.number="couponDraft.thresholdCents" type="number" min="0"></label><label v-if="couponDraft.type === 'percentage'">折扣（%）<input v-model.number="couponDraft.discountPercent" type="number" min="1" max="100"></label><label v-else>优惠金额（分）<input v-model.number="couponDraft.amountCents" type="number" min="1"></label><button class="button button--primary" type="submit">保存优惠券</button></form></template>

    <template v-else-if="props.mode === 'promotions'"><section class="card"><h2>促销列表 <small>{{ promotions.length }} 个</small></h2><table><thead><tr><th>名称</th><th>类型</th><th>范围</th><th>时间</th><th>订单数</th><th>订单金额</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in promotions" :key="item.id"><td>{{ item.name }}</td><td>{{ item.type }}</td><td>{{ item.scopeKind }}</td><td>{{ item.startsAt.slice(0, 10) }} ~ {{ item.endsAt.slice(0, 10) }}</td><td>{{ item.orderCount ?? 'unavailable' }}</td><td>{{ item.orderAmountCents ?? 'unavailable' }}</td><td>{{ item.status }}</td><td><button class="link" type="button" @click="run(() => store.setPromotionStatus(item.id, 'paused'))">暂停</button><button class="link danger" type="button" @click="run(() => store.setPromotionStatus(item.id, 'ended'))">结束</button></td></tr></tbody></table><p class="hint">同一 SKU 重叠有效促销会在保存时原子拒绝。</p></section><form class="card form" @submit.prevent="savePromotion"><h2>新增促销</h2><label>编码<input v-model="promotionDraft.code" required></label><label>名称<input v-model="promotionDraft.name" required maxlength="50"></label><label>类型<select v-model="promotionDraft.type"><option value="limited-discount">限时折扣</option><option value="threshold-discount">满减</option><option value="threshold-gift">满赠</option><option value="buy-gift">买赠</option></select></label><label v-if="promotionDraft.type === 'limited-discount'">折扣率（%）<input v-model.number="promotionDraft.discountPercent" type="number" min="1" max="100"></label><button class="button button--primary" type="submit">保存促销</button></form></template>

    <template v-else-if="props.mode === 'voucher-campaigns'"><section class="card"><h2>易发券活动 <small>{{ voucherCampaigns.length }} 个</small></h2><table><thead><tr><th>活动主题</th><th>关联优惠券</th><th>发放数量</th><th>已领取</th><th>已使用</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in voucherCampaigns" :key="item.id"><td>{{ item.name }}</td><td>{{ coupons.find((coupon) => coupon.id === item.couponId)?.name ?? '不可用' }}</td><td>{{ item.issuedCount }}</td><td>{{ item.claimedCount }}</td><td>{{ item.usedCount }}</td><td>{{ item.status }}</td><td><button class="link" type="button" @click="issueVoucher(item.id)">确认发放</button></td></tr></tbody></table><p class="hint">渠道仅保存 fake 发送元数据，不发送短信、微信或站内信。</p></section><form class="card form" @submit.prevent="createVoucher"><h2>新增易发券活动</h2><label>活动主题<input v-model="voucherDraft.name" required></label><label>关联优惠券<select v-model="voucherDraft.couponId"><option value="" disabled>请选择</option><option v-for="coupon in activeCoupons" :key="coupon.id" :value="coupon.id">{{ coupon.name }}</option></select></label><label>每人发放数量<input v-model.number="voucherDraft.quantityPerCustomer" type="number" min="1" max="10"></label><label>发放渠道<select v-model="voucherDraft.channels[0]"><option value="inbox">站内信（fake）</option><option value="sms">短信（fake）</option><option value="wechat">微信（fake）</option></select></label><button class="button button--primary" type="submit">保存活动</button></form></template>

    <template v-else-if="props.mode === 'articles'"><section class="card"><h2>获客文章 <small>{{ marketingArticles.length }} 篇</small></h2><table><thead><tr><th>标题</th><th>类型</th><th>发布时间</th><th>浏览量</th><th>获客数</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in marketingArticles" :key="item.id"><td>{{ item.title }}</td><td>{{ item.type }}</td><td>{{ item.publishedAt?.slice(0, 10) ?? '—' }}</td><td>{{ item.viewCount ?? 'unavailable' }}</td><td>{{ item.acquiredCustomerCount ?? 'unavailable' }}</td><td>{{ item.status }}</td><td><button class="link" type="button" @click="run(() => store.setMarketingArticleStatus(item.id, item.status === 'published' ? 'unpublished' : 'published'))">{{ item.status === 'published' ? '下架' : '发布' }}</button></td></tr></tbody></table></section><form class="card form" @submit.prevent="saveArticle"><h2>新增获客文章</h2><label>文章标题<input v-model="articleDraft.title" required maxlength="50"></label><label>文章类型<select v-model="articleDraft.type"><option value="graphic">图文</option><option value="video">视频</option></select></label><label>发布方式<select v-model="articleDraft.publishMode"><option value="draft">保存草稿</option><option value="publish-now">立即发布</option><option value="publish-scheduled">定时发布</option></select></label><label>文章内容<textarea v-model="articleDraft.content" rows="5" required></textarea></label><button class="button button--primary" type="submit">保存文章</button><p class="hint">富文本和封面为 fake 元数据，文章渠道只提供原型预览。</p></form></template>

    <template v-else><section class="metric-grid"><article class="metric card"><span>优惠券领取率</span><strong>{{ metricText(metric(marketingAnalysis).couponClaimRate, true) }}</strong></article><article class="metric card"><span>优惠券核销率</span><strong>{{ metricText(metric(marketingAnalysis).couponUseRate, true) }}</strong></article><article class="metric card"><span>促销订单金额</span><strong>{{ metricText(metric(marketingAnalysis).promotionOrderAmountCents) }}</strong></article><article class="metric card"><span>积分使用率</span><strong>{{ metricText(metric(marketingAnalysis).pointsUseRate, true) }}</strong></article></section><section v-if="props.mode === 'marketing-analysis'" class="card"><div class="toolbar"><h2>活动效果</h2><button class="button" type="button" @click="loadAnalysis">刷新分析</button></div><table><thead><tr><th>活动名称</th><th>类型</th><th>覆盖客户</th><th>覆盖商品</th><th>订单金额</th><th>订单笔数</th><th>平均客单价</th><th>平均毛利率</th></tr></thead><tbody><tr v-for="item in metric(marketingAnalysis).activities" :key="item.id"><td>{{ item.name }}</td><td>{{ item.type }}</td><td>{{ metricText(item.customerCount) }}</td><td>{{ metricText(item.productCount) }}</td><td>{{ metricText(item.orderAmountCents) }}</td><td>{{ metricText(item.orderCount) }}</td><td>{{ metricText(item.averageOrderCents) }}</td><td>{{ metricText(item.grossMarginPercent, true) }}</td></tr></tbody></table></section><section v-else-if="props.mode === 'ai-analysis'" class="card"><h2>AI 营销分析</h2><p class="unavailable">AI provider 未接入，指标和效果列表保持 unavailable。</p><div class="metric-grid"><article class="metric card"><span>活动次数</span><strong>{{ metricText(metric(marketingAnalysis).ai.activityCount) }}</strong></article><article class="metric card"><span>活动总成本</span><strong>{{ metricText(metric(marketingAnalysis).ai.totalCostCents) }}</strong></article></div></section><section v-else class="card"><h2>客户拉新提成</h2><table><thead><tr><th>推荐人</th><th>拉新数量</th><th>新客户消费金额</th><th>提成金额</th><th>提成状态</th></tr></thead><tbody><tr v-for="item in metric(marketingAnalysis).referral" :key="item.referrer ?? 'unavailable'"><td>{{ item.referrer ?? 'unavailable' }}</td><td>{{ metricText(item.acquisitionCount) }}</td><td>{{ metricText(item.newCustomerAmountCents) }}</td><td>{{ metricText(item.commissionCents) }}</td><td>{{ item.status ?? 'unavailable' }}</td></tr></tbody></table></section></template>
  </section>
</template>

<style scoped>
.marketing-page{max-width:1680px;margin:0 auto}.page-header{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:14px}.page-header h1{margin:3px 0}.page-header p{margin-bottom:0;color:var(--color-muted)}.button{display:inline-flex;align-items:center;min-height:36px;padding:0 14px;color:#4d5968;background:#fff;border:1px solid var(--color-border-strong);border-radius:var(--radius-sm);text-decoration:none;cursor:pointer}.button--primary{color:#fff;background:var(--color-primary);border-color:var(--color-primary)}.alert{padding:10px;color:var(--color-danger);background:#fff0f0;border:1px solid #efcaca}.card{padding:16px;background:#fff;border:1px solid var(--color-border);border-radius:var(--radius-md)}.card h2{margin:0 0 14px;font-size:16px}.card h2 small{margin-left:8px;color:var(--color-muted);font-size:12px;font-weight:400}.form{display:grid;gap:10px;align-content:start;margin-top:14px}.form label{display:grid;gap:4px;color:var(--color-muted);font-size:12px}.form input,.form select,.form textarea{min-height:35px;padding:6px 8px;border:1px solid var(--color-border-strong);border-radius:var(--radius-sm)}table{width:100%;border-collapse:collapse}th,td{padding:10px 11px;text-align:left;border-bottom:1px solid var(--color-border);white-space:nowrap}th{color:var(--color-muted);font-size:12px;background:var(--color-table-head)}.link{padding:0;color:var(--color-primary-strong);cursor:pointer;background:transparent;border:0}.danger{margin-left:8px;color:var(--color-danger)}.hint,.unavailable{color:var(--color-muted);font-size:12px}.toolbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.state{display:grid;min-height:220px;place-items:center;color:var(--color-muted)}.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:14px}.metric span,.metric strong{display:block}.metric span{color:var(--color-muted);font-size:12px}.metric strong{margin-top:8px;font-size:20px;color:var(--color-text)}@media(max-width:900px){.page-header{align-items:flex-start;flex-direction:column;gap:10px}.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}table{min-width:1000px}}
</style>
