<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import FinanceSubnav from '../components/FinanceSubnav.vue'
import { useOrderStore } from '../../orders/runtime/order-store'
const route=useRoute(),store=useOrderStore();const item=computed(()=>store.refunds.find((value)=>value.id===String(route.params.refundId))??null);const method=ref<'original'|'cash'|'balance'>('original'),accountId=ref(''),reason=ref('');const money=(value:number)=>`¥${(value/100).toFixed(2)}`
async function load(){await store.loadRefunds();if(item.value)method.value=item.value.method}async function confirm(){if(item.value)await store.confirmRefund(item.value.id,item.value.version,method.value,accountId.value||undefined,reason.value||undefined)}async function reject(){if(item.value&&reason.value.trim())await store.rejectRefund(item.value.id,item.value.version,reason.value)}onMounted(load)
</script>
<template><section class="order-page"><FinanceSubnav/><div v-if="store.loading" class="order-state"><strong>正在加载退款详情…</strong></div><div v-else-if="store.error||!item" class="order-state error"><strong>无法打开退款单</strong><p>{{store.error??'退款单不存在'}}</p></div><template v-else><header class="order-detail-header"><div><RouterLink class="order-back" to="/finance/refunds">← 客户退款列表</RouterLink><p class="eyebrow">{{item.refundNo}}</p><h1>{{item.customerSnapshot.name}}</h1></div><RouterLink class="order-button" :to="`/orders/${item.orderId}`">原订单</RouterLink></header><section class="order-card"><h2>退款事实</h2><dl class="order-grid"><div><dt>来源</dt><dd>{{item.sourceType==='customer-return'?'客户退货':'短装退款'}} · {{item.sourceNo}}</dd></div><div><dt>原订单</dt><dd>{{item.orderNo}}</dd></div><div><dt>申请金额</dt><dd>{{money(item.requestedAmountCents)}}</dd></div><div><dt>实退金额</dt><dd>{{money(item.refundedAmountCents)}}</dd></div><div><dt>状态</dt><dd>{{{pending:'待审核',refunded:'已退款',rejected:'已拒绝'}[item.status]}}</dd></div><div><dt>退款方式</dt><dd>{{{original:'原路退回',cash:'现金',balance:'客户余额'}[item.method]}}</dd></div><div><dt>申请时间</dt><dd>{{item.requestedAt}}</dd></div><div><dt>处理时间</dt><dd>{{item.resolvedAt??'—'}}</dd></div></dl></section><section v-if="item.allocations.length" class="order-card"><h2>退款来源分配</h2><div class="order-table-wrap"><table class="order-table"><thead><tr><th>来源类型</th><th>来源 ID</th><th>方式</th><th>账户</th><th class="order-money">金额</th></tr></thead><tbody><tr v-for="part in item.allocations" :key="part.id"><td>{{part.sourceKind}}</td><td>{{part.sourceId}}</td><td>{{part.method}}</td><td>{{part.accountId??'客户余额'}}</td><td class="order-money">{{money(part.amountCents)}}</td></tr></tbody></table></div></section><section v-if="item.status==='pending'" class="order-card"><h2>财务确认</h2><div class="refund-detail-form"><label>退款方式<select v-model="method"><option value="original">原路退回</option><option value="cash">现金</option><option value="balance">客户余额</option></select></label><label v-if="method==='cash'">现金账户<select v-model="accountId"><option value="">请选择</option><option v-for="account in store.refundCashAccounts" :key="account.id" :value="account.id">{{account.name}}</option></select></label><label>原因<input v-model="reason" maxlength="200" :placeholder="method==='original'?'拒绝时必填':'特殊退款必填'"></label></div><div class="order-detail-actions"><button class="order-button" :disabled="store.saving||!reason.trim()" @click="reject">拒绝退款</button><button class="order-button primary" :disabled="store.saving||(method!=='original'&&!reason.trim())||(method==='cash'&&!accountId)" @click="confirm">确认整笔退款</button></div></section><section v-else-if="item.status==='rejected'" class="order-card"><h2>重新提交</h2><p>{{item.reason}}</p><button class="order-button primary" :disabled="store.saving" @click="store.reapplyRefund(item.id,item.version)">按剩余义务生成新退款单</button></section></template></section></template>
<style scoped>.refund-detail-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.refund-detail-form label{display:grid;gap:6px;color:var(--color-muted);font-size:12px}.refund-detail-form input,.refund-detail-form select{min-height:38px;padding:7px 9px;background:#fff;border:1px solid var(--color-border-strong);border-radius:5px}@media(max-width:760px){.refund-detail-form{grid-template-columns:1fr}}</style>
