<script setup lang="ts">
import { computed, onMounted } from 'vue'; import { storeToRefs } from 'pinia'; import { RouterLink, useRoute, useRouter } from 'vue-router'; import FinanceSubnav from '../components/FinanceSubnav.vue'; import FinanceScenarioBar from '../components/FinanceScenarioBar.vue'; import { useFinanceStore } from '../runtime/finance-store'; import './finance-views.css'
const store = useFinanceStore(); const route = useRoute(); const router = useRouter(); const { accounts, loading, error, month, scenario, actor, canManage } = storeToRefs(store)
const money = (value:number)=>`¥${(value/100).toLocaleString('zh-CN',{minimumFractionDigits:2})}`; const typeLabel={cash:'现金',bank:'银行账户',wechat:'微信',alipay:'支付宝'} as const
const totals=computed(()=>accounts.value.reduce((sum,row)=>({opening:sum.opening+row.openingBalanceCents,income:sum.income+row.periodIncomeCents,expense:sum.expense+row.periodExpenseCents,closing:sum.closing+row.closingBalanceCents}),{opening:0,income:0,expense:0,closing:0}))
async function changeMonth(value:string){await router.replace({query:{month:value}});await store.loadAccounts(value)}
onMounted(()=>store.loadAccounts(String(route.query.month??'2026-08')))
</script>
<template><section class="finance-page"><header class="finance-header"><div><h1>资金账户</h1><p>按自然月查看期初、本期收支和期末余额；余额只由不可变流水计算。</p></div><FinanceScenarioBar :scenario="scenario" :role="actor.role" @scenario="store.setScenario" @role="store.setRole"/></header><FinanceSubnav/><div class="finance-toolbar"><label>业务月份<input :value="month" type="month" max="2026-08" @change="changeMonth(($event.target as HTMLInputElement).value)"></label><div><button class="fin-button" @click="store.loadAccounts()">刷新</button><RouterLink v-if="canManage" class="fin-button primary" to="/finance/accounts/new">新增账户</RouterLink></div></div><p v-if="route.query.denied" class="finance-warning">当前角色只有资金账户和流水只读权限。</p><div v-if="error" class="finance-state error" role="alert"><strong>资金数据加载失败</strong><p>{{error}}</p><button class="fin-button" @click="store.loadAccounts()">重试</button></div><div v-else-if="loading" class="finance-state"><strong>正在加载资金账户…</strong></div><div v-else-if="!accounts.length" class="finance-state"><strong>暂无资金账户</strong><p>当前模拟场景没有可展示的账户。</p></div><template v-else><div class="finance-summary"><article><span>期初余额</span><strong>{{money(totals.opening)}}</strong></article><article><span>本期收入</span><strong class="fin-income">{{money(totals.income)}}</strong></article><article><span>本期支出</span><strong class="fin-expense">{{money(totals.expense)}}</strong></article><article><span>期末余额</span><strong>{{money(totals.closing)}}</strong></article></div><div class="finance-table-wrap"><table class="finance-table"><thead><tr><th>账户名称</th><th>账户类型</th><th class="fin-money">期初余额</th><th class="fin-money">本期收入</th><th class="fin-money">本期支出</th><th class="fin-money">当前/期末余额</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in accounts" :key="row.account.id"><td><RouterLink :to="`/finance/accounts/${row.account.id}?month=${month}`"><strong>{{row.account.name}}</strong></RouterLink><small v-if="row.bankAccountMasked">{{row.bankAccountMasked}}</small></td><td>{{typeLabel[row.account.type]}}</td><td class="fin-money">{{money(row.openingBalanceCents)}}</td><td class="fin-money fin-income">{{money(row.periodIncomeCents)}}</td><td class="fin-money fin-expense">{{money(row.periodExpenseCents)}}</td><td class="fin-money"><strong>{{money(row.closingBalanceCents)}}</strong></td><td><span class="fin-status" :class="row.account.status">{{row.account.status==='enabled'?'启用':'停用'}}</span></td><td><RouterLink :to="`/finance/accounts/${row.account.id}?month=${month}`">查看明细</RouterLink> <RouterLink v-if="canManage" :to="`/finance/accounts/${row.account.id}/edit`">编辑</RouterLink></td></tr></tbody></table></div></template></section></template>
