<script setup lang="ts">
import { onMounted, reactive } from 'vue'
import FinanceSubnav from '../components/FinanceSubnav.vue'
import OrderScenarioBar from '../../orders/components/OrderScenarioBar.vue'
import { useOrderStore } from '../../orders/runtime/order-store'

const store = useOrderStore()
const forms = reactive<Record<string,{method:'original'|'cash'|'balance';accountId:string;reason:string}>>({})
const money = (value:number) => `¥${(value/100).toFixed(2)}`
const form = (id:string,method:'original'|'cash'|'balance') => forms[id] ??= {method,accountId:'',reason:''}
async function confirm(id:string,version:number) { const current=forms[id]!; await store.confirmRefund(id,version,current.method,current.accountId||undefined,current.reason||undefined) }
async function reject(id:string,version:number) { const current=forms[id]!; if(current.reason.trim()) await store.rejectRefund(id,version,current.reason) }
onMounted(()=>store.loadRefunds())
</script>

<template><section class="order-page"><header class="order-page-header"><div><p class="eyebrow">ORD-005 · 资金处理</p><h1>客户退款</h1><p>贷项先冲减待收，只有已收现金超额部分才形成退款义务。</p></div><OrderScenarioBar :scenario="store.scenario" :role="store.actor.role" @scenario="async v=>{await store.setScenario(v);await store.loadRefunds()}" @role="async v=>{await store.setRole(v);await store.loadRefunds()}"/></header><FinanceSubnav/><div v-if="store.error" class="order-state error"><strong>退款数据加载失败</strong><p>{{store.error}}</p></div><div v-else-if="store.loading" class="order-state"><strong>正在加载退款…</strong></div><section v-else class="order-panel"><div class="order-toolbar"><strong>共 {{store.refunds.length}} 张退款单</strong><span>仅财务和管理员可操作</span></div><div class="order-table-wrap"><table class="order-table refund-table"><thead><tr><th>退款单号</th><th>来源</th><th>客户 / 原订单</th><th class="order-money">待退金额</th><th>状态</th><th>方式与操作</th></tr></thead><tbody><tr v-for="item in store.refunds" :key="item.id"><td><strong>{{item.refundNo}}</strong><small>{{item.requestedAt}}</small></td><td>{{item.sourceType==='customer-return'?'客户退货':'短装退款'}}<small>{{item.sourceNo}}</small></td><td>{{item.customerSnapshot.name}}<small>{{item.orderNo}}</small></td><td class="order-money">{{money(item.requestedAmountCents)}}</td><td>{{{pending:'待审核',refunded:'已退款',rejected:'已拒绝'}[item.status]}}<small v-if="item.reason">{{item.reason}}</small></td><td><template v-if="item.status==='pending'"><div class="refund-actions"><select v-model="form(item.id,item.method).method"><option value="original">原路退回</option><option value="cash">现金</option><option value="balance">客户余额</option></select><select v-if="forms[item.id]!.method==='cash'" v-model="forms[item.id]!.accountId"><option value="">选择现金账户</option><option v-for="account in store.refundCashAccounts" :key="account.id" :value="account.id">{{account.name}}</option></select><input v-if="forms[item.id]!.method!=='original'" v-model="forms[item.id]!.reason" maxlength="200" placeholder="特殊退款原因（必填）"><input v-else v-model="forms[item.id]!.reason" maxlength="200" placeholder="拒绝原因"><button class="order-button primary" :disabled="store.saving" @click="confirm(item.id,item.version)">确认退款</button><button class="order-button" :disabled="store.saving||!forms[item.id]!.reason.trim()" @click="reject(item.id,item.version)">拒绝</button></div></template><button v-else-if="item.status==='rejected'" class="order-button" :disabled="store.saving" @click="store.reapplyRefund(item.id,item.version)">重新提交</button><span v-else>已完成，不可修改</span></td></tr><tr v-if="!store.refunds.length"><td colspan="6" class="order-empty-cell">暂无退款单；退货入库后会按实收情况自动生成。</td></tr></tbody></table></div></section></section></template>
