<script setup lang="ts">
import{computed,onMounted,reactive,ref,watch}from'vue';import{storeToRefs}from'pinia';import{useRoute,useRouter}from'vue-router';import FinanceSubnav from'../components/FinanceSubnav.vue';import{useFinanceStore}from'../runtime/finance-store';import'./finance-views.css';import'./finance-receivable-views.css'
const store=useFinanceStore();const route=useRoute();const router=useRouter();const{receivableDocuments,settlementSources,saving,error}=storeToRefs(store);const customerId=ref(String(route.query.customerId??''));const occurredAt=ref('2026-08-10T09:00');const note=ref('');const localError=ref('');const rows=reactive([{sourceKey:'',receivableId:'',cashYuan:'',discountYuan:'0'}]);const customers=computed(()=>[...new Map(receivableDocuments.value.map(r=>[r.customerSnapshot.id,r.customerSnapshot])).values()]);const targets=computed(()=>receivableDocuments.value.filter(r=>r.customerSnapshot.id===customerId.value&&r.outstandingCents>0));const money=(v:number)=>`¥${(v/100).toFixed(2)}`;const yuan=(v:string)=>Math.round(Number(v)*100)
watch(customerId,async()=>{await store.loadSettlementSources(customerId.value);rows.splice(0,rows.length,{sourceKey:settlementSources.value[0]?`${settlementSources.value[0].kind}:${settlementSources.value[0].id}`:'',receivableId:targets.value[0]?.id??'',cashYuan:'',discountYuan:'0'})})
function addRow(){rows.push({sourceKey:settlementSources.value[0]?`${settlementSources.value[0].kind}:${settlementSources.value[0].id}`:'',receivableId:targets.value[0]?.id??'',cashYuan:'',discountYuan:'0'})}
async function submit(){localError.value='';try{const allocations=rows.map(r=>{const split=r.sourceKey.indexOf(':');return{sourceKind:r.sourceKey.slice(0,split) as 'receipt'|'prepayment',sourceId:r.sourceKey.slice(split+1),receivableId:r.receivableId,cashCents:yuan(r.cashYuan||'0'),discountCents:yuan(r.discountYuan||'0')}});const value=await store.createWriteoff({customerId:customerId.value,occurredAt:`${occurredAt.value}:00+08:00`,allocations,note:note.value||null});await router.push(`/finance/writeoffs/${value.id}`)}catch(caught){localError.value=caught instanceof Error?caught.message:'核销失败'}}
onMounted(async()=>{await store.loadReceivables();if(!customerId.value)customerId.value=customers.value[0]?.id??'';await store.loadSettlementSources(customerId.value);rows[0]!.sourceKey=settlementSources.value[0]?`${settlementSources.value[0].kind}:${settlementSources.value[0].id}`:'';rows[0]!.receivableId=targets.value[0]?.id??''})
</script>
<template><section class="finance-page"><header class="finance-header"><div><h1>新增收款核销</h1><p>逐行指定来源、目标应收、现金/预收金额与优惠；系统不会自动 FIFO。</p></div></header><FinanceSubnav/><div class="finance-panel"><form class="finance-form wide-form" @submit.prevent="submit"><label>客户<select v-model="customerId" required><option value="">请选择</option><option v-for="c in customers" :key="c.id" :value="c.id">{{c.code}} · {{c.name}}</option></select></label><label>核销日期<input v-model="occurredAt" type="datetime-local" max="2026-08-10T09:00" required></label><div class="wide allocation-editor"><div class="allocation-head"><strong>手工分配矩阵</strong><button class="fin-button" type="button" @click="addRow">添加一行</button></div><div v-for="(row,index) in rows" :key="index" class="allocation-row"><label>来源<select v-model="row.sourceKey" required><option v-for="s in settlementSources" :key="s.id" :value="`${s.kind}:${s.id}`">{{s.label}}（可用 {{money(s.availableCents)}}）</option></select></label><label>目标应收<select v-model="row.receivableId" required><option v-for="r in targets" :key="r.id" :value="r.id">{{r.receivableNo}} / {{r.orderNo}}（待收 {{money(r.outstandingCents)}}）</option></select></label><label>现金/预收（元）<input v-model="row.cashYuan" type="number" min="0" step="0.01" required></label><label>优惠（元）<input v-model="row.discountYuan" type="number" min="0" step="0.01"></label><button v-if="rows.length>1" class="fin-link-button danger" type="button" @click="rows.splice(index,1)">移除</button></div></div><label class="wide">备注<textarea v-model="note" rows="3" placeholder="存在优惠时必填"></textarea></label><p v-if="localError||error" class="finance-warning wide">{{localError||error}}</p><div class="finance-actions"><button class="fin-button primary" :disabled="saving">{{saving?'正在核销…':'确认核销'}}</button><button class="fin-button" type="button" @click="router.back()">取消</button></div></form></div></section></template>
