import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import { createProcurementMockSession, type ProcurementScenarioName } from '../../../../mock/handlers/procurement-handler'
import { setCurrentProcurementRole } from './procurement-access'
import type { ProcurementActor, ProcurementWorkspace, Supplier, SupplierDetail, SupplierDraft, SupplierImportPreview, SupplierListQuery, SupplierProductDraft, SupplierProductListQuery } from '../types'

const emptyWorkspace = (): ProcurementWorkspace => ({ suppliers: { items: [], total: 0, page: 1, pageSize: 30 }, supplierProducts: [], categories: [], skus: [], catalogAvailable: true, directDelivery: { availability: 'unavailable', reason: 'PURCHASE_EXECUTION_PROVIDER_UNAVAILABLE', message: '采购直送执行数据尚未接入' } })

export const useProcurementStore = defineStore('procurement', () => {
  const scenario = ref<ProcurementScenarioName>('normal'); const actor = ref<ProcurementActor>({ role: 'super-admin', actorId: 'admin-demo' })
  const supplierQuery = ref<SupplierListQuery>({ status: 'all', page: 1, pageSize: 30 }); const relationQuery = ref<SupplierProductListQuery>({ status: 'all' })
  const workspace = ref<ProcurementWorkspace>(emptyWorkspace()); const selectedSupplier = ref<SupplierDetail | null>(null)
  const loading = ref(false); const saving = ref(false); const error = ref<string | null>(null); let sequence = 1; let loadToken = 0; let session = createProcurementMockSession('normal')
  const canWrite = computed(() => actor.value.role === 'super-admin' || actor.value.role === 'warehouse'); const isEmpty = computed(() => !loading.value && !error.value && workspace.value.suppliers.total === 0)
  const nextRequestId = (kind: string) => `${kind}-${Date.now()}-${sequence++}`
  async function load(): Promise<void> { const token = ++loadToken; loading.value = true; error.value = null; try { const result = await session.run(() => session.service.getWorkspace(actor.value, supplierQuery.value, relationQuery.value)); if (token === loadToken) workspace.value = result } catch (caught) { if (token === loadToken) { error.value = caught instanceof Error ? caught.message : '采购供应商数据加载失败'; workspace.value = emptyWorkspace() } } finally { if (token === loadToken) loading.value = false } }
  async function loadSupplier(id: string): Promise<void> { loading.value = true; error.value = null; try { selectedSupplier.value = await session.run(() => session.service.getSupplier(actor.value, id)) } catch (caught) { error.value = caught instanceof Error ? caught.message : '供应商加载失败'; selectedSupplier.value = null } finally { loading.value = false } }
  async function setScenario(next: ProcurementScenarioName): Promise<void> { scenario.value = next; actor.value = next === 'permission-denied' ? { role: 'finance', actorId: 'finance-demo' } : { role: 'super-admin', actorId: 'admin-demo' }; setCurrentProcurementRole(actor.value.role); session = createProcurementMockSession(next); selectedSupplier.value = null; await load() }
  async function setRole(role: ProcurementActor['role']): Promise<void> { actor.value = { role, actorId: `${role}-demo` }; setCurrentProcurementRole(role); await load() }
  async function applySupplierQuery(value: SupplierListQuery): Promise<void> { supplierQuery.value = { ...value, page: value.page ?? 1, pageSize: value.pageSize ?? 30 }; await load() }
  async function applyRelationQuery(value: SupplierProductListQuery): Promise<void> { relationQuery.value = { ...value }; await load() }
  async function saveSupplier(value: SupplierDraft, current?: Supplier): Promise<Supplier> { saving.value = true; try { const expectedVersion = current ? current.version - (scenario.value === 'concurrent' ? 1 : 0) : 0; const saved = current ? await session.run(() => session.service.updateSupplier(actor.value, current.id, { value, expectedVersion, requestId: nextRequestId('supplier-update') })) : await session.run(() => session.service.createSupplier(actor.value, { value, expectedVersion: 0, requestId: nextRequestId('supplier-create') })); await load(); return saved } finally { saving.value = false } }
  async function toggleSupplier(value: Supplier): Promise<void> { saving.value = true; try { await session.run(() => session.service.setSupplierStatus(actor.value, value.id, value.status === 'enabled' ? 'disabled' : 'enabled', value.version, nextRequestId('supplier-status'))); await load(); if (selectedSupplier.value?.id === value.id) await loadSupplier(value.id) } finally { saving.value = false } }
  async function saveRelation(value: SupplierProductDraft): Promise<void> { saving.value = true; try { await session.run(() => session.service.createSupplierProduct(actor.value, { value, expectedVersion: 0, requestId: nextRequestId('relation-create') })); await load() } finally { saving.value = false } }
  async function updateRelation(id: string, supplyPriceCents: number, preferred: boolean, version: number): Promise<void> { saving.value = true; try { await session.run(() => session.service.updateSupplierProduct(actor.value, id, { supplyPriceCents, preferred }, version - (scenario.value === 'concurrent' ? 1 : 0), nextRequestId('relation-update'))); await load() } finally { saving.value = false } }
  async function toggleRelation(id: string, status: 'enabled' | 'disabled', version: number): Promise<void> { saving.value = true; try { await session.run(() => session.service.setSupplierProductStatus(actor.value, id, status === 'enabled' ? 'disabled' : 'enabled', version, nextRequestId('relation-status'))); await load() } finally { saving.value = false } }
  function previewImport(rows: Parameters<typeof session.service.previewSupplierImport>[1]): SupplierImportPreview { return session.service.previewSupplierImport(actor.value, rows) }
  async function importSuppliers(preview: SupplierImportPreview): Promise<void> { saving.value = true; try { await session.run(() => session.service.importSuppliers(actor.value, preview, nextRequestId('supplier-import'))); await load() } finally { saving.value = false } }
  function exportSuppliers(): string { return session.service.exportSuppliersCsv(actor.value, supplierQuery.value) }
  function exportRelations(): string { return session.service.exportSupplierProductsCsv(actor.value, relationQuery.value) }
  return { scenario, actor, supplierQuery, relationQuery, workspace, selectedSupplier, loading, saving, error, canWrite, isEmpty, load, loadSupplier, setScenario, setRole, applySupplierQuery, applyRelationQuery, saveSupplier, toggleSupplier, saveRelation, updateRelation, toggleRelation, previewImport, importSuppliers, exportSuppliers, exportRelations }
})
