import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import type { ProcurementScenarioName } from '../../../../mock/handlers/procurement-handler'
import { getApplicationMockRuntimeController } from '../../../app/runtime/app-mock-runtime'
import { setCurrentProcurementRole } from './procurement-access'
import type { ProcurementActor, ProcurementWorkspace, PurchaseOrder, PurchaseOrderDraft, PurchaseOrderInboundInput, PurchaseOrderListQuery, PurchaseReturn, PurchaseReturnDraft, PurchaseReturnListQuery, PurchaseReturnSource, Supplier, SupplierDetail, SupplierDraft, SupplierImportPreview, SupplierListQuery, SupplierProductDraft, SupplierProductListQuery } from '../types'
import type { PurchaseStatisticsActor, PurchaseStatisticsFilterOptions, PurchaseStatisticsPage, PurchaseStatisticsQuery, PurchaseStatisticsReportKey } from '../statistics/types'

const emptyWorkspace = (): ProcurementWorkspace => ({ suppliers: { items: [], total: 0, page: 1, pageSize: 30 }, supplierProducts: [], categories: [], skus: [], catalogAvailable: true, directDelivery: { availability: 'unavailable', reason: 'PURCHASE_EXECUTION_PROVIDER_UNAVAILABLE', message: '采购直送执行数据尚未接入' } })

export const useProcurementStore = defineStore('procurement', () => {
  const runtimeController = getApplicationMockRuntimeController(); const session = runtimeController.procurement; const scenario = computed<ProcurementScenarioName>(() => session.scenarioName); const actor = ref<ProcurementActor>({ role: 'super-admin', actorId: 'admin-demo' })
  const supplierQuery = ref<SupplierListQuery>({ status: 'all', page: 1, pageSize: 30 }); const relationQuery = ref<SupplierProductListQuery>({ status: 'all' })
  const workspace = ref<ProcurementWorkspace>(emptyWorkspace()); const selectedSupplier = ref<SupplierDetail | null>(null)
  const loading = ref(false); const saving = ref(false); const error = ref<string | null>(null); let sequence = 1; let loadToken = 0
  const purchaseOrders = ref<PurchaseOrder[]>([]); const purchaseOrderTotal = ref(0); const purchaseWarehouses = ref<Array<{ id: string; name: string }>>([]); const purchaseLocations = ref<Array<{ id: string; warehouseId: string; name: string }>>([])
  const purchaseReturns = ref<PurchaseReturn[]>([]); const purchaseReturnTotal = ref(0); const purchaseReturnSources = ref<PurchaseReturnSource[]>([]); const selectedPurchaseReturn = ref<PurchaseReturn | null>(null)
  const statisticsPage = ref<PurchaseStatisticsPage>({ report: 'purchase-order-line-detail', availability: 'available', message: null, query: { report: 'purchase-order-line-detail', fromDate: '2026-05-10', toDate: '2026-08-10', page: 1, pageSize: 30 }, items: [], total: 0, totals: { documentCount: 0, baseQuantityMilli: 0, amountCents: 0, amountState: 'available', purchaseOrderCount: 0, purchaseReturnCount: 0, purchaseOrderAmountCents: null, purchaseReturnAmountCents: null, netAmountCents: null }, snapshotVersion: 'unloaded' })
  const statisticsOptions = ref<PurchaseStatisticsFilterOptions>({ suppliers: [], products: [] }); const statisticsExporting = ref(false); let statisticsRequestToken = 0
  const canWrite = computed(() => actor.value.role === 'super-admin' || actor.value.role === 'warehouse'); const isEmpty = computed(() => !loading.value && !error.value && workspace.value.suppliers.total === 0)
  const nextRequestId = (kind: string) => `${kind}-${Date.now()}-${sequence++}`
  async function load(): Promise<void> { const token = ++loadToken; loading.value = true; error.value = null; try { const result = await session.run(() => session.service.getWorkspace(actor.value, supplierQuery.value, relationQuery.value)); if (token === loadToken) workspace.value = result } catch (caught) { if (token === loadToken) { error.value = caught instanceof Error ? caught.message : '采购供应商数据加载失败'; workspace.value = emptyWorkspace() } } finally { if (token === loadToken) loading.value = false } }
  async function loadSupplier(id: string): Promise<void> { loading.value = true; error.value = null; try { selectedSupplier.value = await session.run(() => session.service.getSupplier(actor.value, id)) } catch (caught) { error.value = caught instanceof Error ? caught.message : '供应商加载失败'; selectedSupplier.value = null } finally { loading.value = false } }
  async function setScenario(next: ProcurementScenarioName): Promise<void> { actor.value = next === 'permission-denied' ? { role: 'finance', actorId: 'finance-demo' } : { role: 'super-admin', actorId: 'admin-demo' }; setCurrentProcurementRole(actor.value.role); runtimeController.reset(next); selectedSupplier.value = null; await load() }
  async function setRole(role: ProcurementActor['role']): Promise<void> { actor.value = { role, actorId: `${role}-demo` }; setCurrentProcurementRole(role); await load() }
  async function applySupplierQuery(value: SupplierListQuery): Promise<void> { supplierQuery.value = { ...value, page: value.page ?? 1, pageSize: value.pageSize ?? 30 }; await load() }
  async function applyRelationQuery(value: SupplierProductListQuery): Promise<void> { relationQuery.value = { ...value }; await load() }
  async function saveSupplier(value: SupplierDraft, current?: Supplier): Promise<Supplier> { saving.value = true; try { const expectedVersion = current ? current.version - (scenario.value === 'concurrent' ? 1 : 0) : 0; const saved = current ? await session.run(() => session.service.updateSupplier(actor.value, current.id, { value, expectedVersion, requestId: nextRequestId('supplier-update') })) : await session.run(() => session.service.createSupplier(actor.value, { value, expectedVersion: 0, requestId: nextRequestId('supplier-create') })); await load(); return saved } finally { saving.value = false } }
  async function toggleSupplier(value: Supplier): Promise<void> { saving.value = true; try { await session.run(() => session.service.setSupplierStatus(actor.value, value.id, value.status === 'enabled' ? 'disabled' : 'enabled', value.version, nextRequestId('supplier-status'))); await load(); if (selectedSupplier.value?.id === value.id) await loadSupplier(value.id) } finally { saving.value = false } }
  async function saveRelation(value: SupplierProductDraft): Promise<void> { saving.value = true; try { await session.run(() => session.service.createSupplierProduct(actor.value, { value, expectedVersion: 0, requestId: nextRequestId('relation-create') })); await load() } finally { saving.value = false } }
  async function updateRelation(id: string, supplyPriceCents: number, preferred: boolean, version: number): Promise<void> { saving.value = true; try { await session.run(() => session.service.updateSupplierProduct(actor.value, id, { supplyPriceCents, preferred }, version - (scenario.value === 'concurrent' ? 1 : 0), nextRequestId('relation-update'))); await load() } finally { saving.value = false } }
  async function toggleRelation(id: string, status: 'enabled' | 'disabled', version: number): Promise<void> { saving.value = true; try { await session.run(() => session.service.setSupplierProductStatus(actor.value, id, status === 'enabled' ? 'disabled' : 'enabled', version, nextRequestId('relation-status'))); await load() } finally { saving.value = false } }
  function previewImport(rows: Parameters<typeof session.service.previewSupplierImport>[1]): SupplierImportPreview { return session.service.previewSupplierImport(actor.value, rows) }
  async function importSuppliers(preview: SupplierImportPreview): Promise<void> { saving.value = true; try { await session.run(() => session.service.importSuppliers(actor.value, preview, nextRequestId('supplier-import'))); await load() } finally { saving.value = false } }
  async function loadPurchaseOrders(query: PurchaseOrderListQuery = {}): Promise<void> { loading.value = true; error.value = null; try { const result = await session.run(() => session.service.listPurchaseOrders(actor.value, query)); purchaseOrders.value = result.items; purchaseOrderTotal.value = result.total; const inventory = session.inventory.getWorkspace({ actorId: actor.value.actorId, role: actor.value.role }); purchaseWarehouses.value = inventory.warehouses.map((item) => ({ id: item.id, name: item.name })); purchaseLocations.value = inventory.locations.filter((item) => item.status === 'enabled').map((item) => ({ id: item.id, warehouseId: item.warehouseId, name: item.name })) } catch (caught) { error.value = caught instanceof Error ? caught.message : '采购订单加载失败'; purchaseOrders.value = []; purchaseOrderTotal.value = 0 } finally { loading.value = false } }
  async function createPurchaseOrder(value: PurchaseOrderDraft): Promise<PurchaseOrder> { saving.value = true; try { const result = await session.run(() => session.service.createPurchaseOrder(actor.value, { value, requestId: nextRequestId('purchase-order-create') })); await loadPurchaseOrders(); return result } finally { saving.value = false } }
  async function approvePurchaseOrder(order: PurchaseOrder): Promise<void> { saving.value = true; try { await session.run(() => session.service.approvePurchaseOrder(actor.value, order.id, order.version, nextRequestId('purchase-order-approve'))); await loadPurchaseOrders() } finally { saving.value = false } }
  async function voidPurchaseOrder(order: PurchaseOrder): Promise<void> { saving.value = true; try { await session.run(() => session.service.voidPurchaseOrder(actor.value, order.id, order.version, nextRequestId('purchase-order-void'))); await loadPurchaseOrders() } finally { saving.value = false } }
  async function cancelPurchaseOrder(order: PurchaseOrder): Promise<void> { saving.value = true; try { await session.run(() => session.service.cancelPurchaseOrder(actor.value, order.id, order.version, nextRequestId('purchase-order-cancel'))); await loadPurchaseOrders() } finally { saving.value = false } }
  async function receivePurchaseOrder(input: Omit<PurchaseOrderInboundInput, 'requestId' | 'operatorId' | 'occurredAt'>): Promise<void> { saving.value = true; try { await session.run(() => session.service.receivePurchaseOrder(actor.value, { ...input, requestId: nextRequestId('purchase-order-inbound'), operatorId: actor.value.actorId, occurredAt: '2026-08-10T10:00:00+08:00' })); await loadPurchaseOrders() } finally { saving.value = false } }
  async function loadPurchaseReturns(query: PurchaseReturnListQuery = {}): Promise<void> { const token = ++loadToken; loading.value = true; error.value = null; try { const [result, sources] = await session.run(() => [session.service.listPurchaseReturns(actor.value, query), session.service.listPurchaseReturnSources(actor.value)] as const); if (token === loadToken) { purchaseReturns.value = result.items; purchaseReturnTotal.value = result.total; purchaseReturnSources.value = sources } } catch (caught) { if (token === loadToken) { error.value = caught instanceof Error ? caught.message : '采购退单加载失败'; purchaseReturns.value = []; purchaseReturnTotal.value = 0; purchaseReturnSources.value = [] } } finally { if (token === loadToken) loading.value = false } }
  async function loadPurchaseStatistics(query: PurchaseStatisticsQuery): Promise<void> { const token = ++statisticsRequestToken; loading.value = true; error.value = null; try { const [response, options] = await Promise.all([session.run(() => session.statistics.query(actor.value as PurchaseStatisticsActor, query)), session.run(() => session.statistics.listFilterOptions(actor.value as PurchaseStatisticsActor))]); if (token === statisticsRequestToken) { statisticsPage.value = response; statisticsOptions.value = options } } catch (caught) { if (token === statisticsRequestToken) { error.value = caught instanceof Error ? caught.message : '采购统计加载失败'; statisticsPage.value = { ...statisticsPage.value, report: query.report, items: [], total: 0, snapshotVersion: 'error' }; statisticsOptions.value = { suppliers: [], products: [] } } } finally { if (token === statisticsRequestToken) loading.value = false } }
  async function exportPurchaseStatistics(query: PurchaseStatisticsQuery): Promise<string | null> { statisticsExporting.value = true; error.value = null; try { return await session.run(() => session.statistics.exportCsv(actor.value as PurchaseStatisticsActor, query)) } catch (caught) { error.value = caught instanceof Error ? caught.message : '采购统计导出失败'; return null } finally { statisticsExporting.value = false } }
  async function loadPurchaseReturn(id: string): Promise<void> { loading.value = true; error.value = null; try { selectedPurchaseReturn.value = await session.run(() => session.service.getPurchaseReturn(actor.value, id)) } catch (caught) { error.value = caught instanceof Error ? caught.message : '采购退单详情加载失败'; selectedPurchaseReturn.value = null } finally { loading.value = false } }
  async function createPurchaseReturn(value: PurchaseReturnDraft): Promise<PurchaseReturn> { saving.value = true; try { const result = await session.run(() => session.service.createPurchaseReturn(actor.value, { value, requestId: nextRequestId('purchase-return-create') })); selectedPurchaseReturn.value = result; await loadPurchaseReturns(); return result } finally { saving.value = false } }
  async function approvePurchaseReturn(value: PurchaseReturn): Promise<void> { saving.value = true; try { selectedPurchaseReturn.value = await session.run(() => session.service.approvePurchaseReturn(actor.value, value.id, value.version - (scenario.value === 'concurrent' ? 1 : 0), nextRequestId('purchase-return-approve'))); await loadPurchaseReturns() } finally { saving.value = false } }
  async function voidPurchaseReturn(value: PurchaseReturn, reason: string): Promise<void> { saving.value = true; try { selectedPurchaseReturn.value = await session.run(() => session.service.voidPurchaseReturn(actor.value, value.id, value.version, reason, nextRequestId('purchase-return-void'))); await loadPurchaseReturns() } finally { saving.value = false } }
  async function shipPurchaseReturn(value: PurchaseReturn, lines: Array<{ lineId: string; quantity: number }>): Promise<void> { saving.value = true; try { selectedPurchaseReturn.value = await session.run(() => session.service.shipPurchaseReturn(actor.value, { returnId: value.id, lines, expectedVersion: value.version - (scenario.value === 'concurrent' ? 1 : 0), requestId: nextRequestId('purchase-return-ship'), operatorId: actor.value.actorId, occurredAt: '2026-08-10T12:00:00+08:00' })); await loadPurchaseReturns() } finally { saving.value = false } }
  function exportPurchaseReturns(query: PurchaseReturnListQuery = {}): string { return session.service.exportPurchaseReturnsCsv(actor.value, query) }
  function exportSuppliers(): string { return session.service.exportSuppliersCsv(actor.value, supplierQuery.value) }
  function exportRelations(): string { return session.service.exportSupplierProductsCsv(actor.value, relationQuery.value) }
  return { scenario, actor, supplierQuery, relationQuery, workspace, selectedSupplier, purchaseOrders, purchaseOrderTotal, purchaseWarehouses, purchaseLocations, purchaseReturns, purchaseReturnTotal, purchaseReturnSources, selectedPurchaseReturn, statisticsPage, statisticsOptions, statisticsExporting, loading, saving, error, canWrite, isEmpty, load, loadSupplier, loadPurchaseOrders, loadPurchaseStatistics, loadPurchaseReturns, loadPurchaseReturn, setScenario, setRole, applySupplierQuery, applyRelationQuery, saveSupplier, toggleSupplier, saveRelation, updateRelation, toggleRelation, previewImport, importSuppliers, exportSuppliers, exportRelations, exportPurchaseReturns, exportPurchaseStatistics, createPurchaseOrder, approvePurchaseOrder, voidPurchaseOrder, cancelPurchaseOrder, receivePurchaseOrder, createPurchaseReturn, approvePurchaseReturn, voidPurchaseReturn, shipPurchaseReturn }
})
