<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { storeToRefs } from 'pinia'; import { onBeforeRouteLeave, RouterLink, useRoute, useRouter } from 'vue-router'; import DistributionSubnav from '../components/DistributionSubnav.vue'; import CustomerScopeEditor from '../components/CustomerScopeEditor.vue'; import SuggestedLinesEditor from '../components/SuggestedLinesEditor.vue'; import { useDistributionStore } from '../runtime/distribution-store'; import { emptyCustomerScope } from '../services/distribution-service'; import type { DistributionPlanDraft } from '../types'
const route=useRoute(),router=useRouter(),store=useDistributionStore(); const {options,selectedPlan,loading,saving,referenceError}=storeToRefs(store); const id=computed(()=>String(route.params.planId??'')); const editing=computed(()=>Boolean(id.value)); const error=ref<string|null>(null); const baseline=ref(''); const submitted=ref(false)
const draft=reactive<DistributionPlanDraft>({name:'',status:'enabled',startsAt:'',endsAt:'',scope:emptyCustomerScope(),lines:[]})
const local=(iso:string)=>iso.slice(0,16); const offset=(value:string)=>`${value}:00+08:00`
function snapshot(){return JSON.stringify(draft)}
function hydrate(){if(selectedPlan.value)Object.assign(draft,structuredClone(selectedPlan.value),{startsAt:local(selectedPlan.value.startsAt),endsAt:local(selectedPlan.value.endsAt)});else{const start=new Date(options.value.clock);const end=new Date(start.getTime()+86400000);const format=(date:Date)=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date).replace(' ','T');draft.startsAt=format(start);draft.endsAt=format(end)}baseline.value=snapshot()}
async function save(){error.value=null;try{const input:DistributionPlanDraft={...structuredClone(draft),startsAt:offset(draft.startsAt),endsAt:offset(draft.endsAt)};await store.savePlan(input,editing.value?id.value:undefined);submitted.value=true;await router.push('/products/distribution/plans')}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
onBeforeRouteLeave(()=>submitted.value||snapshot()===baseline.value||window.confirm('当前方案尚未保存，确认离开吗？'))
onMounted(async()=>{if(editing.value)await store.loadPlan(id.value);else await store.load('plans');hydrate()})
</script>
<template><section class="distribution-page"><header class="page-header"><div><p class="eyebrow">PRD-004 · 铺货方案</p><h1>{{editing?'编辑铺货方案':'新增铺货方案'}}</h1><p>时间采用分钟级半开区间 [开始，结束)；方案名称在企业内唯一。</p></div><RouterLink class="button" to="/products/distribution/plans">返回列表</RouterLink></header><DistributionSubnav/><div v-if="loading" class="state">正在加载方案资料…</div><form v-else class="form-card" @submit.prevent="save"><p v-if="referenceError" class="notice">{{referenceError}}</p><p v-if="error" class="warning" role="alert">{{error}}</p><div class="form-grid"><label class="field"><span>方案名称 *（1～20 字）</span><input v-model="draft.name" maxlength="20" required></label><label class="field"><span>状态 *</span><select v-model="draft.status"><option value="enabled">启用</option><option value="disabled">停用</option></select></label><label class="field"><span>开始时间 *</span><input v-model="draft.startsAt" type="datetime-local" required></label><label class="field"><span>结束时间 *</span><input v-model="draft.endsAt" type="datetime-local" required></label><CustomerScopeEditor v-model="draft.scope" :options="options" :disabled="Boolean(referenceError)"/><SuggestedLinesEditor v-model="draft.lines" :skus="options.skus" :max="20" mode="plan"/></div><p class="hint">方案不提供删除；停用后保留历史引用。解析结果只作建议，不修改购物车。</p><div class="form-actions"><RouterLink class="button" to="/products/distribution/plans">取消</RouterLink><button class="button primary" :disabled="saving||Boolean(referenceError)" type="submit">{{saving?'保存中…':'保存'}}</button></div></form></section></template>
<style scoped>@import './distribution-views.css';</style>
