<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { storeToRefs } from 'pinia'; import { RouterLink } from 'vue-router'; import DistributionSubnav from '../components/DistributionSubnav.vue'; import DistributionScenarioSelect from '../components/DistributionScenarioSelect.vue'; import { useDistributionStore, type DistributionRuntimeScenario } from '../runtime/distribution-store'
const store=useDistributionStore(); const {plans,loading,error,isEmpty,scenario,canWrite,saving}=storeToRefs(store); const filters=reactive({keyword:'',status:'',activeFrom:'',activeTo:''}); const actionError=ref<string|null>(null)
const iso=(value:string)=>value?`${value}:00+08:00`:undefined
const search=()=>store.applyPlanQuery({keyword:filters.keyword||undefined,status:(filters.status||undefined) as 'enabled'|'disabled'|undefined,activeFrom:iso(filters.activeFrom),activeTo:iso(filters.activeTo),pageSize:30})
const reset=()=>{Object.assign(filters,{keyword:'',status:'',activeFrom:'',activeTo:''});return search()}
async function changeStatus(id:string,status:'enabled'|'disabled'){actionError.value=null;try{await store.changePlanStatus(id,status)}catch(e){actionError.value=e instanceof Error?e.message:'状态修改失败'}}
onMounted(()=>store.load('plans'))
</script>
<template><section class="distribution-page"><header class="page-header"><div><p class="eyebrow">PRD-004 · 铺货</p><h1>铺货方案</h1><p>为移动端自主下单解析无副作用的商品建议；重叠方案按 SKU 汇总数量。</p></div><div class="tools"><DistributionScenarioSelect :model-value="scenario" @update:model-value="store.setScenario($event as DistributionRuntimeScenario)"/><RouterLink v-if="canWrite" class="button primary" to="/products/distribution/plans/new">新增方案</RouterLink></div></header><DistributionSubnav/><form class="filters" @submit.prevent="search"><label><span>方案名称</span><input v-model="filters.keyword" placeholder="输入方案名称"></label><label><span>状态</span><select v-model="filters.status"><option value="">全部状态</option><option value="enabled">启用</option><option value="disabled">停用</option></select></label><label><span>有效期从</span><input v-model="filters.activeFrom" type="datetime-local"></label><label><span>有效期至</span><input v-model="filters.activeTo" type="datetime-local"></label><div><button class="button" type="button" @click="reset">重置</button><button class="button primary" type="submit">查询</button></div></form><p v-if="actionError" class="warning" role="alert">{{actionError}}</p><div v-if="error" class="state error" role="alert"><strong>铺货方案加载失败</strong><p>{{error}}</p><button class="button" @click="store.load('plans')">重试</button></div><div v-else-if="loading" class="state">正在加载铺货方案…</div><div v-else-if="isEmpty" class="state"><strong>暂无铺货方案</strong><p>当前筛选或模拟场景没有数据。</p></div><template v-else><div class="table-tools"><span>共 {{plans.total}} 个方案 · 创建时间倒序</span><button class="button" @click="store.load('plans')">刷新</button></div><div class="table-wrap"><table><thead><tr><th>方案名称</th><th>状态</th><th>开始时间</th><th>结束时间</th><th>适用范围</th><th>商品种数</th><th>创建人</th><th>操作</th></tr></thead><tbody><tr v-for="item in plans.items" :key="item.id"><td><strong>{{item.name}}</strong></td><td><span class="status" :class="item.status">{{item.status==='enabled'?'启用':'停用'}}</span></td><td>{{item.startsAt.slice(0,16).replace('T',' ')}}</td><td>{{item.endsAt.slice(0,16).replace('T',' ')}}</td><td>{{item.scopeLabel}}</td><td>{{item.productCount}}</td><td>{{item.createdBy}}</td><td><RouterLink v-if="canWrite" :to="`/products/distribution/plans/${item.id}/edit`">编辑</RouterLink><button v-if="canWrite" class="link" :disabled="saving" @click="changeStatus(item.id,item.status==='enabled'?'disabled':'enabled')">{{item.status==='enabled'?'停用':'启用'}}</button><span v-else>只读</span></td></tr></tbody></table></div></template></section></template>
<style scoped>@import './distribution-views.css';</style>
