<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { storeToRefs } from 'pinia'; import DistributionSubnav from '../components/DistributionSubnav.vue'; import DistributionScenarioSelect from '../components/DistributionScenarioSelect.vue'; import { useDistributionStore, type DistributionRuntimeScenario } from '../runtime/distribution-store'; import type { OrderChannel } from '../types'
const store=useDistributionStore(); const {options,templates,preview,loading,error,scenario,referenceError}=storeToRefs(store); const selection=reactive({customerId:'',channel:'mobile-self-order' as OrderChannel,templateId:''}); const actionError=ref<string|null>(null)
async function run(kind:'distribution'|'template'){actionError.value=null;try{if(!selection.customerId)throw new Error('请选择客户');if(kind==='template'&&!selection.templateId)throw new Error('请选择订单模板');if(kind==='distribution')await store.resolveDistribution(selection.customerId,selection.channel);else await store.resolveTemplate(selection.templateId,selection.customerId,selection.channel)}catch(e){actionError.value=e instanceof Error?e.message:'解析失败'}}
async function changeScenario(value:DistributionRuntimeScenario){await store.setScenario(value);defaults()}
function defaults(){selection.customerId=options.value.customers.find(x=>x.status==='active')?.id??'';selection.templateId=templates.value.items.find(x=>x.status==='enabled')?.id??''}
const money=(cents:number|null)=>cents===null?'—':`¥ ${(cents/100).toFixed(2)}`
onMounted(async()=>{await store.load('preview');defaults()})
</script>
<template><section class="distribution-page"><header class="page-header"><div><p class="eyebrow">PRD-004 · 无副作用验算</p><h1>铺货与模板解析预览</h1><p>用同一领域服务查看适用范围、授权、商品状态与数量规则，不创建订单。</p></div><div class="tools"><DistributionScenarioSelect :model-value="scenario" @update:model-value="changeScenario"/></div></header><DistributionSubnav/><div v-if="error" class="state error"><strong>预览资料加载失败</strong><p>{{error}}</p><button class="button" @click="store.load('preview')">重试</button></div><div v-else-if="loading" class="state">正在加载预览资料…</div><div v-else class="preview-card"><p v-if="referenceError" class="notice">{{referenceError}}</p><p v-if="actionError" class="warning" role="alert">{{actionError}}</p><div class="preview-controls"><label><span>客户 *</span><select v-model="selection.customerId"><option value="">请选择客户</option><option v-for="item in options.customers" :key="item.id" :value="item.id">{{item.code}} · {{item.name}} · {{item.status}}</option></select></label><label><span>下单渠道 *</span><select v-model="selection.channel"><option value="mobile-self-order">移动端自主下单</option><option value="assisted-order">业务员代下单</option></select></label><label><span>订单模板</span><select v-model="selection.templateId"><option value="">请选择模板</option><option v-for="item in templates.items" :key="item.id" :value="item.id">{{item.name}} · {{item.status==='enabled'?'启用':'停用'}}</option></select></label></div><div class="preview-actions"><button class="button primary" @click="run('distribution')">解析自动铺货</button><button class="button" @click="run('template')">加载订单模板</button></div><p class="hint">模拟当前时间：{{options.clock}}。代下单不触发自动铺货；模板加载无论渠道都不修改订单。</p><div v-if="preview" class="result-grid"><section><h2>可接受明细（{{preview.accepted.length}}）</h2><p v-if="!preview.applicable" class="notice">当前规则不适用</p><p v-if="!preview.accepted.length">没有可接受商品。</p><ul><li v-for="item in preview.accepted" :key="item.sourceKey"><strong>{{item.productName}} · {{item.specification}}</strong><br>{{item.skuCode}} · {{item.quantity}} {{item.unitName}} · {{money(item.marketPriceCents)}}<small v-if="item.reasons.length">（原数量 {{item.originalQuantity}}，已向上归一）</small></li></ul></section><section class="rejected"><h2>跳过与拒绝（{{preview.rejected.length}}）</h2><p v-if="!preview.rejected.length">没有被跳过的商品。</p><ul><li v-for="(item,index) in preview.rejected" :key="`${item.skuId}-${index}`"><strong>{{item.skuId||'客户/渠道级'}}</strong>：{{item.message}}（{{item.reason}}）</li></ul></section></div></div></section></template>
<style scoped>@import './distribution-views.css';</style>
