<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { storeToRefs } from 'pinia'; import { onBeforeRouteLeave, RouterLink, useRoute, useRouter } from 'vue-router'; import DistributionSubnav from '../components/DistributionSubnav.vue'; import CustomerScopeEditor from '../components/CustomerScopeEditor.vue'; import SuggestedLinesEditor from '../components/SuggestedLinesEditor.vue'; import { useDistributionStore } from '../runtime/distribution-store'; import { emptyCustomerScope } from '../services/distribution-service'; import type { OrderTemplateDraft } from '../types'
const route=useRoute(),router=useRouter(),store=useDistributionStore(); const {options,selectedTemplate,loading,saving,referenceError}=storeToRefs(store); const id=computed(()=>String(route.params.templateId??'')); const editing=computed(()=>Boolean(id.value)); const error=ref<string|null>(null); const baseline=ref(''); const submitted=ref(false)
const draft=reactive<OrderTemplateDraft>({name:'',status:'enabled',selfOrderEnabled:true,scope:emptyCustomerScope(),lines:[]}); const snapshot=()=>JSON.stringify(draft)
function hydrate(){if(selectedTemplate.value)Object.assign(draft,structuredClone(selectedTemplate.value));baseline.value=snapshot()}
async function save(){error.value=null;try{await store.saveTemplate(structuredClone(draft),editing.value?id.value:undefined);submitted.value=true;await router.push('/products/order-templates')}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
onBeforeRouteLeave(()=>submitted.value||snapshot()===baseline.value||window.confirm('当前模板尚未保存，确认离开吗？'))
onMounted(async()=>{if(editing.value)await store.loadTemplate(id.value);else await store.load('templates');hydrate()})
</script>
<template><section class="distribution-page"><header class="page-header"><div><p class="eyebrow">PRD-004 · 订单模板</p><h1>{{editing?'编辑订单模板':'新增订单模板'}}</h1><p>模板数量在加载时向上归一；“允许自主下单”只控制移动端渠道。</p></div><RouterLink class="button" to="/products/order-templates">返回列表</RouterLink></header><DistributionSubnav/><div v-if="loading" class="state">正在加载模板资料…</div><form v-else class="form-card" @submit.prevent="save"><p v-if="referenceError" class="notice">{{referenceError}}</p><p v-if="error" class="warning" role="alert">{{error}}</p><div class="form-grid"><label class="field"><span>模板名称 *（1～20 字）</span><input v-model="draft.name" maxlength="20" required></label><label class="field"><span>状态 *</span><select v-model="draft.status"><option value="enabled">启用</option><option value="disabled">停用</option></select></label><label class="field full"><span><input v-model="draft.selfOrderEnabled" type="checkbox"> 允许移动端自主下单加载此模板</span></label><CustomerScopeEditor v-model="draft.scope" :options="options" :disabled="Boolean(referenceError)"/><SuggestedLinesEditor v-model="draft.lines" :skus="options.skus" :max="200" mode="template"/></div><p class="hint">代下单渠道不受自主下单开关影响；模板不提供删除，加载仅返回候选明细。</p><div class="form-actions"><RouterLink class="button" to="/products/order-templates">取消</RouterLink><button class="button primary" :disabled="saving||Boolean(referenceError)" type="submit">{{saving?'保存中…':'保存'}}</button></div></form></section></template>
<style scoped>@import './distribution-views.css';</style>
