<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { storeToRefs } from 'pinia'; import { RouterLink } from 'vue-router'; import DistributionSubnav from '../components/DistributionSubnav.vue'; import DistributionScenarioSelect from '../components/DistributionScenarioSelect.vue'; import { useDistributionStore, type DistributionRuntimeScenario } from '../runtime/distribution-store'
const store=useDistributionStore(); const {templates,loading,error,isEmpty,scenario,canWrite,saving}=storeToRefs(store); const filters=reactive({keyword:'',status:''}); const actionError=ref<string|null>(null)
const search=()=>store.applyTemplateQuery({keyword:filters.keyword||undefined,status:(filters.status||undefined) as 'enabled'|'disabled'|undefined,pageSize:30}); const reset=()=>{filters.keyword='';filters.status='';return search()}
async function changeStatus(id:string,status:'enabled'|'disabled'){actionError.value=null;try{await store.changeTemplateStatus(id,status)}catch(e){actionError.value=e instanceof Error?e.message:'状态修改失败'}}
onMounted(()=>store.load('templates'))
</script>
<template><section class="distribution-page"><header class="page-header"><div><p class="eyebrow">PRD-004 · 订单模板</p><h1>订单模板</h1><p>配置常用 SKU 与数量；加载仅返回候选明细，不直接改写或提交订单。</p></div><div class="tools"><DistributionScenarioSelect :model-value="scenario" @update:model-value="store.setScenario($event as DistributionRuntimeScenario)"/><RouterLink v-if="canWrite" class="button primary" to="/products/order-templates/new">新增模板</RouterLink></div></header><DistributionSubnav/><form class="filters" @submit.prevent="search"><label><span>名称 / 商品 / 创建人</span><input v-model="filters.keyword" placeholder="输入关键词"></label><label><span>状态</span><select v-model="filters.status"><option value="">全部状态</option><option value="enabled">启用</option><option value="disabled">停用</option></select></label><div><button class="button" type="button" @click="reset">重置</button><button class="button primary" type="submit">查询</button></div></form><p v-if="actionError" class="warning" role="alert">{{actionError}}</p><div v-if="error" class="state error" role="alert"><strong>订单模板加载失败</strong><p>{{error}}</p><button class="button" @click="store.load('templates')">重试</button></div><div v-else-if="loading" class="state">正在加载订单模板…</div><div v-else-if="isEmpty" class="state"><strong>暂无订单模板</strong><p>当前筛选或模拟场景没有数据。</p></div><template v-else><div class="table-tools"><span>共 {{templates.total}} 个模板 · 创建时间倒序</span><button class="button" @click="store.load('templates')">刷新</button></div><div class="table-wrap"><table><thead><tr><th>模板名称</th><th>状态</th><th>自主下单</th><th>适用范围</th><th>商品种数</th><th>创建人</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in templates.items" :key="item.id"><td><strong>{{item.name}}</strong></td><td><span class="status" :class="item.status">{{item.status==='enabled'?'启用':'停用'}}</span></td><td>{{item.selfOrderEnabled?'允许':'不允许'}}</td><td>{{item.scopeLabel}}</td><td>{{item.productCount}}</td><td>{{item.createdBy}}</td><td>{{item.createdAt.slice(0,16).replace('T',' ')}}</td><td><RouterLink v-if="canWrite" :to="`/products/order-templates/${item.id}/edit`">编辑</RouterLink><button v-if="canWrite" class="link" :disabled="saving" @click="changeStatus(item.id,item.status==='enabled'?'disabled':'enabled')">{{item.status==='enabled'?'停用':'启用'}}</button><span v-else>只读</span></td></tr></tbody></table></div></template></section></template>
<style scoped>@import './distribution-views.css';</style>
