import type { AnnouncementDraft, CompanyDraft, RegionDraft, SettingsFeatureState, SettingsEmployee, SettingsRoleRecord } from '../types'
export interface SettingsValidationIssue { path: string; message: string }
export class SettingsValidationError extends Error { readonly code = 'SETTINGS_VALIDATION_FAILED'; constructor(readonly issues: SettingsValidationIssue[]) { super(issues.map((item) => `${item.path}: ${item.message}`).join('；')); this.name = 'SettingsValidationError' } }
const required = (issues: SettingsValidationIssue[], path: string, value: string, max: number) => { const v = value.trim(); if (!v) issues.push({ path, message: '不能为空' }); else if (v.length > max) issues.push({ path, message: `不能超过 ${max} 个字符` }) }
const optional = (issues: SettingsValidationIssue[], path: string, value: string | null | undefined, max: number) => { if (value != null && value.trim().length > max) issues.push({ path, message: `不能超过 ${max} 个字符` }) }
export function validateCompanyDraft(draft: CompanyDraft): SettingsValidationIssue[] { const i: SettingsValidationIssue[] = []; required(i, 'name', draft.name, 100); required(i, 'code', draft.code, 40); required(i, 'contactName', draft.contactName, 40); required(i, 'phone', draft.phone, 40); optional(i, 'email', draft.email, 120); optional(i, 'region', draft.region, 100); optional(i, 'address', draft.address, 200); optional(i, 'description', draft.description, 1000); if (draft.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email.trim())) i.push({ path: 'email', message: '邮箱格式无效' }); if (!/^[0-9+()\-\s]{6,40}$/.test(draft.phone.trim())) i.push({ path: 'phone', message: '联系电话格式无效' }); return i }
export function validateAnnouncementDraft(draft: AnnouncementDraft): SettingsValidationIssue[] { const i: SettingsValidationIssue[] = []; required(i, 'title', draft.title, 20); required(i, 'content', draft.content, 20000); if (!['general', 'policy', 'event', 'alert'].includes(draft.type)) i.push({ path: 'type', message: '通知类型无效' }); if (!['all', 'departments'].includes(draft.recipientScope)) i.push({ path: 'recipientScope', message: '接收对象无效' }); optional(i, 'linkText', draft.linkText, 100); optional(i, 'linkUrl', draft.linkUrl, 300); if (draft.linkUrl && !/^https?:\/\//i.test(draft.linkUrl.trim())) i.push({ path: 'linkUrl', message: '链接必须以 http/https 开头' }); return i }
export function validateRegionDraft(draft: RegionDraft): SettingsValidationIssue[] { const i: SettingsValidationIssue[] = []; required(i, 'name', draft.name, 100); if (!['region', 'province', 'city', 'district', 'warehouse'].includes(draft.type)) i.push({ path: 'type', message: '区域类型无效' }); return i }
export function validateRoleDraft(draft: Pick<SettingsRoleRecord, 'name' | 'description' | 'permissionIds' | 'status'>): SettingsValidationIssue[] { const i: SettingsValidationIssue[] = []; required(i, 'name', draft.name, 60); if (!draft.permissionIds.length) i.push({ path: 'permissionIds', message: '至少选择一个权限' }); if (!['enabled', 'disabled'].includes(draft.status)) i.push({ path: 'status', message: '角色状态无效' }); return i }
export function validateEmployeeDraft(draft: Pick<SettingsEmployee, 'name' | 'account' | 'departmentId' | 'employeeType' | 'roleIds' | 'phone' | 'status'> & { password?: string }): SettingsValidationIssue[] { const i: SettingsValidationIssue[] = []; required(i, 'name', draft.name, 60); required(i, 'account', draft.account, 60); required(i, 'departmentId', draft.departmentId, 60); required(i, 'phone', draft.phone, 40); if (!draft.roleIds.length) i.push({ path: 'roleIds', message: '至少分配一个角色' }); if (!['full-time', 'part-time', 'external'].includes(draft.employeeType)) i.push({ path: 'employeeType', message: '员工类型无效' }); if (!['enabled', 'disabled'].includes(draft.status)) i.push({ path: 'status', message: '员工状态无效' }); if (draft.password !== undefined && draft.password.trim().length < 6) i.push({ path: 'password', message: '初始密码至少 6 位' }); return i }
export function assertValid<T>(issues: SettingsValidationIssue[]): asserts issues is [] { if (issues.length) throw new SettingsValidationError(issues) }
export function assertSettingsFeatureState(state: SettingsFeatureState): void { if (state.schemaVersion !== 1) throw new Error('设置状态 schemaVersion 必须为 1'); if (!state.enterpriseId.trim()) throw new Error('设置状态 enterpriseId 不能为空'); const ids = [...state.departments, ...state.announcements, ...state.regions].map((item) => item.id); if (new Set(ids).size !== ids.length) throw new Error('设置实体 ID 必须唯一'); if (state.regions.filter((item) => item.isDefault && item.parentId === null).length !== 1) throw new Error('必须保留唯一默认根区域') }
