import type { CustomerRepository } from '../repositories/customer-repository'
import { CustomerDomainError, type CustomerServiceDependencies } from './customer-service'
import type {
  CustomerActor, CustomerFeatureState, CustomerFrequentProduct, CustomerMapMarker, CustomerOpportunity, CustomerVisit,
  CustomerVisitPlan, CustomerVisitRoute, EntityId, FrequentProductDraft, OpportunityDraft, OpportunityStage,
  PageResult, PublicSeaEntry, PublicSeaRule, PublicSeaRuleDraft, RouteDraft, VisitDraft, VisitPlanDraft, MembershipLevel, MembershipLevelDraft, CustomerMembership, PointAccount, PointLedgerEntry, PointsSettings, PointsSettingsDraft, PointAdjustmentType,
  CouponTemplate, CouponTemplateDraft, CouponInstance, Promotion, PromotionDraft, PromotionRule, VoucherCampaign, VoucherCampaignDraft, VoucherIssue, MarketingArticle, MarketingArticleDraft, MarketingAnalysisResult, MarketingStatus,
  CustomerChannelState, WecomSyncSettings, WecomSyncRecord, WecomBroadcast, WecomTagMapping, WecomScript, WecomWelcomeMessage, WecomGroup, WecomMoment, MallCustomerAccount, MallEmployeeAccount, MallDesign, MallExtension, MallAd, MallPopup, MallMessage, MallSettings,
} from '../types'

const readRoles = new Set(['super-admin', 'sales-supervisor', 'salesperson'])
const manageRoles = new Set(['super-admin', 'sales-supervisor'])
const allWriteRoles = new Set(['super-admin', 'sales-supervisor', 'salesperson'])
const stageProbability: Record<OpportunityStage, number> = { lead: 10, qualified: 30, proposal: 50, negotiation: 70, won: 100, lost: 0 }

function read(actor: CustomerActor): void { if (!readRoles.has(actor.role)) throw new CustomerDomainError('PERMISSION_DENIED', '当前角色不可访问客户运营') }
function write(actor: CustomerActor): void { if (!allWriteRoles.has(actor.role)) throw new CustomerDomainError('PERMISSION_DENIED', '当前角色不可修改客户运营') }
function manage(actor: CustomerActor): void { if (!manageRoles.has(actor.role)) throw new CustomerDomainError('PERMISSION_DENIED', '当前角色不可管理公海规则或分配') }
function customer(state: CustomerFeatureState, id: EntityId) { const value = state.customers.find((item) => item.id === id); if (!value) throw new CustomerDomainError('NOT_FOUND', '客户不存在'); return value }
function page<T>(items: T[], pageNumber = 1, pageSize = 30): PageResult<T> { const page = Math.max(1, pageNumber); return { items: items.slice((page - 1) * pageSize, page * pageSize), total: items.length, page, pageSize } }
function day(value: string): string { return value.slice(0, 10) }

function ensure(state: CustomerFeatureState, deps: CustomerServiceDependencies): void {
  const now = deps.now()
  state.opportunities ??= [{ id: 'opportunity-demo-1', enterpriseId: state.enterpriseId, customerId: state.customers[0]?.id ?? '', name: '演示年度采购合作', amountCents: 1280000, stage: 'proposal' as const, probabilityPercent: 50, expectedCloseDate: '2026-09-30', ownerId: 'staff-demo-1', source: 'manual' as const, description: '原型演示商机，不会自动创建订单', status: 'open' as const, createdAt: now, updatedAt: now, closedAt: null }].filter((item) => item.customerId)
  state.frequentProducts ??= [{ id: 'frequent-demo-1', enterpriseId: state.enterpriseId, customerId: state.customers[0]?.id ?? '', skuId: 'sku-demo-001', source: 'auto' as const, purchaseCount: 4, lastPurchasedAt: '2026-08-02T10:00:00+08:00', averageQuantity: 12, totalQuantity: 48, totalAmountCents: 960000, note: '按近 3 个月购买次数达到阈值', active: true, createdAt: now, updatedAt: now }].filter((item) => item.customerId)
  state.publicSeaEntries ??= state.customers[1] ? [{ id: 'public-sea-demo-1', enterpriseId: state.enterpriseId, customerId: state.customers[1].id, enteredAt: now, reason: '原型演示：长期未跟进', claimedById: null, claimedAt: null, protectionUntil: null, status: 'available', updatedAt: now }] : []
  state.publicSeaRule ??= { id: 'public-sea-rule-1', enterpriseId: state.enterpriseId, noOrderDays: 30, noVisitDays: 30, newCustomerInactiveDays: 14, dailyClaimLimit: 5, monthlyClaimLimit: 30, protectionDays: 7, excludedCategoryIds: [], excludedTagIds: [], updatedAt: now }
  state.visits ??= state.customers[0] ? [{ id: 'visit-demo-1', enterpriseId: state.enterpriseId, customerId: state.customers[0].id, salespersonId: 'staff-demo-1', visitAt: '2026-08-25T10:00:00+08:00', checkInAt: null, checkOutAt: null, durationMinutes: null, type: 'onsite' as const, result: null, status: 'planned' as const, placedOrder: false, orderId: null, fakeLongitude: null, fakeLatitude: null, checkInDistanceMeters: null, photo: null, note: '原型演示待签到拜访', nextPlan: null, createdAt: now, updatedAt: now }] : []
  state.routes ??= state.customers[0] ? [{ id: 'route-demo-1', enterpriseId: state.enterpriseId, code: 'ROUTE-DEMO-001', name: '演示华东客户线路', salespersonId: 'staff-demo-1', stops: [{ customerId: state.customers[0].id, sortOrder: 1, plannedMinutes: 30 }], estimatedDistanceKm: 2.4, estimatedMinutes: 45, status: 'active' as const, createdAt: now, updatedAt: now }] : []
  state.visitPlans ??= state.customers[0] ? [{ id: 'visit-plan-demo-1', enterpriseId: state.enterpriseId, date: '2026-08-25', salespersonId: 'staff-demo-1', routeId: 'route-demo-1', customerIds: [state.customers[0].id], plannedStartTime: '10:00', plannedMinutes: 30, purpose: '演示客户回访', note: '原型计划，不发送真实提醒', status: 'pending' as const, reminder: 'fake reminder', createdAt: now, updatedAt: now }] : []
  state.membershipLevels ??= [{ id: 'membership-level-demo-1', enterpriseId: state.enterpriseId, name: '演示普通会员', code: 'DEMO-MEMBER-1', icon: null, sortOrder: 1, conditionType: 'amount' as const, conditionValue: 0, retainConditionValue: null, retainPeriodMonths: null, autoUpgrade: false, memberDiscountPercent: 100, pointsMultiplier: 1, benefits: { freeShipping: false, priorityShipping: false, dedicatedService: false, birthdayGift: false, birthdayCouponId: null, exclusiveProductIds: [] }, status: 'active' as const, createdAt: now, updatedAt: now }, { id: 'membership-level-demo-2', enterpriseId: state.enterpriseId, name: '演示金卡会员', code: 'DEMO-MEMBER-2', icon: null, sortOrder: 2, conditionType: 'amount' as const, conditionValue: 1000000, retainConditionValue: 500000, retainPeriodMonths: 12, autoUpgrade: true, memberDiscountPercent: 95, pointsMultiplier: 1.5, benefits: { freeShipping: true, priorityShipping: true, dedicatedService: true, birthdayGift: false, birthdayCouponId: null, exclusiveProductIds: [] }, status: 'active' as const, createdAt: now, updatedAt: now }]
  state.memberships ??= state.customers[0] ? [{ id: 'membership-demo-1', enterpriseId: state.enterpriseId, customerId: state.customers[0].id, levelId: 'membership-level-demo-1', assignedAt: now, source: 'manual' as const, pendingReview: false, updatedAt: now }] : []
  state.pointAccounts ??= state.customers.map((item, index) => ({ id: `point-account-demo-${index + 1}`, enterpriseId: state.enterpriseId, customerId: item.id, totalEarned: index ? 0 : 1200, totalRedeemed: 0, totalExpired: 0, totalRefunded: 0, totalAdjusted: 0, availablePoints: index ? 0 : 1200, expiringWithin30Days: index ? 0 : 200, lastChangedAt: index ? null : now }))
  state.pointLedger ??= state.customers[0] ? [{ id: 'point-ledger-demo-1', enterpriseId: state.enterpriseId, customerId: state.customers[0].id, type: 'earn' as const, points: 1200, balanceAfter: 1200, source: '演示订单 DEMO-ORDER-001', reason: null, occurredAt: now, expiresAt: null, requestId: 'demo-point-request-1' }] : []
  state.pointsSettings ??= { id: 'points-settings-1', enterpriseId: state.enterpriseId, enabled: true, orderEarnPerYuan: 1, orderEarnCapPerOrder: 0, dailyEarnCap: 500, signInPoints: 5, consecutiveSignInBonus: 20, reviewPoints: 10, photoReviewBonus: 5, referralPoints: 100, referralFirstOrderBonus: 50, registrationPoints: 50, profileCompletionPoints: 20, redemptionPointsPerYuan: 100, orderRedemptionCapPercent: 50, minimumRedemptionPoints: 100, mallEnabled: false, exchangePointsRatio: null, expiryType: 'never' as const, expiryDays: null, yearlyExpiryDate: null, expiryReminderDays: 30, ruleDescription: '原型积分规则说明', showRuleInMall: false, updatedAt: now }
  state.pointLevels ??= []
  state.coupons ??= [{ id: 'coupon-demo-1', enterpriseId: state.enterpriseId, code: 'COUPON-DEMO-001', name: '演示满减券', type: 'threshold-discount' as const, thresholdCents: 10000, amountCents: 1000, discountPercent: null, maxDiscountCents: null, issueQuantity: 1000, claimedQuantity: 120, usedQuantity: 45, validityType: 'date-range' as const, validityDays: null, startsAt: '2026-08-01T00:00:00+08:00', endsAt: '2026-09-30T23:59:59+08:00', scopeKind: 'all' as const, scopeIds: [], audienceKind: 'all' as const, audienceIds: [], perCustomerLimit: 1, newCustomerOnly: false, allowPromotionalItems: false, description: '原型演示优惠券', status: 'active' as const, createdAt: now, updatedAt: now }]
  state.couponInstances ??= []
  state.promotions ??= [{ id: 'promotion-demo-1', enterpriseId: state.enterpriseId, code: 'PROMO-DEMO-001', name: '演示限时折扣', type: 'limited-discount' as const, startsAt: '2026-08-01T00:00:00+08:00', endsAt: '2026-09-30T23:59:59+08:00', customerAudienceKind: 'all' as const, customerAudienceIds: [], scopeKind: 'all' as const, scopeIds: [], discountMode: 'rate' as const, discountPercent: 95, discountPriceCents: null, limitQuantity: 0, limitPeriod: 'campaign' as const, rules: [], allowCoupon: false, allowMemberDiscount: false, showCountdown: true, showStock: false, sortWeight: 1, orderCount: null, orderAmountCents: null, status: 'active' as const, description: '原型演示促销', createdAt: now, updatedAt: now }]
  state.voucherCampaigns ??= []
  state.voucherIssues ??= []
  state.marketingArticles ??= [{ id: 'article-demo-1', enterpriseId: state.enterpriseId, title: '演示新品到货文章', type: 'graphic' as const, cover: null, summary: '原型内容预览', content: '这是原型模拟内容。', productIds: [], couponId: 'coupon-demo-1', promotionId: 'promotion-demo-1', publishMode: 'publish-now' as const, scheduledAt: null, channels: ['h5'] as const, readPermission: 'public' as const, publishedAt: now, viewCount: null, acquiredCustomerCount: null, shareCount: null, status: 'published' as const, createdAt: now, updatedAt: now }]
  state.channelState ??= createChannelSeed(state.enterpriseId, now)
}

function createChannelSeed(enterpriseId: string, now: string): CustomerChannelState {
  const syncSettings: WecomSyncSettings = { enabled: false, frequency: 'daily', scope: ['all'], autoCreateCustomer: false, autoMapStaff: false, updatedAt: now }
  const syncRecord: WecomSyncRecord = { id: 'wecom-sync-demo-1', enterpriseId, occurredAt: now, type: 'update', createdCount: 0, updatedCount: 12, failedCount: 0, status: 'success' }
  const broadcast: WecomBroadcast = { id: 'wecom-broadcast-demo-1', enterpriseId, title: '演示新品通知', employeeIds: ['staff-demo-1'], audience: 'all', customerIds: [], content: '原型模拟群发内容', image: null, link: null, sendMode: 'now', scheduledAt: null, status: 'completed', createdAt: now, updatedAt: now }
  const mapping: WecomTagMapping = { id: 'wecom-map-demo-1', enterpriseId, wecomTag: '重点客户', systemTagId: 'tag-demo-1', direction: 'bidirectional', status: 'active', updatedAt: now }
  const script: WecomScript = { id: 'wecom-script-demo-1', enterpriseId, title: '演示欢迎话术', content: '您好，欢迎咨询。', category: '欢迎', productIds: [], couponId: null, usageCount: 4, status: 'active', updatedAt: now }
  const welcome: WecomWelcomeMessage = { id: 'wecom-welcome-demo-1', enterpriseId, type: 'text', content: '您好，欢迎添加。', image: null, link: null, employeeIds: ['staff-demo-1'], status: 'active', updatedAt: now }
  const group: WecomGroup = { id: 'wecom-group-demo-1', enterpriseId, name: '演示客户群', ownerId: 'staff-demo-1', memberCount: 18, createdAt: now, tags: ['重点'] }
  const moment: WecomMoment = { id: 'wecom-moment-demo-1', enterpriseId, content: '原型朋友圈内容', imageCount: 0, employeeIds: ['staff-demo-1'], publishAt: now, scheduled: false, status: 'completed', updatedAt: now }
  const mallCustomer: MallCustomerAccount = { id: 'mall-customer-demo-1', enterpriseId, customerId: null, name: '演示商城客户', account: 'demo@example.com', phone: '138****0000', channel: 'h5', registeredAt: now, lastLoginAt: now, loginCount: 5, orderCount: null, consumptionAmountCents: null, status: 'active', updatedAt: now }
  const mallEmployee: MallEmployeeAccount = { id: 'mall-employee-demo-1', enterpriseId, customerId: 'customer-demo-1', name: '演示店员', phone: '139****0000', role: 'clerk', permissions: ['view-product', 'view-price', 'create-order', 'view-order', 'view-stock'], createdAt: now, lastLoginAt: null, status: 'active', updatedAt: now }
  const design: MallDesign = { id: 'mall-design-demo-1', enterpriseId, name: '演示商城首页', components: [{ type: 'banner', title: '新品专区' }, { type: 'product-list', title: '热销推荐', productIds: [] }], status: 'published', updatedAt: now }
  const extensionKeys = [['live', '直播带货'], ['community', '社区团购'], ['group', '拼团活动'], ['seckill', '秒杀活动'], ['presale', '预售活动'], ['distribution', '分销推广'], ['points-mall', '积分商城'], ['member-center', '会员中心']] as const
  const extensions: MallExtension[] = extensionKeys.map(([key, name], index) => ({ id: `mall-extension-demo-${index + 1}`, enterpriseId, key, name, enabled: false, updatedAt: now }))
  const ad: MallAd = { id: 'mall-ad-demo-1', enterpriseId, title: '演示首页广告', position: 'home-banner', image: null, linkType: 'custom', link: null, startsAt: now, endsAt: '2026-12-31T23:59:59+08:00', sortOrder: 1, status: 'active', updatedAt: now }
  const popup: MallPopup = { id: 'mall-popup-demo-1', enterpriseId, title: '演示弹窗', image: null, frequency: 'daily', startsAt: now, endsAt: '2026-12-31T23:59:59+08:00', channels: ['h5'], status: 'active', updatedAt: now }
  const message: MallMessage = { id: 'mall-message-demo-1', enterpriseId, title: '演示商城通知', type: 'system', content: '原型模拟通知', audience: 'all', customerIds: [], sendMode: 'now', scheduledAt: null, status: 'published', readCount: 0, updatedAt: now }
  const settings: MallSettings = { id: 'mall-settings-1', enterpriseId, name: '蜂订商城（原型）', introduction: '原型商城配置', displayMode: 'double', searchEnabled: true, categoryEnabled: true, salesVisible: false, stockVisible: false, reviewVisible: false, cartEnabled: true, favoriteEnabled: true, shareEnabled: true, reviewEnabled: true, serviceEnabled: false, paymentMethods: ['wechat', 'alipay'], minimumPaymentCents: 0, paymentTimeoutMinutes: 30, updatedAt: now }
  return { wecomSyncSettings: syncSettings, wecomSyncRecords: [syncRecord], wecomBroadcasts: [broadcast], wecomTagMappings: [mapping], wecomScripts: [script], wecomWelcomeMessages: [welcome], wecomGroups: [group], wecomMoments: [moment], mallCustomers: [mallCustomer], mallEmployees: [mallEmployee], mallDesigns: [design], mallExtensions: extensions, mallAds: [ad], mallPopups: [popup], mallMessages: [message], mallSettings: settings }
}

export function createCustomerOperationsService(deps: CustomerServiceDependencies) {
  const { repository } = deps
  function ready(): CustomerFeatureState { repository.transact((state) => ensure(state, deps)); return repository.read() }
  function listOpportunities(actor: CustomerActor, query: { keyword?: string; stage?: OpportunityStage; ownerId?: string; page?: number; pageSize?: number } = {}): PageResult<CustomerOpportunity> {
    const state = ready(); read(actor); const keyword = query.keyword?.trim().toLocaleLowerCase()
    const items = (state.opportunities ?? []).filter((item) => (!query.stage || item.stage === query.stage) && (!query.ownerId || item.ownerId === query.ownerId) && (!keyword || `${item.name}${item.id}`.toLocaleLowerCase().includes(keyword))).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
    return page(items, query.page, query.pageSize)
  }
  function createOpportunity(actor: CustomerActor, input: OpportunityDraft): CustomerOpportunity {
    write(actor); if (!Number.isInteger(input.amountCents) || input.amountCents < 0) throw new CustomerDomainError('INVALID_TRANSITION', '商机金额必须为非负整数分'); if (!Number.isInteger(input.probabilityPercent) || input.probabilityPercent < 0 || input.probabilityPercent > 100) throw new CustomerDomainError('INVALID_TRANSITION', '商机概率必须为 0～100 的整数')
    return repository.transact((state) => { ensure(state, deps); customer(state, input.customerId); const now = deps.now(); const value: CustomerOpportunity = { ...structuredClone(input), id: deps.nextId('opportunity'), enterpriseId: state.enterpriseId, status: input.status ?? 'open', createdAt: now, updatedAt: now, closedAt: null }; state.opportunities!.push(value); return value })
  }
  function updateOpportunity(actor: CustomerActor, id: string, input: OpportunityDraft): CustomerOpportunity {
    write(actor); return repository.transact((state) => { ensure(state, deps); const current = state.opportunities!.find((item) => item.id === id); if (!current) throw new CustomerDomainError('NOT_FOUND', '商机不存在'); if (current.status !== 'open') throw new CustomerDomainError('INVALID_TRANSITION', '终态商机不可编辑'); customer(state, input.customerId); const updated = { ...current, ...structuredClone(input), status: 'open' as const, updatedAt: deps.now() }; state.opportunities![state.opportunities!.indexOf(current)] = updated; return updated })
  }
  function advanceOpportunity(actor: CustomerActor, id: string, stage: OpportunityStage, probabilityPercent?: number): CustomerOpportunity {
    write(actor); return repository.transact((state) => { ensure(state, deps); const item = state.opportunities!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '商机不存在'); if (item.status !== 'open') throw new CustomerDomainError('INVALID_TRANSITION', '终态商机不可推进'); if (stage === 'won' || stage === 'lost') { item.status = stage; item.closedAt = deps.now() } item.stage = stage; item.probabilityPercent = probabilityPercent ?? stageProbability[stage]; item.updatedAt = deps.now(); return item })
  }
  function deleteOpportunity(actor: CustomerActor, id: string): void { write(actor); repository.transact((state) => { ensure(state, deps); const item = state.opportunities!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '商机不存在'); if (item.status === 'won') throw new CustomerDomainError('REFERENCE_CONFLICT', '成交商机保留审计，不能删除'); state.opportunities = state.opportunities!.filter((value) => value.id !== id) }) }

  function listFrequentProducts(actor: CustomerActor, customerId?: string): PageResult<CustomerFrequentProduct> { const state = ready(); read(actor); return page((state.frequentProducts ?? []).filter((item) => !customerId || item.customerId === customerId && item.active).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))) }
  function addFrequentProduct(actor: CustomerActor, input: FrequentProductDraft): CustomerFrequentProduct { write(actor); return repository.transact((state) => { ensure(state, deps); customer(state, input.customerId); if (state.frequentProducts!.some((item) => item.customerId === input.customerId && item.skuId === input.skuId && item.active)) throw new CustomerDomainError('DUPLICATE_CODE', '该客户的常购商品已存在'); const now = deps.now(); const value = { ...structuredClone(input), id: deps.nextId('frequent-product'), enterpriseId: state.enterpriseId, createdAt: now, updatedAt: now }; state.frequentProducts!.push(value); return value }) }
  function removeFrequentProduct(actor: CustomerActor, id: string): void { write(actor); repository.transact((state) => { ensure(state, deps); const item = state.frequentProducts!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '常购商品不存在'); item.active = false; item.updatedAt = deps.now() }) }
  function quickOrder(actor: CustomerActor, customerId: string, skuId: string): { path: string; simulated: true } { read(actor); ready(); return { path: `/orders/new?customerId=${encodeURIComponent(customerId)}&skuId=${encodeURIComponent(skuId)}`, simulated: true } }

  function mapMarkers(actor: CustomerActor, keyword?: string): CustomerMapMarker[] { const state = ready(); read(actor); return state.customers.filter((item) => !keyword || `${item.name}${item.code}${item.primaryContactName}`.toLocaleLowerCase().includes(keyword.trim().toLocaleLowerCase())).map((item, index) => ({ customerId: item.id, longitude: item.longitude ?? 121.4737 + index * 0.03, latitude: item.latitude ?? 31.2304 + index * 0.02, clusterKey: `${item.provinceCode}-${item.cityCode}`, label: item.name })) }
  function listPublicSea(actor: CustomerActor, keyword?: string): PageResult<PublicSeaEntry> { const state = ready(); read(actor); const entries = (state.publicSeaEntries ?? []).filter((entry) => { const item = customer(state, entry.customerId); return !keyword || `${item.name}${item.code}${item.primaryContactName}${item.primaryPhone}`.toLocaleLowerCase().includes(keyword.trim().toLocaleLowerCase()) }).sort((a, b) => b.enteredAt.localeCompare(a.enteredAt)); return page(entries) }
  function getPublicSeaRule(actor: CustomerActor): PublicSeaRule { const state = ready(); read(actor); return state.publicSeaRule! }
  function savePublicSeaRule(actor: CustomerActor, input: PublicSeaRuleDraft): PublicSeaRule { manage(actor); return repository.transact((state) => { ensure(state, deps); const numbers = [input.noOrderDays, input.noVisitDays, input.newCustomerInactiveDays, input.dailyClaimLimit, input.monthlyClaimLimit, input.protectionDays]; if (numbers.some((value) => !Number.isInteger(value) || value <= 0)) throw new CustomerDomainError('INVALID_TRANSITION', '公海规则必须为正整数'); const value = { ...structuredClone(input), id: state.publicSeaRule!.id, enterpriseId: state.enterpriseId, updatedAt: deps.now() }; state.publicSeaRule = value; return value }) }
  function claimPublicSea(actor: CustomerActor, id: string): PublicSeaEntry { write(actor); return repository.transact((state) => { ensure(state, deps); const entry = state.publicSeaEntries!.find((value) => value.id === id); if (!entry) throw new CustomerDomainError('NOT_FOUND', '公海记录不存在'); if (entry.claimedById === actor.actorId) return entry; if (entry.status !== 'available') throw new CustomerDomainError('INVALID_TRANSITION', '公海记录已被领取或处于保护期'); const now = deps.now(); const rule = state.publicSeaRule!; const claims = state.publicSeaEntries!.filter((value) => value.claimedById === actor.actorId && value.claimedAt); const daily = claims.filter((value) => day(value.claimedAt!) === day(now)).length; const monthly = claims.filter((value) => value.claimedAt!.slice(0, 7) === now.slice(0, 7)).length; if (daily >= rule.dailyClaimLimit) throw new CustomerDomainError('INVALID_TRANSITION', '已达到当日领取上限'); if (monthly >= rule.monthlyClaimLimit) throw new CustomerDomainError('INVALID_TRANSITION', '已达到当月领取上限'); entry.claimedById = actor.actorId; entry.claimedAt = now; entry.protectionUntil = new Date(Date.parse(now) + rule.protectionDays * 86400000).toISOString(); entry.status = 'protected'; entry.updatedAt = now; return entry }) }
  function assignPublicSea(actor: CustomerActor, id: string, salespersonId: string): PublicSeaEntry { manage(actor); return repository.transact((state) => { ensure(state, deps); customer(state, state.publicSeaEntries!.find((value) => value.id === id)?.customerId ?? ''); const entry = state.publicSeaEntries!.find((value) => value.id === id); if (!entry) throw new CustomerDomainError('NOT_FOUND', '公海记录不存在'); entry.claimedById = salespersonId; entry.claimedAt = deps.now(); entry.protectionUntil = new Date(Date.parse(entry.claimedAt) + state.publicSeaRule!.protectionDays * 86400000).toISOString(); entry.status = 'assigned'; entry.updatedAt = deps.now(); return entry }) }
  function reclaimPublicSea(actor: CustomerActor): number { manage(actor); return repository.transact((state) => { ensure(state, deps); const now = deps.now(); let count = 0; for (const entry of state.publicSeaEntries!) if (entry.status !== 'available' && entry.protectionUntil && entry.protectionUntil < now) { entry.status = 'available'; entry.claimedById = null; entry.claimedAt = null; entry.protectionUntil = null; entry.updatedAt = now; count += 1 } return count }) }

  function listVisits(actor: CustomerActor, customerId?: string): PageResult<CustomerVisit> { const state = ready(); read(actor); return page((state.visits ?? []).filter((item) => (!customerId || item.customerId === customerId) && (actor.role !== 'salesperson' || item.salespersonId === actor.actorId)).sort((a, b) => b.visitAt.localeCompare(a.visitAt))) }
  function createVisit(actor: CustomerActor, input: VisitDraft): CustomerVisit { write(actor); if (actor.role === 'salesperson' && input.salespersonId !== actor.actorId) throw new CustomerDomainError('PERMISSION_DENIED', '业务员只能维护自己的拜访'); if (input.status === 'completed' && (input.checkInAt === null || !input.result)) throw new CustomerDomainError('INVALID_TRANSITION', '完成拜访必须有 fake 签到和结果'); return repository.transact((state) => { ensure(state, deps); customer(state, input.customerId); const now = deps.now(); const value = { ...structuredClone(input), id: deps.nextId('visit'), enterpriseId: state.enterpriseId, createdAt: now, updatedAt: now }; state.visits!.push(value); return value }) }
  function checkInVisit(actor: CustomerActor, id: string): CustomerVisit { write(actor); return repository.transact((state) => { ensure(state, deps); const item = state.visits!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '拜访记录不存在'); if (actor.role === 'salesperson' && item.salespersonId !== actor.actorId) throw new CustomerDomainError('PERMISSION_DENIED', '不能操作其他业务员的拜访'); item.checkInAt = deps.now(); item.fakeLongitude = 121.4737; item.fakeLatitude = 31.2304; item.checkInDistanceMeters = 120; item.status = 'in-progress'; item.updatedAt = deps.now(); return item }) }
  function completeVisit(actor: CustomerActor, id: string, result: NonNullable<CustomerVisit['result']>): CustomerVisit { write(actor); return repository.transact((state) => { ensure(state, deps); const item = state.visits!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '拜访记录不存在'); if (!item.checkInAt) throw new CustomerDomainError('INVALID_TRANSITION', '请先使用 fake 签到'); item.checkOutAt = deps.now(); item.durationMinutes = Math.max(1, Math.round((Date.parse(item.checkOutAt) - Date.parse(item.checkInAt)) / 60000)); item.result = result; item.status = 'completed'; item.updatedAt = deps.now(); return item }) }
  function listRoutes(actor: CustomerActor): CustomerVisitRoute[] { const state = ready(); read(actor); return (state.routes ?? []).filter((item) => actor.role !== 'salesperson' || item.salespersonId === actor.actorId).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)) }
  function createRoute(actor: CustomerActor, input: RouteDraft): CustomerVisitRoute { write(actor); if (!input.stops.length) throw new CustomerDomainError('INVALID_TRANSITION', '线路至少需要一个站点'); return repository.transact((state) => { ensure(state, deps); const now = deps.now(); const value = { ...structuredClone(input), id: deps.nextId('route'), enterpriseId: state.enterpriseId, createdAt: now, updatedAt: now }; if (state.routes!.some((item) => item.code.toLocaleLowerCase() === value.code.toLocaleLowerCase())) throw new CustomerDomainError('DUPLICATE_CODE', '线路编码已存在'); state.routes!.push(value); return value }) }
  function listVisitPlans(actor: CustomerActor): CustomerVisitPlan[] { const state = ready(); read(actor); return (state.visitPlans ?? []).filter((item) => actor.role !== 'salesperson' || item.salespersonId === actor.actorId).sort((a, b) => b.date.localeCompare(a.date)) }
  function createVisitPlan(actor: CustomerActor, input: VisitPlanDraft): CustomerVisitPlan { write(actor); if (!input.customerIds.length && !input.routeId) throw new CustomerDomainError('INVALID_TRANSITION', '计划至少需要一个客户或线路'); return repository.transact((state) => { ensure(state, deps); const now = deps.now(); const value = { ...structuredClone(input), id: deps.nextId('visit-plan'), enterpriseId: state.enterpriseId, createdAt: now, updatedAt: now }; state.visitPlans!.push(value); return value }) }
  function updateVisitPlanStatus(actor: CustomerActor, id: string, status: CustomerVisitPlan['status']): CustomerVisitPlan { write(actor); return repository.transact((state) => { ensure(state, deps); const item = state.visitPlans!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '拜访计划不存在'); item.status = status; item.updatedAt = deps.now(); return item }) }

  function listMembershipLevels(actor: CustomerActor): MembershipLevel[] { const state = ready(); read(actor); return (state.membershipLevels ?? []).slice().sort((a, b) => b.sortOrder - a.sortOrder || a.id.localeCompare(b.id)) }
  function saveMembershipLevel(actor: CustomerActor, input: MembershipLevelDraft, id?: string): MembershipLevel { write(actor); if (!input.name.trim() || !input.code.trim()) throw new CustomerDomainError('INVALID_TRANSITION', '会员等级名称和编码不能为空'); if (!Number.isInteger(input.sortOrder) || input.sortOrder < 0) throw new CustomerDomainError('INVALID_TRANSITION', '等级排序必须为非负整数'); if (input.memberDiscountPercent < 1 || input.memberDiscountPercent > 100 || input.pointsMultiplier < 0 || input.conditionValue < 0) throw new CustomerDomainError('INVALID_TRANSITION', '会员折扣、积分倍数或条件值不合法'); return repository.transact((state) => { ensure(state, deps); if (state.membershipLevels!.some((item) => item.id !== id && item.code.toLocaleLowerCase() === input.code.trim().toLocaleLowerCase())) throw new CustomerDomainError('DUPLICATE_CODE', '会员等级编码已存在'); const now = deps.now(); if (id) { const current = state.membershipLevels!.find((item) => item.id === id); if (!current) throw new CustomerDomainError('NOT_FOUND', '会员等级不存在'); const updated = { ...current, ...structuredClone(input), name: input.name.trim(), code: input.code.trim(), updatedAt: now }; state.membershipLevels![state.membershipLevels!.indexOf(current)] = updated; return updated } const value = { ...structuredClone(input), id: deps.nextId('membership-level'), enterpriseId: state.enterpriseId, name: input.name.trim(), code: input.code.trim(), createdAt: now, updatedAt: now }; state.membershipLevels!.push(value); return value }) }
  function deleteMembershipLevel(actor: CustomerActor, id: string): void { write(actor); repository.transact((state) => { ensure(state, deps); if (state.memberships!.some((item) => item.levelId === id)) throw new CustomerDomainError('REFERENCE_CONFLICT', '会员等级存在客户引用，不能删除'); if (state.membershipLevels!.find((item) => item.id === id)?.status === 'active') throw new CustomerDomainError('REFERENCE_CONFLICT', '启用等级不能直接删除'); state.membershipLevels = state.membershipLevels!.filter((item) => item.id !== id) }) }
  function assignMembership(actor: CustomerActor, customerId: string, levelId: string, source: 'manual' | 'automatic' = 'manual'): CustomerMembership { manage(actor); return repository.transact((state) => { ensure(state, deps); customer(state, customerId); const level = state.membershipLevels!.find((item) => item.id === levelId); if (!level) throw new CustomerDomainError('NOT_FOUND', '会员等级不存在'); if (level.status !== 'active') throw new CustomerDomainError('INACTIVE_REFERENCE', '停用等级不能新关联'); const current = state.memberships!.find((item) => item.customerId === customerId); const value = { id: current?.id ?? deps.nextId('membership'), enterpriseId: state.enterpriseId, customerId, levelId, assignedAt: current?.assignedAt ?? deps.now(), source, pendingReview: false, updatedAt: deps.now() }; if (current) state.memberships![state.memberships!.indexOf(current)] = value; else state.memberships!.push(value); return value }) }
  function listMemberships(actor: CustomerActor): CustomerMembership[] { const state = ready(); read(actor); return state.memberships ?? [] }

  function getPointAccount(state: CustomerFeatureState, customerId: string): PointAccount { const account = state.pointAccounts!.find((item) => item.customerId === customerId); if (!account) throw new CustomerDomainError('NOT_FOUND', '积分账户不存在'); return account }
  function listPointAccounts(actor: CustomerActor, keyword?: string): PageResult<PointAccount> { const state = ready(); read(actor); const items = (state.pointAccounts ?? []).filter((item) => { const c = customer(state, item.customerId); return !keyword || `${c.name}${c.code}`.toLocaleLowerCase().includes(keyword.trim().toLocaleLowerCase()) }).sort((a, b) => (b.lastChangedAt ?? '').localeCompare(a.lastChangedAt ?? '')); return page(items) }
  function listPointLedger(actor: CustomerActor, customerId: string): PointLedgerEntry[] { const state = ready(); read(actor); customer(state, customerId); return (state.pointLedger ?? []).filter((item) => item.customerId === customerId).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)) }
  function adjustPoints(actor: CustomerActor, customerId: string, type: PointAdjustmentType, points: number, reason: string, requestId: string): PointLedgerEntry { manage(actor); if (!Number.isInteger(points) || points <= 0 || !reason.trim() || !requestId.trim()) throw new CustomerDomainError('INVALID_TRANSITION', '积分调整必须填写正整数、原因和 requestId'); return repository.transact((state) => { ensure(state, deps); const existing = state.pointLedger!.find((item) => item.requestId === requestId); if (existing) return existing; const account = getPointAccount(state, customerId); const signed = type === 'increase' ? points : -points; if (signed < 0 && account.availablePoints < points) throw new CustomerDomainError('INVALID_TRANSITION', '扣减积分不能超过可用余额'); const now = deps.now(); account.availablePoints += signed; account.totalAdjusted += signed; account.lastChangedAt = now; const entry: PointLedgerEntry = { id: deps.nextId('point-ledger'), enterpriseId: state.enterpriseId, customerId, type: 'adjust', points: signed, balanceAfter: account.availablePoints, source: 'manual-adjustment', reason: reason.trim(), occurredAt: now, expiresAt: null, requestId: requestId.trim() }; state.pointLedger!.push(entry); return entry }) }
  function savePointsSettings(actor: CustomerActor, input: PointsSettingsDraft): PointsSettings { manage(actor); if (input.orderEarnPerYuan < 0 || input.dailyEarnCap < 0 || input.orderRedemptionCapPercent < 0 || input.orderRedemptionCapPercent > 100 || input.redemptionPointsPerYuan < 0) throw new CustomerDomainError('INVALID_TRANSITION', '积分设置比例或上限不合法'); if (input.expiryType === 'fixed-days' && (!input.expiryDays || input.expiryDays <= 0)) throw new CustomerDomainError('INVALID_TRANSITION', '固定天数有效期必须为正整数'); if (input.expiryType === 'yearly' && !input.yearlyExpiryDate) throw new CustomerDomainError('INVALID_TRANSITION', '按年度有效期必须填写清零日期'); if (input.mallEnabled && (!input.exchangePointsRatio || input.exchangePointsRatio <= 0)) throw new CustomerDomainError('INVALID_TRANSITION', '积分商城开启时兑换比例必填'); return repository.transact((state) => { ensure(state, deps); const value = { ...structuredClone(input), id: state.pointsSettings!.id, enterpriseId: state.enterpriseId, updatedAt: deps.now() }; state.pointsSettings = value; return value }) }
  function getPointsSettings(actor: CustomerActor): PointsSettings { const state = ready(); read(actor); return state.pointsSettings! }
  function expirePoints(actor: CustomerActor): number { manage(actor); return repository.transact((state) => { ensure(state, deps); const now = deps.now(); let count = 0; for (const entry of state.pointLedger!) { if (entry.expiresAt && entry.expiresAt < now && entry.points > 0 && !state.pointLedger!.some((item) => item.type === 'expire' && item.source === entry.id)) { const account = getPointAccount(state, entry.customerId); const expired = Math.min(account.availablePoints, entry.points); if (expired <= 0) continue; account.availablePoints -= expired; account.totalExpired += expired; account.lastChangedAt = now; state.pointLedger!.push({ id: deps.nextId('point-ledger'), enterpriseId: state.enterpriseId, customerId: entry.customerId, type: 'expire', points: -expired, balanceAfter: account.availablePoints, source: entry.id, reason: '受控时钟积分过期', occurredAt: now, expiresAt: null, requestId: null }); count += expired } } return count }) }

  function periodStatus(startsAt: string, endsAt: string, paused: boolean, now = deps.now()): MarketingStatus {
    if (paused) return 'paused'
    if (now < startsAt) return 'not-started'
    if (now > endsAt) return 'ended'
    return 'active'
  }
  function listCoupons(actor: CustomerActor): CouponTemplate[] { const state = ready(); read(actor); return (state.coupons ?? []).map((item) => ({ ...item, status: periodStatus(item.startsAt, item.endsAt, item.status === 'paused') })).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)) }
  function saveCoupon(actor: CustomerActor, input: CouponTemplateDraft, id?: string): CouponTemplate {
    manage(actor)
    if (!input.name.trim() || !input.code.trim()) throw new CustomerDomainError('INVALID_TRANSITION', '优惠券名称和编码不能为空')
    if (!Number.isInteger(input.issueQuantity) || input.issueQuantity < 1 || input.issueQuantity > 10000000) throw new CustomerDomainError('INVALID_TRANSITION', '发行数量必须为 1～10000000 的整数')
    if (input.startsAt >= input.endsAt) throw new CustomerDomainError('INVALID_TRANSITION', '优惠券结束时间必须晚于开始时间')
    if (input.type === 'percentage' && (input.discountPercent === null || input.discountPercent < 1 || input.discountPercent > 100)) throw new CustomerDomainError('INVALID_TRANSITION', '折扣券必须填写 1～100 的折扣')
    if (input.type !== 'percentage' && input.amountCents !== null && (!Number.isInteger(input.amountCents) || input.amountCents <= 0)) throw new CustomerDomainError('INVALID_TRANSITION', '优惠金额必须为正整数分')
    if (input.validityType === 'after-days' && (!input.validityDays || input.validityDays <= 0)) throw new CustomerDomainError('INVALID_TRANSITION', '领取后有效期必须为正整数')
    if (input.audienceKind === 'customer' && input.audienceIds.length > 100) throw new CustomerDomainError('INVALID_TRANSITION', '指定客户最多 100 个')
    return repository.transact((state) => { ensure(state, deps); if (state.coupons!.some((item) => item.id !== id && item.code.toLocaleLowerCase() === input.code.trim().toLocaleLowerCase())) throw new CustomerDomainError('DUPLICATE_CODE', '优惠券编码已存在'); const now = deps.now(); if (id) { const current = state.coupons!.find((item) => item.id === id); if (!current) throw new CustomerDomainError('NOT_FOUND', '优惠券不存在'); if (current.claimedQuantity > 0) throw new CustomerDomainError('REFERENCE_CONFLICT', '已领取优惠券不可编辑'); const updated = { ...current, ...structuredClone(input), code: input.code.trim(), name: input.name.trim(), updatedAt: now }; state.coupons![state.coupons!.indexOf(current)] = updated; return updated } const value: CouponTemplate = { ...structuredClone(input), id: deps.nextId('coupon'), enterpriseId: state.enterpriseId, claimedQuantity: 0, usedQuantity: 0, status: periodStatus(input.startsAt, input.endsAt, false, now), createdAt: now, updatedAt: now }; state.coupons!.push(value); return value })
  }
  function setCouponStatus(actor: CustomerActor, id: string, status: 'paused' | 'ended'): CouponTemplate { manage(actor); return repository.transact((state) => { ensure(state, deps); const item = state.coupons!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '优惠券不存在'); if (item.status === 'ended') throw new CustomerDomainError('INVALID_TRANSITION', '已结束优惠券不可再次操作'); item.status = status; item.updatedAt = deps.now(); return item }) }
  function listPromotions(actor: CustomerActor): Promotion[] { const state = ready(); read(actor); return (state.promotions ?? []).map((item) => ({ ...item, status: periodStatus(item.startsAt, item.endsAt, item.status === 'paused') })).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)) }
  function savePromotion(actor: CustomerActor, input: PromotionDraft, id?: string): Promotion {
    manage(actor)
    if (!input.name.trim() || !input.code.trim()) throw new CustomerDomainError('INVALID_TRANSITION', '促销名称和编码不能为空')
    if (input.startsAt >= input.endsAt) throw new CustomerDomainError('INVALID_TRANSITION', '促销结束时间必须晚于开始时间')
    if (input.type === 'limited-discount' && (!input.discountMode || (input.discountMode === 'rate' && (!input.discountPercent || input.discountPercent < 1 || input.discountPercent > 100)) || (input.discountMode === 'price' && (!input.discountPriceCents || input.discountPriceCents <= 0)))) throw new CustomerDomainError('INVALID_TRANSITION', '限时折扣规则不完整')
    return repository.transact((state) => { ensure(state, deps); if (state.promotions!.some((item) => item.id !== id && item.code.toLocaleLowerCase() === input.code.trim().toLocaleLowerCase())) throw new CustomerDomainError('DUPLICATE_CODE', '促销编码已存在'); const overlaps = state.promotions!.some((item) => item.id !== id && item.status !== 'ended' && item.scopeKind === 'product' && input.scopeKind === 'product' && item.scopeIds.some((sku) => input.scopeIds.includes(sku)) && item.startsAt < input.endsAt && input.startsAt < item.endsAt); if (overlaps) throw new CustomerDomainError('REFERENCE_CONFLICT', '同一商品存在重叠有效促销'); const now = deps.now(); if (id) { const current = state.promotions!.find((item) => item.id === id); if (!current) throw new CustomerDomainError('NOT_FOUND', '促销不存在'); const updated = { ...current, ...structuredClone(input), code: input.code.trim(), name: input.name.trim(), updatedAt: now }; state.promotions![state.promotions!.indexOf(current)] = updated; return updated } const value: Promotion = { ...structuredClone(input), id: deps.nextId('promotion'), enterpriseId: state.enterpriseId, orderCount: null, orderAmountCents: null, status: periodStatus(input.startsAt, input.endsAt, false, now), createdAt: now, updatedAt: now }; state.promotions!.push(value); return value })
  }
  function setPromotionStatus(actor: CustomerActor, id: string, status: 'paused' | 'ended'): Promotion { manage(actor); return repository.transact((state) => { ensure(state, deps); const item = state.promotions!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '促销不存在'); if (item.status === 'ended') throw new CustomerDomainError('INVALID_TRANSITION', '已结束促销不可再次操作'); item.status = status; item.updatedAt = deps.now(); return item }) }
  function listVoucherCampaigns(actor: CustomerActor): VoucherCampaign[] { const state = ready(); read(actor); return (state.voucherCampaigns ?? []).slice().sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)) }
  function createVoucherCampaign(actor: CustomerActor, input: VoucherCampaignDraft): VoucherCampaign { write(actor); if (!input.name.trim() || !input.couponId || !input.channels.length || input.quantityPerCustomer < 1 || input.quantityPerCustomer > 10 || input.startsAt >= input.endsAt) throw new CustomerDomainError('INVALID_TRANSITION', '易发券活动字段不完整'); return repository.transact((state) => { ensure(state, deps); if (!state.coupons!.some((item) => item.id === input.couponId)) throw new CustomerDomainError('NOT_FOUND', '关联优惠券不存在'); const now = deps.now(); const value: VoucherCampaign = { ...structuredClone(input), id: deps.nextId('voucher-campaign'), enterpriseId: state.enterpriseId, issuedCount: 0, claimedCount: 0, usedCount: 0, status: now <= input.endsAt ? 'active' : 'ended', createdAt: now, updatedAt: now }; state.voucherCampaigns!.push(value); return value }) }
  function issueVoucherCampaign(actor: CustomerActor, campaignId: string): number { write(actor); return repository.transact((state) => { ensure(state, deps); const campaign = state.voucherCampaigns!.find((item) => item.id === campaignId); if (!campaign) throw new CustomerDomainError('NOT_FOUND', '易发券活动不存在'); if (campaign.status === 'ended' || campaign.endsAt < deps.now()) throw new CustomerDomainError('INVALID_TRANSITION', '易发券活动已结束'); const customers = campaign.audienceKind === 'customer' ? state.customers.filter((item) => campaign.audienceIds.includes(item.id)) : state.customers; const coupon = state.coupons!.find((item) => item.id === campaign.couponId)!; const now = deps.now(); let count = 0; for (const item of customers) { for (let i = 0; i < campaign.quantityPerCustomer; i += 1) { if (coupon.claimedQuantity >= coupon.issueQuantity) throw new CustomerDomainError('INVALID_TRANSITION', '优惠券发行数量已用尽'); const issue: VoucherIssue = { id: deps.nextId('voucher-issue'), enterpriseId: state.enterpriseId, campaignId, couponId: coupon.id, customerId: item.id, channels: [...campaign.channels], issuedAt: now, status: 'issued' }; state.voucherIssues!.push(issue); state.couponInstances!.push({ id: deps.nextId('coupon-instance'), enterpriseId: state.enterpriseId, templateId: coupon.id, customerId: item.id, issuedAt: now, expiresAt: coupon.validityType === 'after-days' ? new Date(Date.parse(now) + (coupon.validityDays ?? 1) * 86400000).toISOString() : coupon.endsAt, usedAt: null, orderId: null, status: 'unused' }); coupon.claimedQuantity += 1; campaign.issuedCount += 1; count += 1 } } campaign.updatedAt = now; return count }) }
  function listVoucherIssues(actor: CustomerActor, campaignId?: string): VoucherIssue[] { const state = ready(); read(actor); return (state.voucherIssues ?? []).filter((item) => !campaignId || item.campaignId === campaignId).sort((a, b) => b.issuedAt.localeCompare(a.issuedAt)) }
  function listMarketingArticles(actor: CustomerActor): MarketingArticle[] { const state = ready(); read(actor); return (state.marketingArticles ?? []).slice().sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)) }
  function saveMarketingArticle(actor: CustomerActor, input: MarketingArticleDraft, id?: string): MarketingArticle { manage(actor); if (!input.title.trim() || input.title.trim().length > 50 || !input.content.trim() || !input.channels.length || (input.publishMode === 'publish-scheduled' && (!input.scheduledAt || input.scheduledAt <= deps.now()))) throw new CustomerDomainError('INVALID_TRANSITION', '文章字段或定时发布时间不合法'); return repository.transact((state) => { ensure(state, deps); const now = deps.now(); if (id) { const current = state.marketingArticles!.find((item) => item.id === id); if (!current) throw new CustomerDomainError('NOT_FOUND', '文章不存在'); if (current.status === 'published') throw new CustomerDomainError('REFERENCE_CONFLICT', '已发布文章只能下架后重新编辑'); const updated = { ...current, ...structuredClone(input), title: input.title.trim(), updatedAt: now }; state.marketingArticles![state.marketingArticles!.indexOf(current)] = updated; return updated } const value: MarketingArticle = { ...structuredClone(input), id: deps.nextId('marketing-article'), enterpriseId: state.enterpriseId, publishedAt: null, viewCount: null, acquiredCustomerCount: null, shareCount: null, status: input.publishMode === 'publish-now' ? 'published' : 'draft', createdAt: now, updatedAt: now }; if (value.status === 'published') value.publishedAt = now; state.marketingArticles!.push(value); return value }) }
  function setMarketingArticleStatus(actor: CustomerActor, id: string, status: 'published' | 'unpublished'): MarketingArticle { manage(actor); return repository.transact((state) => { ensure(state, deps); const item = state.marketingArticles!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '文章不存在'); item.status = status; item.publishedAt = status === 'published' ? deps.now() : item.publishedAt; item.updatedAt = deps.now(); return item }) }
  function listMarketingAnalysis(actor: CustomerActor): MarketingAnalysisResult { const state = ready(); read(actor); const coupons = state.coupons ?? []; const promotions = state.promotions ?? []; const issued = (state.couponInstances ?? []).length; const used = (state.couponInstances ?? []).filter((item) => item.usedAt).length; const points = state.pointAccounts ?? []; const totalEarned = points.reduce((sum, item) => sum + item.totalEarned, 0); const totalUsed = points.reduce((sum, item) => sum + item.totalRedeemed, 0); const metric = (value: number | null, unavailableReason: string | null = null) => ({ value, unavailableReason }); return { couponClaimRate: metric(coupons.reduce((sum, item) => sum + item.claimedQuantity, 0) ? coupons.reduce((sum, item) => sum + item.claimedQuantity, 0) / Math.max(1, coupons.reduce((sum, item) => sum + item.issueQuantity, 0)) : 0), couponUseRate: metric(issued ? used / issued : 0), promotionOrderCount: metric(null, '订单 provider 未接入'), promotionOrderAmountCents: metric(null, '订单 provider 未接入'), acquisitionConversionRate: metric(null, '拉新归因 provider 未接入'), pointsUseRate: metric(totalEarned ? totalUsed / totalEarned : 0), activities: [...coupons.map((item) => ({ id: item.id, name: item.name, type: 'coupon' as const, customerCount: metric(item.claimedQuantity), productCount: metric(null, '商品范围 provider 未接入'), orderAmountCents: metric(null, '订单 provider 未接入'), orderCount: metric(null, '订单 provider 未接入'), averageOrderCents: metric(null, '订单 provider 未接入'), grossMarginPercent: metric(null, '财务 provider 未接入') })), ...promotions.map((item) => ({ id: item.id, name: item.name, type: 'promotion' as const, customerCount: metric(null, '客户触达 provider 未接入'), productCount: metric(item.scopeIds.length || null), orderAmountCents: metric(null, '订单 provider 未接入'), orderCount: metric(null, '订单 provider 未接入'), averageOrderCents: metric(null, '订单 provider 未接入'), grossMarginPercent: metric(null, '财务 provider 未接入') }))], ai: { activityCount: metric(null, 'AI provider 未接入'), customerCount: metric(null, 'AI provider 未接入'), productCount: metric(null, 'AI provider 未接入'), totalCostCents: metric(null, 'AI provider 未接入'), activities: [] }, referral: [{ referrer: null, acquisitionCount: metric(null, '拉新归因 provider 未接入'), newCustomerAmountCents: metric(null, '拉新归因 provider 未接入'), commissionCents: metric(null, '提成结算 provider 未接入'), status: null }] } }

  function listChannelState(actor: CustomerActor): CustomerChannelState { const state = ready(); read(actor); return structuredClone(state.channelState ?? createChannelSeed(state.enterpriseId, deps.now())) }
  function saveWecomSyncSettings(actor: CustomerActor, input: Omit<WecomSyncSettings, 'updatedAt'>): WecomSyncSettings { write(actor); return repository.transact((state) => { ensure(state, deps); if (!input.frequency || !input.scope.length) throw new CustomerDomainError('INVALID_TRANSITION', '企微同步频率和范围不能为空'); state.channelState!.wecomSyncSettings = { ...structuredClone(input), updatedAt: deps.now() }; return state.channelState!.wecomSyncSettings }) }
  function saveWecomBroadcast(actor: CustomerActor, input: Omit<WecomBroadcast, 'id' | 'enterpriseId' | 'createdAt' | 'updatedAt' | 'status'>): WecomBroadcast { write(actor); if (!input.title.trim() || !input.employeeIds.length || !input.content.trim() || (input.sendMode === 'scheduled' && (!input.scheduledAt || input.scheduledAt <= deps.now()))) throw new CustomerDomainError('INVALID_TRANSITION', '企微群发字段不完整'); return repository.transact((state) => { ensure(state, deps); const now = deps.now(); const item: WecomBroadcast = { ...structuredClone(input), id: deps.nextId('wecom-broadcast'), enterpriseId: state.enterpriseId, status: input.sendMode === 'scheduled' ? 'scheduled' : 'completed', createdAt: now, updatedAt: now }; state.channelState!.wecomBroadcasts!.push(item); return item }) }
  function setWecomBroadcastStatus(actor: CustomerActor, id: string, status: 'recalled' | 'completed'): WecomBroadcast { write(actor); return repository.transact((state) => { ensure(state, deps); const item = state.channelState!.wecomBroadcasts!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '企微群发不存在'); if (item.status === 'recalled') throw new CustomerDomainError('INVALID_TRANSITION', '已撤回群发不可再次操作'); item.status = status; item.updatedAt = deps.now(); return item }) }
  function saveMallSettings(actor: CustomerActor, input: Omit<MallSettings, 'id' | 'enterpriseId' | 'updatedAt'>): MallSettings { manage(actor); if (!input.name.trim() || input.paymentTimeoutMinutes < 1 || input.minimumPaymentCents < 0) throw new CustomerDomainError('INVALID_TRANSITION', '商城设置不合法'); return repository.transact((state) => { ensure(state, deps); const item: MallSettings = { ...structuredClone(input), id: state.channelState!.mallSettings!.id, enterpriseId: state.enterpriseId, updatedAt: deps.now() }; state.channelState!.mallSettings = item; return item }) }
  function saveMallDesign(actor: CustomerActor, input: Omit<MallDesign, 'id' | 'enterpriseId' | 'updatedAt'>): MallDesign { manage(actor); return repository.transact((state) => { ensure(state, deps); const item: MallDesign = { ...structuredClone(input), id: state.channelState!.mallDesigns?.[0]?.id ?? deps.nextId('mall-design'), enterpriseId: state.enterpriseId, updatedAt: deps.now() }; state.channelState!.mallDesigns = [item]; return item }) }
  function setMallExtension(actor: CustomerActor, id: string, enabled: boolean): MallExtension { manage(actor); return repository.transact((state) => { ensure(state, deps); const item = state.channelState!.mallExtensions!.find((value) => value.id === id); if (!item) throw new CustomerDomainError('NOT_FOUND', '商城扩展不存在'); item.enabled = enabled; item.updatedAt = deps.now(); return item }) }
  function saveMallCustomer(actor: CustomerActor, input: Omit<MallCustomerAccount, 'id' | 'enterpriseId' | 'registeredAt' | 'lastLoginAt' | 'loginCount' | 'orderCount' | 'consumptionAmountCents' | 'updatedAt'> & { password?: string }): MallCustomerAccount { manage(actor); if (!input.name.trim() || !input.account.trim() || !input.phone.trim()) throw new CustomerDomainError('INVALID_TRANSITION', '商城客户字段不完整'); return repository.transact((state) => { ensure(state, deps); const now = deps.now(); const { password: _password, ...safe } = input; const item: MallCustomerAccount = { ...structuredClone(safe), id: deps.nextId('mall-customer'), enterpriseId: state.enterpriseId, registeredAt: now, lastLoginAt: null, loginCount: 0, orderCount: null, consumptionAmountCents: null, updatedAt: now }; state.channelState!.mallCustomers!.push(item); return item }) }
  function saveMallEmployee(actor: CustomerActor, input: Omit<MallEmployeeAccount, 'id' | 'enterpriseId' | 'createdAt' | 'lastLoginAt' | 'updatedAt'> & { password?: string }): MallEmployeeAccount { manage(actor); if (!input.name.trim() || !input.customerId || !input.phone.trim() || !input.permissions.length) throw new CustomerDomainError('INVALID_TRANSITION', '商城员工字段不完整'); return repository.transact((state) => { ensure(state, deps); const now = deps.now(); const { password: _password, ...safe } = input; const item: MallEmployeeAccount = { ...structuredClone(safe), id: deps.nextId('mall-employee'), enterpriseId: state.enterpriseId, createdAt: now, lastLoginAt: null, updatedAt: now }; state.channelState!.mallEmployees!.push(item); return item }) }
  function saveMallAd(actor: CustomerActor, input: Omit<MallAd, 'id' | 'enterpriseId' | 'updatedAt'>): MallAd { manage(actor); if (!input.title.trim() || input.startsAt >= input.endsAt) throw new CustomerDomainError('INVALID_TRANSITION', '商城广告字段不合法'); return repository.transact((state) => { ensure(state, deps); const item: MallAd = { ...structuredClone(input), id: deps.nextId('mall-ad'), enterpriseId: state.enterpriseId, updatedAt: deps.now() }; state.channelState!.mallAds!.push(item); return item }) }
  function saveMallPopup(actor: CustomerActor, input: Omit<MallPopup, 'id' | 'enterpriseId' | 'updatedAt'>): MallPopup { manage(actor); if (!input.title.trim() || !input.channels.length || input.startsAt >= input.endsAt) throw new CustomerDomainError('INVALID_TRANSITION', '商城弹窗字段不合法'); return repository.transact((state) => { ensure(state, deps); const item: MallPopup = { ...structuredClone(input), id: deps.nextId('mall-popup'), enterpriseId: state.enterpriseId, updatedAt: deps.now() }; state.channelState!.mallPopups!.push(item); return item }) }
  function saveMallMessage(actor: CustomerActor, input: Omit<MallMessage, 'id' | 'enterpriseId' | 'readCount' | 'updatedAt'>): MallMessage { manage(actor); if (!input.title.trim() || !input.content.trim() || (input.sendMode === 'scheduled' && (!input.scheduledAt || input.scheduledAt <= deps.now()))) throw new CustomerDomainError('INVALID_TRANSITION', '商城消息字段不完整'); return repository.transact((state) => { ensure(state, deps); const item: MallMessage = { ...structuredClone(input), id: deps.nextId('mall-message'), enterpriseId: state.enterpriseId, readCount: 0, updatedAt: deps.now() }; state.channelState!.mallMessages!.push(item); return item }) }

  return { listOpportunities, createOpportunity, updateOpportunity, advanceOpportunity, deleteOpportunity, listFrequentProducts, addFrequentProduct, removeFrequentProduct, quickOrder, mapMarkers, listPublicSea, getPublicSeaRule, savePublicSeaRule, claimPublicSea, assignPublicSea, reclaimPublicSea, listVisits, createVisit, checkInVisit, completeVisit, listRoutes, createRoute, listVisitPlans, createVisitPlan, updateVisitPlanStatus, listMembershipLevels, saveMembershipLevel, deleteMembershipLevel, assignMembership, listMemberships, listPointAccounts, listPointLedger, adjustPoints, getPointsSettings, savePointsSettings, expirePoints, listCoupons, saveCoupon, pauseCoupon: (actor: CustomerActor, id: string) => setCouponStatus(actor, id, 'paused'), endCoupon: (actor: CustomerActor, id: string) => setCouponStatus(actor, id, 'ended'), listPromotions, savePromotion, pausePromotion: (actor: CustomerActor, id: string) => setPromotionStatus(actor, id, 'paused'), endPromotion: (actor: CustomerActor, id: string) => setPromotionStatus(actor, id, 'ended'), listVoucherCampaigns, createVoucherCampaign, issueVoucherCampaign, listVoucherIssues, listMarketingArticles, saveMarketingArticle, publishMarketingArticle: (actor: CustomerActor, id: string) => setMarketingArticleStatus(actor, id, 'published'), unpublishMarketingArticle: (actor: CustomerActor, id: string) => setMarketingArticleStatus(actor, id, 'unpublished'), listMarketingAnalysis, listChannelState, saveWecomSyncSettings, saveWecomBroadcast, setWecomBroadcastStatus, saveMallSettings, saveMallDesign, setMallExtension, saveMallCustomer, saveMallEmployee, saveMallAd, saveMallPopup, saveMallMessage }
}
