import { describe,expect,it } from 'vitest'
import { createInventoryCatalogProvider,inventoryBaseline } from '../../../../mock/handlers/inventory-handler'
import { InMemoryInventoryRepository } from '../repositories/inventory-repository'
import { createInventoryService,InventoryDomainError } from './inventory-service'

const actor={role:'super-admin' as const,actorId:'admin-demo'}
function setup(){const repository=new InMemoryInventoryRepository(inventoryBaseline);let sequence=1;const service=createInventoryService({repository,catalog:createInventoryCatalogProvider(),now:()=> '2026-08-10T10:00:00+08:00',nextId:(kind)=>`${kind}-fulfillment-${sequence++}`});return{repository,service}}

describe('inventory fulfillment commands',()=>{
  it('allocates a multi-line request atomically and returns immutable movement references',()=>{const {repository,service}=setup();const before=repository.read().balances.reduce((sum,item)=>sum+item.quantityMilli,0);const result=service.confirmOutboundBatch(actor,{requestId:'batch-1',sourceType:'sales-outbound',sourceId:'outbound-1',operatorId:actor.actorId,occurredAt:'2026-08-10T10:00:00+08:00',warehouseId:'warehouse-main',lines:[{referenceId:'line-a',skuId:'sku-1',quantityMilli:3000},{referenceId:'line-b',skuId:'sku-1',quantityMilli:4000}]});expect(result.reduce((sum,item)=>sum+item.quantityMilli,0)).toBe(7000);expect(new Set(result.map((item)=>item.referenceId))).toEqual(new Set(['line-a','line-b']));expect(result.every((item)=>item.movementId)).toBe(true);expect(repository.read().balances.reduce((sum,item)=>sum+item.quantityMilli,0)).toBe(before-7000)})
  it('does not leave the first line deducted when a later line is insufficient',()=>{const {repository,service}=setup();const before=repository.read();expect(()=>service.confirmOutboundBatch(actor,{requestId:'batch-fail',sourceType:'sales-outbound',sourceId:'outbound-fail',operatorId:actor.actorId,occurredAt:'2026-08-10T10:00:00+08:00',warehouseId:'warehouse-main',lines:[{referenceId:'line-a',skuId:'sku-1',quantityMilli:1000},{referenceId:'line-b',skuId:'sku-1',quantityMilli:999999}]})).toThrow(InventoryDomainError);expect(repository.read()).toEqual(before)})
  it('reverses the exact original balance, batch and location once',()=>{const {repository,service}=setup();const before=repository.read();const allocations=service.confirmOutboundBatch(actor,{requestId:'batch-reverse',sourceType:'sales-outbound',sourceId:'outbound-reverse',operatorId:actor.actorId,occurredAt:'2026-08-10T10:00:00+08:00',warehouseId:'warehouse-main',lines:[{referenceId:'line-a',skuId:'sku-1',quantityMilli:6000}]});const movementsBefore=repository.read().movements.length;service.reverseOutbound(actor,{requestId:'reverse-1',sourceType:'sales-outbound-void',sourceId:'outbound-reverse',operatorId:actor.actorId,occurredAt:'2026-08-10T10:00:00+08:00',warehouseId:'warehouse-main',allocations:allocations.map((item)=>({movementId:item.movementId!,balanceId:item.balanceId,locationId:item.locationId,batchId:item.batchId,skuId:item.skuId,quantityMilli:item.quantityMilli}))});expect(repository.read().balances.map((item)=>({id:item.id,warehouseId:item.warehouseId,locationId:item.locationId,batchId:item.batchId,skuId:item.skuId,quantityMilli:item.quantityMilli}))).toEqual(before.balances.map((item)=>({id:item.id,warehouseId:item.warehouseId,locationId:item.locationId,batchId:item.batchId,skuId:item.skuId,quantityMilli:item.quantityMilli})));const replay=service.reverseOutbound(actor,{requestId:'reverse-1',sourceType:'sales-outbound-void',sourceId:'outbound-reverse',operatorId:actor.actorId,occurredAt:'2026-08-10T10:00:00+08:00',warehouseId:'warehouse-main',allocations:allocations.map((item)=>({movementId:item.movementId!,balanceId:item.balanceId,locationId:item.locationId,batchId:item.batchId,skuId:item.skuId,quantityMilli:item.quantityMilli}))});expect(replay.length).toBeGreaterThan(0);expect(repository.read().movements.length).toBeGreaterThan(movementsBefore)})
})
