import type { InventoryRepository } from '../repositories/inventory-repository'
import { InventoryValidationError } from '../schemas/inventory-schema'
import type {
  DeliveryRoute, DeliveryRouteDraft, DeliveryStaffProvider, DeliveryTask, DeliveryTaskDraft, DeliveryVehicle,
  DeliveryVehicleDraft, InventoryActor, InventoryDocumentPage, InventoryFeatureState, PickingDifference,
  PickingLabel, PickingLabelDraft, PickingListQuery, PickingOrderCoordinator, PickingOrderProviderResult, PickingOrderSnapshot,
  PickingTask, PickingWave, PickingWaveDraft, PendingPickingOrderRow,
} from '../types'

export type InventoryPickingErrorCode = 'PERMISSION_DENIED' | 'NOT_FOUND' | 'DUPLICATE' | 'INVALID_STATE' | 'CONFLICT' | 'DATA_PROVIDER_UNAVAILABLE'
export class InventoryPickingError extends Error {
  constructor(readonly code: InventoryPickingErrorCode, message: string) { super(message); this.name = 'InventoryPickingError' }
}

export interface InventoryPickingDeliveryDependencies {
  repository: InventoryRepository
  orderCoordinator?: PickingOrderCoordinator
  staffProvider?: DeliveryStaffProvider
  now: () => string
  nextId: (kind: 'log') => string
}

const readRoles = new Set(['super-admin', 'warehouse', 'sales-supervisor'])
const writeRoles = new Set(['super-admin', 'warehouse'])
const normalize = (value: string) => value.trim().toLocaleLowerCase()
const datePart = (value: string) => value.slice(0, 10)
const positiveMilli = (value: number, path: string) => { if (!Number.isSafeInteger(value) || value <= 0) throw new InventoryValidationError([{ path, message: '必须是正整数毫单位' }]) }
const required = (value: string | null | undefined, max: number, path: string) => {
  const result = value?.trim() ?? ''; if (!result || result.length > max) throw new InventoryValidationError([{ path, message: `必须为 1～${max} 个字符` }]); return result
}
const optional = (value: string | null | undefined, max: number, path: string) => {
  const result = value?.trim() ?? ''; if (result.length > max) throw new InventoryValidationError([{ path, message: `不能超过 ${max} 个字符` }]); return result || null
}

export function createInventoryPickingDeliveryService(deps: InventoryPickingDeliveryDependencies) {
  const assertRead = (actor: InventoryActor) => { if (!readRoles.has(actor.role)) throw new InventoryPickingError('PERMISSION_DENIED', '当前角色不可访问分拣配送') }
  const assertWrite = (actor: InventoryActor) => { if (!writeRoles.has(actor.role)) throw new InventoryPickingError('PERMISSION_DENIED', '当前角色不可修改分拣配送') }
  const arrays = (state: InventoryFeatureState) => {
    state.pickingTasks ??= []; state.pickingWaves ??= []; state.pickingDifferences ??= []
    state.deliveryRoutes ??= []; state.deliveryVehicles ??= []; state.deliveryTasks ??= []
    state.pickingLabels ??= []; state.pickingRequests ??= []
  }
  const page = <T>(items: T[], query: PickingListQuery = {}): InventoryDocumentPage<T> => {
    const current = Math.max(1, query.page ?? 1); const pageSize = query.pageSize ?? 30
    return { items: structuredClone(items.slice((current - 1) * pageSize, current * pageSize)), total: items.length, page: current, pageSize }
  }
  const nextCode = (state: InventoryFeatureState, prefix: string, rows: Array<{ code: string }>) => {
    const day = datePart(deps.now()).replaceAll('-', '').slice(2); const count = rows.filter((item) => item.code.startsWith(`${prefix}${day}`)).length + 1
    return `${prefix}${day}-${String(count).padStart(5, '0')}`
  }
  const provider = () => { if (!deps.orderCoordinator) throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', '订单协调接口未接入'); return deps.orderCoordinator }
  const providerItems = (kind: 'picking' | 'delivery') => {
    const result = kind === 'picking' ? provider().listPickingOrders() : provider().listDeliveryOrders()
    if (result.state !== 'available') throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', result.message ?? '订单来源不可用')
    return result.items
  }
  const taskById = (state: InventoryFeatureState, id: string) => { const value = state.pickingTasks?.find((item) => item.id === id); if (!value) throw new InventoryPickingError('NOT_FOUND', '订单分拣单不存在'); return value }
  const waveById = (state: InventoryFeatureState, id: string) => { const value = state.pickingWaves?.find((item) => item.id === id); if (!value) throw new InventoryPickingError('NOT_FOUND', '波次不存在'); return value }
  const routeById = (state: InventoryFeatureState, id: string) => { const value = state.deliveryRoutes?.find((item) => item.id === id); if (!value) throw new InventoryPickingError('NOT_FOUND', '配送线路不存在'); return value }
  const vehicleById = (state: InventoryFeatureState, id: string) => { const value = state.deliveryVehicles?.find((item) => item.id === id); if (!value) throw new InventoryPickingError('NOT_FOUND', '车辆不存在'); return value }
  const deliveryById = (state: InventoryFeatureState, id: string) => { const value = state.deliveryTasks?.find((item) => item.id === id); if (!value) throw new InventoryPickingError('NOT_FOUND', '配送任务不存在'); return value }
  const activeOwner = (state: InventoryFeatureState, orderId: string) => {
    const task = state.pickingTasks?.find((item) => item.orderSnapshot.orderId === orderId && ['pending', 'picking'].includes(item.status))
    if (task) return { type: 'task' as const, id: task.id, status: task.status }
    const wave = state.pickingWaves?.find((item) => item.orders.some((order) => order.orderId === orderId) && ['pending', 'picking'].includes(item.status))
    return wave ? { type: 'wave' as const, id: wave.id, status: wave.status } : null
  }
  const suggestedLocations = (state: InventoryFeatureState, order: PickingOrderSnapshot, skuId: string) => {
    const batchMap = new Map(state.batches.map((item) => [item.id, item]))
    return state.balances.filter((item) => item.warehouseId === order.warehouseId && item.skuId === skuId && item.quantityMilli > 0)
      .sort((a, b) => (batchMap.get(a.batchId)?.productionDate ?? '9999').localeCompare(batchMap.get(b.batchId)?.productionDate ?? '9999') || a.id.localeCompare(b.id))
      .map((item) => item.locationId).filter((id, index, all) => all.indexOf(id) === index)
  }
  const matches = (query: PickingListQuery, value: { status: string; at: string; keyword: string; warehouseId?: string }) =>
    (!query.status || value.status === query.status) && (!query.fromDate || datePart(value.at) >= query.fromDate) && (!query.toDate || datePart(value.at) <= query.toDate) && (!query.warehouseId || value.warehouseId === query.warehouseId) && (!query.keyword || normalize(value.keyword).includes(normalize(query.keyword)))

  function listPendingPickingOrders(actor: InventoryActor, query: PickingListQuery = {}): InventoryDocumentPage<PendingPickingOrderRow> {
    assertRead(actor); const state = deps.repository.read(); arrays(state)
    const rows = providerItems('picking').map((order): PendingPickingOrderRow => {
      const owner = activeOwner(state, order.orderId)
      const completed = state.pickingTasks!.find((item) => item.orderSnapshot.orderId === order.orderId && item.status === 'completed' && !item.outboundId) ?? state.pickingWaves!.find((item) => item.orders.some((entry) => entry.orderId === order.orderId) && item.status === 'completed' && !item.outboundResults.some((entry) => entry.orderId === order.orderId))
      return { order, pickingStatus: owner ? (owner.status === 'pending' ? 'pending' : 'picking') : completed ? 'picked' : 'pending', ownerType: owner?.type ?? null, ownerId: owner?.id ?? null }
    }).filter((row) => matches(query, { status: row.pickingStatus, at: row.order.requestedDeliveryAt, keyword: `${row.order.orderNo} ${row.order.customerName} ${row.order.lines.map((line) => `${line.skuCode} ${line.productName}`).join(' ')}`, warehouseId: row.order.warehouseId }))
      .sort((a, b) => a.order.requestedDeliveryAt.localeCompare(b.order.requestedDeliveryAt) || a.order.orderNo.localeCompare(b.order.orderNo))
    return page(rows, query)
  }

  function createPickingTask(actor: InventoryActor, orderId: string): PickingTask {
    assertWrite(actor); const order = provider().getPickingOrder(orderId); if (!order) throw new InventoryPickingError('INVALID_STATE', '订单不再满足待分拣条件')
    return deps.repository.transact((state) => {
      arrays(state); if (activeOwner(state, orderId)) throw new InventoryPickingError('DUPLICATE', '订单已有活动分拣任务或波次')
      const value: PickingTask = { id: deps.nextId('log'), enterpriseId: state.enterpriseId, code: nextCode(state, 'FJD', state.pickingTasks!), orderSnapshot: structuredClone(order), warehouseId: order.warehouseId, status: 'pending', pickerId: null,
        lines: order.lines.map((line) => ({ id: deps.nextId('log'), orderLineId: line.orderLineId, skuId: line.skuId, skuCode: line.skuCode, productName: line.productName, specification: line.specification, unitName: line.unitName, conversionRateMilli: line.conversionRateMilli, expectedQuantityMilli: line.remainingQuantityMilli, actualQuantityMilli: null, suggestedLocationIds: suggestedLocations(state, order, line.skuId), status: 'pending' })),
        version: 1, createdAt: deps.now(), updatedAt: deps.now(), completedAt: null, cancelledAt: null, outboundId: null, orderDifferenceId: null }
      state.pickingTasks!.push(value); return value
    })
  }
  function listPickingTasks(actor: InventoryActor, query: PickingListQuery = {}) { assertRead(actor); const rows = (deps.repository.read().pickingTasks ?? []).filter((item) => matches(query, { status: item.status, at: item.completedAt ?? item.createdAt, keyword: `${item.code} ${item.orderSnapshot.orderNo} ${item.orderSnapshot.customerName}`, warehouseId: item.warehouseId })).sort((a, b) => b.createdAt.localeCompare(a.createdAt) || b.code.localeCompare(a.code)); return page(rows, query) }
  function startPickingTask(actor: InventoryActor, id: string, expectedVersion: number, pickerId: string): PickingTask {
    assertWrite(actor); const staff = deps.staffProvider?.listStaff().find((item) => item.id === pickerId); if (!staff) throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', '分拣人员不存在或员工来源不可用')
    return deps.repository.transact((state) => { arrays(state); const value = taskById(state, id); if (value.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '分拣单版本已变化'); if (value.status !== 'pending') throw new InventoryPickingError('INVALID_STATE', '只有待分拣任务可开始'); const current = provider().getPickingOrder(value.orderSnapshot.orderId); if (!current || current.updatedAt !== value.orderSnapshot.updatedAt) throw new InventoryPickingError('CONFLICT', '来源订单已变化，请重新创建分拣任务'); value.status = 'picking'; value.pickerId = staff.id; value.version++; value.updatedAt = deps.now(); return value })
  }
  function cancelPickingTask(actor: InventoryActor, id: string, expectedVersion: number): PickingTask { assertWrite(actor); return deps.repository.transact((state) => { arrays(state); const value = taskById(state, id); if (value.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '分拣单版本已变化'); if (value.status !== 'pending') throw new InventoryPickingError('INVALID_STATE', '只有待分拣任务可取消'); value.status = 'cancelled'; value.cancelledAt = deps.now(); value.updatedAt = deps.now(); value.version++; return value }) }
  function addDifference(state: InventoryFeatureState, ownerType: 'task' | 'wave', ownerId: string, order: PickingOrderSnapshot, lines: PickingDifference['lines'], reason: string) {
    const value: PickingDifference = { id: deps.nextId('log'), enterpriseId: state.enterpriseId, code: nextCode(state, 'FJCY', state.pickingDifferences!), ownerType, ownerId, orderId: order.orderId, lines, reason: required(reason, 200, 'reason'), status: 'pending', orderDifferenceId: null, createdAt: deps.now(), resolvedAt: null, version: 1 }
    state.pickingDifferences!.push(value); return value
  }
  function submitPickingTask(actor: InventoryActor, id: string, expectedVersion: number, actuals: Array<{ lineId: string; actualQuantityMilli: number }>, reason = ''): PickingTask {
    assertWrite(actor)
    return deps.repository.transact((state) => { arrays(state); const value = taskById(state, id); if (value.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '分拣单版本已变化'); if (value.status !== 'picking') throw new InventoryPickingError('INVALID_STATE', '只有分拣中任务可提交'); if (actuals.length !== value.lines.length || new Set(actuals.map((item) => item.lineId)).size !== value.lines.length) throw new InventoryPickingError('INVALID_STATE', '必须录入全部分拣行且不能重复'); const differences: PickingDifference['lines'] = []
      for (const line of value.lines) { const input = actuals.find((item) => item.lineId === line.id); if (!input || !Number.isSafeInteger(input.actualQuantityMilli) || input.actualQuantityMilli < 0 || input.actualQuantityMilli > line.expectedQuantityMilli) throw new InventoryValidationError([{ path: `lines.${line.id}`, message: '实拣数量必须为不超过应拣数量的非负整数毫单位' }]); line.actualQuantityMilli = input.actualQuantityMilli; line.status = input.actualQuantityMilli === line.expectedQuantityMilli ? 'picked' : 'difference'; if (line.status === 'difference') differences.push({ orderLineId: line.orderLineId, skuId: line.skuId, expectedQuantityMilli: line.expectedQuantityMilli, actualQuantityMilli: input.actualQuantityMilli, differenceQuantityMilli: input.actualQuantityMilli - line.expectedQuantityMilli }) }
      if (differences.length) addDifference(state, 'task', value.id, value.orderSnapshot, differences, reason); else { value.status = 'completed'; value.completedAt = deps.now() }
      value.updatedAt = deps.now(); value.version++; return value })
  }
  function listPickingDifferences(actor: InventoryActor, query: PickingListQuery = {}) { assertRead(actor); const rows = (deps.repository.read().pickingDifferences ?? []).filter((item) => matches(query, { status: item.status, at: item.createdAt, keyword: `${item.code} ${item.orderId}` })).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return page(rows, query) }
  function resolvePickingDifference(actor: InventoryActor, id: string, expectedVersion: number, outcome: 'continue-picking' | 'accepted-short'): PickingDifference {
    assertWrite(actor); return deps.repository.transact((state) => { arrays(state); const value = state.pickingDifferences!.find((item) => item.id === id); if (!value) throw new InventoryPickingError('NOT_FOUND', '分拣差异不存在'); if (value.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '差异版本已变化'); if (value.status !== 'pending') throw new InventoryPickingError('INVALID_STATE', '差异已经处理'); value.status = outcome; value.resolvedAt = deps.now(); value.version++
      if (value.ownerType === 'task') { const task = taskById(state, value.ownerId); if (outcome === 'continue-picking') { for (const line of task.lines) if (value.lines.some((item) => item.orderLineId === line.orderLineId)) { line.actualQuantityMilli = null; line.status = 'pending' } } else { task.status = 'completed'; task.completedAt = deps.now() } task.version++; task.updatedAt = deps.now() }
      else { const wave = waveById(state, value.ownerId); if (outcome === 'continue-picking') for (const line of wave.allocations) if (line.orderId === value.orderId && value.lines.some((item) => item.orderLineId === line.orderLineId)) line.actualQuantityMilli = null; const pending = state.pickingDifferences!.some((item) => item.ownerType === 'wave' && item.ownerId === wave.id && item.id !== value.id && item.status === 'pending'); if (outcome === 'accepted-short' && !pending) { wave.status = 'completed'; wave.completedAt = deps.now() } wave.version++; wave.updatedAt = deps.now() }
      return value })
  }
  const crossAtomic = <T>(operation: () => T): T => { const inventory = deps.repository.read(); const coordinator = provider(); const external = coordinator.checkpoint(); try { return operation() } catch (error) { deps.repository.reset(inventory); coordinator.restore(external); throw error } }
  function confirmPickingOutbound(actor: InventoryActor, id: string, expectedVersion: number, requestId: string): PickingTask {
    assertWrite(actor); return crossAtomic(() => { const before = deps.repository.read(); arrays(before); const replay = before.pickingRequests!.find((item) => item.requestId === requestId); if (replay) return taskById(before, replay.targetId); const task = taskById(before, id); if (task.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '分拣单版本已变化'); if (task.status !== 'completed' || task.outboundId) throw new InventoryPickingError('INVALID_STATE', '分拣单尚未完成或已经出库'); const difference = before.pickingDifferences!.find((item) => item.ownerType === 'task' && item.ownerId === id && item.status === 'accepted-short'); const result = provider().confirmOutbounds(actor, [{ requestId: `${requestId}:order`, orderId: task.orderSnapshot.orderId, expectedUpdatedAt: task.orderSnapshot.updatedAt, warehouseId: task.warehouseId, lines: task.lines.map((line) => ({ orderLineId: line.orderLineId, quantityMilli: line.actualQuantityMilli ?? 0, conversionRateMilli: line.conversionRateMilli })), finishShort: Boolean(difference), reason: difference?.reason ?? null }])[0]!
      return deps.repository.transact((state) => { arrays(state); const current = taskById(state, id); if (current.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '分拣单版本已变化'); current.outboundId = result.outboundId; current.orderDifferenceId = result.differenceId; current.orderSnapshot.updatedAt = result.updatedAt; current.version++; current.updatedAt = deps.now(); if (difference) { const currentDifference = state.pickingDifferences!.find((item) => item.id === difference.id)!; currentDifference.orderDifferenceId = result.differenceId; currentDifference.version++ } state.pickingRequests!.push({ requestId, kind: 'picking-outbound', targetId: current.id, appliedAt: deps.now() }); return current }) })
  }

  function createPickingWave(actor: InventoryActor, draft: PickingWaveDraft): PickingWave {
    assertWrite(actor); if (!draft.orderIds.length || new Set(draft.orderIds).size !== draft.orderIds.length) throw new InventoryValidationError([{ path: 'orderIds', message: '至少选择一张且不能重复' }]); if (draft.cutoffAt < deps.now()) throw new InventoryValidationError([{ path: 'cutoffAt', message: '截止时间不能早于当前时间' }])
    const candidates = new Map(providerItems('picking').map((item) => [item.orderId, item])); const orders = draft.orderIds.map((id) => candidates.get(id)); if (orders.some((item) => !item)) throw new InventoryPickingError('INVALID_STATE', '包含不再满足条件的订单'); if (orders.some((item) => item!.warehouseId !== draft.warehouseId)) throw new InventoryPickingError('INVALID_STATE', '波次只能包含同仓订单')
    return deps.repository.transact((state) => { arrays(state); if (draft.orderIds.some((id) => activeOwner(state, id))) throw new InventoryPickingError('DUPLICATE', '订单已被其他活动分拣占用'); if (draft.strategy === 'route' && (!draft.routeId || routeById(state, draft.routeId).status !== 'enabled')) throw new InventoryPickingError('INVALID_STATE', '线路策略必须选择启用线路'); if (draft.strategy === 'area' && !draft.area?.trim() || draft.strategy === 'category' && !draft.categoryId) throw new InventoryValidationError([{ path: 'strategy', message: '策略筛选值不能为空' }]); const snapshots = orders as PickingOrderSnapshot[]; const value: PickingWave = { id: deps.nextId('log'), enterpriseId: state.enterpriseId, code: nextCode(state, 'BC', state.pickingWaves!), strategy: draft.strategy, warehouseId: draft.warehouseId, cutoffAt: draft.cutoffAt, routeId: draft.routeId ?? null, area: draft.area?.trim() || null, categoryId: draft.categoryId ?? null, orders: structuredClone(snapshots), allocations: snapshots.flatMap((order) => order.lines.map((line) => ({ orderId: order.orderId, orderLineId: line.orderLineId, skuId: line.skuId, expectedQuantityMilli: line.remainingQuantityMilli, actualQuantityMilli: null }))), status: 'pending', pickerId: null, version: 1, createdAt: deps.now(), updatedAt: deps.now(), completedAt: null, cancelledAt: null, outboundResults: [] }; state.pickingWaves!.push(value); return value })
  }
  function listPickingWaves(actor: InventoryActor, query: PickingListQuery = {}) { assertRead(actor); const rows = (deps.repository.read().pickingWaves ?? []).filter((item) => matches(query, { status: item.status, at: item.createdAt, keyword: `${item.code} ${item.orders.map((order) => order.orderNo).join(' ')}`, warehouseId: item.warehouseId })).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return page(rows, query) }
  function startPickingWave(actor: InventoryActor, id: string, expectedVersion: number, pickerId: string): PickingWave { assertWrite(actor); const staff = deps.staffProvider?.listStaff().find((item) => item.id === pickerId); if (!staff) throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', '分拣人员不存在或员工来源不可用'); return deps.repository.transact((state) => { arrays(state); const value = waveById(state, id); if (value.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '波次版本已变化'); if (value.status !== 'pending') throw new InventoryPickingError('INVALID_STATE', '只有待分拣波次可开始'); for (const snapshot of value.orders) { const current = provider().getPickingOrder(snapshot.orderId); if (!current || current.updatedAt !== snapshot.updatedAt) throw new InventoryPickingError('CONFLICT', `来源订单 ${snapshot.orderNo} 已变化，请重新创建波次`) } value.status = 'picking'; value.pickerId = staff.id; value.version++; value.updatedAt = deps.now(); return value }) }
  function cancelPickingWave(actor: InventoryActor, id: string, expectedVersion: number): PickingWave { assertWrite(actor); return deps.repository.transact((state) => { arrays(state); const value = waveById(state, id); if (value.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '波次版本已变化'); if (value.status !== 'pending') throw new InventoryPickingError('INVALID_STATE', '只有待分拣波次可取消'); value.status = 'cancelled'; value.cancelledAt = deps.now(); value.version++; value.updatedAt = deps.now(); return value }) }
  function submitPickingWave(actor: InventoryActor, id: string, expectedVersion: number, allocations: Array<{ orderId: string; orderLineId: string; actualQuantityMilli: number }>, reason = ''): PickingWave {
    assertWrite(actor); return deps.repository.transact((state) => { arrays(state); const wave = waveById(state, id); if (wave.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '波次版本已变化'); if (wave.status !== 'picking') throw new InventoryPickingError('INVALID_STATE', '只有分拣中波次可提交'); if (allocations.length !== wave.allocations.length) throw new InventoryPickingError('INVALID_STATE', '必须完成全部订单分播'); const differences = new Map<string, PickingDifference['lines']>(); for (const line of wave.allocations) { const input = allocations.find((item) => item.orderId === line.orderId && item.orderLineId === line.orderLineId); if (!input || !Number.isSafeInteger(input.actualQuantityMilli) || input.actualQuantityMilli < 0 || input.actualQuantityMilli > line.expectedQuantityMilli) throw new InventoryValidationError([{ path: `allocations.${line.orderLineId}`, message: '分播量必须是不超过应拣量的非负整数毫单位' }]); line.actualQuantityMilli = input.actualQuantityMilli; const alreadyAccepted = state.pickingDifferences!.some((item) => item.ownerType === 'wave' && item.ownerId === wave.id && item.orderId === line.orderId && item.status === 'accepted-short'); if (input.actualQuantityMilli !== line.expectedQuantityMilli && !alreadyAccepted) differences.set(line.orderId, [...(differences.get(line.orderId) ?? []), { orderLineId: line.orderLineId, skuId: line.skuId, expectedQuantityMilli: line.expectedQuantityMilli, actualQuantityMilli: input.actualQuantityMilli, differenceQuantityMilli: input.actualQuantityMilli - line.expectedQuantityMilli }]) } for (const [orderId, lines] of differences) addDifference(state, 'wave', wave.id, wave.orders.find((item) => item.orderId === orderId)!, lines, reason); const pending = state.pickingDifferences!.some((item) => item.ownerType === 'wave' && item.ownerId === wave.id && item.status === 'pending'); if (!differences.size && !pending) { wave.status = 'completed'; wave.completedAt = deps.now() } wave.version++; wave.updatedAt = deps.now(); return wave })
  }
  function confirmWaveOutbounds(actor: InventoryActor, id: string, expectedVersion: number, requestId: string): PickingWave {
    assertWrite(actor); return crossAtomic(() => { const before = deps.repository.read(); arrays(before); const replay = before.pickingRequests!.find((item) => item.requestId === requestId); if (replay) return waveById(before, replay.targetId); const wave = waveById(before, id); if (wave.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '波次版本已变化'); if (wave.status !== 'completed' || wave.outboundResults.length) throw new InventoryPickingError('INVALID_STATE', '波次尚未完成或已经出库'); const commands = wave.orders.map((order) => { const lines = wave.allocations.filter((line) => line.orderId === order.orderId); const difference = before.pickingDifferences!.find((item) => item.ownerType === 'wave' && item.ownerId === wave.id && item.orderId === order.orderId && item.status === 'accepted-short'); return { requestId: `${requestId}:${order.orderId}`, orderId: order.orderId, expectedUpdatedAt: order.updatedAt, warehouseId: wave.warehouseId, lines: lines.map((line) => ({ orderLineId: line.orderLineId, quantityMilli: line.actualQuantityMilli ?? 0, conversionRateMilli: order.lines.find((item) => item.orderLineId === line.orderLineId)!.conversionRateMilli })), finishShort: Boolean(difference), reason: difference?.reason ?? null } }); const results = provider().confirmOutbounds(actor, commands)
      return deps.repository.transact((state) => { arrays(state); const current = waveById(state, id); if (current.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '波次版本已变化'); current.outboundResults = results.map((item) => ({ orderId: item.orderId, outboundId: item.outboundId, differenceId: item.differenceId })); for (const result of results) { const snapshot = current.orders.find((item) => item.orderId === result.orderId); if (snapshot) snapshot.updatedAt = result.updatedAt; const difference = state.pickingDifferences!.find((item) => item.ownerType === 'wave' && item.ownerId === id && item.orderId === result.orderId && item.status === 'accepted-short'); if (difference) { difference.orderDifferenceId = result.differenceId; difference.version++ } } current.version++; current.updatedAt = deps.now(); state.pickingRequests!.push({ requestId, kind: 'wave-outbound', targetId: current.id, appliedAt: deps.now() }); return current }) })
  }

  function validateRouteDraft(draft: DeliveryRouteDraft, state: InventoryFeatureState) { required(draft.name, 100, 'name'); required(draft.province, 50, 'province'); required(draft.city, 50, 'city'); required(draft.district, 50, 'district'); if (!draft.stops.length) throw new InventoryValidationError([{ path: 'stops', message: '至少配置一个站点' }]); draft.stops.forEach((stop, index) => { required(stop.name, 100, `stops.${index}.name`); required(stop.address, 200, `stops.${index}.address`) }); if (draft.estimatedMinutes !== null && draft.estimatedMinutes !== undefined && (!Number.isSafeInteger(draft.estimatedMinutes) || draft.estimatedMinutes <= 0)) throw new InventoryValidationError([{ path: 'estimatedMinutes', message: '预计分钟必须为正整数' }]); if (draft.defaultVehicleId) vehicleById(state, draft.defaultVehicleId); if (draft.defaultDriverId && !deps.staffProvider?.listStaff().some((item) => item.id === draft.defaultDriverId)) throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', '默认司机不存在或员工来源不可用') }
  function saveDeliveryRoute(actor: InventoryActor, draft: DeliveryRouteDraft, id?: string, expectedVersion?: number): DeliveryRoute { assertWrite(actor); return deps.repository.transact((state) => { arrays(state); validateRouteDraft(draft, state); const existing = id ? routeById(state, id) : null; if (existing && existing.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '线路版本已变化'); const value: DeliveryRoute = { id: existing?.id ?? deps.nextId('log'), enterpriseId: state.enterpriseId, code: existing?.code ?? nextCode(state, 'XL', state.deliveryRoutes!), name: required(draft.name, 100, 'name'), province: required(draft.province, 50, 'province'), city: required(draft.city, 50, 'city'), district: required(draft.district, 50, 'district'), stops: draft.stops.map((item, index) => ({ ...item, id: existing?.stops[index]?.id ?? deps.nextId('log'), sequence: index + 1 })), defaultDriverId: draft.defaultDriverId ?? null, defaultVehicleId: draft.defaultVehicleId ?? null, estimatedMinutes: draft.estimatedMinutes ?? null, status: draft.status, note: optional(draft.note, 500, 'note'), version: (existing?.version ?? 0) + 1, createdAt: existing?.createdAt ?? deps.now(), updatedAt: deps.now() }; if (existing) Object.assign(existing, value); else state.deliveryRoutes!.push(value); return value }) }
  function listDeliveryRoutes(actor: InventoryActor, query: PickingListQuery = {}) { assertRead(actor); const rows = (deps.repository.read().deliveryRoutes ?? []).filter((item) => matches(query, { status: item.status, at: item.createdAt, keyword: `${item.code} ${item.name} ${item.province}${item.city}${item.district}` })).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return page(rows, query) }
  function deleteDeliveryRoute(actor: InventoryActor, id: string, expectedVersion: number): void { assertWrite(actor); deps.repository.transact((state) => { arrays(state); const value = routeById(state, id); if (value.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '线路版本已变化'); if (state.deliveryTasks!.some((item) => item.routeSnapshot.id === id)) throw new InventoryPickingError('INVALID_STATE', '线路已被配送任务引用，不能删除'); state.deliveryRoutes = state.deliveryRoutes!.filter((item) => item.id !== id) }) }
  function saveDeliveryVehicle(actor: InventoryActor, draft: DeliveryVehicleDraft, id?: string, expectedVersion?: number): DeliveryVehicle { assertWrite(actor); required(draft.plateNumber, 30, 'plateNumber'); if (!Number.isSafeInteger(draft.capacityKg) || draft.capacityKg <= 0) throw new InventoryValidationError([{ path: 'capacityKg', message: '载重必须为正整数千克' }]); if (draft.type === 'other') required(draft.otherType, 40, 'otherType'); if (draft.defaultDriverId && !deps.staffProvider?.listStaff().some((item) => item.id === draft.defaultDriverId)) throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', '默认司机不存在或员工来源不可用'); return deps.repository.transact((state) => { arrays(state); const existing = id ? vehicleById(state, id) : null; if (existing && existing.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '车辆版本已变化'); if (existing?.status === 'dispatching') throw new InventoryPickingError('INVALID_STATE', '出车中的车辆不能编辑'); if (state.deliveryVehicles!.some((item) => item.id !== id && normalize(item.plateNumber) === normalize(draft.plateNumber))) throw new InventoryPickingError('DUPLICATE', '车牌号企业内必须唯一'); const value: DeliveryVehicle = { id: existing?.id ?? deps.nextId('log'), enterpriseId: state.enterpriseId, plateNumber: required(draft.plateNumber, 30, 'plateNumber'), type: draft.type, otherType: draft.type === 'other' ? required(draft.otherType, 40, 'otherType') : null, capacityKg: draft.capacityKg, defaultDriverId: draft.defaultDriverId ?? null, status: draft.status, note: optional(draft.note, 500, 'note'), version: (existing?.version ?? 0) + 1, createdAt: existing?.createdAt ?? deps.now(), updatedAt: deps.now() }; if (existing) Object.assign(existing, value); else state.deliveryVehicles!.push(value); return value }) }
  function listDeliveryVehicles(actor: InventoryActor, query: PickingListQuery = {}) { assertRead(actor); const rows = (deps.repository.read().deliveryVehicles ?? []).filter((item) => matches(query, { status: item.status, at: item.createdAt, keyword: `${item.plateNumber} ${item.type} ${item.otherType ?? ''}` })).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return page(rows, query) }
  function listDeliveryCandidates(actor: InventoryActor): PickingOrderProviderResult { assertRead(actor); const state = deps.repository.read(); arrays(state); const delivered = new Set(state.deliveryTasks!.filter((item) => item.status !== 'cancelled').flatMap((item) => item.orders.map((order) => order.orderId))); const picked = new Set<string>(); state.pickingTasks!.filter((item) => item.status === 'completed' && item.outboundId).forEach((item) => picked.add(item.orderSnapshot.orderId)); state.pickingWaves!.filter((item) => item.status === 'completed').forEach((item) => item.outboundResults.forEach((result) => { if (result.outboundId) picked.add(result.orderId) })); const result = provider().listDeliveryOrders(); return { ...result, items: result.items.filter((item) => picked.has(item.orderId) && !delivered.has(item.orderId)) } }
  function createDeliveryTask(actor: InventoryActor, draft: DeliveryTaskDraft): DeliveryTask { assertWrite(actor); if (!draft.orderIds.length || new Set(draft.orderIds).size !== draft.orderIds.length) throw new InventoryValidationError([{ path: 'orderIds', message: '至少选择一张且不能重复' }]); if (draft.plannedDepartureAt < deps.now()) throw new InventoryValidationError([{ path: 'plannedDepartureAt', message: '计划出发时间不能早于当前时间' }]); const candidates = new Map(listDeliveryCandidates(actor).items.map((item) => [item.orderId, item])); const orders = draft.orderIds.map((id) => candidates.get(id)); if (orders.some((item) => !item)) throw new InventoryPickingError('INVALID_STATE', '包含不满足待配送条件的订单'); return deps.repository.transact((state) => { arrays(state); const route = routeById(state, draft.routeId); const vehicle = vehicleById(state, draft.vehicleId); const driver = deps.staffProvider?.listStaff().find((item) => item.id === draft.driverId); if (route.status !== 'enabled') throw new InventoryPickingError('INVALID_STATE', '配送线路已停用'); if (vehicle.status !== 'idle') throw new InventoryPickingError('INVALID_STATE', '车辆不是空闲状态'); if (!driver) throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', '司机不存在或员工来源不可用'); if (state.deliveryTasks!.some((item) => item.status !== 'cancelled' && (item.vehicleSnapshot.id === vehicle.id || item.orders.some((entry) => draft.orderIds.includes(entry.orderId))))) throw new InventoryPickingError('DUPLICATE', '订单或车辆已被其他配送任务占用'); const value: DeliveryTask = { id: deps.nextId('log'), enterpriseId: state.enterpriseId, code: nextCode(state, 'PS', state.deliveryTasks!), routeSnapshot: structuredClone(route), driverSnapshot: structuredClone(driver), vehicleSnapshot: structuredClone(vehicle), orders: structuredClone(orders as PickingOrderSnapshot[]), plannedDepartureAt: draft.plannedDepartureAt, actualDepartureAt: null, completedAt: null, note: optional(draft.note, 500, 'note'), status: 'pending', shipmentIds: [], version: 1, createdAt: deps.now(), updatedAt: deps.now(), cancelledAt: null }; state.deliveryTasks!.push(value); return value }) }
  function updateDeliveryTask(actor: InventoryActor, id: string, expectedVersion: number, draft: DeliveryTaskDraft): DeliveryTask { assertWrite(actor); if (!draft.orderIds.length || new Set(draft.orderIds).size !== draft.orderIds.length) throw new InventoryValidationError([{ path: 'orderIds', message: '至少选择一张且不能重复' }]); if (draft.plannedDepartureAt < deps.now()) throw new InventoryValidationError([{ path: 'plannedDepartureAt', message: '计划出发时间不能早于当前时间' }]); const stateBefore = deps.repository.read(); arrays(stateBefore); const existing = deliveryById(stateBefore, id); if (existing.status !== 'pending') throw new InventoryPickingError('INVALID_STATE', '只有待配送任务可编辑'); const available = provider().listDeliveryOrders(); if (available.state !== 'available') throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', available.message ?? '待配送订单来源不可用'); const picked = new Set<string>(); stateBefore.pickingTasks!.filter((item) => item.status === 'completed' && item.outboundId).forEach((item) => picked.add(item.orderSnapshot.orderId)); stateBefore.pickingWaves!.filter((item) => item.status === 'completed').forEach((item) => item.outboundResults.forEach((result) => { if (result.outboundId) picked.add(result.orderId) })); const candidates = new Map(available.items.filter((item) => picked.has(item.orderId)).map((item) => [item.orderId, item])); const orders = draft.orderIds.map((orderId) => candidates.get(orderId)); if (orders.some((item) => !item)) throw new InventoryPickingError('INVALID_STATE', '包含不满足待配送条件的订单'); return deps.repository.transact((state) => { arrays(state); const current = deliveryById(state, id); if (current.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '配送任务版本已变化'); if (current.status !== 'pending') throw new InventoryPickingError('INVALID_STATE', '只有待配送任务可编辑'); const route = routeById(state, draft.routeId); const vehicle = vehicleById(state, draft.vehicleId); const driver = deps.staffProvider?.listStaff().find((item) => item.id === draft.driverId); if (route.status !== 'enabled' || vehicle.status !== 'idle') throw new InventoryPickingError('INVALID_STATE', '线路必须启用且车辆必须空闲'); if (!driver) throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', '司机不存在或员工来源不可用'); if (state.deliveryTasks!.some((item) => item.id !== id && item.status !== 'cancelled' && (item.vehicleSnapshot.id === vehicle.id || item.orders.some((entry) => draft.orderIds.includes(entry.orderId))))) throw new InventoryPickingError('DUPLICATE', '订单或车辆已被其他配送任务占用'); current.routeSnapshot = structuredClone(route); current.driverSnapshot = structuredClone(driver); current.vehicleSnapshot = structuredClone(vehicle); current.orders = structuredClone(orders as PickingOrderSnapshot[]); current.plannedDepartureAt = draft.plannedDepartureAt; current.note = optional(draft.note, 500, 'note'); current.version++; current.updatedAt = deps.now(); return current }) }
  function listDeliveryTasks(actor: InventoryActor, query: PickingListQuery = {}) { assertRead(actor); const rows = (deps.repository.read().deliveryTasks ?? []).filter((item) => matches(query, { status: item.status, at: item.plannedDepartureAt, keyword: `${item.code} ${item.routeSnapshot.name} ${item.driverSnapshot.name} ${item.vehicleSnapshot.plateNumber} ${item.orders.map((order) => `${order.orderNo} ${order.customerName}`).join(' ')}` })).sort((a, b) => b.plannedDepartureAt.localeCompare(a.plannedDepartureAt)); return page(rows, query) }
  function startDeliveryTask(actor: InventoryActor, id: string, expectedVersion: number, requestId: string): DeliveryTask { assertWrite(actor); return crossAtomic(() => { const before = deps.repository.read(); arrays(before); const replay = before.pickingRequests!.find((item) => item.requestId === requestId); if (replay) return deliveryById(before, replay.targetId); const task = deliveryById(before, id); if (task.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '配送任务版本已变化'); if (task.status !== 'pending') throw new InventoryPickingError('INVALID_STATE', '只有待配送任务可开始'); const vehicle = vehicleById(before, task.vehicleSnapshot.id); if (vehicle.status !== 'idle') throw new InventoryPickingError('CONFLICT', '车辆已被占用'); const results = provider().confirmShipments(actor, task.orders.map((order) => ({ requestId: `${requestId}:${order.orderId}`, orderId: order.orderId, expectedUpdatedAt: order.updatedAt, remark: `配送任务 ${task.code}` }))); return deps.repository.transact((state) => { arrays(state); const current = deliveryById(state, id); const currentVehicle = vehicleById(state, current.vehicleSnapshot.id); if (current.version !== expectedVersion || currentVehicle.status !== 'idle') throw new InventoryPickingError('CONFLICT', '配送任务或车辆已变化'); current.status = 'delivering'; current.actualDepartureAt = deps.now(); current.shipmentIds = results.map((item) => item.shipmentId); results.forEach((item) => { const order = current.orders.find((entry) => entry.orderId === item.orderId); if (order) order.updatedAt = item.updatedAt }); current.version++; current.updatedAt = deps.now(); currentVehicle.status = 'dispatching'; currentVehicle.version++; currentVehicle.updatedAt = deps.now(); state.pickingRequests!.push({ requestId, kind: 'delivery-start', targetId: current.id, appliedAt: deps.now() }); return current }) }) }
  function completeDeliveryTask(actor: InventoryActor, id: string, expectedVersion: number): DeliveryTask { assertWrite(actor); return deps.repository.transact((state) => { arrays(state); const task = deliveryById(state, id); if (task.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '配送任务版本已变化'); if (task.status !== 'delivering') throw new InventoryPickingError('INVALID_STATE', '只有配送中任务可完成'); const vehicle = vehicleById(state, task.vehicleSnapshot.id); task.status = 'completed'; task.completedAt = deps.now(); task.updatedAt = deps.now(); task.version++; if (vehicle.status === 'dispatching') { vehicle.status = 'idle'; vehicle.version++; vehicle.updatedAt = deps.now() } return task }) }
  function cancelDeliveryTask(actor: InventoryActor, id: string, expectedVersion: number): DeliveryTask { assertWrite(actor); return deps.repository.transact((state) => { arrays(state); const task = deliveryById(state, id); if (task.version !== expectedVersion) throw new InventoryPickingError('CONFLICT', '配送任务版本已变化'); if (task.status !== 'pending') throw new InventoryPickingError('INVALID_STATE', '只有待配送任务可取消'); task.status = 'cancelled'; task.cancelledAt = deps.now(); task.updatedAt = deps.now(); task.version++; return task }) }
  function listDeliveryStaff(actor: InventoryActor) { assertRead(actor); if (!deps.staffProvider) throw new InventoryPickingError('DATA_PROVIDER_UNAVAILABLE', '员工来源不可用'); return deps.staffProvider.listStaff() }
  function createPickingLabel(actor: InventoryActor, draft: PickingLabelDraft): PickingLabel { assertWrite(actor); positiveMilli(draft.quantityMilli, 'quantityMilli'); required(draft.templateId, 80, 'templateId'); return deps.repository.transact((state) => { arrays(state); let order: PickingOrderSnapshot; if (draft.sourceType === 'task') { const source = taskById(state, draft.sourceId); if (source.status !== 'completed') throw new InventoryPickingError('INVALID_STATE', '只能为已完成分拣创建标签'); order = source.orderSnapshot } else { const source = waveById(state, draft.sourceId); if (source.status !== 'completed') throw new InventoryPickingError('INVALID_STATE', '只能为已完成分拣创建标签'); const found = source.orders.find((item) => item.orderId === draft.orderId); if (!found) throw new InventoryPickingError('INVALID_STATE', '标签订单不属于分拣来源'); order = found } if (order.orderId !== draft.orderId) throw new InventoryPickingError('INVALID_STATE', '标签订单不属于分拣来源'); if (draft.type === 'order' && state.pickingLabels!.some((item) => item.sourceType === draft.sourceType && item.sourceId === draft.sourceId && item.orderId === draft.orderId && item.type === 'order')) throw new InventoryPickingError('DUPLICATE', '该订单已经存在订单标签'); const code = nextCode(state, 'BQ', state.pickingLabels!); const value: PickingLabel = { id: deps.nextId('log'), enterpriseId: state.enterpriseId, code, sourceType: draft.sourceType, sourceId: draft.sourceId, type: draft.type, orderId: order.orderId, orderNo: order.orderNo, skuId: draft.type === 'order' ? null : draft.skuId ?? null, productName: draft.type === 'order' ? null : optional(draft.productName, 100, 'productName'), quantityMilli: draft.quantityMilli, locationText: optional(draft.locationText, 100, 'locationText'), barcode: code.replaceAll('-', ''), templateId: required(draft.templateId, 80, 'templateId'), printCount: 0, createdAt: deps.now(), lastPrintedAt: null, version: 1 }; state.pickingLabels!.push(value); return value }) }
  function listPickingLabels(actor: InventoryActor, query: PickingListQuery = {}) { assertRead(actor); const rows = (deps.repository.read().pickingLabels ?? []).filter((item) => matches(query, { status: item.printCount ? 'printed' : 'pending', at: item.createdAt, keyword: `${item.code} ${item.orderNo} ${item.productName ?? ''}` })).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return page(rows, query) }
  function printPickingLabels(actor: InventoryActor, ids: string[], copies: number, requestId: string): PickingLabel[] { assertWrite(actor); if (!ids.length || new Set(ids).size !== ids.length || !Number.isSafeInteger(copies) || copies <= 0 || copies > 100) throw new InventoryValidationError([{ path: 'print', message: '请选择唯一标签且打印份数为 1～100' }]); return deps.repository.transact((state) => { arrays(state); const replay = state.pickingRequests!.find((item) => item.requestId === requestId); if (replay) return state.pickingLabels!.filter((item) => ids.includes(item.id)); const rows = ids.map((id) => { const item = state.pickingLabels!.find((entry) => entry.id === id); if (!item) throw new InventoryPickingError('NOT_FOUND', '标签不存在'); return item }); rows.forEach((item) => { item.printCount += copies; item.lastPrintedAt = deps.now(); item.version++ }); state.pickingRequests!.push({ requestId, kind: 'label-print', targetId: ids.join(','), appliedAt: deps.now() }); return rows }) }
  const csv = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`
  function exportPickingCsv(actor: InventoryActor, kind: 'pending' | 'tasks' | 'waves' | 'deliveries' | 'routes' | 'vehicles' | 'labels', query: PickingListQuery = {}) {
    assertWrite(actor)
    const all = <T>(loader: (value: PickingListQuery) => InventoryDocumentPage<T>) => { const first = loader({ ...query, page: 1, pageSize: 100 }); const items = [...first.items]; for (let current = 2; items.length < first.total; current++) items.push(...loader({ ...query, page: current, pageSize: 100 }).items); return items }
    const headers: Record<typeof kind, string[]> = { pending: ['订单号', '客户', '仓库', '交货时间', '分拣状态'], tasks: ['分拣单号', '订单号', '状态', '分拣人ID', '创建时间'], waves: ['波次号', '策略', '订单数', '状态', '创建时间'], deliveries: ['配送任务号', '线路', '司机', '车辆', '订单数', '状态'], routes: ['线路号', '名称', '省', '市', '区县', '站点数', '状态'], vehicles: ['车牌号', '车型', '载重kg', '状态'], labels: ['标签号', '类型', '订单号', '商品', '数量毫单位', '打印次数'] }
    const rows: unknown[][] = kind === 'pending' ? all((value) => listPendingPickingOrders(actor, value)).map((item) => [item.order.orderNo, item.order.customerName, item.order.warehouseName, item.order.requestedDeliveryAt, item.pickingStatus]) : kind === 'tasks' ? all((value) => listPickingTasks(actor, value)).map((item) => [item.code, item.orderSnapshot.orderNo, item.status, item.pickerId, item.createdAt]) : kind === 'waves' ? all((value) => listPickingWaves(actor, value)).map((item) => [item.code, item.strategy, item.orders.length, item.status, item.createdAt]) : kind === 'deliveries' ? all((value) => listDeliveryTasks(actor, value)).map((item) => [item.code, item.routeSnapshot.name, item.driverSnapshot.name, item.vehicleSnapshot.plateNumber, item.orders.length, item.status]) : kind === 'routes' ? all((value) => listDeliveryRoutes(actor, value)).map((item) => [item.code, item.name, item.province, item.city, item.district, item.stops.length, item.status]) : kind === 'vehicles' ? all((value) => listDeliveryVehicles(actor, value)).map((item) => [item.plateNumber, item.type, item.capacityKg, item.status]) : all((value) => listPickingLabels(actor, value)).map((item) => [item.code, item.type, item.orderNo, item.productName, item.quantityMilli, item.printCount])
    return `\uFEFF${[headers[kind], ...rows].map((row) => row.map(csv).join(',')).join('\r\n')}`
  }

  return { listPendingPickingOrders, createPickingTask, listPickingTasks, startPickingTask, cancelPickingTask, submitPickingTask, listPickingDifferences, resolvePickingDifference, confirmPickingOutbound, createPickingWave, listPickingWaves, startPickingWave, cancelPickingWave, submitPickingWave, confirmWaveOutbounds, saveDeliveryRoute, listDeliveryRoutes, deleteDeliveryRoute, saveDeliveryVehicle, listDeliveryVehicles, listDeliveryCandidates, createDeliveryTask, updateDeliveryTask, listDeliveryTasks, startDeliveryTask, completeDeliveryTask, cancelDeliveryTask, listDeliveryStaff, createPickingLabel, listPickingLabels, printPickingLabels, exportPickingCsv }
}
