import { describe, expect, it } from 'vitest'
import { createInventoryCatalogProvider, inventoryBaseline } from '../../../../mock/handlers/inventory-handler'
import { InMemoryInventoryRepository } from '../repositories/inventory-repository'
import type { InventoryActor } from '../types'
import { calculateBatchStatus, calculateInventoryStatus, createInventoryService, InventoryDomainError } from './inventory-service'

const admin: InventoryActor = { role: 'super-admin', actorId: 'admin-test' }
const supervisor: InventoryActor = { role: 'sales-supervisor', actorId: 'supervisor-test' }
const finance: InventoryActor = { role: 'finance', actorId: 'finance-test' }
function setup() { const repository = new InMemoryInventoryRepository(inventoryBaseline); let id = 1; const service = createInventoryService({ repository, catalog: createInventoryCatalogProvider(), now: () => '2026-08-10T09:00:00+08:00', nextId: (kind) => `${kind}-test-${id++}` }); return { repository, service } }

describe('inventory status and dates', () => {
  it('uses zero, lower-bound, upper-bound and normal priority', () => { const threshold={warehouseId:'w',skuId:'s',safetyMinimumMilli:10000,maximumMilli:30000}; expect(calculateInventoryStatus(0,threshold)).toBe('zero'); expect(calculateInventoryStatus(10000,threshold)).toBe('insufficient'); expect(calculateInventoryStatus(30001,threshold)).toBe('overstock'); expect(calculateInventoryStatus(20000,threshold)).toBe('normal'); expect(calculateInventoryStatus(null,threshold)).toBe('unavailable') })
  it('treats expiry day as near-expiry and next day as expired', () => { expect(calculateBatchStatus({expiresOn:'2026-08-10'},'2026-08-10T09:00:00+08:00')).toBe('near-expiry'); expect(calculateBatchStatus({expiresOn:'2026-08-09'},'2026-08-10T09:00:00+08:00')).toBe('expired'); expect(calculateBatchStatus({expiresOn:'2026-09-09'},'2026-08-10T09:00:00+08:00')).toBe('near-expiry'); expect(calculateBatchStatus({expiresOn:'2026-09-10'},'2026-08-10T09:00:00+08:00')).toBe('normal') })
})

describe('inventory service queries and permission', () => {
  it('does not fabricate unavailable cross-domain quantities and masks sensitive fields', () => { const {service}=setup(); const adminRow=service.listStocks(admin).items[0]!; expect(adminRow.pendingOutboundMilli).toBeNull(); expect(adminRow.availableMilli).toBeNull(); expect(adminRow.status).toBe('unavailable'); expect(adminRow.costPerBaseUnitCents).not.toBeNull(); const row=service.listStocks(supervisor).items[0]!; expect(row.costPerBaseUnitCents).toBeNull(); expect(row.amountCents).toBeNull(); expect(row.warehouse.phone).toBeNull() })
  it('rejects finance at service boundary', () => { const {service}=setup(); expect(() => service.listStocks(finance)).toThrowError(expect.objectContaining({code:'PERMISSION_DENIED'})) })
  it('preserves stock identifiers when catalog fails', () => { const repository=new InMemoryInventoryRepository(inventoryBaseline);const service=createInventoryService({repository,catalog:createInventoryCatalogProvider(true),now:()=> '2026-08-10T09:00:00+08:00',nextId:k=>`${k}-x`});const rows=service.listStocks(admin).items;expect(rows.length).toBeGreaterThan(0);expect(rows[0]!.sku).toBeNull() })
})

describe('inventory commands', () => {
  it('previews FIFO ignoring expired stock and commits atomically', () => { const {service,repository}=setup(); const allocation=service.previewOutbound(admin,{warehouseId:'warehouse-main',skuId:'sku-1',quantityMilli:12000}); expect(allocation.map(x=>[x.batchNumber,x.quantityMilli])).toEqual([['DEMO-BATCH-0720',8000],['DEMO-BATCH-0801',4000]]); const movements=service.confirmOutbound(admin,{requestId:'request-out-1',sourceType:'prototype-outbound',sourceId:'source-outbound-1',operatorId:'admin-test',occurredAt:'2026-08-10T09:10:00+08:00',warehouseId:'warehouse-main',skuId:'sku-1',quantityMilli:12000}); expect(movements).toHaveLength(2); expect(repository.read().balances.find(x=>x.id==='balance-2')!.quantityMilli).toBe(0); expect(repository.read().balances.find(x=>x.id==='balance-3')!.quantityMilli).toBe(16000) })
  it('is idempotent for outbound and inbound', () => { const {service,repository}=setup(); const out={requestId:'same-out',sourceType:'prototype-outbound',sourceId:'source-outbound-1',operatorId:'admin-test',occurredAt:'2026-08-10T09:20:00+08:00',warehouseId:'warehouse-main',skuId:'sku-1',quantityMilli:1000}; service.confirmOutbound(admin,out); const afterOut=repository.read(); service.confirmOutbound(admin,out); expect(repository.read()).toEqual(afterOut); const inbound={requestId:'same-in',sourceType:'prototype-inbound',sourceId:'source-inbound-1',operatorId:'admin-test',occurredAt:'2026-08-10T09:30:00+08:00',warehouseId:'warehouse-main',locationId:'location-main-a',skuId:'sku-1',quantityMilli:1000,costPerBaseUnitCents:700,batchNumber:'DEMO-NEW',productionDate:'2026-08-10'}; service.confirmInbound(admin,inbound); const afterIn=repository.read(); service.confirmInbound(admin,inbound); expect(repository.read()).toEqual(afterIn) })
  it('rejects insufficient stock and unknown source without any state change', () => { const {service,repository}=setup(); const before=repository.read(); expect(()=>service.confirmOutbound(admin,{requestId:'bad',sourceType:'prototype-outbound',sourceId:'source-outbound-1',operatorId:'a',occurredAt:'2026-08-10T09:00:00+08:00',warehouseId:'warehouse-main',skuId:'sku-2',quantityMilli:1000})).toThrowError(expect.objectContaining({code:'INSUFFICIENT_STOCK'})); expect(repository.read()).toEqual(before); expect(()=>service.confirmInbound(admin,{requestId:'bad-source',sourceType:'purchase',sourceId:'missing',operatorId:'a',occurredAt:'2026-08-10T09:00:00+08:00',warehouseId:'warehouse-main',locationId:'location-main-a',skuId:'sku-1',quantityMilli:1000,costPerBaseUnitCents:700,batchNumber:'X',productionDate:'2026-08-10'})).toThrowError(expect.objectContaining({code:'SOURCE_NOT_FOUND'})); expect(repository.read()).toEqual(before) })
  it('requires tracked batch data and creates a system batch for untracked goods', () => { const {service,repository}=setup(); expect(()=>service.confirmInbound(admin,{requestId:'tracked-bad',sourceType:'prototype-inbound',sourceId:'source-inbound-1',operatorId:'a',occurredAt:'2026-08-10T09:00:00+08:00',warehouseId:'warehouse-main',locationId:'location-main-a',skuId:'sku-1',quantityMilli:1000,costPerBaseUnitCents:700})).toThrow(); service.confirmInbound(admin,{requestId:'untracked',sourceType:'prototype-inbound',sourceId:'source-inbound-1',operatorId:'a',occurredAt:'2026-08-10T09:00:00+08:00',warehouseId:'warehouse-main',locationId:'location-main-a',skuId:'sku-4',quantityMilli:1500,costPerBaseUnitCents:100}); expect(repository.read().batches.some(x=>x.batchNumber==='SYSTEM-NONTRACKED-sku-4'&&!x.tracked)).toBe(true) })
})

describe('inventory master data', () => {
  it('blocks disabling referenced warehouse and nonzero location', () => { const {service}=setup(); const warehouse=service.getWorkspace(admin).warehouses.find(x=>x.id==='warehouse-main')!; expect(()=>service.saveWarehouse(admin,{...warehouse,status:'disabled'},warehouse.id)).toThrowError(expect.objectContaining({code:'INVALID_STATE'})); const location=service.getWorkspace(admin).locations.find(x=>x.id==='location-main-a')!; expect(()=>service.saveLocation(admin,{...location,status:'disabled'},location.id)).toThrowError(expect.objectContaining({code:'INVALID_STATE'})) })
  it('previews duplicate rows and rejects the whole import', () => { const {service,repository}=setup(); const rows=[{warehouseCode:'DEMO-WH-01',locationCode:'NEW',locationName:'新库位',status:'enabled' as const,note:null},{warehouseCode:'DEMO-WH-01',locationCode:'NEW',locationName:'另一名称',status:'enabled' as const,note:null}]; expect(service.previewLocationImport(admin,rows).errors.length).toBeGreaterThan(0); const before=repository.read(); expect(()=>service.importLocations(admin,rows)).toThrow(); expect(repository.read()).toEqual(before) })
  it('exports location columns without warehouse sensitive contacts', () => { const {service}=setup(); const csv=service.exportLocationsCsv(admin,['location-main-a']); expect(csv).toContain('warehouseCode,locationCode,locationName,status,note'); expect(csv).toContain('DEMO-A-01'); expect(csv).not.toContain('000-0000-0101') })
  it('validates threshold upper bound', () => { const {service}=setup(); expect(()=>service.saveThreshold(admin,{warehouseId:'warehouse-main',skuId:'sku-1',safetyMinimumMilli:10000,maximumMilli:10000})).toThrow(); expect(service.saveThreshold(admin,{warehouseId:'warehouse-main',skuId:'sku-1',safetyMinimumMilli:10000,maximumMilli:20000}).maximumMilli).toBe(20000) })
})
