import { defineStore } from 'pinia'
import { computed,ref,toRaw } from 'vue'
import { createOrderMockSession,type OrderScenarioName } from '../../../../mock/handlers/order-handler'
import { createEmptyOrderDraft } from '../services/order-service'
import { setCurrentOrderRole } from './order-access'
import type {
  ConfirmDifferenceInput,ConfirmReceiptInput,ConfirmShipmentInput,CustomerOrder,CustomerReturnDraft,CustomerReturnListRow,CustomerReturnQuery,DifferenceDocument,OrderActor,OrderCustomerContext,OrderDetailResult,
  OrderDraft,OrderDraftPreview,OrderFormOptions,OrderFulfillmentDetail,OrderLineDraft,OrderListRow,OrderOutboundPreview,OrderQuery,
  OrderReviewAction,OrderShareResult,OrderSkuOption,PageResult,PreviewOrderOutboundInput,SalesOutbound,SharedOrderView,ShareDurationDays,
} from '../types'
import type { CustomerRefund, FundAccount } from '../../finance/types'
import type { InventoryLocation } from '../../inventory/types'

type ReturnableLine=ReturnType<ReturnType<typeof createOrderMockSession>['returns']['getReturnableLines']>[number]
type ReturnPreview=ReturnType<ReturnType<typeof createOrderMockSession>['returns']['previewReturn']>

const emptyResult=():PageResult<OrderListRow>=>({items:[],total:0,page:1,pageSize:30})
const prototypeNow='2026-08-10T10:00:00+08:00'
function emptyFormDraft(actorId:string):OrderDraft{const value=createEmptyOrderDraft(prototypeNow,actorId);value.requestedDeliveryAt=prototypeNow.slice(0,16);return value}
const messageOf=(caught:unknown,fallback:string)=>caught instanceof Error?caught.message:fallback
export const useOrderStore=defineStore('orders',()=>{
  const scenario=ref<OrderScenarioName>('normal');const actor=ref<OrderActor>({role:'super-admin',actorId:'admin-demo'});const query=ref<OrderQuery>({page:1,pageSize:30});const result=ref<PageResult<OrderListRow>>(emptyResult());const detail=ref<OrderDetailResult|null>(null);const fulfillmentDetail=ref<OrderFulfillmentDetail|null>(null);const outboundPreview=ref<OrderOutboundPreview|null>(null);const outbounds=ref<SalesOutbound[]>([]);const differences=ref<DifferenceDocument[]>([])
  const draft=ref<OrderDraft>(emptyFormDraft(actor.value.actorId));const editingOrderId=ref<string|null>(null);const expectedUpdatedAt=ref<string|null>(null);const formOptions=ref<OrderFormOptions|null>(null);const customerContext=ref<OrderCustomerContext|null>(null);const skus=ref<OrderSkuOption[]>([]);const preview=ref<OrderDraftPreview|null>(null)
  const share=ref<OrderShareResult|null>(null);const sharedOrder=ref<SharedOrderView|null>(null);const loading=ref(false);const saving=ref(false);const error=ref<string|null>(null);let session=createOrderMockSession('normal',true);let requestVersion=0
  const returnQuery=ref<CustomerReturnQuery>({page:1,pageSize:30});const returnResult=ref<PageResult<CustomerReturnListRow>>({items:[],total:0,page:1,pageSize:30});const returnDetail=ref<CustomerReturnListRow|null>(null);const returnDraft=ref<CustomerReturnDraft>({orderId:'',warehouseId:'warehouse-main',returnType:'partial',refundPreference:'original',reason:'',remark:null,priceAdjustmentReason:null,lines:[]});const editingReturnId=ref<string|null>(null);const eligibleReturnOrders=ref<CustomerOrder[]>([]);const returnableLines=ref<ReturnableLine[]>([]);const returnPreview=ref<ReturnPreview|null>(null);const returnLocations=ref<InventoryLocation[]>([]);const returnWarehouses=ref<Array<{id:string;code:string;name:string}>>([]);const refunds=ref<CustomerRefund[]>([]);const refundCashAccounts=ref<FundAccount[]>([])
  const canOutput=computed(()=>['super-admin','sales-supervisor','salesperson'].includes(actor.value.role));const canManage=computed(()=>canOutput.value);const isEmpty=computed(()=>!loading.value&&!error.value&&result.value.total===0)
  async function load():Promise<void>{const version=++requestVersion;loading.value=true;error.value=null;try{const response=await session.run(()=>session.service.listOrders(actor.value,query.value));if(version===requestVersion)result.value=response}catch(caught){if(version===requestVersion){error.value=messageOf(caught,'订单数据加载失败');result.value={...emptyResult(),page:query.value.page??1,pageSize:query.value.pageSize??30}}}finally{if(version===requestVersion)loading.value=false}}
  function clearTransient():void{detail.value=null;fulfillmentDetail.value=null;outboundPreview.value=null;outbounds.value=[];differences.value=[];formOptions.value=null;customerContext.value=null;skus.value=[];preview.value=null;share.value=null;sharedOrder.value=null;editingOrderId.value=null;expectedUpdatedAt.value=null;draft.value=emptyFormDraft(actor.value.actorId);returnDetail.value=null;returnPreview.value=null;editingReturnId.value=null;eligibleReturnOrders.value=[];returnableLines.value=[];refunds.value=[]}
  async function setScenario(next:OrderScenarioName):Promise<void>{scenario.value=next;actor.value={role:'super-admin',actorId:'admin-demo'};setCurrentOrderRole(actor.value.role);session=createOrderMockSession(next,true);clearTransient();await load()}
  async function setRole(role:OrderActor['role']):Promise<void>{actor.value={role,actorId:role==='salesperson'?'staff-demo-1':`${role}-demo`};setCurrentOrderRole(role);clearTransient();await load()}
  async function applyQuery(next:OrderQuery):Promise<void>{query.value={...next,page:next.page??1,pageSize:next.pageSize??30};await load()}
  async function setPage(page:number):Promise<void>{query.value={...query.value,page:Math.max(1,page)};await load()}
  async function loadDetail(id:string):Promise<void>{loading.value=true;error.value=null;try{detail.value=await session.run(()=>session.service.getOrderDetail(actor.value,id))}catch(caught){error.value=messageOf(caught,'订单详情加载失败');detail.value=null}finally{loading.value=false}}
  function exportCsv(selected:string[]):string{return session.service.exportOrdersCsv(actor.value,query.value,selected)}
  async function confirmPrint(ids:string[],requestId:string):Promise<void>{saving.value=true;try{await session.run(()=>session.service.printOrders(actor.value,ids,requestId));await load();if(detail.value&&ids.includes(detail.value.order.id))await loadDetail(detail.value.order.id)}finally{saving.value=false}}
  async function reviewOrder(orderId:string,action:OrderReviewAction,expected:string,reason:string|null=null):Promise<boolean>{saving.value=true;error.value=null;try{session.simulateConcurrentEdit(orderId);await session.run(()=>session.service.reviewOrder(actor.value,{requestId:`review-ui-${Date.now()}`,orderId,action,expectedUpdatedAt:expected,reason}));await load();if(detail.value?.order.id===orderId)await loadDetail(orderId);return true}catch(caught){error.value=messageOf(caught,'订单审核失败');return false}finally{saving.value=false}}
  async function reviewOrders(items:Array<{orderId:string;expectedUpdatedAt:string}>):Promise<boolean>{saving.value=true;error.value=null;try{if(items[0])session.simulateConcurrentEdit(items[0].orderId);await session.run(()=>session.service.reviewOrders(actor.value,{requestId:`batch-review-ui-${Date.now()}`,items}));await load();return true}catch(caught){error.value=messageOf(caught,'批量审核失败');return false}finally{saving.value=false}}

  async function initializeForm(orderId?:string):Promise<void>{loading.value=true;error.value=null;preview.value=null;share.value=null;try{if(orderId){const editable=await session.run(()=>session.service.getEditableDraft(actor.value,orderId));editable.draft.requestedDeliveryAt=editable.draft.requestedDeliveryAt.slice(0,16);draft.value=editable.draft;editingOrderId.value=orderId;expectedUpdatedAt.value=editable.updatedAt}else{draft.value=emptyFormDraft(actor.value.actorId);editingOrderId.value=null;expectedUpdatedAt.value=null}formOptions.value=await session.run(()=>session.service.getFormOptions(actor.value,draft.value.customerId||undefined));if(draft.value.customerId){customerContext.value=await session.run(()=>session.service.getCustomerContext(actor.value,draft.value.customerId,orderId));skus.value=await session.run(()=>session.service.listOrderableSkus(actor.value,draft.value.customerId))}else{customerContext.value=null;skus.value=[]}}catch(caught){error.value=messageOf(caught,'订单表单加载失败')}finally{loading.value=false}}
  async function selectCustomer(customerId:string):Promise<void>{error.value=null;preview.value=null;const customer=formOptions.value?.customers.find((item)=>item.id===customerId);const empty=emptyFormDraft(actor.value.actorId);draft.value={...empty,customerId,salespersonId:customer?.salespersonId||actor.value.actorId,shipping:customer?{recipient:customer.recipient,phone:customer.phone,province:customer.province,city:customer.city,district:customer.district,address:customer.address}:empty.shipping,invoiceTitle:customer?.invoiceTitle??customer?.name??null};try{customerContext.value=await session.run(()=>session.service.getCustomerContext(actor.value,customerId,editingOrderId.value??undefined));skus.value=await session.run(()=>session.service.listOrderableSkus(actor.value,customerId));formOptions.value=await session.run(()=>session.service.getFormOptions(actor.value,customerId))}catch(caught){error.value=messageOf(caught,'客户关联数据加载失败');customerContext.value=null;skus.value=[]}}
  function addSku(skuId:string,lineKind:'sale'|'gift'='sale'):void{const sku=skus.value.find((item)=>item.skuId===skuId);if(!sku)return;const unit=sku.units.find((item)=>item.id===sku.baseUnitId)??sku.units[0];if(!unit)return;const found=draft.value.lines.find((item)=>item.skuId===skuId&&item.unitId===unit.id&&item.lineKind===lineKind);if(found)found.quantity+=1;else draft.value.lines.push({skuId,unitId:unit.id,quantity:1,lineKind,manualDealUnitPriceCents:null,reason:null,sourceKeys:[]});preview.value=null}
  function mergeLines(lines:OrderLineDraft[]):void{for(const line of lines){const found=draft.value.lines.find((item)=>item.skuId===line.skuId&&item.unitId===line.unitId&&item.lineKind===line.lineKind);if(found){found.quantity+=line.quantity;found.sourceKeys=[...new Set([...found.sourceKeys,...line.sourceKeys])]}else draft.value.lines.push(structuredClone(line))}preview.value=null}
  function domainDraft():OrderDraft{const value=structuredClone(toRaw(draft.value));if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value.requestedDeliveryAt))value.requestedDeliveryAt=`${value.requestedDeliveryAt}:00+08:00`;return value}
  async function pasteProducts(text:string){const parsed=await session.run(()=>session.service.parsePastedProducts(actor.value,draft.value.customerId,text));if(!parsed.errors.length)mergeLines(parsed.lines);return parsed}
  async function scanBarcode(value:string):Promise<void>{mergeLines([await session.run(()=>session.service.findByBarcode(actor.value,draft.value.customerId,value))])}
  async function applyTemplate(templateId:string){const parsed=await session.run(()=>session.service.loadTemplateLines(actor.value,draft.value.customerId,templateId));mergeLines(parsed.accepted.map((item)=>({skuId:item.skuId,unitId:item.unitId,quantity:item.quantity,lineKind:'sale',manualDealUnitPriceCents:null,reason:null,sourceKeys:[item.sourceKey]})));return parsed}
  async function previewForm():Promise<boolean>{error.value=null;try{const inputDraft=domainDraft();preview.value=await session.run(()=>session.service.previewOrder(actor.value,inputDraft,editingOrderId.value??undefined));return true}catch(caught){preview.value=null;error.value=messageOf(caught,'订单预览失败');return false}}
  async function saveForm(requestId:string):Promise<CustomerOrder|null>{saving.value=true;error.value=null;try{const inputDraft=domainDraft();if(editingOrderId.value)session.simulateConcurrentEdit(editingOrderId.value);const order=await session.run(()=>session.service.saveOrder(actor.value,{requestId,draft:inputDraft,orderId:editingOrderId.value??undefined,expectedUpdatedAt:expectedUpdatedAt.value??undefined}));detail.value=await session.run(()=>session.service.getOrderDetail(actor.value,order.id));return order}catch(caught){error.value=messageOf(caught,'订单保存失败');return null}finally{saving.value=false}}
  async function createShare(orderId:string,duration:ShareDurationDays=7):Promise<OrderShareResult|null>{saving.value=true;error.value=null;try{share.value=await session.run(()=>session.service.createShare(actor.value,orderId,duration));return share.value}catch(caught){error.value=messageOf(caught,'订单分享失败');return null}finally{saving.value=false}}
  async function viewShare(token:string):Promise<void>{loading.value=true;error.value=null;try{sharedOrder.value=await session.run(()=>session.service.viewSharedOrder(token))}catch(caught){sharedOrder.value=null;error.value=messageOf(caught,'分享链接无效')}finally{loading.value=false}}
  async function confirmShare(token:string):Promise<void>{saving.value=true;error.value=null;try{sharedOrder.value=await session.run(()=>session.service.confirmSharedOrder(token))}catch(caught){error.value=messageOf(caught,'确认失败')}finally{saving.value=false}}
  async function loadFulfillment(orderId:string):Promise<void>{loading.value=true;error.value=null;try{fulfillmentDetail.value=await session.run(()=>session.fulfillment.getFulfillment(actor.value,orderId))}catch(caught){fulfillmentDetail.value=null;error.value=messageOf(caught,'订单履约加载失败')}finally{loading.value=false}}
  async function loadOutbounds():Promise<void>{loading.value=true;error.value=null;try{outbounds.value=await session.run(()=>session.fulfillment.listOutbounds(actor.value))}catch(caught){outbounds.value=[];error.value=messageOf(caught,'销售出库单加载失败')}finally{loading.value=false}}
  async function loadDifferences():Promise<void>{loading.value=true;error.value=null;try{differences.value=await session.run(()=>session.fulfillment.listDifferences(actor.value))}catch(caught){differences.value=[];error.value=messageOf(caught,'差异单加载失败')}finally{loading.value=false}}
  async function refreshFulfillment(orderId:string):Promise<void>{await load();await loadDetail(orderId);await loadFulfillment(orderId)}
  async function previewFulfillment(input:PreviewOrderOutboundInput):Promise<boolean>{saving.value=true;error.value=null;try{outboundPreview.value=await session.run(()=>session.fulfillment.previewOutbound(actor.value,input));return true}catch(caught){outboundPreview.value=null;error.value=messageOf(caught,'出库预览失败');return false}finally{saving.value=false}}
  async function confirmFulfillment(input:PreviewOrderOutboundInput):Promise<boolean>{const expected=fulfillmentDetail.value?.order.updatedAt;if(!expected)return false;saving.value=true;error.value=null;try{await session.run(()=>session.fulfillment.confirmOutbound(actor.value,{...input,requestId:`outbound-ui-${Date.now()}`,expectedUpdatedAt:expected}));outboundPreview.value=null;await refreshFulfillment(input.orderId);return true}catch(caught){error.value=messageOf(caught,'确认出库失败');return false}finally{saving.value=false}}
  async function voidFulfillment(outboundId:string,reason:string):Promise<boolean>{const current=fulfillmentDetail.value;if(!current)return false;saving.value=true;error.value=null;try{await session.run(()=>session.fulfillment.voidOutbound(actor.value,{requestId:`void-outbound-ui-${Date.now()}`,outboundId,expectedOrderUpdatedAt:current.order.updatedAt,reason}));await refreshFulfillment(current.order.id);return true}catch(caught){error.value=messageOf(caught,'作废出库单失败');return false}finally{saving.value=false}}
  async function resolveDifference(differenceId:string,outcome:ConfirmDifferenceInput['outcome']):Promise<boolean>{const current=fulfillmentDetail.value;if(!current)return false;saving.value=true;error.value=null;try{await session.run(()=>session.fulfillment.confirmDifference(actor.value,{requestId:`difference-ui-${Date.now()}`,differenceId,expectedOrderUpdatedAt:current.order.updatedAt,outcome}));await refreshFulfillment(current.order.id);return true}catch(caught){error.value=messageOf(caught,'差异处理失败');return false}finally{saving.value=false}}
  async function shipOrder(input:Omit<ConfirmShipmentInput,'requestId'|'expectedUpdatedAt'>):Promise<boolean>{const current=fulfillmentDetail.value;if(!current)return false;saving.value=true;error.value=null;try{await session.run(()=>session.fulfillment.confirmShipment(actor.value,{...input,requestId:`shipment-ui-${Date.now()}`,expectedUpdatedAt:current.order.updatedAt}));await refreshFulfillment(input.orderId);return true}catch(caught){error.value=messageOf(caught,'确认发货失败');return false}finally{saving.value=false}}
  async function receiveOrder(input:Omit<ConfirmReceiptInput,'requestId'|'expectedUpdatedAt'>):Promise<boolean>{const current=fulfillmentDetail.value;if(!current)return false;saving.value=true;error.value=null;try{await session.run(()=>session.fulfillment.confirmReceipt(actor.value,{...input,requestId:`receipt-ui-${Date.now()}`,expectedUpdatedAt:current.order.updatedAt}));await refreshFulfillment(input.orderId);return true}catch(caught){error.value=messageOf(caught,'确认签收失败');return false}finally{saving.value=false}}
  async function printOutbounds(items:Array<{outboundId:string;expectedVersion:number}>):Promise<boolean>{saving.value=true;error.value=null;try{await session.run(()=>session.fulfillment.printOutbounds(actor.value,{requestId:`outbound-print-ui-${Date.now()}`,items}));if(fulfillmentDetail.value)await refreshFulfillment(fulfillmentDetail.value.order.id);else await loadOutbounds();return true}catch(caught){error.value=messageOf(caught,'打印出库单失败');return false}finally{saving.value=false}}
  async function loadReturns(next:CustomerReturnQuery=returnQuery.value):Promise<void>{returnQuery.value={...next,page:next.page??1,pageSize:next.pageSize??30};loading.value=true;error.value=null;try{returnResult.value=await session.run(()=>session.returns.listReturns(actor.value,returnQuery.value))}catch(caught){error.value=messageOf(caught,'退单列表加载失败');returnResult.value={items:[],total:0,page:1,pageSize:30}}finally{loading.value=false}}
  async function loadReturnDetail(id:string):Promise<void>{loading.value=true;error.value=null;try{returnDetail.value=await session.run(()=>session.returns.getReturn(actor.value,id));returnLocations.value=session.inventoryRepository.read().locations.filter((item)=>item.warehouseId===returnDetail.value!.value.warehouseSnapshot.id&&item.status==='enabled')}catch(caught){error.value=messageOf(caught,'退单详情加载失败');returnDetail.value=null}finally{loading.value=false}}
  async function selectReturnOrder(orderId:string):Promise<void>{returnDraft.value.orderId=orderId;returnableLines.value=await session.run(()=>session.returns.getReturnableLines(actor.value,orderId,editingReturnId.value??undefined));returnDraft.value.lines=returnableLines.value.map((item)=>({orderLineId:item.line.id,returnQuantityMilli:returnDraft.value.returnType==='whole'?item.returnableQuantityMilli:0}));returnPreview.value=null}
  async function initializeReturnForm(returnId?:string,orderId?:string):Promise<void>{loading.value=true;error.value=null;try{editingReturnId.value=returnId??null;eligibleReturnOrders.value=await session.run(()=>session.returns.listEligibleOrders(actor.value));returnWarehouses.value=session.inventoryRepository.read().warehouses.filter((item)=>item.status==='enabled').map(({id,code,name})=>({id,code,name}));if(returnId){const row=await session.run(()=>session.returns.getReturn(actor.value,returnId));const value=row.value;returnDraft.value={orderId:value.orderId,warehouseId:value.warehouseSnapshot.id,returnType:value.returnType,refundPreference:value.refundPreference,reason:value.reason,remark:value.remark,priceAdjustmentReason:value.priceAdjustmentReason,lines:value.items.map((item)=>({orderLineId:item.orderLineId,returnQuantityMilli:item.returnQuantityMilli,returnAmountCents:item.returnAmountCents}))};returnableLines.value=await session.run(()=>session.returns.getReturnableLines(actor.value,value.orderId,value.id))}else{returnDraft.value={orderId:'',warehouseId:returnWarehouses.value[0]?.id??'',returnType:'partial',refundPreference:'original',reason:'',remark:null,priceAdjustmentReason:null,lines:[]};if(orderId)await selectReturnOrder(orderId)}returnPreview.value=null}catch(caught){error.value=messageOf(caught,'退单表单加载失败')}finally{loading.value=false}}
  async function previewReturnForm():Promise<boolean>{error.value=null;try{returnPreview.value=await session.run(()=>session.returns.previewReturn(actor.value,structuredClone(toRaw(returnDraft.value)),editingReturnId.value??undefined));return true}catch(caught){returnPreview.value=null;error.value=messageOf(caught,'退单金额计算失败');return false}}
  async function saveReturnForm():Promise<string|null>{saving.value=true;error.value=null;try{const existing=editingReturnId.value?session.returns.getReturn(actor.value,editingReturnId.value).value:null;const value=await session.run(()=>session.returns.saveReturn(actor.value,{requestId:`return-save-ui-${crypto.randomUUID()}`,returnId:editingReturnId.value??undefined,expectedVersion:existing?.version,draft:structuredClone(toRaw(returnDraft.value))}));return value.id}catch(caught){error.value=messageOf(caught,'退单保存失败');return null}finally{saving.value=false}}
  async function reviewReturn(id:string,version:number,action:'approve'|'return',reason?:string):Promise<boolean>{saving.value=true;error.value=null;try{await session.run(()=>session.returns.reviewReturn(actor.value,{requestId:`return-review-ui-${crypto.randomUUID()}`,returnId:id,expectedVersion:version,action,reason}));await loadReturnDetail(id);return true}catch(caught){error.value=messageOf(caught,'退单审核失败');return false}finally{saving.value=false}}
  async function cancelReturn(id:string,version:number,reason:string):Promise<boolean>{saving.value=true;error.value=null;try{await session.run(()=>session.returns.cancelReturn(actor.value,{requestId:`return-cancel-ui-${crypto.randomUUID()}`,returnId:id,expectedVersion:version,reason}));await loadReturnDetail(id);return true}catch(caught){error.value=messageOf(caught,'退单取消失败');return false}finally{saving.value=false}}
  async function confirmReturnInbound(id:string,version:number,locationId:string):Promise<boolean>{saving.value=true;error.value=null;try{await session.run(()=>session.returnCoordinator.confirmInbound(actor.value,{requestId:`return-inbound-ui-${crypto.randomUUID()}`,returnId:id,expectedVersion:version,locationId}));await loadReturnDetail(id);return true}catch(caught){error.value=messageOf(caught,'退货入库失败');return false}finally{saving.value=false}}
  async function voidReturnInbound(id:string,version:number,reason:string):Promise<boolean>{saving.value=true;error.value=null;try{await session.run(()=>session.returnCoordinator.voidInbound(actor.value,{requestId:`return-inbound-void-ui-${crypto.randomUUID()}`,returnId:id,expectedVersion:version,reason}));await loadReturnDetail(id);return true}catch(caught){error.value=messageOf(caught,'退货入库作废失败');return false}finally{saving.value=false}}
  async function loadRefunds():Promise<void>{loading.value=true;error.value=null;try{refunds.value=await session.run(()=>session.financeRefunds.listRefunds({actorId:actor.value.actorId,role:actor.value.role}));refundCashAccounts.value=session.financeRepository.read().accounts.filter((item)=>item.status==='enabled'&&item.type==='cash')}catch(caught){error.value=messageOf(caught,'退款列表加载失败');refunds.value=[]}finally{loading.value=false}}
  async function confirmRefund(id:string,version:number,method:'original'|'cash'|'balance',cashAccountId?:string,reason?:string):Promise<boolean>{saving.value=true;error.value=null;try{const paid=await session.run(()=>session.financeRefunds.confirmRefund({actorId:actor.value.actorId,role:actor.value.role},{requestId:`refund-confirm-ui-${crypto.randomUUID()}`,refundId:id,expectedVersion:version,method,cashAccountId,reason,occurredAt:prototypeNow}));session.returnCoordinator.refreshRefundProjection(paid.sourceId);await loadRefunds();return true}catch(caught){error.value=messageOf(caught,'确认退款失败');return false}finally{saving.value=false}}
  async function rejectRefund(id:string,version:number,reason:string):Promise<boolean>{saving.value=true;error.value=null;try{await session.run(()=>session.financeRefunds.rejectRefund({actorId:actor.value.actorId,role:actor.value.role},{requestId:`refund-reject-ui-${crypto.randomUUID()}`,refundId:id,expectedVersion:version,reason,occurredAt:prototypeNow}));await loadRefunds();return true}catch(caught){error.value=messageOf(caught,'拒绝退款失败');return false}finally{saving.value=false}}
  async function reapplyRefund(id:string,version:number):Promise<boolean>{saving.value=true;error.value=null;try{await session.run(()=>session.financeRefunds.reapplyRefund({actorId:actor.value.actorId,role:actor.value.role},{requestId:`refund-reapply-ui-${crypto.randomUUID()}`,refundId:id,expectedVersion:version,occurredAt:prototypeNow}));await loadRefunds();return true}catch(caught){error.value=messageOf(caught,'退款重提失败');return false}finally{saving.value=false}}
  return{scenario,actor,query,result,detail,fulfillmentDetail,outboundPreview,outbounds,differences,draft,editingOrderId,expectedUpdatedAt,formOptions,customerContext,skus,preview,share,sharedOrder,returnQuery,returnResult,returnDetail,returnDraft,editingReturnId,eligibleReturnOrders,returnableLines,returnPreview,returnLocations,returnWarehouses,refunds,refundCashAccounts,loading,saving,error,canOutput,canManage,isEmpty,load,setScenario,setRole,applyQuery,setPage,loadDetail,loadFulfillment,loadOutbounds,loadDifferences,exportCsv,confirmPrint,reviewOrder,reviewOrders,initializeForm,selectCustomer,addSku,pasteProducts,scanBarcode,applyTemplate,previewForm,saveForm,createShare,viewShare,confirmShare,previewFulfillment,confirmFulfillment,voidFulfillment,resolveDifference,shipOrder,receiveOrder,printOutbounds,loadReturns,loadReturnDetail,initializeReturnForm,selectReturnOrder,previewReturnForm,saveReturnForm,reviewReturn,cancelReturn,confirmReturnInbound,voidReturnInbound,loadRefunds,confirmRefund,rejectRefund,reapplyRefund}
})
