import { defineStore } from 'pinia'
import { computed,ref,toRaw } from 'vue'
import { createOrderMockSession,type OrderScenarioName } from '../../../../mock/handlers/order-handler'
import { createEmptyOrderDraft } from '../services/order-service'
import { setCurrentOrderRole } from './order-access'
import type {
  CustomerOrder,OrderActor,OrderCustomerContext,OrderDetailResult,OrderDraft,OrderDraftPreview,OrderFormOptions,
  OrderLineDraft,OrderListRow,OrderQuery,OrderShareResult,OrderSkuOption,PageResult,SharedOrderView,ShareDurationDays,
} from '../types'

const emptyResult=():PageResult<OrderListRow>=>({items:[],total:0,page:1,pageSize:30})
const prototypeNow='2026-08-10T10:00:00+08:00'
function emptyFormDraft(actorId:string):OrderDraft{const value=createEmptyOrderDraft(prototypeNow,actorId);value.requestedDeliveryAt=prototypeNow.slice(0,16);return value}
const messageOf=(caught:unknown,fallback:string)=>caught instanceof Error?caught.message:fallback
export const useOrderStore=defineStore('orders',()=>{
  const scenario=ref<OrderScenarioName>('normal');const actor=ref<OrderActor>({role:'super-admin',actorId:'admin-demo'});const query=ref<OrderQuery>({page:1,pageSize:30});const result=ref<PageResult<OrderListRow>>(emptyResult());const detail=ref<OrderDetailResult|null>(null)
  const draft=ref<OrderDraft>(emptyFormDraft(actor.value.actorId));const editingOrderId=ref<string|null>(null);const expectedUpdatedAt=ref<string|null>(null);const formOptions=ref<OrderFormOptions|null>(null);const customerContext=ref<OrderCustomerContext|null>(null);const skus=ref<OrderSkuOption[]>([]);const preview=ref<OrderDraftPreview|null>(null)
  const share=ref<OrderShareResult|null>(null);const sharedOrder=ref<SharedOrderView|null>(null);const loading=ref(false);const saving=ref(false);const error=ref<string|null>(null);let session=createOrderMockSession('normal');let requestVersion=0
  const canOutput=computed(()=>['super-admin','sales-supervisor','salesperson'].includes(actor.value.role));const canManage=computed(()=>canOutput.value);const isEmpty=computed(()=>!loading.value&&!error.value&&result.value.total===0)
  async function load():Promise<void>{const version=++requestVersion;loading.value=true;error.value=null;try{const response=await session.run(()=>session.service.listOrders(actor.value,query.value));if(version===requestVersion)result.value=response}catch(caught){if(version===requestVersion){error.value=messageOf(caught,'订单数据加载失败');result.value={...emptyResult(),page:query.value.page??1,pageSize:query.value.pageSize??30}}}finally{if(version===requestVersion)loading.value=false}}
  function clearTransient():void{detail.value=null;formOptions.value=null;customerContext.value=null;skus.value=[];preview.value=null;share.value=null;sharedOrder.value=null;editingOrderId.value=null;expectedUpdatedAt.value=null;draft.value=emptyFormDraft(actor.value.actorId)}
  async function setScenario(next:OrderScenarioName):Promise<void>{scenario.value=next;actor.value={role:'super-admin',actorId:'admin-demo'};setCurrentOrderRole(actor.value.role);session=createOrderMockSession(next);clearTransient();await load()}
  async function setRole(role:OrderActor['role']):Promise<void>{actor.value={role,actorId:`${role}-demo`};setCurrentOrderRole(role);clearTransient();await load()}
  async function applyQuery(next:OrderQuery):Promise<void>{query.value={...next,page:next.page??1,pageSize:next.pageSize??30};await load()}
  async function setPage(page:number):Promise<void>{query.value={...query.value,page:Math.max(1,page)};await load()}
  async function loadDetail(id:string):Promise<void>{loading.value=true;error.value=null;try{detail.value=await session.run(()=>session.service.getOrderDetail(actor.value,id))}catch(caught){error.value=messageOf(caught,'订单详情加载失败');detail.value=null}finally{loading.value=false}}
  function exportCsv(selected:string[]):string{return session.service.exportOrdersCsv(actor.value,query.value,selected)}
  async function confirmPrint(ids:string[],requestId:string):Promise<void>{saving.value=true;try{await session.run(()=>session.service.printOrders(actor.value,ids,requestId));await load();if(detail.value&&ids.includes(detail.value.order.id))await loadDetail(detail.value.order.id)}finally{saving.value=false}}

  async function initializeForm(orderId?:string):Promise<void>{loading.value=true;error.value=null;preview.value=null;share.value=null;try{if(orderId){const editable=await session.run(()=>session.service.getEditableDraft(actor.value,orderId));editable.draft.requestedDeliveryAt=editable.draft.requestedDeliveryAt.slice(0,16);draft.value=editable.draft;editingOrderId.value=orderId;expectedUpdatedAt.value=editable.updatedAt}else{draft.value=emptyFormDraft(actor.value.actorId);editingOrderId.value=null;expectedUpdatedAt.value=null}formOptions.value=await session.run(()=>session.service.getFormOptions(actor.value,draft.value.customerId||undefined));if(draft.value.customerId){customerContext.value=await session.run(()=>session.service.getCustomerContext(actor.value,draft.value.customerId,orderId));skus.value=await session.run(()=>session.service.listOrderableSkus(actor.value,draft.value.customerId))}else{customerContext.value=null;skus.value=[]}}catch(caught){error.value=messageOf(caught,'订单表单加载失败')}finally{loading.value=false}}
  async function selectCustomer(customerId:string):Promise<void>{error.value=null;preview.value=null;const customer=formOptions.value?.customers.find((item)=>item.id===customerId);const empty=emptyFormDraft(actor.value.actorId);draft.value={...empty,customerId,salespersonId:customer?.salespersonId||actor.value.actorId,shipping:customer?{recipient:customer.recipient,phone:customer.phone,province:customer.province,city:customer.city,district:customer.district,address:customer.address}:empty.shipping,invoiceTitle:customer?.invoiceTitle??customer?.name??null};try{customerContext.value=await session.run(()=>session.service.getCustomerContext(actor.value,customerId,editingOrderId.value??undefined));skus.value=await session.run(()=>session.service.listOrderableSkus(actor.value,customerId));formOptions.value=await session.run(()=>session.service.getFormOptions(actor.value,customerId))}catch(caught){error.value=messageOf(caught,'客户关联数据加载失败');customerContext.value=null;skus.value=[]}}
  function addSku(skuId:string,lineKind:'sale'|'gift'='sale'):void{const sku=skus.value.find((item)=>item.skuId===skuId);if(!sku)return;const unit=sku.units.find((item)=>item.id===sku.baseUnitId)??sku.units[0];if(!unit)return;const found=draft.value.lines.find((item)=>item.skuId===skuId&&item.unitId===unit.id&&item.lineKind===lineKind);if(found)found.quantity+=1;else draft.value.lines.push({skuId,unitId:unit.id,quantity:1,lineKind,manualDealUnitPriceCents:null,reason:null,sourceKeys:[]});preview.value=null}
  function mergeLines(lines:OrderLineDraft[]):void{for(const line of lines){const found=draft.value.lines.find((item)=>item.skuId===line.skuId&&item.unitId===line.unitId&&item.lineKind===line.lineKind);if(found){found.quantity+=line.quantity;found.sourceKeys=[...new Set([...found.sourceKeys,...line.sourceKeys])]}else draft.value.lines.push(structuredClone(line))}preview.value=null}
  function domainDraft():OrderDraft{const value=structuredClone(toRaw(draft.value));if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value.requestedDeliveryAt))value.requestedDeliveryAt=`${value.requestedDeliveryAt}:00+08:00`;return value}
  async function pasteProducts(text:string){const parsed=await session.run(()=>session.service.parsePastedProducts(actor.value,draft.value.customerId,text));if(!parsed.errors.length)mergeLines(parsed.lines);return parsed}
  async function scanBarcode(value:string):Promise<void>{mergeLines([await session.run(()=>session.service.findByBarcode(actor.value,draft.value.customerId,value))])}
  async function applyTemplate(templateId:string){const parsed=await session.run(()=>session.service.loadTemplateLines(actor.value,draft.value.customerId,templateId));mergeLines(parsed.accepted.map((item)=>({skuId:item.skuId,unitId:item.unitId,quantity:item.quantity,lineKind:'sale',manualDealUnitPriceCents:null,reason:null,sourceKeys:[item.sourceKey]})));return parsed}
  async function previewForm():Promise<boolean>{error.value=null;try{const inputDraft=domainDraft();preview.value=await session.run(()=>session.service.previewOrder(actor.value,inputDraft,editingOrderId.value??undefined));return true}catch(caught){preview.value=null;error.value=messageOf(caught,'订单预览失败');return false}}
  async function saveForm(requestId:string):Promise<CustomerOrder|null>{saving.value=true;error.value=null;try{const inputDraft=domainDraft();if(editingOrderId.value)session.simulateConcurrentEdit(editingOrderId.value);const order=await session.run(()=>session.service.saveOrder(actor.value,{requestId,draft:inputDraft,orderId:editingOrderId.value??undefined,expectedUpdatedAt:expectedUpdatedAt.value??undefined}));detail.value=await session.run(()=>session.service.getOrderDetail(actor.value,order.id));return order}catch(caught){error.value=messageOf(caught,'订单保存失败');return null}finally{saving.value=false}}
  async function createShare(orderId:string,duration:ShareDurationDays=7):Promise<OrderShareResult|null>{saving.value=true;error.value=null;try{share.value=await session.run(()=>session.service.createShare(actor.value,orderId,duration));return share.value}catch(caught){error.value=messageOf(caught,'订单分享失败');return null}finally{saving.value=false}}
  async function viewShare(token:string):Promise<void>{loading.value=true;error.value=null;try{sharedOrder.value=await session.run(()=>session.service.viewSharedOrder(token))}catch(caught){sharedOrder.value=null;error.value=messageOf(caught,'分享链接无效')}finally{loading.value=false}}
  async function confirmShare(token:string):Promise<void>{saving.value=true;error.value=null;try{sharedOrder.value=await session.run(()=>session.service.confirmSharedOrder(token))}catch(caught){error.value=messageOf(caught,'确认失败')}finally{saving.value=false}}
  return{scenario,actor,query,result,detail,draft,editingOrderId,expectedUpdatedAt,formOptions,customerContext,skus,preview,share,sharedOrder,loading,saving,error,canOutput,canManage,isEmpty,load,setScenario,setRole,applyQuery,setPage,loadDetail,exportCsv,confirmPrint,initializeForm,selectCustomer,addSku,pasteProducts,scanBarcode,applyTemplate,previewForm,saveForm,createShare,viewShare,confirmShare}
})
