<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import PriceSubnav from '../components/PriceSubnav.vue'
import { usePricingStore, type PricingRuntimeScenario } from '../runtime/pricing-store'
import type { AutoPriceStrategy, SalePriceField, StrategyAmplitudeType, StrategyAnchor } from '../types'
import type { SaveStrategyInput } from '../services/pricing-service'

const store = usePricingStore()
const { strategies, unitPrices, clock, loading, saving, error, canWrite, scenario } = storeToRefs(store)
const selectedCategory = ref('')
const dialogOpen = ref(false)
const editingId = ref<string | null>(null)
const actionError = ref<string | null>(null)
const clockTarget = ref('')
const targetLabels: Record<SalePriceField, string> = { baseOrderPriceCents: '基准订货价', tierOnePriceCents: '一批价', tierTwoPriceCents: '二批价', storePriceCents: '门店价', terminalPriceCents: '终端价' }
const anchorLabels: Record<StrategyAnchor,string> = { 'cost-price': '成本价', 'base-purchase-price': '基准进货价', 'base-order-price': '基准订货价' }
const form = reactive<SaveStrategyInput>({ skuId: '', unitId: '', targetField: 'storePriceCents', anchor: 'base-order-price', amplitudeType: 'percent', amplitude: 0, enabled: true, startsAt: '', endsAt: null })
const categories = computed(() => Array.from(new Map(unitPrices.value.map((row) => [row.sku.categoryId, row.sku.categoryName])).entries()))
const visible = computed(() => strategies.value.filter((strategy) => !selectedCategory.value || rowFor(strategy)?.sku.categoryId === selectedCategory.value))
const skuRows = computed(() => unitPrices.value.filter((row, index, rows) => rows.findIndex((item) => item.sku.skuId === row.sku.skuId) === index))
const unitsForSku = computed(() => unitPrices.value.filter((row) => row.sku.skuId === form.skuId))
function rowFor(strategy: AutoPriceStrategy) { return unitPrices.value.find((row) => row.sku.skuId === strategy.skuId && row.unitId === strategy.unitId) }
function local(value: string | null): string { return value ? value.slice(0,16).replace('T',' ') : '—' }
function iso(value: string): string { return `${value}:00+08:00` }
function openCreate(): void { editingId.value=null; Object.assign(form,{ skuId:'',unitId:'',targetField:'storePriceCents',anchor:'base-order-price',amplitudeType:'percent',amplitude:0,enabled:true,startsAt:'',endsAt:null }); actionError.value=null; dialogOpen.value=true }
function edit(item: AutoPriceStrategy): void { editingId.value=item.id; Object.assign(form,{...item,amplitude:item.amplitudeType==='fixed'?item.amplitude/100:item.amplitude,startsAt:item.startsAt.slice(0,16),endsAt:item.endsAt?.slice(0,16)??null}); actionError.value=null; dialogOpen.value=true }
async function save(): Promise<void> { actionError.value=null; try { await store.saveStrategy({ ...form, amplitude:form.amplitudeType==='fixed'?Math.round(form.amplitude*100):form.amplitude, id:editingId.value??undefined, startsAt:iso(form.startsAt), endsAt:form.endsAt?iso(form.endsAt):null }); dialogOpen.value=false } catch(caught){actionError.value=caught instanceof Error?caught.message:'策略保存失败'} }
async function toggle(item: AutoPriceStrategy): Promise<void> { actionError.value=null; try { await store.saveStrategy({ ...item, enabled:!item.enabled }) } catch(caught){actionError.value=caught instanceof Error?caught.message:'策略状态保存失败'} }
async function advance(): Promise<void> { if(!clockTarget.value)return; actionError.value=null; try{await store.advanceClock(iso(clockTarget.value))}catch(caught){actionError.value=caught instanceof Error?caught.message:'时钟推进失败'} }
async function switchScenario(event:Event):Promise<void>{await store.setScenario((event.target as HTMLSelectElement).value as PricingRuntimeScenario)}
watch(()=>form.skuId,()=>{if(!unitsForSku.value.some((row)=>row.unitId===form.unitId))form.unitId=unitsForSku.value[0]?.unitId??''})
watch(()=>true,()=>store.loadWorkspace('strategies'),{immediate:true})
</script>

<template>
  <section class="page" aria-labelledby="strategy-title">
    <header class="page-header"><div><p class="eyebrow">PRD-002 · 自动调价</p><h1 id="strategy-title">自动调价策略</h1><p>每个 SKU + 单位 + 目标售价最多一个启用策略；越界或冲突时保留旧价格并记录原因。</p></div><div class="header-actions"><label><span>模拟场景</span><select :value="scenario" @change="switchScenario"><option value="normal">正常</option><option value="empty">空数据</option><option value="error">服务错误</option><option value="slow">慢响应</option><option value="permission-denied">无权限</option></select></label><button v-if="canWrite" class="button primary" @click="openCreate">新增策略</button></div></header>
    <PriceSubnav />
    <div class="clock"><strong>模拟时钟</strong><span>{{ local(clock) }}</span><small>策略只在推进可控时钟时执行，不使用真实定时器。</small><input v-if="canWrite" v-model="clockTarget" aria-label="推进策略时钟到" type="datetime-local" :min="clock.slice(0,16)"><button v-if="canWrite" class="button" :disabled="!clockTarget||saving" @click="advance">推进并执行</button></div>
    <p v-if="actionError" class="error-text" role="alert">{{actionError}}</p>
    <div v-if="error" class="state error" role="alert"><strong>策略加载失败</strong><p>{{error}}</p><button class="button" @click="store.loadWorkspace('strategies')">重试</button></div>
    <div v-else-if="loading" class="state">正在加载自动调价策略…</div>
    <div v-else class="workspace"><aside><h2>商品分类</h2><button :class="{active:!selectedCategory}" @click="selectedCategory=''">全部商品</button><button v-for="category in categories" :key="category[0]" :class="{active:selectedCategory===category[0]}" @click="selectedCategory=category[0]">{{category[1]}}</button></aside><div class="table-wrap"><table><thead><tr><th>商品 / SKU</th><th>规格</th><th>单位</th><th>条码</th><th>目标售价</th><th>调价基准</th><th>调价幅度</th><th>有效时间</th><th>状态</th><th>最后执行</th><th>失败日志</th><th>操作</th></tr></thead><tbody><tr v-for="item in visible" :key="item.id"><td><strong>{{rowFor(item)?.sku.productName||item.skuId}}</strong><small>{{rowFor(item)?.sku.skuCode}}</small></td><td>{{rowFor(item)?.sku.specification||'—'}}</td><td>{{rowFor(item)?.unitName||item.unitId}}</td><td>{{rowFor(item)?.sku.barcode||'—'}}</td><td>{{targetLabels[item.targetField]}}</td><td>{{anchorLabels[item.anchor]}}</td><td>{{item.amplitudeType==='percent'?`${item.amplitude}%`:`¥ ${(item.amplitude/100).toFixed(2)}`}}</td><td>{{local(item.startsAt)}}<small>至 {{local(item.endsAt)}}</small></td><td><span class="status" :class="{on:item.enabled}">{{item.enabled?'启用':'停用'}}</span></td><td>{{local(item.lastRunAt)}}</td><td class="log">{{item.lastError||'—'}}</td><td><button v-if="canWrite" class="link" @click="edit(item)">编辑</button><button v-if="canWrite" class="link" @click="toggle(item)">{{item.enabled?'停用':'启用'}}</button><span v-else>只读</span></td></tr><tr v-if="!visible.length"><td colspan="12" class="empty">当前分类暂无自动调价策略。</td></tr></tbody></table></div></div>
    <div v-if="dialogOpen" class="mask"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="strategy-dialog-title"><header><div><h2 id="strategy-dialog-title">{{editingId?'编辑':'新增'}}自动调价策略</h2><p>策略结果按分舍入，执行失败不会覆盖旧价格。</p></div><button aria-label="关闭" @click="dialogOpen=false">×</button></header><div class="form-grid"><label><span>商品 / SKU *</span><select v-model="form.skuId" :disabled="Boolean(editingId)"><option value="">请选择</option><option v-for="row in skuRows" :key="row.sku.skuId" :value="row.sku.skuId">{{row.sku.skuCode}} · {{row.sku.productName}}</option></select></label><label><span>计量单位 *</span><select v-model="form.unitId" :disabled="Boolean(editingId)"><option value="">请选择</option><option v-for="row in unitsForSku" :key="row.unitId" :value="row.unitId">{{row.unitName}}</option></select></label><label><span>目标售价 *</span><select v-model="form.targetField"><option v-for="(label,key) in targetLabels" :key="key" :value="key">{{label}}</option></select></label><label><span>调价基准 *</span><select v-model="form.anchor"><option v-for="(label,key) in anchorLabels" :key="key" :value="key">{{label}}</option></select></label><label><span>幅度类型 *</span><select v-model="form.amplitudeType"><option value="fixed">固定额增加</option><option value="percent">百分比增加</option></select></label><label><span>{{form.amplitudeType==='percent'?'百分比（%）':'固定额（元）'}} *</span><input v-model.number="form.amplitude" aria-label="调价幅度" type="number" min="0" step="0.01"></label><label><span>开始时间 *</span><input v-model="form.startsAt" aria-label="开始时间" type="datetime-local"></label><label><span>结束时间</span><input :value="form.endsAt||''" aria-label="结束时间" type="datetime-local" @input="form.endsAt=($event.target as HTMLInputElement).value||null"></label><label class="check"><input v-model="form.enabled" type="checkbox">启用策略</label></div><p v-if="actionError" class="error-text" role="alert">{{actionError}}</p><footer><button class="button" @click="dialogOpen=false">取消</button><button class="button primary" :disabled="saving||!form.skuId||!form.unitId||!form.startsAt" @click="save">保存策略</button></footer></section></div>
  </section>
</template>

<style scoped>
.page{max-width:1680px;margin:0 auto}.page-header,.header-actions,.clock,.dialog header,.dialog footer{display:flex;align-items:center;justify-content:space-between;gap:12px}.page-header{margin-bottom:14px}.page-header h1{margin:3px 0}.page-header p{margin:0;color:var(--color-muted)}.header-actions{align-items:flex-end}label{display:grid;gap:4px;color:var(--color-muted);font-size:12px}input,select{min-height:36px;padding:7px 10px;background:#fff;border:1px solid var(--color-border-strong);border-radius:var(--radius-sm)}.button{min-height:36px;padding:0 13px;color:#4d5968;background:#fff;border:1px solid var(--color-border-strong);border-radius:var(--radius-sm);cursor:pointer}.button.primary{color:#fff;background:var(--color-primary);border-color:var(--color-primary)}.clock{justify-content:flex-start;padding:10px 14px;background:#f4faf9;border:1px solid #cfe6e3;border-top:0}.clock small{margin-left:auto;color:var(--color-muted)}.workspace{display:grid;grid-template-columns:210px minmax(0,1fr);gap:12px;margin-top:12px}.workspace aside,.table-wrap{background:#fff;border:1px solid var(--color-border)}aside{padding:12px}aside h2{font-size:14px}aside button{display:block;width:100%;padding:10px;text-align:left;background:none;border:0;border-radius:4px;cursor:pointer}aside button.active{color:var(--color-primary);background:#eaf8f7}.table-wrap{overflow:auto}table{width:100%;min-width:1650px;border-collapse:collapse}th,td{height:54px;padding:8px 10px;text-align:left;white-space:nowrap;border-bottom:1px solid var(--color-border)}th{font-size:12px;background:var(--color-table-head)}td small{display:block;color:var(--color-muted)}.status{padding:3px 8px;color:#687586;background:#eef1f5;border-radius:999px}.status.on{color:#087f75;background:#e9f8f6}.link{margin-right:6px;color:var(--color-primary);background:none;border:0;cursor:pointer}.log{max-width:250px;overflow:hidden;text-overflow:ellipsis}.empty{text-align:center;color:var(--color-muted)}.state{min-height:260px;margin-top:12px;padding:50px;text-align:center;background:#fff;border:1px solid var(--color-border)}.state.error,.error-text{color:var(--color-danger)}.mask{position:fixed;inset:0;z-index:20;display:grid;place-items:center;padding:20px;background:#14223599}.dialog{width:min(760px,100%);padding:20px;background:#fff;border-radius:8px}.dialog h2,.dialog p{margin:0}.dialog header>button{font-size:24px;background:none;border:0}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:18px}.check{display:flex;align-items:center}.dialog footer{justify-content:flex-end;margin-top:18px}@media(max-width:900px){.workspace{grid-template-columns:1fr}.page-header{display:block}.header-actions{margin-top:10px}.clock{align-items:flex-start;flex-direction:column}.clock small{margin-left:0}.form-grid{grid-template-columns:1fr}}
</style>

