<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { storeToRefs } from 'pinia'; import { RouterLink,useRoute,useRouter } from 'vue-router'; import AuthorizationSubnav from '../components/AuthorizationSubnav.vue'; import { useAuthorizationStore } from '../runtime/authorization-store'; import type { AuthorizationPlanDraft } from '../types'
const route=useRoute(),router=useRouter(),store=useAuthorizationStore(); const {options,selectedPlan,loading,saving,referenceError}=storeToRefs(store); const id=computed(()=>String(route.params.planId??'')); const editing=computed(()=>Boolean(id.value)); const error=ref<string|null>(null); const csv=ref('productCode\n'); const importMessage=ref(''); const draft=reactive<AuthorizationPlanDraft>({name:'',status:'enabled',categoryIds:[],brandIds:[],productIds:[],customerIds:[]})
function hydrate(){if(selectedPlan.value)Object.assign(draft,{name:selectedPlan.value.name,status:selectedPlan.value.status,categoryIds:[...selectedPlan.value.categoryIds],brandIds:[...selectedPlan.value.brandIds],productIds:[...selectedPlan.value.productIds],customerIds:[...selectedPlan.value.customerIds]})}
async function save(){error.value=null;try{if(editing.value)await store.updatePlan(id.value,draft);else await store.createPlan(draft);await router.push('/products/authorizations/plans')}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
async function importProducts(){if(!editing.value)return;error.value=null;try{const p=await store.importCsv(id.value,csv.value);importMessage.value=p.errorCount?`存在 ${p.errorCount} 行错误，整批未导入`:`已导入 ${p.validCount} 个商品，重复行已去重`;if(!p.errorCount)await store.loadPlan(id.value)}catch(e){error.value=e instanceof Error?e.message:'导入失败'}}
onMounted(async()=>{if(editing.value){await store.loadPlan(id.value);hydrate()}else await store.load('plans')})
</script>
<template><section class="auth-page"><header class="page-header"><div><p class="eyebrow">PRD-003 · 授权方案</p><h1>{{editing?'编辑授权方案':'新增授权方案'}}</h1><p>范围公式：(分类并集 ∩ 品牌并集) ∪ 显式 SPU；只填一组时直接使用该组。</p></div><RouterLink class="button" to="/products/authorizations/plans">返回列表</RouterLink></header><AuthorizationSubnav/><div v-if="loading" class="state">正在加载方案资料…</div><form v-else class="form-card" @submit.prevent="save"><p v-if="referenceError" class="warning">{{referenceError}}</p><p v-if="error" class="warning" role="alert">{{error}}</p><div class="form-grid"><label class="field"><span>方案名称 *</span><input v-model="draft.name" maxlength="40" required></label><label class="field"><span>状态 *</span><select v-model="draft.status"><option value="enabled">启用</option><option value="disabled">停用</option></select></label><div class="field full"><span>商品分类（包含后代）</span><div class="checks"><label v-for="item in options.categories.filter(x=>x.status==='active')" :key="item.id"><input v-model="draft.categoryIds" type="checkbox" :value="item.id">{{item.name}}</label></div></div><div class="field full"><span>商品品牌</span><div class="checks"><label v-for="item in options.brands.filter(x=>x.status==='active')" :key="item.id"><input v-model="draft.brandIds" type="checkbox" :value="item.id">{{item.name}}</label></div></div><div class="field full"><span>显式指定商品</span><div class="checks"><label v-for="item in options.products.filter(x=>!x.deletedAt)" :key="item.id"><input v-model="draft.productIds" type="checkbox" :value="item.id">{{item.code}} · {{item.name}}（{{item.status==='on-sale'?'上架':item.status==='off-sale'?'下架':'草稿'}}）</label></div></div><div class="field full"><span>适用客户（全天长期）</span><div class="checks"><label v-for="item in options.customers.filter(x=>x.status==='active')" :key="item.id"><input v-model="draft.customerIds" type="checkbox" :value="item.id">{{item.code}} · {{item.name}}</label><em v-if="!options.customers.length">客户资料不可用，禁止空覆盖</em></div></div></div><section v-if="editing" class="csv-box"><h2>批量导入显式商品 <small>原型模拟 · UTF-8 CSV</small></h2><p class="hint">首行为 productCode，一行一个 SPU 编码；先预览校验，任一错误整批拒绝。</p><textarea v-model="csv" rows="6" aria-label="商品 CSV 内容"></textarea><button class="button" type="button" :disabled="saving" @click="importProducts">预览并导入</button><span>{{importMessage}}</span></section><p class="hint">方案编码保存时自动生成且不复用；列表按分类范围分组，不存在上级方案。</p><div class="form-actions"><RouterLink class="button" to="/products/authorizations/plans">取消</RouterLink><button class="button primary" :disabled="saving||Boolean(referenceError)" type="submit">{{saving?'保存中…':'保存'}}</button></div></form></section></template>
<style scoped>@import './authorization-views.css';.csv-box{display:grid;gap:10px;margin-top:20px;padding-top:18px;border-top:1px solid var(--color-border)}.csv-box h2{margin:0;font-size:15px}.csv-box small{color:var(--color-muted);font-weight:400}.csv-box textarea{padding:9px;border:1px solid var(--color-border-strong);border-radius:4px;font-family:monospace}.csv-box .button{justify-self:start}</style>

