<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { storeToRefs } from 'pinia'; import { RouterLink } from 'vue-router'; import AuthorizationSubnav from '../components/AuthorizationSubnav.vue'; import { useAuthorizationStore, type AuthorizationRuntimeScenario } from '../runtime/authorization-store'
const store=useAuthorizationStore(); const {plans,loading,error,isEmpty,scenario,canWrite}=storeToRefs(store); const filters=reactive({keyword:'',status:''}); const selected=ref<string[]>([]); const actionError=ref<string|null>(null); const statusLabels={enabled:'启用',disabled:'停用'} as const
const search=()=>store.applyPlanQuery({keyword:filters.keyword||undefined,status:(filters.status||undefined) as 'enabled'|'disabled'|undefined,pageSize:30}); const reset=()=>{filters.keyword='';filters.status='';return search()}; const switchScenario=(e:Event)=>store.setScenario((e.target as HTMLSelectElement).value as AuthorizationRuntimeScenario)
async function remove(id:string){if(!window.confirm('确认删除该授权方案吗？被规则引用时系统会拒绝删除。'))return;actionError.value=null;try{await store.deletePlan(id)}catch(e){actionError.value=e instanceof Error?e.message:'删除失败'}}
function download(){const csv=store.exportCsv(selected.value); const blob=new Blob([`\uFEFF${csv}`],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a');a.href=url;a.download='authorization-plans.csv';a.click();URL.revokeObjectURL(url)}
function tutorial(){window.alert('原型模拟：授权方案教程说明分类/品牌交集、显式商品并集和客户关联。')}
onMounted(()=>store.load('plans'))
</script>
<template><section class="auth-page"><header class="page-header"><div><p class="eyebrow">PRD-003 · 商品授权</p><h1>商品授权方案</h1><p>分类与品牌范围动态计算，再与显式商品并集；方案停用后保留引用但不再命中。</p></div><div class="tools"><label><span>模拟场景</span><select :value="scenario" @change="switchScenario"><option value="normal">正常</option><option value="empty">空数据</option><option value="error">服务错误</option><option value="slow">慢响应</option><option value="permission-denied">无权限</option><option value="partial-failure">部分资料失败</option><option value="boundary">时间边界</option></select></label><button v-if="canWrite" class="button" type="button" @click="download">导出 CSV</button><RouterLink v-if="canWrite" class="button primary" to="/products/authorizations/plans/new">新增方案</RouterLink></div></header><AuthorizationSubnav/><form class="filters" @submit.prevent="search"><label><span>方案名称</span><input v-model="filters.keyword" placeholder="输入方案名称"></label><label><span>状态</span><select v-model="filters.status"><option value="">全部状态</option><option value="enabled">启用</option><option value="disabled">停用</option></select></label><div><button class="button" type="button" @click="reset">重置</button><button class="button primary" type="submit">查询</button></div></form><p v-if="actionError" class="warning" role="alert">{{actionError}}</p><div v-if="error" class="state error"><strong>授权方案加载失败</strong><p>{{error}}</p><button class="button" @click="store.load('plans')">重试</button></div><div v-else-if="loading" class="state">正在加载授权方案…</div><div v-else-if="isEmpty" class="state"><strong>暂无授权方案</strong><p>当前筛选或模拟场景没有数据。</p></div><template v-else><div class="table-tools"><span>共 {{plans.total}} 个方案 · 按分类范围分组展示，不建立方案父级</span><button class="button" @click="store.load('plans')">刷新</button></div><div class="table-wrap"><table><thead><tr><th><span class="sr-only">选择</span></th><th>授权方案名称</th><th>方案编码</th><th>分类范围</th><th>商品数量</th><th>适用客户</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in plans.items" :key="item.id"><td><input v-model="selected" type="checkbox" :value="item.id" :aria-label="`选择${item.name}`"></td><td><strong>{{item.name}}</strong></td><td class="mono">{{item.code}}</td><td>{{item.categoryNames.join('、')||'显式商品'}}</td><td>{{item.productCount}}</td><td>{{item.customerIds.length}} 个客户</td><td><span class="status" :class="item.status">{{statusLabels[item.status]}}</span></td><td>{{item.createdAt.slice(0,16).replace('T',' ')}}</td><td><RouterLink v-if="canWrite" :to="`/products/authorizations/plans/${item.id}/edit`">编辑</RouterLink><button v-if="canWrite" class="link danger" @click="remove(item.id)">删除</button><span v-else>只读</span></td></tr></tbody></table></div></template></section></template>
<style scoped>@import '../views/authorization-views.css';</style>
